package com.tcs.sgv.common.valueobject;

// Generated Jun 7, 2007 11:41:43 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * BillVitoRegister generated by hbm2java
 */
public class BillVitoRegister implements java.io.Serializable {

	// Fields    

	private long vitoId;

	private String vitoCode;

	private String vitoType;

	private long billNo;

	private long createdUserId;

	private long createdPostId;

	private Date createdDate;
	
	private String locationCode;

	private long dbId;
	
	private Long trnCounter;

	// Constructors

	/** default constructor */
	public BillVitoRegister() {
	}

	/** minimal constructor */
	public BillVitoRegister(long vitoId, String vitoCode, long billNo,
			long createdUserId, long createdPostId, String locationCode, long dbId) {
		this.vitoId = vitoId;
		this.vitoCode = vitoCode;
		this.billNo = billNo;
		this.createdUserId = createdUserId;
		this.createdPostId = createdPostId;
		this.locationCode = locationCode;
		this.dbId = dbId;
	}

	/** full constructor */
	public BillVitoRegister(long vitoId, String vitoCode, String vitoType,
			long billNo, long createdUserId, long createdPostId,
			Date createdDate, String locationCode, long dbId) {
		this.vitoId = vitoId;
		this.vitoCode = vitoCode;
		this.vitoType = vitoType;
		this.billNo = billNo;
		this.createdUserId = createdUserId;
		this.createdPostId = createdPostId;
		this.createdDate = createdDate;
		this.locationCode = locationCode;
		this.dbId = dbId;
	}

	// Property accessors
	public long getVitoId() {
		return this.vitoId;
	}

	public void setVitoId(long vitoId) {
		this.vitoId = vitoId;
	}

	public String getVitoCode() {
		return this.vitoCode;
	}

	public void setVitoCode(String vitoCode) {
		this.vitoCode = vitoCode;
	}
	
	public long getBillNo() {
		return this.billNo;
	}

	public void setBillNo(long billNo) {
		this.billNo = billNo;
	}

	public long getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(long createdUserId) {
		this.createdUserId = createdUserId;
	}

	public long getCreatedPostId() {
		return this.createdPostId;
	}

	public void setCreatedPostId(long createdPostId) {
		this.createdPostId = createdPostId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getLocationCode() {
		return this.locationCode;
	}

	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}

	public long getDbId() {
		return this.dbId;
	}

	public void setDbId(long dbId) {
		this.dbId = dbId;
	}

	public String getVitoType() {
		return vitoType;
	}

	public void setVitoType(String vitoType) {
		this.vitoType = vitoType;
	}

	public Long getTrnCounter() {
		return trnCounter;
	}

	public void setTrnCounter(Long trnCounter) {
		this.trnCounter = trnCounter;
	}
	
}
