package com.tcs.sgv.common.valueobject;

// Generated Jul 21, 2008 6:54:11 AM by Hibernate Tools 3.2.0.CR1

/**
 * HstConfigAudCategoryId generated by hbm2java
 */
public class HstConfigAudCategoryId implements java.io.Serializable {

	private Long audCatId;
	private Integer trnCounter;

	public HstConfigAudCategoryId() {
	}

	public HstConfigAudCategoryId(Long audCatId, Integer trnCounter) {
		this.audCatId = audCatId;
		this.trnCounter = trnCounter;
	}

	public Long getAudCatId() {
		return this.audCatId;
	}

	public void setAudCatId(Long audCatId) {
		this.audCatId = audCatId;
	}

	public Integer getTrnCounter() {
		return this.trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HstConfigAudCategoryId))
			return false;
		HstConfigAudCategoryId castOther = (HstConfigAudCategoryId) other;

		return ((this.getAudCatId() == castOther.getAudCatId()) || (this.getAudCatId() != null && castOther.getAudCatId() != null 
				&& this.getAudCatId().equals(castOther.getAudCatId())))
				&& (this.getTrnCounter() == castOther.getTrnCounter());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAudCatId() == null ? 0 : this.getAudCatId().hashCode());
		result = 37 * result + (int) this.getTrnCounter();
		return result;
	}

}
