package com.tcs.sgv.common.valueobject;

import java.util.Date;

/**
 * MstAuditorConfig generated by hbm2java
 */
public class MstAudConfigPriority implements java.io.Serializable {

	private Long priorityId;
	private Integer majorHead;
	private Integer billType;
	private Integer goNgo;
	private Integer cardexNo;
	private String locationCode;
	private String branchCode;
	private Long createdUserId;
	private Long createdPostId;
	private Date createdDate;
	private Long updatedUserId;
	private Long updatedPostId;
	private Date updatedDate;
	
	public MstAudConfigPriority() {
	}

	public MstAudConfigPriority(Long priorityId, Long createdUserId,
			Long createdPostId, Date createdDate) {
		this.priorityId = priorityId;
		this.createdUserId = createdUserId;
		this.createdPostId = createdPostId;
		this.createdDate = createdDate;
	}

	public MstAudConfigPriority(Long priorityId,Integer billType,
			Integer majorHead,Integer goNgo,
			Integer cardexNo,String branchCode,
			String locationCode, Long createdUserId, Long createdPostId,
			Date createdDate, Long updatedUserId, Long updatedPostId,
			Date updatedDate) {
		this.priorityId = priorityId;
		this.majorHead = majorHead;
		this.billType = billType;
		this.goNgo = goNgo;
		this.cardexNo = cardexNo;
		this.locationCode = locationCode;
		this.branchCode = branchCode;
		this.createdUserId = createdUserId;
		this.createdPostId = createdPostId;
		this.createdDate = createdDate;
		this.updatedUserId = updatedUserId;
		this.updatedPostId = updatedPostId;
		this.updatedDate = updatedDate;		
	}
	
	public Long getPriorityId() {
		return this.priorityId;
	}

	public void setPriorityId(Long priorityId) {
		this.priorityId = priorityId;
	}
	
	public Integer getMajorHead() {
		return this.majorHead;
	}

	public void setMajorHead(Integer majorHead) {
		this.majorHead = majorHead;
	}

	public Integer getBillType() {
		return this.billType;
	}

	public void setBillType(Integer billType) {
		this.billType = billType;
	}

	public Integer getGoNgo() {
		return this.goNgo;
	}

	public void setGoNgo(Integer goNgo) {
		this.goNgo = goNgo;
	}

	public Integer getCardexNo() {
		return this.cardexNo;
	}

	public void setCardexNo(Integer cardexNo) {
		this.cardexNo = cardexNo;
	}

	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	public String getLocationCode() {
		return this.locationCode;
	}

	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}
	
	public Long getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(Long createdUserId) {
		this.createdUserId = createdUserId;
	}

	public Long getCreatedPostId() {
		return this.createdPostId;
	}

	public void setCreatedPostId(Long createdPostId) {
		this.createdPostId = createdPostId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Long getUpdatedUserId() {
		return this.updatedUserId;
	}

	public void setUpdatedUserId(Long updatedUserId) {
		this.updatedUserId = updatedUserId;
	}

	public Long getUpdatedPostId() {
		return this.updatedPostId;
	}

	public void setUpdatedPostId(Long updatedPostId) {
		this.updatedPostId = updatedPostId;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
}
