package com.tcs.sgv.common.valueobject;

// Generated Mar 20, 2012 06:32:39 AM 

import java.util.Date;

/**
 * RltBankBranch generated by hbm2java
 */
public class RltLevelRole implements java.io.Serializable {
	

	private long roleLevelId;

	private String moduleName;

	private Integer levelId;
	
	private Integer roleId;
	
	private String roleDesc;

	private String workFlow;
	
	private String department;

	public long getRoleLevelId() {
		return roleLevelId;
	}

	public void setRoleLevelId(long roleLevelId) {
		this.roleLevelId = roleLevelId;
	}

	public String getModuleName() {
		return moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	public Integer getLevelId() {
		return levelId;
	}

	public void setLevelId(Integer levelId) {
		this.levelId = levelId;
	}

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getRoleDesc() {
		return roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	public String getWorkFlow() {
		return workFlow;
	}

	public void setWorkFlow(String workFlow) {
		this.workFlow = workFlow;
	}

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

}
