package com.tcs.sgv.common.valueobject;
// Generated Oct 10, 2008 4:25:53 PM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;

/**
 * SgvaGrantOrderDetail generated by hbm2java
 */

public class SgvaGrantOrderDetail implements java.io.Serializable {

	// Fields    

	private Long orderDetailId;
	private long orderId;
	private long finYearId;
	private String planNonplan;
	private String fromMonthCode;
	private String toMonthCode;
	private String fileCreatorType;
	private String fromDeptId;
	private String fromCoCode;
	private String toDeptId;
	private String toCoCode;
	private String toDdoCode;
	private String deptId;
	private String demandCode;
	private String budmjrhdCode;
	private String budsubmjrhdCode;
	private String budminhdCode;
	private String budsubhdCode;
	private BigDecimal grantAmountState;
	private BigDecimal grantAmountStateGia;
	private BigDecimal grantAmountCss;
	private BigDecimal grantAmountCssGia;
	private String remarks;
	private Long mergeId;
	private String grantReleaseStatus;
	private Date crtDt;
	private String crtUsr;
	private String lstUpdUsr;
	private Date lstUpdDt;
	private String toDivisionId;
	private Boolean normalLc;
	private Long dbId;
	private String isNewData;

	// Constructors

	/** default constructor */
	public SgvaGrantOrderDetail() {
	}

	/** minimal constructor */
	public SgvaGrantOrderDetail(Long orderDetailId, long orderId,
			long finYearId, String planNonplan, String fromMonthCode,
			String toMonthCode, String fileCreatorType,
			BigDecimal grantAmountState, BigDecimal grantAmountStateGia,
			BigDecimal grantAmountCss, BigDecimal grantAmountCssGia,
			String grantReleaseStatus, Date crtDt, String crtUsr,
			Long dbId) {
		this.orderDetailId = orderDetailId;
		this.orderId = orderId;
		this.finYearId = finYearId;
		this.planNonplan = planNonplan;
		this.fromMonthCode = fromMonthCode;
		this.toMonthCode = toMonthCode;
		this.fileCreatorType = fileCreatorType;
		this.grantAmountState = grantAmountState;
		this.grantAmountStateGia = grantAmountStateGia;
		this.grantAmountCss = grantAmountCss;
		this.grantAmountCssGia = grantAmountCssGia;
		this.grantReleaseStatus = grantReleaseStatus;
		this.crtDt = crtDt;
		this.crtUsr = crtUsr;
		this.dbId = dbId;
	}

	/** full constructor */
	public SgvaGrantOrderDetail(Long orderDetailId, long orderId,
			long finYearId, String planNonplan, String fromMonthCode,
			String toMonthCode, String fileCreatorType, String fromDeptId,
			String fromCoCode, String toDeptId, String toCoCode,
			String toDdoCode, String deptId, String demandCode,
			String budmjrhdCode, String budsubmjrhdCode, String budminhdCode,
			String budsubhdCode, BigDecimal grantAmountState,
			BigDecimal grantAmountStateGia, BigDecimal grantAmountCss,
			BigDecimal grantAmountCssGia, String remarks, Long mergeId,
			String grantReleaseStatus, Date crtDt, String crtUsr,
			String lstUpdUsr, Date lstUpdDt, String toDivisionId,
			Boolean normalLc, Long dbId, String isNewData) {
		this.orderDetailId = orderDetailId;
		this.orderId = orderId;
		this.finYearId = finYearId;
		this.planNonplan = planNonplan;
		this.fromMonthCode = fromMonthCode;
		this.toMonthCode = toMonthCode;
		this.fileCreatorType = fileCreatorType;
		this.fromDeptId = fromDeptId;
		this.fromCoCode = fromCoCode;
		this.toDeptId = toDeptId;
		this.toCoCode = toCoCode;
		this.toDdoCode = toDdoCode;
		this.deptId = deptId;
		this.demandCode = demandCode;
		this.budmjrhdCode = budmjrhdCode;
		this.budsubmjrhdCode = budsubmjrhdCode;
		this.budminhdCode = budminhdCode;
		this.budsubhdCode = budsubhdCode;
		this.grantAmountState = grantAmountState;
		this.grantAmountStateGia = grantAmountStateGia;
		this.grantAmountCss = grantAmountCss;
		this.grantAmountCssGia = grantAmountCssGia;
		this.remarks = remarks;
		this.mergeId = mergeId;
		this.grantReleaseStatus = grantReleaseStatus;
		this.crtDt = crtDt;
		this.crtUsr = crtUsr;
		this.lstUpdUsr = lstUpdUsr;
		this.lstUpdDt = lstUpdDt;
		this.toDivisionId = toDivisionId;
		this.normalLc = normalLc;
		this.dbId = dbId;
		this.isNewData = isNewData;
	}

	// Property accessors
	public Long getOrderDetailId() {
		return this.orderDetailId;
	}

	public void setOrderDetailId(Long orderDetailId) {
		this.orderDetailId = orderDetailId;
	}

	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	public long getFinYearId() {
		return this.finYearId;
	}

	public void setFinYearId(long finYearId) {
		this.finYearId = finYearId;
	}

	public String getPlanNonplan() {
		return this.planNonplan;
	}

	public void setPlanNonplan(String planNonplan) {
		this.planNonplan = planNonplan;
	}

	public String getFromMonthCode() {
		return this.fromMonthCode;
	}

	public void setFromMonthCode(String fromMonthCode) {
		this.fromMonthCode = fromMonthCode;
	}

	public String getToMonthCode() {
		return this.toMonthCode;
	}

	public void setToMonthCode(String toMonthCode) {
		this.toMonthCode = toMonthCode;
	}

	public String getFileCreatorType() {
		return this.fileCreatorType;
	}

	public void setFileCreatorType(String fileCreatorType) {
		this.fileCreatorType = fileCreatorType;
	}

	public String getFromDeptId() {
		return this.fromDeptId;
	}

	public void setFromDeptId(String fromDeptId) {
		this.fromDeptId = fromDeptId;
	}

	public String getFromCoCode() {
		return this.fromCoCode;
	}

	public void setFromCoCode(String fromCoCode) {
		this.fromCoCode = fromCoCode;
	}

	public String getToDeptId() {
		return this.toDeptId;
	}

	public void setToDeptId(String toDeptId) {
		this.toDeptId = toDeptId;
	}

	public String getToCoCode() {
		return this.toCoCode;
	}

	public void setToCoCode(String toCoCode) {
		this.toCoCode = toCoCode;
	}

	public String getToDdoCode() {
		return this.toDdoCode;
	}

	public void setToDdoCode(String toDdoCode) {
		this.toDdoCode = toDdoCode;
	}

	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	public String getDemandCode() {
		return this.demandCode;
	}

	public void setDemandCode(String demandCode) {
		this.demandCode = demandCode;
	}

	public String getBudmjrhdCode() {
		return this.budmjrhdCode;
	}

	public void setBudmjrhdCode(String budmjrhdCode) {
		this.budmjrhdCode = budmjrhdCode;
	}

	public String getBudsubmjrhdCode() {
		return this.budsubmjrhdCode;
	}

	public void setBudsubmjrhdCode(String budsubmjrhdCode) {
		this.budsubmjrhdCode = budsubmjrhdCode;
	}

	public String getBudminhdCode() {
		return this.budminhdCode;
	}

	public void setBudminhdCode(String budminhdCode) {
		this.budminhdCode = budminhdCode;
	}

	public String getBudsubhdCode() {
		return this.budsubhdCode;
	}

	public void setBudsubhdCode(String budsubhdCode) {
		this.budsubhdCode = budsubhdCode;
	}

	public BigDecimal getGrantAmountState() {
		return this.grantAmountState;
	}

	public void setGrantAmountState(BigDecimal grantAmountState) {
		this.grantAmountState = grantAmountState;
	}

	public BigDecimal getGrantAmountStateGia() {
		return this.grantAmountStateGia;
	}

	public void setGrantAmountStateGia(BigDecimal grantAmountStateGia) {
		this.grantAmountStateGia = grantAmountStateGia;
	}

	public BigDecimal getGrantAmountCss() {
		return this.grantAmountCss;
	}

	public void setGrantAmountCss(BigDecimal grantAmountCss) {
		this.grantAmountCss = grantAmountCss;
	}

	public BigDecimal getGrantAmountCssGia() {
		return this.grantAmountCssGia;
	}

	public void setGrantAmountCssGia(BigDecimal grantAmountCssGia) {
		this.grantAmountCssGia = grantAmountCssGia;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Long getMergeId() {
		return this.mergeId;
	}

	public void setMergeId(Long mergeId) {
		this.mergeId = mergeId;
	}

	public String getGrantReleaseStatus() {
		return this.grantReleaseStatus;
	}

	public void setGrantReleaseStatus(String grantReleaseStatus) {
		this.grantReleaseStatus = grantReleaseStatus;
	}

	public Date getCrtDt() {
		return this.crtDt;
	}

	public void setCrtDt(Date crtDt) {
		this.crtDt = crtDt;
	}

	public String getCrtUsr() {
		return this.crtUsr;
	}

	public void setCrtUsr(String crtUsr) {
		this.crtUsr = crtUsr;
	}

	public String getLstUpdUsr() {
		return this.lstUpdUsr;
	}

	public void setLstUpdUsr(String lstUpdUsr) {
		this.lstUpdUsr = lstUpdUsr;
	}

	public Date getLstUpdDt() {
		return this.lstUpdDt;
	}

	public void setLstUpdDt(Date lstUpdDt) {
		this.lstUpdDt = lstUpdDt;
	}

	public String getToDivisionId() {
		return this.toDivisionId;
	}

	public void setToDivisionId(String toDivisionId) {
		this.toDivisionId = toDivisionId;
	}

	public Boolean getNormalLc() {
		return this.normalLc;
	}

	public void setNormalLc(Boolean normalLc) {
		this.normalLc = normalLc;
	}

	public Long getDbId() {
		return this.dbId;
	}

	public void setDbId(Long dbId) {
		this.dbId = dbId;
	}

	public String getIsNewData() {
		return this.isNewData;
	}

	public void setIsNewData(String isNewData) {
		this.isNewData = isNewData;
	}

}
