// default package
// Generated Feb 29, 2008 6:24:11 PM by Hibernate Tools 3.2.0.beta8
package com.tcs.sgv.pension.valueobject;

import java.math.BigDecimal;
import java.util.Date;

/**
 * MstPensionerHdr generated by hbm2java
 */
public class MstPensionerHdr implements java.io.Serializable
{

    // Fields

    private Long pensionerId;

    private String pensionerCode;

    private String firstName;

    private String middleName;

    private String lastName;

    private String pensnerAddr;

    private BigDecimal stateCode;

    private BigDecimal districtCode;

    private String teleNo;

    private Date dateOfBirth;

    private Date dateOfJoin;

    private Date dateOfRetirement;

    private Date dateOfDeath;

    private String aliveFlag;

    private String panNo;

    private String payScale;

    private BigDecimal lastPay;

    private String gender;

    private String officeAddr;

    private BigDecimal deptCode;

    private BigDecimal hodCode;

    private BigDecimal attachmentPhotoId;

    private String locationCode;

    private BigDecimal createdUserId;

    private BigDecimal createdPostId;

    private Date createdDate;

    private BigDecimal updatedUserId;

    private BigDecimal updatedPostId;

    private Date updatedDate;

    private String classType;

    private String cadreType;

    private String designation;

    private String caseStatus;

    private String identityMark;

    private String height;

    private String pnsnrEmailId;

    private String officeEmailId;

    private String pnsnrPrefix;


    // Constructors

    /** default constructor */
    public MstPensionerHdr()
    {
    }


    /** minimal constructor */
    public MstPensionerHdr(Long pensionerId, String pensionerCode, String firstName, String locationCode,
            BigDecimal createdUserId, BigDecimal createdPostId, Date createdDate)
    {
        this.pensionerId = pensionerId;
        this.pensionerCode = pensionerCode;
        this.firstName = firstName;
        this.locationCode = locationCode;
        this.createdUserId = createdUserId;
        this.createdPostId = createdPostId;
        this.createdDate = createdDate;
    }


    /** full constructor */
    public MstPensionerHdr(Long pensionerId, String pensionerCode, String firstName, String middleName,
            String lastName, String pensnerAddr, BigDecimal stateCode, BigDecimal districtCode, String teleNo,
            Date dateOfBirth, Date dateOfJoin, Date dateOfRetirement, Date dateOfDeath, String aliveFlag,
            String panNo, String payScale, BigDecimal lastPay, String gender, String officeAddr, BigDecimal deptCode,
            BigDecimal hodCode, BigDecimal attachmentPhotoId, String locationCode, BigDecimal createdUserId,
            BigDecimal createdPostId, Date createdDate, BigDecimal updatedUserId, BigDecimal updatedPostId,
            Date updatedDate, String classType, String cadreType, String designation, String caseStatus,
            String identityMark, String height, String pnsnrEmailId, String pnsnrPrefix)
    {
        this.pensionerId = pensionerId;
        this.pensionerCode = pensionerCode;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.pensnerAddr = pensnerAddr;
        this.stateCode = stateCode;
        this.districtCode = districtCode;
        this.teleNo = teleNo;
        this.dateOfBirth = dateOfBirth;
        this.dateOfJoin = dateOfJoin;
        this.dateOfRetirement = dateOfRetirement;
        this.dateOfDeath = dateOfDeath;
        this.aliveFlag = aliveFlag;
        this.panNo = panNo;
        this.payScale = payScale;
        this.lastPay = lastPay;
        this.gender = gender;
        this.officeAddr = officeAddr;
        this.deptCode = deptCode;
        this.hodCode = hodCode;
        this.attachmentPhotoId = attachmentPhotoId;
        this.locationCode = locationCode;
        this.createdUserId = createdUserId;
        this.createdPostId = createdPostId;
        this.createdDate = createdDate;
        this.updatedUserId = updatedUserId;
        this.updatedPostId = updatedPostId;
        this.updatedDate = updatedDate;
        this.classType = classType;
        this.cadreType = cadreType;
        this.designation = designation;
        this.caseStatus = caseStatus;
        this.identityMark = identityMark;
        this.height = height;
        this.pnsnrEmailId = pnsnrEmailId;
        this.pnsnrPrefix = pnsnrPrefix;
    }


    // Property accessors
    public Long getPensionerId()
    {
        return this.pensionerId;
    }


    public void setPensionerId(Long pensionerId)
    {
        this.pensionerId = pensionerId;
    }


    public String getPensionerCode()
    {
        return this.pensionerCode;
    }


    public void setPensionerCode(String pensionerCode)
    {
        this.pensionerCode = pensionerCode;
    }


    public String getFirstName()
    {
        return this.firstName;
    }


    public void setFirstName(String firstName)
    {
        this.firstName = firstName;
    }


    public String getMiddleName()
    {
        return this.middleName;
    }


    public void setMiddleName(String middleName)
    {
        this.middleName = middleName;
    }


    public String getLastName()
    {
        return this.lastName;
    }


    public void setLastName(String lastName)
    {
        this.lastName = lastName;
    }


    public String getPensnerAddr()
    {
        return this.pensnerAddr;
    }


    public void setPensnerAddr(String pensnerAddr)
    {
        this.pensnerAddr = pensnerAddr;
    }


    public BigDecimal getStateCode()
    {
        return this.stateCode;
    }


    public void setStateCode(BigDecimal stateCode)
    {
        this.stateCode = stateCode;
    }


    public BigDecimal getDistrictCode()
    {
        return this.districtCode;
    }


    public void setDistrictCode(BigDecimal districtCode)
    {
        this.districtCode = districtCode;
    }


    public String getTeleNo()
    {
        return this.teleNo;
    }


    public void setTeleNo(String teleNo)
    {
        this.teleNo = teleNo;
    }


    public Date getDateOfBirth()
    {
        return this.dateOfBirth;
    }


    public void setDateOfBirth(Date dateOfBirth)
    {
        this.dateOfBirth = dateOfBirth;
    }


    public Date getDateOfJoin()
    {
        return this.dateOfJoin;
    }


    public void setDateOfJoin(Date dateOfJoin)
    {
        this.dateOfJoin = dateOfJoin;
    }


    public Date getDateOfRetirement()
    {
        return this.dateOfRetirement;
    }


    public void setDateOfRetirement(Date dateOfRetirement)
    {
        this.dateOfRetirement = dateOfRetirement;
    }


    public Date getDateOfDeath()
    {
        return this.dateOfDeath;
    }


    public void setDateOfDeath(Date dateOfDeath)
    {
        this.dateOfDeath = dateOfDeath;
    }


    public String getAliveFlag()
    {
        return this.aliveFlag;
    }


    public void setAliveFlag(String aliveFlag)
    {
        this.aliveFlag = aliveFlag;
    }


    public String getPanNo()
    {
        return this.panNo;
    }


    public void setPanNo(String panNo)
    {
        this.panNo = panNo;
    }


    public String getPayScale()
    {
        return this.payScale;
    }


    public void setPayScale(String payScale)
    {
        this.payScale = payScale;
    }


    public BigDecimal getLastPay()
    {
        return this.lastPay;
    }


    public void setLastPay(BigDecimal lastPay)
    {
        this.lastPay = lastPay;
    }


    public String getGender()
    {
        return this.gender;
    }


    public void setGender(String gender)
    {
        this.gender = gender;
    }


    public String getOfficeAddr()
    {
        return this.officeAddr;
    }


    public void setOfficeAddr(String officeAddr)
    {
        this.officeAddr = officeAddr;
    }


    public BigDecimal getDeptCode()
    {
        return this.deptCode;
    }


    public void setDeptCode(BigDecimal deptCode)
    {
        this.deptCode = deptCode;
    }


    public BigDecimal getHodCode()
    {
        return this.hodCode;
    }


    public void setHodCode(BigDecimal hodCode)
    {
        this.hodCode = hodCode;
    }


    public BigDecimal getAttachmentPhotoId()
    {
        return this.attachmentPhotoId;
    }


    public void setAttachmentPhotoId(BigDecimal attachmentPhotoId)
    {
        this.attachmentPhotoId = attachmentPhotoId;
    }


    public String getLocationCode()
    {
        return this.locationCode;
    }


    public void setLocationCode(String locationCode)
    {
        this.locationCode = locationCode;
    }


    public BigDecimal getCreatedUserId()
    {
        return this.createdUserId;
    }


    public void setCreatedUserId(BigDecimal createdUserId)
    {
        this.createdUserId = createdUserId;
    }


    public BigDecimal getCreatedPostId()
    {
        return this.createdPostId;
    }


    public void setCreatedPostId(BigDecimal createdPostId)
    {
        this.createdPostId = createdPostId;
    }


    public Date getCreatedDate()
    {
        return this.createdDate;
    }


    public void setCreatedDate(Date createdDate)
    {
        this.createdDate = createdDate;
    }


    public BigDecimal getUpdatedUserId()
    {
        return this.updatedUserId;
    }


    public void setUpdatedUserId(BigDecimal updatedUserId)
    {
        this.updatedUserId = updatedUserId;
    }


    public BigDecimal getUpdatedPostId()
    {
        return this.updatedPostId;
    }


    public void setUpdatedPostId(BigDecimal updatedPostId)
    {
        this.updatedPostId = updatedPostId;
    }


    public Date getUpdatedDate()
    {
        return this.updatedDate;
    }


    public void setUpdatedDate(Date updatedDate)
    {
        this.updatedDate = updatedDate;
    }


    public String getClassType()
    {
        return this.classType;
    }


    public void setClassType(String classType)
    {
        this.classType = classType;
    }


    public String getCadreType()
    {
        return this.cadreType;
    }


    public void setCadreType(String cadreType)
    {
        this.cadreType = cadreType;
    }


    public String getDesignation()
    {
        return this.designation;
    }


    public void setDesignation(String designation)
    {
        this.designation = designation;
    }


    public String getCaseStatus()
    {
        return this.caseStatus;
    }


    public void setCaseStatus(String caseStatus)
    {
        this.caseStatus = caseStatus;
    }


    public String getIdentityMark()
    {
        return this.identityMark;
    }


    public void setIdentityMark(String identityMark)
    {
        this.identityMark = identityMark;
    }


    public String getHeight()
    {
        return this.height;
    }


    public void setHeight(String height)
    {
        this.height = height;
    }


    public void setPnsnrEmailId(String pnsnrEmailId)
    {
        this.pnsnrEmailId = pnsnrEmailId;
    }


    public String getPnsnrEmailId()
    {
        return this.pnsnrEmailId;
    }


    public void setOfficeEmailId(String officeEmailId)
    {
        this.officeEmailId = officeEmailId;
    }


    public String getOfficeEmailId()
    {
        return this.officeEmailId;
    }


    public void setPnsnrPrefix(String pnsnrPrefix)
    {
        this.pnsnrPrefix = pnsnrPrefix;
    }


    public String getPnsnrPrefix()
    {
        return this.pnsnrPrefix;
    }
}
