package com.tcs.sgv.pension.valueobject;

// Generated May 30, 2008 6:23:47 PM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;

/**
 * MstPensionRop1986 generated by hbm2java
 */
public class MstPensionRop1986 implements java.io.Serializable {

	// Fields    

	private Long pensionRop86Id;

	private BigDecimal oldAmount;

	private BigDecimal column2Amount;

	private BigDecimal column3Amount;

	private BigDecimal column4Amount;

	private BigDecimal column5Amount;

	private BigDecimal createdUserId;

	private BigDecimal createdPostId;

	private Date createdDate;

	private BigDecimal updatedUserId;

	private BigDecimal updatedPostId;

	private Date updatedDate;

	// Constructors

	/** default constructor */
	public MstPensionRop1986() {
	}

	/** minimal constructor */
	public MstPensionRop1986(Long pensionRop86Id,
			BigDecimal createdUserId, BigDecimal createdPostId) {
		this.pensionRop86Id = pensionRop86Id;
		this.createdUserId = createdUserId;
		this.createdPostId = createdPostId;
	}

	/** full constructor */
	public MstPensionRop1986(Long pensionRop86Id, BigDecimal oldAmount,
			BigDecimal column2Amount, BigDecimal column3Amount,
			BigDecimal column4Amount, BigDecimal column5Amount,
			BigDecimal createdUserId, BigDecimal createdPostId,
			Date createdDate, BigDecimal updatedUserId,
			BigDecimal updatedPostId, Date updatedDate) {
		this.pensionRop86Id = pensionRop86Id;
		this.oldAmount = oldAmount;
		this.column2Amount = column2Amount;
		this.column3Amount = column3Amount;
		this.column4Amount = column4Amount;
		this.column5Amount = column5Amount;
		this.createdUserId = createdUserId;
		this.createdPostId = createdPostId;
		this.createdDate = createdDate;
		this.updatedUserId = updatedUserId;
		this.updatedPostId = updatedPostId;
		this.updatedDate = updatedDate;
	}

	// Property accessors
	public Long getPensionRop86Id() {
		return this.pensionRop86Id;
	}

	public void setPensionRop86Id(Long pensionRop86Id) {
		this.pensionRop86Id = pensionRop86Id;
	}

	public BigDecimal getOldAmount() {
		return this.oldAmount;
	}

	public void setOldAmount(BigDecimal oldAmount) {
		this.oldAmount = oldAmount;
	}

	public BigDecimal getColumn2Amount() {
		return this.column2Amount;
	}

	public void setColumn2Amount(BigDecimal column2Amount) {
		this.column2Amount = column2Amount;
	}

	public BigDecimal getColumn3Amount() {
		return this.column3Amount;
	}

	public void setColumn3Amount(BigDecimal column3Amount) {
		this.column3Amount = column3Amount;
	}

	public BigDecimal getColumn4Amount() {
		return this.column4Amount;
	}

	public void setColumn4Amount(BigDecimal column4Amount) {
		this.column4Amount = column4Amount;
	}

	public BigDecimal getColumn5Amount() {
		return this.column5Amount;
	}

	public void setColumn5Amount(BigDecimal column5Amount) {
		this.column5Amount = column5Amount;
	}

	public BigDecimal getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(BigDecimal createdUserId) {
		this.createdUserId = createdUserId;
	}

	public BigDecimal getCreatedPostId() {
		return this.createdPostId;
	}

	public void setCreatedPostId(BigDecimal createdPostId) {
		this.createdPostId = createdPostId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public BigDecimal getUpdatedUserId() {
		return this.updatedUserId;
	}

	public void setUpdatedUserId(BigDecimal updatedUserId) {
		this.updatedUserId = updatedUserId;
	}

	public BigDecimal getUpdatedPostId() {
		return this.updatedPostId;
	}

	public void setUpdatedPostId(BigDecimal updatedPostId) {
		this.updatedPostId = updatedPostId;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
