package com.tcs.sgv.common.valueobject;

// default package
// Generated Jan 17, 2008 2:14:46 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrDeclarationFlagDtlsData generated by hbm2java
 */
public class HrDeclarationFlagDtlsData implements java.io.Serializable {

	// Fields    

	private long flagDtlId;

	private CmnLanguageMst cmnLanguageMst;

	private CmnDatabaseMst cmnDatabaseMst;

	private HrDeclarationFlagMst hrDeclarationFlagMst;

	private OrgPostMst orgPostMstByCreatedPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;

	private OrgPostMst orgPostMstByUpdatedPost;

	private String label;

	private Integer order;

	private long flagDtlCode;

	private Date createdDate;

	private Date updatedDate;

	// Constructors

	/** default constructor */
	public HrDeclarationFlagDtlsData() {
	}

	/** minimal constructor */
	public HrDeclarationFlagDtlsData(long flagDtlId,
			CmnLanguageMst cmnLanguageMst,
			HrDeclarationFlagMst hrDeclarationFlagMst,
			OrgPostMst orgPostMstByCreatedPost,
			OrgUserMst orgUserMstByCreatedBy, Date createdDate) {
		this.flagDtlId = flagDtlId;
		this.cmnLanguageMst = cmnLanguageMst;
		this.hrDeclarationFlagMst = hrDeclarationFlagMst;
		this.orgPostMstByCreatedPost = orgPostMstByCreatedPost;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.createdDate = createdDate;
	}

	/** full constructor */
	public HrDeclarationFlagDtlsData(long flagDtlId,
			CmnLanguageMst cmnLanguageMst, CmnDatabaseMst cmnDatabaseMst,
			HrDeclarationFlagMst hrDeclarationFlagMst,
			OrgPostMst orgPostMstByCreatedPost, CmnLocationMst cmnLocationMst,
			OrgUserMst orgUserMstByUpdatedBy, OrgUserMst orgUserMstByCreatedBy,
			OrgPostMst orgPostMstByUpdatedPost, String label, Integer order,
			long flagDtlCode, Date createdDate, Date updatedDate) {
		this.flagDtlId = flagDtlId;
		this.cmnLanguageMst = cmnLanguageMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.hrDeclarationFlagMst = hrDeclarationFlagMst;
		this.orgPostMstByCreatedPost = orgPostMstByCreatedPost;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByUpdatedPost = orgPostMstByUpdatedPost;
		this.label = label;
		this.order = order;
		this.flagDtlCode = flagDtlCode;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	// Property accessors
	public long getFlagDtlId() {
		return this.flagDtlId;
	}

	public void setFlagDtlId(long flagDtlId) {
		this.flagDtlId = flagDtlId;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return this.cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return this.cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public HrDeclarationFlagMst getHrDeclarationFlagMst() {
		return this.hrDeclarationFlagMst;
	}

	public void setHrDeclarationFlagMst(
			HrDeclarationFlagMst hrDeclarationFlagMst) {
		this.hrDeclarationFlagMst = hrDeclarationFlagMst;
	}

	public OrgPostMst getOrgPostMstByCreatedPost() {
		return this.orgPostMstByCreatedPost;
	}

	public void setOrgPostMstByCreatedPost(OrgPostMst orgPostMstByCreatedPost) {
		this.orgPostMstByCreatedPost = orgPostMstByCreatedPost;
	}

	public CmnLocationMst getCmnLocationMst() {
		return this.cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return this.orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return this.orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgPostMst getOrgPostMstByUpdatedPost() {
		return this.orgPostMstByUpdatedPost;
	}

	public void setOrgPostMstByUpdatedPost(OrgPostMst orgPostMstByUpdatedPost) {
		this.orgPostMstByUpdatedPost = orgPostMstByUpdatedPost;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	public long getFlagDtlCode() {
		return this.flagDtlCode;
	}

	public void setFlagDtlCode(long flagDtlCode) {
		this.flagDtlCode = flagDtlCode;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
