package com.tcs.sgv.eis.valueobject;

// default package
// Generated Mar 8, 2008 1:13:59 PM by Hibernate Tools 3.2.0.beta8

/**
 * HrEmpnomineeDtlTxnId generated by hbm2java
 */
public class HrEisNomineeDtlTxnId implements java.io.Serializable {

	// Fields    

	private long reqId;

	private long memberId;

	// Constructors

	/** default constructor */
	public HrEisNomineeDtlTxnId() {
	}

	/** full constructor */
	public HrEisNomineeDtlTxnId(long reqId, long memberId) {
		this.reqId = reqId;
		this.memberId = memberId;
	}

	// Property accessors
	public long getReqId() {
		return this.reqId;
	}

	public void setReqId(long reqId) {
		this.reqId = reqId;
	}

	public long getMemberId() {
		return this.memberId;
	}

	public void setMemberId(long memberId) {
		this.memberId = memberId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HrEisNomineeDtlTxnId))
			return false;
		HrEisNomineeDtlTxnId castOther = (HrEisNomineeDtlTxnId) other;

		return (this.getReqId() == castOther.getReqId())
				&& (this.getMemberId() == castOther.getMemberId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getReqId();
		result = 37 * result + (int) this.getMemberId();
		return result;
	}

}
