package com.tcs.sgv.pension.valueobject;
// default package
// Generated Mar 26, 2008 4:01:17 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * CmnPayscaleMst generated by hbm2java
 */
public class CmnPayscaleMst implements java.io.Serializable {

	// Fields    

	private Long payscaleId;

	private String payscale;

	private String payscaleDesc;

	private Long langId;

	private Long createdBy;

	private Long createdByPost;

	private Date createdDate;

	private Long updatedBy;

	private Long updatedByPost;

	private Date updatedDate;

	// Constructors

	/** default constructor */
	public CmnPayscaleMst() {
	}

	/** minimal constructor */
	public CmnPayscaleMst(Long payscaleId, String payscale,
			Long langId, Long createdBy, Long createdByPost,
			Date createdDate) {
		this.payscaleId = payscaleId;
		this.payscale = payscale;
		this.langId = langId;
		this.createdBy = createdBy;
		this.createdByPost = createdByPost;
		this.createdDate = createdDate;
	}

	/** full constructor */
	public CmnPayscaleMst(Long payscaleId, String payscale,
			String payscaleDesc, Long langId, Long createdBy,
			Long createdByPost, Date createdDate, Long updatedBy,
			Long updatedByPost, Date updatedDate) {
		this.payscaleId = payscaleId;
		this.payscale = payscale;
		this.payscaleDesc = payscaleDesc;
		this.langId = langId;
		this.createdBy = createdBy;
		this.createdByPost = createdByPost;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedByPost = updatedByPost;
		this.updatedDate = updatedDate;
	}

	// Property accessors
	public Long getPayscaleId() {
		return this.payscaleId;
	}

	public void setPayscaleId(Long payscaleId) {
		this.payscaleId = payscaleId;
	}

	public String getPayscale() {
		return this.payscale;
	}

	public void setPayscale(String payscale) {
		this.payscale = payscale;
	}

	public String getPayscaleDesc() {
		return this.payscaleDesc;
	}

	public void setPayscaleDesc(String payscaleDesc) {
		this.payscaleDesc = payscaleDesc;
	}

	public Long getLangId() {
		return this.langId;
	}

	public void setLangId(Long langId) {
		this.langId = langId;
	}

	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	public Long getCreatedByPost() {
		return this.createdByPost;
	}

	public void setCreatedByPost(Long createdByPost) {
		this.createdByPost = createdByPost;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Long getUpdatedByPost() {
		return this.updatedByPost;
	}

	public void setUpdatedByPost(Long updatedByPost) {
		this.updatedByPost = updatedByPost;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
