package com.tcs.sgv.onlinebillprep.valueobject;
// default package
// Generated Sep 28, 2007 12:36:58 PM by Hibernate Tools 3.2.0.beta8


/**
 * HstTrnTarqstHdrId generated by hbm2java
 */
public class HstTrnTarqstHdrId implements java.io.Serializable {

	// Fields    

	private Long trnTarqstHdrId;

	private Integer trnCounter;

	// Constructors

	/** default constructor */
	public HstTrnTarqstHdrId() {
	}

	/** full constructor */
	public HstTrnTarqstHdrId(Long trnTarqstHdrId, Integer trnCounter) {
		this.trnTarqstHdrId = trnTarqstHdrId;
		this.trnCounter = trnCounter;
	}

	// Property accessors
	public Long getTrnTarqstHdrId() {
		return this.trnTarqstHdrId;
	}

	public void setTrnTarqstHdrId(Long trnTarqstHdrId) {
		this.trnTarqstHdrId = trnTarqstHdrId;
	}

	public Integer getTrnCounter() {
		return this.trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HstTrnTarqstHdrId))
			return false;
		HstTrnTarqstHdrId castOther = (HstTrnTarqstHdrId) other;

		return ((this.getTrnTarqstHdrId() == castOther.getTrnTarqstHdrId()) || (this
				.getTrnTarqstHdrId() != null
				&& castOther.getTrnTarqstHdrId() != null && this
				.getTrnTarqstHdrId().equals(castOther.getTrnTarqstHdrId())))
				&& ((this.getTrnCounter() == castOther.getTrnCounter()) || (this
						.getTrnCounter() != null
						&& castOther.getTrnCounter() != null && this
						.getTrnCounter().equals(castOther.getTrnCounter())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getTrnTarqstHdrId() == null ? 0 : this.getTrnTarqstHdrId()
						.hashCode());
		result = 37
				* result
				+ (getTrnCounter() == null ? 0 : this.getTrnCounter()
						.hashCode());
		return result;
	}

}
