package com.tcs.sgv.eis.valueobject;

// default package
// Generated Jul 14, 2011 4:22:06 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.ess.quarter.valueobject.HrQuaterTypeMst;
import com.tcs.sgv.ess.valueobject.OrgEmpMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;
import com.tcs.sgv.hod.common.valueobject.CmnAddressMst;

/**
 * HrEisQuarterDtls generated by hbm2java
 */
public class HrEisQuarterDtls implements java.io.Serializable {

	private long quarterDtlsId;
	private OrgUserMst orgUserMstByCreatedBy;
	private CmnLocationMst cmnLocationMst;
	private OrgUserMst orgUserMstByUpdatedBy;
	private HrQuaterTypeMst hrQuaterTypeMst;
	private CmnDatabaseMst cmnDatabaseMst;
	private OrgPostMst orgPostMstByCreatedByPost;
	private OrgEmpMst orgEmpMst;
	private OrgPostMst orgPostMstByUpdatedByPost;
	private CmnAddressMst cmnAddressMst;
	private CmnLookupMst govtAccomodationTypeLookup;
	private CmnLookupMst quarterAllottedToLookup;
	private Long rentAmount;
	private Long rentServiceCharge;
	private Long rentOtherCharge;
	private Integer isQuarterVacated;
	private Long vacatingLetterNo;
	private Date letterDate;
	private Date vacatedDate;
	private Date createdDate;
	private Date updatedDate;

	public HrEisQuarterDtls() {
	}

	public HrEisQuarterDtls(long quarterDtlsId, CmnLookupMst quarterAllottedTo) {
		this.quarterDtlsId = quarterDtlsId;
		this.quarterAllottedToLookup = quarterAllottedTo;
	}

	public HrEisQuarterDtls(long quarterDtlsId,
			OrgUserMst orgUserMstByCreatedBy, CmnLocationMst cmnLocationMst,
			OrgUserMst orgUserMstByUpdatedBy, HrQuaterTypeMst hrQuaterTypeMst,
			CmnDatabaseMst cmnDatabaseMst,
			OrgPostMst orgPostMstByCreatedByPost, OrgEmpMst orgEmpMst,
			OrgPostMst orgPostMstByUpdatedByPost, CmnAddressMst cmnAddressMst,
			CmnLookupMst govtAccomodationTypeLookup, CmnLookupMst quarterAllottedToLookup, Long rentAmount,
			Long rentServiceCharge, Long rentOtherCharge,
			Integer isQuarterVacated, Long vacatingLetterNo, Date letterDate,
			Date vacatedDate, Date createdDate, Date updatedDate) {
		this.quarterDtlsId = quarterDtlsId;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.hrQuaterTypeMst = hrQuaterTypeMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgEmpMst = orgEmpMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.cmnAddressMst = cmnAddressMst;
		this.govtAccomodationTypeLookup = govtAccomodationTypeLookup;
		this.quarterAllottedToLookup = quarterAllottedToLookup;
		this.rentAmount = rentAmount;
		this.rentServiceCharge = rentServiceCharge;
		this.rentOtherCharge = rentOtherCharge;
		this.isQuarterVacated = isQuarterVacated;
		this.vacatingLetterNo = vacatingLetterNo;
		this.letterDate = letterDate;
		this.vacatedDate = vacatedDate;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public long getQuarterDtlsId() {
		return this.quarterDtlsId;
	}

	public void setQuarterDtlsId(long quarterDtlsId) {
		this.quarterDtlsId = quarterDtlsId;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return this.orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public CmnLocationMst getCmnLocationMst() {
		return this.cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return this.orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public HrQuaterTypeMst getHrQuaterTypeMst() {
		return this.hrQuaterTypeMst;
	}

	public void setHrQuaterTypeMst(HrQuaterTypeMst hrQuaterTypeMst) {
		this.hrQuaterTypeMst = hrQuaterTypeMst;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return this.cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return this.orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(
			OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgEmpMst getOrgEmpMst() {
		return this.orgEmpMst;
	}

	public void setOrgEmpMst(OrgEmpMst orgEmpMst) {
		this.orgEmpMst = orgEmpMst;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return this.orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(
			OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public CmnAddressMst getCmnAddressMst() {
		return this.cmnAddressMst;
	}

	public void setCmnAddressMst(CmnAddressMst cmnAddressMst) {
		this.cmnAddressMst = cmnAddressMst;
	}

	public CmnLookupMst getGovtAccomodationTypeLookup() {
		return this.govtAccomodationTypeLookup;
	}

	public void setGovtAccomodationTypeLookup(CmnLookupMst govtAccomodationTypeLookup) {
		this.govtAccomodationTypeLookup = govtAccomodationTypeLookup;
	}

	public CmnLookupMst getQuarterAllottedToLookup() {
		return this.quarterAllottedToLookup;
	}

	public void setQuarterAllottedToLookup(CmnLookupMst quarterAllottedToLookup) {
		this.quarterAllottedToLookup = quarterAllottedToLookup;
	}

	public Long getRentAmount() {
		return this.rentAmount;
	}

	public void setRentAmount(Long rentAmount) {
		this.rentAmount = rentAmount;
	}

	public Long getRentServiceCharge() {
		return this.rentServiceCharge;
	}

	public void setRentServiceCharge(Long rentServiceCharge) {
		this.rentServiceCharge = rentServiceCharge;
	}

	public Long getRentOtherCharge() {
		return this.rentOtherCharge;
	}

	public void setRentOtherCharge(Long rentOtherCharge) {
		this.rentOtherCharge = rentOtherCharge;
	}

	public Integer getIsQuarterVacated() {
		return this.isQuarterVacated;
	}

	public void setIsQuarterVacated(Integer isQuarterVacated) {
		this.isQuarterVacated = isQuarterVacated;
	}

	public Long getVacatingLetterNo() {
		return this.vacatingLetterNo;
	}

	public void setVacatingLetterNo(Long vacatingLetterNo) {
		this.vacatingLetterNo = vacatingLetterNo;
	}

	public Date getLetterDate() {
		return this.letterDate;
	}

	public void setLetterDate(Date letterDate) {
		this.letterDate = letterDate;
	}

	public Date getVacatedDate() {
		return this.vacatedDate;
	}

	public void setVacatedDate(Date vacatedDate) {
		this.vacatedDate = vacatedDate;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
