<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@ taglib prefix="hdiits" uri="http://hdiits.tcs.com"%>
<%@ taglib uri="http://ajaxtags.org/tags/ajax" prefix="ajax"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="display" uri="http://displaytag.sf.net" %>

<fmt:setBundle basename="resources.dcps.dcpsLabels" var="dcpsLables"scope="request" />

<script type="text/javascript" src="script/common/ajax_saveData.js"> </script>
<script type="text/javascript" src="script/common/CalendarPopup.js"></script>
<script type="text/javascript" src="script/dppf/calendarDppf.js"></script>
<script type="text/javascript"  src="script/dcps/dcpsvalidation.js"></script>

<c:set var="resultObj" value="${result}"></c:set>
<c:set var="resValue" value="${resultObj.resultValue}"></c:set>
<c:set var="lListContri" value="${resValue.lListContri}"></c:set>
<c:set var="totalRecords" value="${resValue.totalRecords}"></c:set>
<c:set var="UserType" value="${resValue.UserType}"></c:set>

<script>

function window_new_update(url)
{
	var newWindow = null;
   	var height = screen.height - 150;
   	var width = screen.width;
   	var urlstring = url;
   	var urlstyle = "height="+height+",width="+width+",toolbar=no,minimize=no,status=yes,menubar=no,location=no,scrollbars=yes,top=0,left=0";
   	newWindow = window.open(urlstring, "DepositAccMst", urlstyle);
}

function getPostEmpDetails()
{
	var finYear=document.getElementById("cmbFinYear").value;
	var contriMonth=document.getElementById("cmbMonth").value;

	
	if(finYear != -1 && contriMonth != -1)
	{
		self.location.href = "ifms.htm?actionFlag=loadPostEmpContri&UserType=SRKA&elementId=700103&finYear="+finYear+"&contriMonth="+contriMonth;
	}

	
}

function updateContributions(action){
	
	var totalContributions= document.getElementById("vo").rows.length - 1;
	var postEmpContriIds = "";
	var billNo = "";
	var billAmount = "";
	var flag=0;
	
	for(var i=1;i<=totalContributions;i++)
	{
		if(document.getElementById("checkbox"+i).checked == true)
		{
			
			postEmpContriIds = postEmpContriIds + document.getElementById("checkbox"+i).value + "~" ;
			// Code Added By Vihan
			if(action == "F")
			{
				if(document.getElementById("hidCaseStatus"+i).value == "A")
				{
					alert('Sorry.You cannot forward the bill '+ document.getElementById("txtBillNo"+i).value + ' as it has already been approved. Please deselect these bills.'  );
					return;
				}
			}
			
			flag = 1;
		}
	}
	if(flag == 1)
	{
		var uri="ifms.htm?actionFlag=actOnPostEmpContriToPAO";
		var url="action="+action+"&postEmpContriIds="+postEmpContriIds;
		updateContributionsUsingAjax(uri,url,action);
	}
	else
	{
		alert("Please select a bill");
		return;
	}
}
function updateContributionsUsingAjax(uri,url,action){
	
	var myAjax = new Ajax.Request(uri,
		       {
		        method: 'post',
		        asynchronous: false,
		        parameters:url,
		        onSuccess: function(myAjax) {
					dataStateChangedForUpdateConti(myAjax,action);
				},
		        onFailure: function(){ alert('Something went wrong...');} 
		          } );
}

function dataStateChangedForUpdateConti(myAjax,action)
{
	XMLDoc = myAjax.responseXML.documentElement;
	var XMLEntries  = XMLDoc.getElementsByTagName('XMLDOC');
	var successFlag = XMLEntries[0].childNodes[0].firstChild.nodeValue;
	if(successFlag)
	{
		sendAlert(action);
		self.location.reload(true);
	}
}

function sendAlert(url){
	
	if(url=='F'){
		alert("The cases are forwarded to PAO.");
	}
	else if(url=='A'){
		alert("The cases are approved.");
	}
	else if(url=='R'){
		alert("The cases are rejected.");
	}
	else if(url=='S'){
		alert("The cases are saved.");
	}
}

function AutoGenerateData(){
	
	 var finYearId = document.getElementById("cmbFinYear").value;
	 var uri = "ifms.htm?actionFlag=getSancBudgetForFinYear";
	 var url = "finYearId="+ finYearId ;

	 var myAjax = new Ajax.Request(uri,
		       {
		        method: 'post',
		        asynchronous: false,
		        parameters:url,
		        onSuccess: function(myAjax) {
					dataStateChangedForAutoGenerateData(myAjax);
				},
		        onFailure: function(){ alert('Something went wrong...');} 
		          } );
}

function dataStateChangedForAutoGenerateData(myAjax)
{
	XMLDoc = myAjax.responseXML.documentElement;
	var XmlHiddenValues = XMLDoc.getElementsByTagName('XMLDOC');
	var SancBudget = XmlHiddenValues[0].childNodes[0].firstChild.nodeValue;
	var expnTillDt = XmlHiddenValues[0].childNodes[1].firstChild.nodeValue;
	var BillNo = XmlHiddenValues[0].childNodes[2].firstChild.nodeValue;
	var ExcessAmount = XmlHiddenValues[0].childNodes[3].firstChild.nodeValue;
	var AvailableBudget = SancBudget-expnTillDt;
	
		
	document.getElementById("txtSancBudget").value=SancBudget;
	document.getElementById("txtETD").value=expnTillDt;
	if(AvailableBudget < 0 )
	{
		document.getElementById("txtAvailableBudget").value= "0";
	}
	else
	{
		document.getElementById("txtAvailableBudget").value=AvailableBudget;
	}
	document.getElementById("txtBillAmount").value="";
	document.getElementById("txtExcessAmount").value=ExcessAmount;
	document.getElementById("txtBillNo").value=BillNo;
	document.getElementById("btnExcess").disabled=true;
}

function AddBillData()
{
	if(!chkEmpty(document.getElementById('cmbFinYear'),'Financial Year'))
	{
		return false; 
	}
	
	if(!chkEmpty(document.getElementById('cmbMonth'),'Month'))
	{
		return false;
	}
	if(!chkEmpty(document.getElementById('txtBillNo'),'Bill No'))
	{
		return false;
	}
	if(!chkEmpty(document.getElementById('txtBillAmount'),'Expenditure in Current Bill'))
	{
		alert('Please enter expenditure in current bill');
		return false;
	}
	if(document.getElementById('txtBillAmount').value == 0)
	{
			alert('Please enter expenditure in current bill');
			return false;
	}
	var billAmount = parseInt(document.getElementById("txtBillAmount").value);
	var availableBudget = parseInt(document.getElementById("txtAvailableBudget").value);
	var excessAmount = parseInt(document.getElementById("txtExcessAmount").value);
	var initialExcessAmount = parseInt(document.getElementById("txtInitialExcessAmount").value);
	

	if(billAmount>availableBudget)
	{
		if(excessAmount != (initialExcessAmount+billAmount-availableBudget))
		{
			alert("Bill Amount is greater than Available Budget. Click on 'Allow Excess Expense' button to save the records.");
			document.getElementById("btnExcess").disabled = false;
			document.getElementById("btnExcess").readOnly = false;
			return false;
		}
	}
	SaveDataUsingAjax();
	return true;
}

function SaveDataUsingAjax()
{
	var finYear=document.getElementById("cmbFinYear").value;
	var contriMonth=document.getElementById("cmbMonth").value;
	var billNo=document.getElementById("txtBillNo").value;
	var billAmount=document.getElementById("txtBillAmount").value;
	var excessAmount=document.getElementById("txtExcessAmount").value;
	var uri = "ifms.htm?actionFlag=savePostEmpContri";
	var url = "UserType=SRKA&StatusFlag=D&finYear="+finYear+
				"&contriMonth="+contriMonth+"&billNo="+billNo+"&billAmount="+billAmount+"&txtExcessAmount="+excessAmount;

	var myAjax = new Ajax.Request(uri,
		       {
		        method: 'post',
		        asynchronous: false,
		        parameters:url,
		        onSuccess: function(myAjax) {
					dataStateChangedForSaveData(myAjax);
				},
		        onFailure: function(){ alert('Something went wrong...');} 
		          } );
}

function dataStateChangedForSaveData(myAjax)
{
	XMLDoc = myAjax.responseXML.documentElement;
	var XMLEntries  = XMLDoc.getElementsByTagName('XMLDOC');
	var successFlag = XMLEntries[0].childNodes[0].firstChild.nodeValue;
	if(successFlag)
	{
		alert("Record Entered Successfully");
		self.location.reload(true);
	}
}
function validateBillAmt(){
	
	var billAmount = document.getElementById("txtBillAmount").value;
	var availableBudget = document.getElementById("txtAvailableBudget").value;
	if(parseInt(billAmount)>parseInt(availableBudget)){
		
		alert("Bill Amount is greater than Available Budget. Click on 'Allow Excess Expense' button to save the records.");
		document.getElementById("btnExcess").disabled = false;
		document.getElementById("btnExcess").readOnly = false;
		
		return false;
	}
	else
	{
		document.getElementById("txtExcessAmount").value = 0;
		document.getElementById("btnExcess").disabled = true;
		document.getElementById("btnExcess").readOnly = true;
	}
	return true;
}

function getExcessAmount()
{
	var billAmount = document.getElementById("txtBillAmount").value;
	var availableBudget = document.getElementById("txtAvailableBudget").value;
	
		
	document.getElementById("txtExcessAmount").value = parseInt(document.getElementById("txtInitialExcessAmount").value) + parseInt(billAmount - availableBudget);
		
		
}
function saveVoucherDetails(action){
	
	var totalContributions= document.getElementById("vo").rows.length - 1;
	var postEmpContriIds = "";
	var billNo = "";
	var billAmount = "";
	var voucherNo = "";
	var voucherDate = "";
	
	var flag=0;
	
	for(var i=1;i<=totalContributions;i++)
	{
		if(document.getElementById("checkbox"+i).checked == true)
		{
			postEmpContriIds = postEmpContriIds + document.getElementById("checkbox"+i).value + ":" ;
			billNo = billNo + document.getElementById("txtBillNo"+i).value + ":" ;
			billAmount = billAmount + document.getElementById("txtBillAmount"+i).value + ":" ;
			
			if(document.getElementById("txtVoucherNo"+i).value == "")
			{
				voucherNo= voucherNo + "NULL" + ":";
			}
			else
			{
				voucherNo= voucherNo + document.getElementById("txtVoucherNo"+i).value + ":";
			} 
			
			if(document.getElementById("txtVoucherDate"+i).value == "")
			{
				voucherDate= voucherDate + "NULL" + ":" ;
			}
			else
			{
				voucherDate= voucherDate + document.getElementById("txtVoucherDate"+i).value + ":" ;
			}

			
			
			flag = 1;
		}
	}
	if(flag == 1)
	{
		var uri = "ifms.htm?actionFlag=savePostEmpContriRows";
		var url = "postEmpContriIds="+postEmpContriIds+"&billNo="+billNo
		+"&billAmount="+billAmount+"&voucherNo="+voucherNo+"&voucherDate="+voucherDate;
		updateContributionsUsingAjax(uri,url,action);
	}
	else
	{
		alert("Please select a contribution");
	}
}

function generateBill(){

	var postEmpContriPkId = "";
	var totalContributions= document.getElementById("vo").rows.length - 1;
	var totalContributionsSelected = 0;
	var caseStatus;

	for(var i=1;i<=totalContributions;i++)
	{
		if(document.getElementById("checkbox"+i).checked == true)
		{
			totalContributionsSelected++ ; 
		}
	}

	if(totalContributionsSelected == 0)
	{
		alert('Please select a bill');
		return false;
	}

	if(totalContributionsSelected > 1)
	{
		alert('Please select only one bill');
		return false;
	}

	for(i=1;i<=totalContributions;i++)
	{
		if(document.getElementById("checkbox"+i).checked == true)
		{
			postEmpContriPkId = document.getElementById("checkbox"+i).value;
			caseStatus = document.getElementById("hidCaseStatus"+i).value;
		}
	}

	if(caseStatus == 'R')
	{
		alert('Bill can not be generated for a rejected bill');
		return false;
	}

	if(caseStatus == 'A' || caseStatus == 'D')
	{
		url = "ifms.htm?actionFlag=reportService&reportCode=700032&action=generateReport&postEmpContriPkId="+postEmpContriPkId+"&asPopup=TRUE";
		window_new_update(url);
	}
}

</script>

<hdiits:form name="DCPSPostEmpContriForm" id="DCPSPostEmpContriForm" encType="multipart/form-data" validate="true" method="post" >
	<input type="hidden" id="ForwardToPost" name="ForwardToPost" value="${UpperUserList[0]}"/>
	<table width="100%">
	<c:if test="${UserType == 'SRKA'}">
	   <tr>
		  <td></td>
   		  <td>
 				<fieldset style="width: 100%" class="tabstyle">
					<legend><b>Select Year</b></legend>
   					<table align="left" width="70%" >
   						<tr align="center">
					       <td align="left" width="30%"><fmt:message key="CMN.FINANCIALYEAR"
									bundle="${dcpsLables}"></fmt:message>
						   </td>
						   
						   <td align="left" width="30%">
								<select name="cmbFinYear" id="cmbFinYear" maxlength="10" onchange="AutoGenerateData();">
								<option value="-1"><fmt:message key="COMMON.DROPDOWN.SELECT" /></option>
								<c:forEach var="finYear" items="${resValue.lLstFinYear}" >
								<c:choose>
								<c:when test="${resValue.FinYear == finYear.id }">
									<option value="${finYear.id}" selected="selected" ><c:out value="${finYear.desc}"></c:out></option>
								</c:when>
								<c:otherwise>
									<option value="${finYear.id}" ><c:out value="${finYear.desc}"></c:out></option>
								</c:otherwise>					         					
								</c:choose>
								</c:forEach>
								
								</select>&nbsp;&nbsp;<label class="mandatoryindicator">*</label>
						   </td>
						   <td align="left" width="30%"><fmt:message key="CMN.SANCBUDGET"
									bundle="${dcpsLables}"></fmt:message>
						   </td>
						   
						   <td align="left" width="30%">
						       <input type="text"  size="20%" name='txtSancBudget' id="txtSancBudget" maxlength="10" style="text-align: left" readonly="readonly" value="${resValue.SancBudget }"/>
						   </td>
					 </tr>
					 <tr align="center">
					       <td align="left" width="30%"><fmt:message key="CMN.MONTH"
									bundle="${dcpsLables}"></fmt:message>
						   </td>
						   
						   <td align="left" width="30%">
								<select name="cmbMonth" id="cmbMonth" onchange="getPostEmpDetails();">
								
									<option value="-1"><fmt:message key="COMMON.DROPDOWN.SELECT"/></option>
										<c:forEach var="month" items="${resValue.MONTHS}" >
										<c:choose>
											<c:when test="${resValue.ContriMonth == month.id }">
											<option value="${month.id}" selected="selected"><c:out value="${month.desc}"></c:out></option>
											</c:when>
											<c:otherwise>
											<option value="${month.id}"><c:out value="${month.desc}"></c:out></option>
											</c:otherwise>
											</c:choose>
										</c:forEach>
								</select>&nbsp;&nbsp;<label class="mandatoryindicator">*</label>
						   </td>
						   <td align="left" width="30%"><fmt:message key="CMN.ETD"
									bundle="${dcpsLables}"></fmt:message>
						   </td>
						   
						   <td align="left" width="30%">
						       <input type="text"  size="20%" name='txtETD' id="txtETD" maxlength="10" style="text-align: left" readonly="readonly"  value="${resValue.Expenditure }"/>
						   </td>
					 </tr>
					 <tr align="center">
					       <td align="left" width="30%"><fmt:message key="CMN.BILLNO"
									bundle="${dcpsLables}"></fmt:message>
						   </td>
						   
						   <td align="left" width="30%">
						       <input type="text"  size="20%" name='txtBillNo' id="txtBillNo" maxlength="10" style="text-align: left" readOnly="readOnly" value="${resValue.BillNo }"/>
						       
						   </td>
						   <td align="left" width="30%"><fmt:message key="CMN.BUDGET"
									bundle="${dcpsLables}"></fmt:message>
						   </td>
						   
						   <td align="left" width="30%">
						       <input type="text"  size="20%" name='txtAvailableBudget' id="txtAvailableBudget" maxlength="10" style="text-align: left" readonly="readonly"  value="${resValue.AvailBudget }"/>
						   </td>
					 </tr>
					 <tr align="center">
					       <td align="left" width="30%"><fmt:message key="CMN.BILLAMOUNT"
									bundle="${dcpsLables}"></fmt:message>
						   </td>
						   
						   <td align="left" width="45%">
						       <input type="text"  size="20%" name='txtBillAmount' id="txtBillAmount" maxlength="10" style="text-align: left" onkeypress="digitFormat(this);" onblur="validateBillAmt();" value="${resValue.ExpInCurrBill}"/>
						       &nbsp;&nbsp;<label class="mandatoryindicator">*</label>
						   </td>
						   <td align="left" width="30%">
						   <fmt:message key="CMN.EXCESS"
									bundle="${dcpsLables}"></fmt:message>
						   </td>
						   
						   <td align="left" width="30%">
						   	<input type="text"  size="20%" name='txtExcessAmount' id="txtExcessAmount" maxlength="10" style="text-align: left" readonly="readonly"  value="${resValue.ExcessAmount }"/>
						   	<input type="text"  size="20%" name='txtInitialExcessAmount' id="txtInitialExcessAmount" maxlength="10" style="display:none" readonly="readonly"  value="${resValue.ExcessAmount }"/>
						   </td>
					 </tr>
   					</table>
	   		</fieldset>
   			</td>
   			<td></td>
   		</tr>

		<tr align="center">
		<td></td>
		<td>
			<hdiits:button name="btnAdd" id="btnAdd" type="button" captionid="BTN.SAVE" bundle="${dcpsLables}" onclick="AddBillData();" />
			
			<hdiits:button name="btnExcess" id="btnExcess" type ="button" classcss="bigbutton" captionid="BTN.ALLOWEXCESS" bundle="${dcpsLables}" onclick="getExcessAmount();" readonly="true" />
		</td>
		<td>
		</td>
		</tr>
		</c:if>
	   <tr>
		   <td></td>
		   <td id="displayTable" >
		   
			<fieldset style="width: 100%" class="tabstyle">
				<legend id="headerMsg">
					<b>Post Employer Contribution </b>
				</legend>
    					<display:table list="${lListContri}" id="vo" cellpadding="4" style="width:80%" pagesize="100" export="false"  >    			      			        			      			      			  		         		         				
			              <display:setProperty name="paging.banner.placement" value="bottom" />
			              
			              <display:column style="text-align: left;"  title="" headerClass="datatableheader" class="oddcentre">
			              	<c:if test="${vo[7] == 'D' || vo[7] == 'R' || vo[7] == 'A'}">
			              	   		<input type="checkbox" id="checkbox${vo_rowNum}" name="checkbox" value="${vo[0]}"/>
			              	</c:if> 	
			              	<c:if test="${vo[7] == 'F'}">
			              		<c:if test ="${UserType == 'SRKA'}">
			              	   		<input type="checkbox" id="checkbox${vo_rowNum}" name="checkbox" value="${vo[0]}" disabled="disabled"/>
			              	   		</c:if>
			              	   		<c:if test ="${UserType == 'PAO'}">
			              	   		<input type="checkbox" id="checkbox${vo_rowNum}" name="checkbox" value="${vo[0]}"/>
			              	   		</c:if>
			              	</c:if>
			              	<input type ="hidden" name="hidCaseStatus" id="hidCaseStatus${vo_rowNum}" value="${vo[7]}"></input>
			              </display:column>
			              
			              <display:column  style="text-align:left" title= "Year" headerClass="datatableheader" class="oddcentre">
				              <c:forEach var="finYear" items="${resValue.lLstFinYear}">
					          	<c:choose>
									<c:when test="${vo[1] == finYear.id}">
										<c:out value="${finYear.desc}"></c:out>
									</c:when>
								</c:choose>
							  </c:forEach>
				          	
				          </display:column>
				          <display:column  style="text-align:left" title= "Month" headerClass="datatableheader" class="oddcentre">
				          	<c:forEach var="month" items="${resValue.MONTHS}">
					          	<c:choose>
									<c:when test="${vo[2] == month.id}">
										<c:out value="${month.desc}"></c:out>
									</c:when>
								</c:choose>
							  </c:forEach>
				          </display:column>
				          	
			              <display:column  style="text-align:left" title= "Bill No" headerClass="datatableheader" class="oddcentre" >	
			               	<c:if test="${vo[7] == 'D' || vo[7] == 'R'}">
				           		<input type="text" id="txtBillNo${vo_rowNum}" name="txtBillNo${vo_rowNum}" value="${vo[3]}" />
				           	</c:if> 
				           	<c:if test="${vo[7] == 'A' || vo[7] == 'F'}">
				           		<input type="text" id="txtBillNo${vo_rowNum}" name="txtBillNo${vo_rowNum}" value="${vo[3]}" readonly="readonly"/>
				           	</c:if>
			               			      
				          </display:column>
			              	
			              <display:column  style="text-align:left" title= "Bill Amount" headerClass="datatableheader" class="oddcentre">
			              	<c:if test="${vo[7] == 'D' || vo[7] == 'R'}">
				           		<input type="text" id="txtBillAmount${vo_rowNum}" name="txtBillAmount${vo_rowNum}" value="${vo[4]}" style="text-align:right"/>
				           	</c:if> 
				           	<c:if test="${vo[7] == 'A' || vo[7] == 'F'}">
				           		<input type="text" id="txtBillAmount${vo_rowNum}" name="txtBillAmount${vo_rowNum}" value="${vo[4]}" readonly="readonly" style="text-align:right"/>
				           	</c:if>
			               	
				          </display:column>
				                		         
			              	              	              
			              <display:column style="text-align: left;"  title="Voucher No" headerClass="datatableheader" class="oddcentre">
				           	<c:if test="${vo[7] == 'D' || vo[7] == 'R' || vo[7] == 'F'}">
				           		<input type="text" id="txtVoucherNo${vo_rowNum}" name="txtVoucherNo${vo_rowNum}" value="${vo[5]}" readonly="readonly"/>
				           	</c:if> 
				           	<c:if test="${vo[7] == 'A' }">
				           		<input type="text" id="txtVoucherNo${vo_rowNum}" name="txtVoucherNo${vo_rowNum}" value="${vo[5]}" />
				           	</c:if>		           	          
			              </display:column>
			              
			              <display:column style="text-align:left;"  title="Voucher Date" headerClass="datatableheader" class="oddcentre">
			              
			              <c:choose>
			              	<c:when test="${vo[6] != null}">
			              		<fmt:formatDate dateStyle="full" pattern="dd/MM/yyyy" value="${vo[6]}" var="voucherDate"/>
			              	</c:when>
			              	<c:otherwise>
			              		<c:set var="voucherDate" value="" ></c:set>
			              	</c:otherwise>
			              
			              </c:choose>
			              
				          	<c:if test="${vo[7] == 'D' || vo[7] == 'R'  || vo[7] == 'F'}">
				           		<input type="text" id="txtVoucherDate${vo_rowNum}" style="text-transform: uppercase" size="20"
									onkeypress="digitFormat(this);dateFormat(this);"
									name="txtVoucherDate${vo_rowNum}" value="${voucherDate}" readonly="readonly"/>
				           	</c:if> 
				           	<c:if test="${vo[7] == 'A'}">
				           		<input type="text" id="txtVoucherDate${vo_rowNum}" style="text-transform: uppercase" size="20"
									onkeypress="digitFormat(this);dateFormat(this);"
									name="txtVoucherDate${vo_rowNum}" value="${voucherDate}" /><img
									src='images/CalendarImages/ico-calendar.gif' width='20'
									onClick='window_open(event,"txtVoucherDate${vo_rowNum}", 375, 570)'
									style="cursor: pointer;"/>
				           	</c:if>
			              </display:column>
			              
			              <display:column  style="text-align:left" title= "Status" headerClass="datatableheader" class="oddcentre">
				          	<c:if test="${vo[7] == 'D'}"><c:out value="Draft"></c:out></c:if>
			               	<c:if test="${vo[7] == 'F'}"><c:out value="Pending for Approval"></c:out></c:if>
			               	<c:if test="${vo[7] == 'R'}"><c:out value="Rejected"></c:out></c:if> 		
			               	<c:if test="${vo[7] == 'A'}"><c:out value="Approved"></c:out></c:if> 	
				          </display:column>		
			              
			          
			              
     					</display:table>
     					</fieldset>
      		</td>
      		</tr><tr><td>
     		<input type="hidden" id="finYearId" name="finYearId" value="${vo[8]}"/>
     	</td>
     	<td></td>
     	</tr>
		<tr>
		<td></td>
		<td align="center">
			<c:if test="${totalRecords!=0 && lListContri!=null}"> 
				<c:if test="${UserType == 'SRKA'}">
					<table align="center">
						<tr align="center">
							<td align="center">
								<hdiits:button name="btnForward" id="btnForward" type="button" captionid="BTN.FORWARD" bundle="${dcpsLables}" onclick="updateContributions('F')"/>
								<hdiits:button name="btnGenerateBill" id="btnGenerateBill" type="button" captionid="BTN.GENERATEBILL" bundle="${dcpsLables}" onclick="generateBill()"/>
								<hdiits:button name="btnSaveVoucherDetails" id="btnSaveVoucherDetails" type="button" captionid="BTN.SAVE" bundle="${dcpsLables}" onclick="saveVoucherDetails('S')"/>
							</td>
						</tr>
					</table>
				</c:if>

				<c:if test="${UserType == 'PAO'}">
				    <div align="center" >
						<hdiits:button name="btnApprove" id="btnApprove" type="button" captionid="BTN.APPROVE" bundle="${dcpsLables}" onclick="updateContributions('A');" />
						<hdiits:button name="btnReject" id="btnReject" type="button" captionid="BTN.REJECT" bundle="${dcpsLables}" onclick="updateContributions('R');" />
					</div>
				</c:if>
			</c:if>	
		</td>
		<td></td>
		</tr>
	</table>	   
</hdiits:form>
