// default package
// Generated Aug 2, 2007 4:06:32 PM by Hibernate Tools 3.2.0.beta8
package com.tcs.sgv.eis.valueobject;
import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrLoanEmpPrinRecoverDtls generated by hbm2java
 */
public class HrLoanEmpPrinRecoverDtls implements java.io.Serializable {

	// Fields    

	private long prinRecoverId;

	private HrLoanEmpDtls hrLoanEmpDtls;

	private long totalRecoveredAmt;

	private long totalRecoveredInst;

	private Date createdDate;

	private Date updatedDate;
	
	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;
	
	private Integer trnCounter;
	

	// Constructors

	/** default constructor */
	public HrLoanEmpPrinRecoverDtls() {
	}

	/** minimal constructor */
	public HrLoanEmpPrinRecoverDtls(long prinRecoverId,
			HrLoanEmpDtls hrLoanEmpDtls, long totalRecoveredAmt,
			long totalRecoveredInst, Date createdDate,
			CmnDatabaseMst cmnDatabaseMst,CmnLocationMst 
			cmnLocationMst, OrgUserMst orgUserMstByCreatedBy, 
			OrgPostMst orgPostMstByCreatedByPost) {
		this.prinRecoverId = prinRecoverId;
		this.hrLoanEmpDtls = hrLoanEmpDtls;
		this.totalRecoveredAmt = totalRecoveredAmt;
		this.totalRecoveredInst = totalRecoveredInst;
		this.createdDate = createdDate;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	/** full constructor */
	public HrLoanEmpPrinRecoverDtls(long prinRecoverId,
			HrLoanEmpDtls hrLoanEmpDtls, long totalRecoveredAmt,
			long totalRecoveredInst, Date createdDate, Date updatedDate,
			CmnDatabaseMst cmnDatabaseMst,CmnLocationMst 
			cmnLocationMst, OrgUserMst orgUserMstByCreatedBy, 
			OrgPostMst orgPostMstByCreatedByPost,
			OrgUserMst orgUserMstByUpdatedBy,  OrgPostMst orgPostMstByUpdatedByPost,Integer trnCounter) {
		this.prinRecoverId = prinRecoverId;
		this.hrLoanEmpDtls = hrLoanEmpDtls;
		this.totalRecoveredAmt = totalRecoveredAmt;
		this.totalRecoveredInst = totalRecoveredInst;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.trnCounter = trnCounter;
	}

	// Property accessors
	public long getPrinRecoverId() {
		return this.prinRecoverId;
	}

	public void setPrinRecoverId(long prinRecoverId) {
		this.prinRecoverId = prinRecoverId;
	}

	public HrLoanEmpDtls getHrLoanEmpDtls() {
		return this.hrLoanEmpDtls;
	}

	public void setHrLoanEmpDtls(HrLoanEmpDtls hrLoanEmpDtls) {
		this.hrLoanEmpDtls = hrLoanEmpDtls;
	}

	public long getTotalRecoveredAmt() {
		return this.totalRecoveredAmt;
	}

	public void setTotalRecoveredAmt(long totalRecoveredAmt) {
		this.totalRecoveredAmt = totalRecoveredAmt;
	}

	public long getTotalRecoveredInst() {
		return this.totalRecoveredInst;
	}

	public void setTotalRecoveredInst(long totalRecoveredInst) {
		this.totalRecoveredInst = totalRecoveredInst;
	}

	
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public Integer getTrnCounter() {
		return trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}

}
