package com.tcs.sgv.eis.valueobject;
// Generated Aug 13, 2007 12:49:41 PM by Hibernate Tools 3.2.0.beta8

//Comment By Maruthi For import Organisation.
import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.MstBankPay;
import com.tcs.sgv.common.valueobject.RltBankBranchPay;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrEisBankDtls generated by hbm2java
 */
public class HrEisBankDtls implements java.io.Serializable {

	// Fields    


	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;
	
	private long bankDtlId;

	private HrEisEmpMst hrEisEmpMst;

	private RltBankBranchPay rltBankBranch;

	private MstBankPay mstBank;

	private String bankAcctNo;

	public void setBankAcctNo(String bankAcctNo) {
		this.bankAcctNo = bankAcctNo;
	}

	private Date bankAcctStartDt;

	public String getBankAcctNo() {
		return bankAcctNo;
	}

	private long bankAcctType;
	
    private Date createdDate;

	private Date updatedDate;

	

	// Constructors

	/** default constructor */
	public HrEisBankDtls() {
	}

	/** minimal constructor */
	public HrEisBankDtls(long bankDtlId) {
		this.bankDtlId = bankDtlId;
	}

	/** full constructor  */
	public HrEisBankDtls(long bankDtlId, HrEisEmpMst hrEisEmpMst,
			HrEisBranchMst hrEisBranchMst, HrEisBankMst hrEisBankMst,
			String bankAcctNo, Date bankAcctStartDt,
			long bankAcctType, long dbId, long createdBy,
			long createdByPost, Date createdDate, long updatedBy,
			long updatedByPost, Date updatedDate, RltBankBranchPay rltBankBranch, MstBankPay mstBank) {
		this.bankDtlId = bankDtlId;
		this.hrEisEmpMst = hrEisEmpMst;
		this.rltBankBranch = rltBankBranch;
		this.mstBank = mstBank;
		this.bankAcctNo = bankAcctNo;
		this.bankAcctStartDt = bankAcctStartDt;
		this.bankAcctType = bankAcctType;		
	}

	// Property accessors
	public long getBankDtlId() {
		return this.bankDtlId;
	}

	public void setBankDtlId(long bankDtlId) {
		this.bankDtlId = bankDtlId;
	}

	public HrEisEmpMst getHrEisEmpMst() {
		return this.hrEisEmpMst;
	}

	public void setHrEisEmpMst(HrEisEmpMst hrEisEmpMst) {
		this.hrEisEmpMst = hrEisEmpMst;
	}

	

	public RltBankBranchPay getRltBankBranch() {
		return rltBankBranch;
	}

	public void setRltBankBranch(RltBankBranchPay rltBankBranchPay) {
		this.rltBankBranch = rltBankBranchPay;
	}

	



	/**
	 * @return the MstBankPay
	 */
	public MstBankPay getMstBank() {
		return mstBank;
	}

	/**
	 * @param mstBank the mstBank to set
	 */
	public void setMstBank(MstBankPay mstBank) {
		this.mstBank = mstBank;
	}

	public Date getBankAcctStartDt() {
		return this.bankAcctStartDt;
	}

	public void setBankAcctStartDt(Date bankAcctStartDt) {
		this.bankAcctStartDt = bankAcctStartDt;
	}

	public long getBankAcctType() {
		return this.bankAcctType;
	}

	public void setBankAcctType(long bankAcctType) {
		this.bankAcctType = bankAcctType;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	

	
	

}
