package com.tcs.sgv.onlinebillprep.valueobject;
// Generated Sep 7, 2007 2:50:34 PM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;

/**
 * TrnMedblHdr generated by hbm2java
 */
public class TrnMedblHdr implements java.io.Serializable
{

    // Fields    

    private Long trnMedblHdrId;

    private Long billNo;

    private String empName;

    private String empDesgn;

    private String monthCode;

    private Date billPassedDate;

    private BigDecimal billPassedAmt;

    private Long attachmentId;

    private String deptName;

    private Integer trnCounter;

    private Long createdUserId;

    private Long createdPostId;

    private Date createdDate;

    private Long updatedUserId;

    private Long updatedPostId;

    private Date updatedDate;

    private Long dbId;

    private String locationCode;


    // Constructors

    /** default constructor */
    public TrnMedblHdr()
    {
    }


    /** minimal constructor */
    public TrnMedblHdr(Long trnMedblHdrId, Long billNo, String monthCode, String deptName,
    		Integer trnCounter, Long createdUserId, Long createdPostId, Date createdDate,
            Long dbId, String locationCode)
    {
        this.trnMedblHdrId = trnMedblHdrId;
        this.billNo = billNo;
        this.monthCode = monthCode;
        this.deptName = deptName;
        this.trnCounter = trnCounter;
        this.createdUserId = createdUserId;
        this.createdPostId = createdPostId;
        this.createdDate = createdDate;
        this.dbId = dbId;
        this.locationCode = locationCode;
    }


    /** full constructor */
    public TrnMedblHdr(Long trnMedblHdrId, Long billNo, String empName, String empDesgn,
            String monthCode, Date billPassedDate, BigDecimal billPassedAmt, Long attachmentId,
            String deptName, Integer trnCounter, Long createdUserId, Long createdPostId,
            Date createdDate, Long updatedUserId, Long updatedPostId, Date updatedDate, Long dbId,
            String locationCode)
    {
        this.trnMedblHdrId = trnMedblHdrId;
        this.billNo = billNo;
        this.empName = empName;
        this.empDesgn = empDesgn;
        this.monthCode = monthCode;
        this.billPassedDate = billPassedDate;
        this.billPassedAmt = billPassedAmt;
        this.attachmentId = attachmentId;
        this.deptName = deptName;
        this.trnCounter = trnCounter;
        this.createdUserId = createdUserId;
        this.createdPostId = createdPostId;
        this.createdDate = createdDate;
        this.updatedUserId = updatedUserId;
        this.updatedPostId = updatedPostId;
        this.updatedDate = updatedDate;
        this.dbId = dbId;
        this.locationCode = locationCode;
    }


    // Property accessors
    public Long getTrnMedblHdrId()
    {
        return this.trnMedblHdrId;
    }


    public void setTrnMedblHdrId(Long trnMedblHdrId)
    {
        this.trnMedblHdrId = trnMedblHdrId;
    }


    public Long getBillNo()
    {
        return this.billNo;
    }


    public void setBillNo(Long billNo)
    {
        this.billNo = billNo;
    }


    public String getEmpName()
    {
        return this.empName;
    }


    public void setEmpName(String empName)
    {
        this.empName = empName;
    }


    public String getEmpDesgn()
    {
        return this.empDesgn;
    }


    public void setEmpDesgn(String empDesgn)
    {
        this.empDesgn = empDesgn;
    }


    public String getMonthCode()
    {
        return this.monthCode;
    }


    public void setMonthCode(String monthCode)
    {
        this.monthCode = monthCode;
    }


    public Date getBillPassedDate()
    {
        return this.billPassedDate;
    }


    public void setBillPassedDate(Date billPassedDate)
    {
        this.billPassedDate = billPassedDate;
    }


    public BigDecimal getBillPassedAmt()
    {
        return this.billPassedAmt;
    }


    public void setBillPassedAmt(BigDecimal billPassedAmt)
    {
        this.billPassedAmt = billPassedAmt;
    }


    public Long getAttachmentId()
    {
        return this.attachmentId;
    }


    public void setAttachmentId(Long attachmentId)
    {
        this.attachmentId = attachmentId;
    }


    public String getDeptName()
    {
        return this.deptName;
    }


    public void setDeptName(String deptName)
    {
        this.deptName = deptName;
    }


    public Integer getTrnCounter()
    {
        return this.trnCounter;
    }


    public void setTrnCounter(Integer trnCounter)
    {
        this.trnCounter = trnCounter;
    }


    public Long getCreatedUserId()
    {
        return this.createdUserId;
    }


    public void setCreatedUserId(Long createdUserId)
    {
        this.createdUserId = createdUserId;
    }


    public Long getCreatedPostId()
    {
        return this.createdPostId;
    }


    public void setCreatedPostId(Long createdPostId)
    {
        this.createdPostId = createdPostId;
    }


    public Date getCreatedDate()
    {
        return this.createdDate;
    }


    public void setCreatedDate(Date createdDate)
    {
        this.createdDate = createdDate;
    }


    public Long getUpdatedUserId()
    {
        return this.updatedUserId;
    }


    public void setUpdatedUserId(Long updatedUserId)
    {
        this.updatedUserId = updatedUserId;
    }


    public Long getUpdatedPostId()
    {
        return this.updatedPostId;
    }


    public void setUpdatedPostId(Long updatedPostId)
    {
        this.updatedPostId = updatedPostId;
    }


    public Date getUpdatedDate()
    {
        return this.updatedDate;
    }


    public void setUpdatedDate(Date updatedDate)
    {
        this.updatedDate = updatedDate;
    }


    public Long getDbId()
    {
        return this.dbId;
    }


    public void setDbId(Long dbId)
    {
        this.dbId = dbId;
    }


    public String getLocationCode()
    {
        return this.locationCode;
    }


    public void setLocationCode(String locationCode)
    {
        this.locationCode = locationCode;
    }

}
