package com.tcs.sgv.deduction.valueobject;
// Generated Jul 27, 2007 3:29:32 PM by Hibernate Tools 3.1.0.beta5

import java.util.Date;

import com.tcs.sgv.common.payroll.valueobject.HrPayCommissionMst;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrDeducExpMst generated by hbm2java
 */
public class HrDeducExpMst implements java.io.Serializable {

	// Fields    

	private long deducRuleId;
	private HrPayDeducTypeMst hrPayDeducTypeMst;
	private String deducRuleDesc;
	private String deducRuleExp;
	private CmnLanguageMst cmnLanguageMst;	
	private long deducRuleValue;	
	private long deducExpIsActive;
	private Date deducExpEffStartDt;
	private Date deducExpEffEndDt;	
	private CmnDatabaseMst cmnDatabaseMst;
	private OrgPostMst orgPostMstByUpdatedByPost;
	private OrgPostMst orgPostMstByCreatedByPost;
	private CmnLocationMst cmnLocationMst;
	private OrgUserMst orgUserMstByUpdatedBy;
	private OrgUserMst orgUserMstByCreatedBy;
	private Date createdDate;	
	private Date updatedDate;
	private Long deducExpCode;

	private HrPayCommissionMst hrPayCommissionMst;	
	
	// Constructors

	public HrPayCommissionMst getHrPayCommissionMst() {
		return hrPayCommissionMst;
	}

	public void setHrPayCommissionMst(HrPayCommissionMst hrPayCommissionMst) {
		this.hrPayCommissionMst = hrPayCommissionMst;
	}

	/** default constructor */
	public HrDeducExpMst() {
	}

	/** minimal constructor */
	public HrDeducExpMst(long deducRuleId) {
		this.deducRuleId = deducRuleId;
	}

	/** full constructor */
	public HrDeducExpMst(long deducRuleId,
			HrPayDeducTypeMst hrPayDeducTypeMst, String deducRuleDesc,
			String deducRuleExp, long deducRuleValue,
			long deducExpIsActive,Long deducExpCode,
			Date deducExpEffStartDt, Date deducExpEffEndDt, CmnDatabaseMst cmnDatabaseMst ,CmnLanguageMst cmnLanguageMst,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByCreatedBy, OrgPostMst orgPostMstByCreatedByPost,
			Date createdDate) {
		this.deducRuleId = deducRuleId;
		this.hrPayDeducTypeMst = hrPayDeducTypeMst;
		this.deducRuleDesc = deducRuleDesc;
		this.deducRuleExp = deducRuleExp;
		this.deducRuleValue = deducRuleValue;
		
		this.deducExpIsActive = deducExpIsActive;
		this.deducExpEffStartDt = deducExpEffStartDt;
		this.deducExpEffEndDt = deducExpEffEndDt;		
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.createdDate = createdDate;
		this.cmnLanguageMst = cmnLanguageMst;
		this.deducExpCode = deducExpCode;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}	

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getDeducExpEffEndDt() {
		return deducExpEffEndDt;
	}

	public void setDeducExpEffEndDt(Date deducExpEffEndDt) {
		this.deducExpEffEndDt = deducExpEffEndDt;
	}

	public Date getDeducExpEffStartDt() {
		return deducExpEffStartDt;
	}

	public void setDeducExpEffStartDt(Date deducExpEffStartDt) {
		this.deducExpEffStartDt = deducExpEffStartDt;
	}

	public long getDeducExpIsActive() {
		return deducExpIsActive;
	}

	public void setDeducExpIsActive(long deducExpIsActive) {
		this.deducExpIsActive = deducExpIsActive;
	}

	public String getDeducRuleDesc() {
		return deducRuleDesc;
	}

	public void setDeducRuleDesc(String deducRuleDesc) {
		this.deducRuleDesc = deducRuleDesc;
	}

	public String getDeducRuleExp() {
		return deducRuleExp;
	}

	public void setDeducRuleExp(String deducRuleExp) {
		this.deducRuleExp = deducRuleExp;
	}

	public long getDeducRuleId() {
		return deducRuleId;
	}

	public void setDeducRuleId(long deducRuleId) {
		this.deducRuleId = deducRuleId;
	}
	
	public long getDeducRuleValue() {
		return deducRuleValue;
	}

	public void setDeducRuleValue(long deducRuleValue) {
		this.deducRuleValue = deducRuleValue;
	}

	public HrPayDeducTypeMst getHrPayDeducTypeMst() {
		return hrPayDeducTypeMst;
	}

	public void setHrPayDeducTypeMst(HrPayDeducTypeMst hrPayDeducTypeMst) {
		this.hrPayDeducTypeMst = hrPayDeducTypeMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public Long getDeducExpCode() {
		return deducExpCode;
	}

	public void setDeducExpCode(Long deducExpCode) {
		this.deducExpCode = deducExpCode;
	}

	// Property accessors
	

}
