// default package
// Generated Aug 1, 2007 12:27:07 PM by Hibernate Tools 3.2.0.beta8

package com.tcs.sgv.common.valueobject;

import java.util.Date;

/**
 * SgvaBudsubhdMst generated by hbm2java
 */
public class SgvaBudsubhdMst implements java.io.Serializable {

	// Fields    

	private long budsubhdId;

	private String budsubhdCode;

	private String budsubhdDescLong;

	private String budsubhdDescShort;

	private String bpnCode;

	private String demandCode;

	private String budmjrhdCode;

	private String budsubmjrhdCode;

	private String budminhdCode;

	private String langId;

	private String locId;

	private Date crtDt;

	private String crtUsr;

	private Date lstUpdDt;

	private String lstUpdUsr;

	private String status;

	private Long terminatedYrId;

	private String edpcode;

	private String plngcode;

	private Long finYrId;
	
	private String css;
	
	private Long revisionId;

	// Constructors

	public String getCss() {
		return css;
	}

	public void setCss(String css) {
		this.css = css;
	}

	public Long getRevisionId() {
		return revisionId;
	}

	public void setRevisionId(Long revisionId) {
		this.revisionId = revisionId;
	}

	/** default constructor */
	public SgvaBudsubhdMst() {
	}

	/** minimal constructor */
	public SgvaBudsubhdMst(long budsubhdId, String budsubhdCode,
			String bpnCode, String demandCode, String budmjrhdCode,
			String budminhdCode, String langId, String locId, Date crtDt,
			String crtUsr, String status) {
		this.budsubhdId = budsubhdId;
		this.budsubhdCode = budsubhdCode;
		this.bpnCode = bpnCode;
		this.demandCode = demandCode;
		this.budmjrhdCode = budmjrhdCode;
		this.budminhdCode = budminhdCode;
		this.langId = langId;
		this.locId = locId;
		this.crtDt = crtDt;
		this.crtUsr = crtUsr;
		this.status = status;
	}

	/** full constructor */
	public SgvaBudsubhdMst(long budsubhdId, String budsubhdCode,
			String budsubhdDescLong, String budsubhdDescShort,
			String bpnCode, String demandCode, String budmjrhdCode,
			String budsubmjrhdCode, String budminhdCode, String langId,
			String locId, Date crtDt, String crtUsr, Date lstUpdDt,
			String lstUpdUsr, String status, Long terminatedYrId,
			String edpcode, String plngcode, Long finYrId) {
		this.budsubhdId = budsubhdId;
		this.budsubhdCode = budsubhdCode;
		this.budsubhdDescLong = budsubhdDescLong;
		this.budsubhdDescShort = budsubhdDescShort;
		this.bpnCode = bpnCode;
		this.demandCode = demandCode;
		this.budmjrhdCode = budmjrhdCode;
		this.budsubmjrhdCode = budsubmjrhdCode;
		this.budminhdCode = budminhdCode;
		this.langId = langId;
		this.locId = locId;
		this.crtDt = crtDt;
		this.crtUsr = crtUsr;
		this.lstUpdDt = lstUpdDt;
		this.lstUpdUsr = lstUpdUsr;
		this.status = status;
		this.terminatedYrId = terminatedYrId;
		this.edpcode = edpcode;
		this.plngcode = plngcode;
		this.finYrId = finYrId;
	}

	// Property accessors
	public long getBudsubhdId() {
		return this.budsubhdId;
	}

	public void setBudsubhdId(long budsubhdId) {
		this.budsubhdId = budsubhdId;
	}

	public String getBudsubhdCode() {
		return this.budsubhdCode;
	}

	public void setBudsubhdCode(String budsubhdCode) {
		this.budsubhdCode = budsubhdCode;
	}

	public String getBudsubhdDescLong() {
		return this.budsubhdDescLong;
	}

	public void setBudsubhdDescLong(String budsubhdDescLong) {
		this.budsubhdDescLong = budsubhdDescLong;
	}

	public String getBudsubhdDescShort() {
		return this.budsubhdDescShort;
	}

	public void setBudsubhdDescShort(String budsubhdDescShort) {
		this.budsubhdDescShort = budsubhdDescShort;
	}

	public String getBpnCode() {
		return this.bpnCode;
	}

	public void setBpnCode(String bpnCode) {
		this.bpnCode = bpnCode;
	}

	public String getDemandCode() {
		return this.demandCode;
	}

	public void setDemandCode(String demandCode) {
		this.demandCode = demandCode;
	}

	public String getBudmjrhdCode() {
		return this.budmjrhdCode;
	}

	public void setBudmjrhdCode(String budmjrhdCode) {
		this.budmjrhdCode = budmjrhdCode;
	}

	public String getBudsubmjrhdCode() {
		return this.budsubmjrhdCode;
	}

	public void setBudsubmjrhdCode(String budsubmjrhdCode) {
		this.budsubmjrhdCode = budsubmjrhdCode;
	}

	public String getBudminhdCode() {
		return this.budminhdCode;
	}

	public void setBudminhdCode(String budminhdCode) {
		this.budminhdCode = budminhdCode;
	}

	public String getLangId() {
		return this.langId;
	}

	public void setLangId(String langId) {
		this.langId = langId;
	}

	public String getLocId() {
		return this.locId;
	}

	public void setLocId(String locId) {
		this.locId = locId;
	}

	public Date getCrtDt() {
		return this.crtDt;
	}

	public void setCrtDt(Date crtDt) {
		this.crtDt = crtDt;
	}

	public String getCrtUsr() {
		return this.crtUsr;
	}

	public void setCrtUsr(String crtUsr) {
		this.crtUsr = crtUsr;
	}

	public Date getLstUpdDt() {
		return this.lstUpdDt;
	}

	public void setLstUpdDt(Date lstUpdDt) {
		this.lstUpdDt = lstUpdDt;
	}

	public String getLstUpdUsr() {
		return this.lstUpdUsr;
	}

	public void setLstUpdUsr(String lstUpdUsr) {
		this.lstUpdUsr = lstUpdUsr;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Long getTerminatedYrId() {
		return this.terminatedYrId;
	}

	public void setTerminatedYrId(Long terminatedYrId) {
		this.terminatedYrId = terminatedYrId;
	}

	public String getEdpcode() {
		return this.edpcode;
	}

	public void setEdpcode(String edpcode) {
		this.edpcode = edpcode;
	}

	public String getPlngcode() {
		return this.plngcode;
	}

	public void setPlngcode(String plngcode) {
		this.plngcode = plngcode;
	}

	public Long getFinYrId() {
		return this.finYrId;
	}

	public void setFinYrId(Long finYrId) {
		this.finYrId = finYrId;
	}

}
