// default package
// Generated Aug 24, 2007 7:34:40 PM by Hibernate Tools 3.2.0.beta8

package com.tcs.sgv.eis.valueobject;


import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.deduction.valueobject.HrPayDeducTypeMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrPayDeductionDtlsHst generated by hbm2java
 */
public class HrPayDeductionDtlsHst implements java.io.Serializable {

	// Fields    

	private HrPayDeductionDtlsHstId id;

	//private long empId;

	//private long empDeducId;

	private double empDeducAmount;

	private long empCurrentStatus;

	/*private long locId;

	private long dbId;

	private long createdBy;*/

	private Date createdDate;

	/*private long createdByPost;

	private long updatedBy;*/

	private Date updatedDate;

	//private long updatedByPost;
	
	private HrEisEmpMst hrEisEmpMst;

	private HrPayDeducTypeMst hrPayDeducTypeMst;	

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByCreatedBy;

	private OrgUserMst orgUserMstByUpdatedBy;

	// Constructors

	/** default constructor */
	public HrPayDeductionDtlsHst() {
	}

	/** minimal constructor */
	public HrPayDeductionDtlsHst(HrPayDeductionDtlsHstId id, HrEisEmpMst hrEisEmpMst) {
		this.id = id;
		this.hrEisEmpMst= hrEisEmpMst;
	}

	/** full constructor */
	public HrPayDeductionDtlsHst(HrPayDeductionDtlsHstId id, HrEisEmpMst hrEisEmpMst,
			double empDeducAmount,
			long empCurrentStatus,Date createdDate,
			Date updatedDate) {
		this.id = id;
		//this.empId = empId;
		//this.empDeducId = empDeducId;
		this.empDeducAmount = empDeducAmount;
		this.empCurrentStatus = empCurrentStatus;
		/*this.locId = locId;
		this.dbId = dbId;
		this.createdBy = createdBy;*/
		this.createdDate = createdDate;
		/*this.createdByPost = createdByPost;
		this.updatedBy = updatedBy;*/
		this.updatedDate = updatedDate;
		//this.updatedByPost = updatedByPost;
		this.hrEisEmpMst= hrEisEmpMst;
	}

	// Property accessors
	public HrPayDeductionDtlsHstId getId() {
		return this.id;
	}

	public void setId(HrPayDeductionDtlsHstId id) {
		this.id = id;
	}

	/*public long getEmpId() {
		return this.empId;
	}

	public void setEmpId(long empId) {
		this.empId = empId;
	}*/

	/*public long getEmpDeducId() {
		return this.empDeducId;
	}

	public void setEmpDeducId(long empDeducId) {
		this.empDeducId = empDeducId;
	}*/

	public double getEmpDeducAmount() {
		return this.empDeducAmount;
	}

	public void setEmpDeducAmount(double empDeducAmount) {
		this.empDeducAmount = empDeducAmount;
	}

	public long getEmpCurrentStatus() {
		return this.empCurrentStatus;
	}

	public void setEmpCurrentStatus(long empCurrentStatus) {
		this.empCurrentStatus = empCurrentStatus;
	}

	/*public long getLocId() {
		return this.locId;
	}

	public void setLocId(long locId) {
		this.locId = locId;
	}

	public long getDbId() {
		return this.dbId;
	}

	public void setDbId(long dbId) {
		this.dbId = dbId;
	}

	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}*/

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/*public long getCreatedByPost() {
		return this.createdByPost;
	}

	public void setCreatedByPost(long createdByPost) {
		this.createdByPost = createdByPost;
	}

	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}*/

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public HrEisEmpMst getHrEisEmpMst() {
		return hrEisEmpMst;
	}

	public void setHrEisEmpMst(HrEisEmpMst hrEisEmpMst) {
		this.hrEisEmpMst = hrEisEmpMst;
	}

	public HrPayDeducTypeMst getHrPayDeducTypeMst() {
		return hrPayDeducTypeMst;
	}

	public void setHrPayDeducTypeMst(HrPayDeducTypeMst hrPayDeducTypeMst) {
		this.hrPayDeducTypeMst = hrPayDeducTypeMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	/*public long getUpdatedByPost() {
		return this.updatedByPost;
	}

	public void setUpdatedByPost(long updatedByPost) {
		this.updatedByPost = updatedByPost;
	}*/

}
