package com.tcs.sgv.stamp.valueobject;
// Generated Oct 24, 2007 12:30:13 PM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;

/**
 * TrnStampChallanHdr generated by hbm2java
 */
public class TrnStampChallanHdr implements java.io.Serializable {

	// Fields    

	private BigDecimal challanId;

	private BigDecimal enfreshmentNo;

	private Date challanDate;

	private long locCode;

	private Short vendorCode;

	private String vendorPartyName;

	private String partyAddress;

	private String status;

	private BigDecimal challanValue;

	private BigDecimal createdUserId;

	private BigDecimal createdPostId;

	private Date createdDate;

	private BigDecimal updatedUserId;

	private BigDecimal updatedPostId;

	private Date updatedDate;

	private BigDecimal dbId;

	private String printingStatus;

	private String reason;

	private String bankScrollRefNo;

	private BigDecimal bankScrollRefAmt;

	// Constructors

	/** default constructor */
	public TrnStampChallanHdr() {
	}

	/** minimal constructor */
	public TrnStampChallanHdr(BigDecimal challanId, BigDecimal enfreshmentNo,
			Date challanDate, long locCode, String vendorPartyName,
			String status, BigDecimal challanValue) {
		this.challanId = challanId;
		this.enfreshmentNo = enfreshmentNo;
		this.challanDate = challanDate;
		this.locCode = locCode;
		this.vendorPartyName = vendorPartyName;
		this.status = status;
		this.challanValue = challanValue;
	}

	/** full constructor */
	public TrnStampChallanHdr(BigDecimal challanId, BigDecimal enfreshmentNo,
			Date challanDate, long locCode, Short vendorCode,
			String vendorPartyName, String partyAddress, String status,
			BigDecimal challanValue, BigDecimal createdUserId,
			BigDecimal createdPostId, Date createdDate,
			BigDecimal updatedUserId, BigDecimal updatedPostId,
			Date updatedDate, BigDecimal dbId, String printingStatus,
			String reason, String bankScrollRefNo, BigDecimal bankScrollRefAmt) {
		this.challanId = challanId;
		this.enfreshmentNo = enfreshmentNo;
		this.challanDate = challanDate;
		this.locCode = locCode;
		this.vendorCode = vendorCode;
		this.vendorPartyName = vendorPartyName;
		this.partyAddress = partyAddress;
		this.status = status;
		this.challanValue = challanValue;
		this.createdUserId = createdUserId;
		this.createdPostId = createdPostId;
		this.createdDate = createdDate;
		this.updatedUserId = updatedUserId;
		this.updatedPostId = updatedPostId;
		this.updatedDate = updatedDate;
		this.dbId = dbId;
		this.printingStatus = printingStatus;
		this.reason = reason;
		this.bankScrollRefNo = bankScrollRefNo;
		this.bankScrollRefAmt = bankScrollRefAmt;
	}

	// Property accessors
	public BigDecimal getChallanId() {
		return this.challanId;
	}

	public void setChallanId(BigDecimal challanId) {
		this.challanId = challanId;
	}

	public BigDecimal getEnfreshmentNo() {
		return this.enfreshmentNo;
	}

	public void setEnfreshmentNo(BigDecimal enfreshmentNo) {
		this.enfreshmentNo = enfreshmentNo;
	}

	public Date getChallanDate() {
		return this.challanDate;
	}

	public void setChallanDate(Date challanDate) {
		this.challanDate = challanDate;
	}

	public long getLocCode() {
		return this.locCode;
	}

	public void setLocCode(long locCode) {
		this.locCode = locCode;
	}

	public Short getVendorCode() {
		return this.vendorCode;
	}

	public void setVendorCode(Short vendorCode) {
		this.vendorCode = vendorCode;
	}

	public String getVendorPartyName() {
		return this.vendorPartyName;
	}

	public void setVendorPartyName(String vendorPartyName) {
		this.vendorPartyName = vendorPartyName;
	}

	public String getPartyAddress() {
		return this.partyAddress;
	}

	public void setPartyAddress(String partyAddress) {
		this.partyAddress = partyAddress;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public BigDecimal getChallanValue() {
		return this.challanValue;
	}

	public void setChallanValue(BigDecimal challanValue) {
		this.challanValue = challanValue;
	}

	public BigDecimal getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(BigDecimal createdUserId) {
		this.createdUserId = createdUserId;
	}

	public BigDecimal getCreatedPostId() {
		return this.createdPostId;
	}

	public void setCreatedPostId(BigDecimal createdPostId) {
		this.createdPostId = createdPostId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public BigDecimal getUpdatedUserId() {
		return this.updatedUserId;
	}

	public void setUpdatedUserId(BigDecimal updatedUserId) {
		this.updatedUserId = updatedUserId;
	}

	public BigDecimal getUpdatedPostId() {
		return this.updatedPostId;
	}

	public void setUpdatedPostId(BigDecimal updatedPostId) {
		this.updatedPostId = updatedPostId;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public BigDecimal getDbId() {
		return this.dbId;
	}

	public void setDbId(BigDecimal dbId) {
		this.dbId = dbId;
	}

	public String getPrintingStatus() {
		return this.printingStatus;
	}

	public void setPrintingStatus(String printingStatus) {
		this.printingStatus = printingStatus;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getBankScrollRefNo() {
		return this.bankScrollRefNo;
	}

	public void setBankScrollRefNo(String bankScrollRefNo) {
		this.bankScrollRefNo = bankScrollRefNo;
	}

	public BigDecimal getBankScrollRefAmt() {
		return this.bankScrollRefAmt;
	}

	public void setBankScrollRefAmt(BigDecimal bankScrollRefAmt) {
		this.bankScrollRefAmt = bankScrollRefAmt;
	}

}
