package com.tcs.sgv.stamp.valueobject;
// Generated Oct 15, 2007 12:20:22 PM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;

/**
 * TrnStampIndentHdr generated by hbm2java
 */
public class TrnStampIndentHdr implements java.io.Serializable {

	// Fields    

	private BigDecimal indHdrId;

	private BigDecimal indNo;

	private long locCode;

	private Date fromDate;

	private Date toDate;

	private String status;

	private String typeCode;

	private BigDecimal grossAmnt;

	private BigDecimal consolidatedIndNo;

	private BigDecimal createdUserId;

	private BigDecimal createdPostId;

	private Date createdDate;

	private BigDecimal updatedUserId;

	private BigDecimal updatedPostId;

	private Date updatedDate;

	private BigDecimal dbId;

	// Constructors

	/** default constructor */
	public TrnStampIndentHdr() {
	}

	/** minimal constructor */
	public TrnStampIndentHdr(BigDecimal indHdrId, BigDecimal indNo,
			long locCode, Date fromDate, Date toDate, String status,
			String typeCode, BigDecimal grossAmnt) {
		this.indHdrId = indHdrId;
		this.indNo = indNo;
		this.locCode = locCode;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.status = status;
		this.typeCode = typeCode;
		this.grossAmnt = grossAmnt;
	}

	/** full constructor */
	public TrnStampIndentHdr(BigDecimal indHdrId, BigDecimal indNo,
			long locCode, Date fromDate, Date toDate, String status,
			String typeCode, BigDecimal grossAmnt,
			BigDecimal consolidatedIndNo, BigDecimal createdUserId,
			BigDecimal createdPostId, Date createdDate,
			BigDecimal updatedUserId, BigDecimal updatedPostId,
			Date updatedDate, BigDecimal dbId) {
		this.indHdrId = indHdrId;
		this.indNo = indNo;
		this.locCode = locCode;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.status = status;
		this.typeCode = typeCode;
		this.grossAmnt = grossAmnt;
		this.consolidatedIndNo = consolidatedIndNo;
		this.createdUserId = createdUserId;
		this.createdPostId = createdPostId;
		this.createdDate = createdDate;
		this.updatedUserId = updatedUserId;
		this.updatedPostId = updatedPostId;
		this.updatedDate = updatedDate;
		this.dbId = dbId;
	}

	// Property accessors
	public BigDecimal getIndHdrId() {
		return this.indHdrId;
	}

	public void setIndHdrId(BigDecimal indHdrId) {
		this.indHdrId = indHdrId;
	}

	public BigDecimal getIndNo() {
		return this.indNo;
	}

	public void setIndNo(BigDecimal indNo) {
		this.indNo = indNo;
	}

	public long getLocCode() {
		return this.locCode;
	}

	public void setLocCode(long locCode) {
		this.locCode = locCode;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	public BigDecimal getGrossAmnt() {
		return this.grossAmnt;
	}

	public void setGrossAmnt(BigDecimal grossAmnt) {
		this.grossAmnt = grossAmnt;
	}

	public BigDecimal getConsolidatedIndNo() {
		return this.consolidatedIndNo;
	}

	public void setConsolidatedIndNo(BigDecimal consolidatedIndNo) {
		this.consolidatedIndNo = consolidatedIndNo;
	}

	public BigDecimal getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(BigDecimal createdUserId) {
		this.createdUserId = createdUserId;
	}

	public BigDecimal getCreatedPostId() {
		return this.createdPostId;
	}

	public void setCreatedPostId(BigDecimal createdPostId) {
		this.createdPostId = createdPostId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public BigDecimal getUpdatedUserId() {
		return this.updatedUserId;
	}

	public void setUpdatedUserId(BigDecimal updatedUserId) {
		this.updatedUserId = updatedUserId;
	}

	public BigDecimal getUpdatedPostId() {
		return this.updatedPostId;
	}

	public void setUpdatedPostId(BigDecimal updatedPostId) {
		this.updatedPostId = updatedPostId;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public BigDecimal getDbId() {
		return this.dbId;
	}

	public void setDbId(BigDecimal dbId) {
		this.dbId = dbId;
	}

}
