package com.tcs.sgv.stamp.valueobject;
// Generated Oct 24, 2007 12:30:13 PM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;

/**
 * MstStampDenomination generated by hbm2java
 */
public class MstStampDenomination implements java.io.Serializable {

	// Fields    

	private BigDecimal dnmId;

	private Short grpCode;

	private Integer dnmCode;

	private String dnmDesc;

	private Integer dnmValue;

	private Short labelPerSheet;

	private BigDecimal createdUserId;

	private BigDecimal createdPostId;

	private Date createdDate;

	private BigDecimal updatedUserId;

	private BigDecimal updatedPostId;

	private Date updatedDate;

	private BigDecimal dbId;

	private BigDecimal discount;

	private String status;

	// Constructors

	/** default constructor */
	public MstStampDenomination() {
	}

	/** minimal constructor */
	public MstStampDenomination(BigDecimal dnmId) {
		this.dnmId = dnmId;
	}

	/** full constructor */
	public MstStampDenomination(BigDecimal dnmId, Short grpCode,
			Integer dnmCode, String dnmDesc, Integer dnmValue,
			Short labelPerSheet, BigDecimal createdUserId,
			BigDecimal createdPostId, Date createdDate,
			BigDecimal updatedUserId, BigDecimal updatedPostId,
			Date updatedDate, BigDecimal dbId, BigDecimal discount,
			String status) {
		this.dnmId = dnmId;
		this.grpCode = grpCode;
		this.dnmCode = dnmCode;
		this.dnmDesc = dnmDesc;
		this.dnmValue = dnmValue;
		this.labelPerSheet = labelPerSheet;
		this.createdUserId = createdUserId;
		this.createdPostId = createdPostId;
		this.createdDate = createdDate;
		this.updatedUserId = updatedUserId;
		this.updatedPostId = updatedPostId;
		this.updatedDate = updatedDate;
		this.dbId = dbId;
		this.discount = discount;
		this.status = status;
	}

	// Property accessors
	public BigDecimal getDnmId() {
		return this.dnmId;
	}

	public void setDnmId(BigDecimal dnmId) {
		this.dnmId = dnmId;
	}

	public Short getGrpCode() {
		return this.grpCode;
	}

	public void setGrpCode(Short grpCode) {
		this.grpCode = grpCode;
	}

	public Integer getDnmCode() {
		return this.dnmCode;
	}

	public void setDnmCode(Integer dnmCode) {
		this.dnmCode = dnmCode;
	}

	public String getDnmDesc() {
		return this.dnmDesc;
	}

	public void setDnmDesc(String dnmDesc) {
		this.dnmDesc = dnmDesc;
	}

	public Integer getDnmValue() {
		return this.dnmValue;
	}

	public void setDnmValue(Integer dnmValue) {
		this.dnmValue = dnmValue;
	}

	public Short getLabelPerSheet() {
		return this.labelPerSheet;
	}

	public void setLabelPerSheet(Short labelPerSheet) {
		this.labelPerSheet = labelPerSheet;
	}

	public BigDecimal getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(BigDecimal createdUserId) {
		this.createdUserId = createdUserId;
	}

	public BigDecimal getCreatedPostId() {
		return this.createdPostId;
	}

	public void setCreatedPostId(BigDecimal createdPostId) {
		this.createdPostId = createdPostId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public BigDecimal getUpdatedUserId() {
		return this.updatedUserId;
	}

	public void setUpdatedUserId(BigDecimal updatedUserId) {
		this.updatedUserId = updatedUserId;
	}

	public BigDecimal getUpdatedPostId() {
		return this.updatedPostId;
	}

	public void setUpdatedPostId(BigDecimal updatedPostId) {
		this.updatedPostId = updatedPostId;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public BigDecimal getDbId() {
		return this.dbId;
	}

	public void setDbId(BigDecimal dbId) {
		this.dbId = dbId;
	}

	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
