package com.tcs.sgv.eis.valueobject;

// default package
// Generated Mar 8, 2008 1:13:59 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnAttachmentMst;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrEmpbiometricDtl generated by hbm2java
 */
public class HrEisBiometricDtl implements java.io.Serializable {

	// Fields    

	private long biometricId;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private CmnAttachmentMst cmnAttachmentMstByEmpPhotoAttachmentId;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnAttachmentMst cmnAttachmentMstByEmpThumbAttachmentId;

	private OrgUserMst orgUserMstByCreatedBy;

	private OrgUserMst orgUserMstByUpdatedBy;

	private CmnLookupMst cmnLookupMstByEmpTypeOfDisability;

	private CmnLookupMst cmnLookupMstByEmpBloodGroup;

	private CmnLocationMst cmnLocationMst;

	private Date createdDate;

	private Date updatedDate;

	private Character empPhyChallenged;

	private String empDisabilityDetails;

	private String empIdentificationMark;

	private Double empWeight;

	private Double empChest;

	private Double empHeight;

	// Constructors

	/** default constructor */
	public HrEisBiometricDtl() {
	}

	/** minimal constructor */
	public HrEisBiometricDtl(long biometricId, CmnDatabaseMst cmnDatabaseMst,
			OrgPostMst orgPostMstByCreatedByPost,
			OrgUserMst orgUserMstByCreatedBy, long locId, Date createdDate) {
		this.biometricId = biometricId;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.cmnLocationMst = cmnLocationMst;
		this.createdDate = createdDate;
	}

	/** full constructor */
	public HrEisBiometricDtl(long biometricId, CmnDatabaseMst cmnDatabaseMst,
			OrgPostMst orgPostMstByUpdatedByPost,
			CmnAttachmentMst cmnAttachmentMstByEmpPhotoAttachmentId,
			OrgPostMst orgPostMstByCreatedByPost,
			CmnAttachmentMst cmnAttachmentMstByEmpThumbAttachmentId,
			OrgUserMst orgUserMstByCreatedBy, OrgUserMst orgUserMstByUpdatedBy,
			CmnLookupMst cmnLookupMstByEmpTypeOfDisability,
			CmnLookupMst cmnLookupMstByEmpBloodGroup, long locId,
			Date createdDate, Date updatedDate, Character empPhyChallenged,
			String empDisabilityDetails, String empIdentificationMark,
			Double empWeight, Double empChest, Double empHeight) {
		this.biometricId = biometricId;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.cmnAttachmentMstByEmpPhotoAttachmentId = cmnAttachmentMstByEmpPhotoAttachmentId;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnAttachmentMstByEmpThumbAttachmentId = cmnAttachmentMstByEmpThumbAttachmentId;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.cmnLookupMstByEmpTypeOfDisability = cmnLookupMstByEmpTypeOfDisability;
		this.cmnLookupMstByEmpBloodGroup = cmnLookupMstByEmpBloodGroup;
		this.cmnLocationMst = cmnLocationMst;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.empPhyChallenged = empPhyChallenged;
		this.empDisabilityDetails = empDisabilityDetails;
		this.empIdentificationMark = empIdentificationMark;
		this.empWeight = empWeight;
		this.empChest = empChest;
		this.empHeight = empHeight;
	}

	// Property accessors
	public long getBiometricId() {
		return this.biometricId;
	}

	public void setBiometricId(long biometricId) {
		this.biometricId = biometricId;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return this.cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return this.orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(
			OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public CmnAttachmentMst getCmnAttachmentMstByEmpPhotoAttachmentId() {
		return this.cmnAttachmentMstByEmpPhotoAttachmentId;
	}

	public void setCmnAttachmentMstByEmpPhotoAttachmentId(
			CmnAttachmentMst cmnAttachmentMstByEmpPhotoAttachmentId) {
		this.cmnAttachmentMstByEmpPhotoAttachmentId = cmnAttachmentMstByEmpPhotoAttachmentId;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return this.orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(
			OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public CmnAttachmentMst getCmnAttachmentMstByEmpThumbAttachmentId() {
		return this.cmnAttachmentMstByEmpThumbAttachmentId;
	}

	public void setCmnAttachmentMstByEmpThumbAttachmentId(
			CmnAttachmentMst cmnAttachmentMstByEmpThumbAttachmentId) {
		this.cmnAttachmentMstByEmpThumbAttachmentId = cmnAttachmentMstByEmpThumbAttachmentId;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return this.orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return this.orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public CmnLookupMst getCmnLookupMstByEmpTypeOfDisability() {
		return this.cmnLookupMstByEmpTypeOfDisability;
	}

	public void setCmnLookupMstByEmpTypeOfDisability(
			CmnLookupMst cmnLookupMstByEmpTypeOfDisability) {
		this.cmnLookupMstByEmpTypeOfDisability = cmnLookupMstByEmpTypeOfDisability;
	}

	public CmnLookupMst getCmnLookupMstByEmpBloodGroup() {
		return this.cmnLookupMstByEmpBloodGroup;
	}

	public void setCmnLookupMstByEmpBloodGroup(
			CmnLookupMst cmnLookupMstByEmpBloodGroup) {
		this.cmnLookupMstByEmpBloodGroup = cmnLookupMstByEmpBloodGroup;
	}

	

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Character getEmpPhyChallenged() {
		return this.empPhyChallenged;
	}

	public void setEmpPhyChallenged(Character empPhyChallenged) {
		this.empPhyChallenged = empPhyChallenged;
	}

	public String getEmpDisabilityDetails() {
		return this.empDisabilityDetails;
	}

	public void setEmpDisabilityDetails(String empDisabilityDetails) {
		this.empDisabilityDetails = empDisabilityDetails;
	}

	public String getEmpIdentificationMark() {
		return this.empIdentificationMark;
	}

	public void setEmpIdentificationMark(String empIdentificationMark) {
		this.empIdentificationMark = empIdentificationMark;
	}

	public Double getEmpWeight() {
		return this.empWeight;
	}

	public void setEmpWeight(Double empWeight) {
		this.empWeight = empWeight;
	}

	public Double getEmpChest() {
		return this.empChest;
	}

	public void setEmpChest(Double empChest) {
		this.empChest = empChest;
	}

	public Double getEmpHeight() {
		return this.empHeight;
	}

	public void setEmpHeight(Double empHeight) {
		this.empHeight = empHeight;
	}

}
