// default package
// Generated Aug 23, 2007 4:08:29 PM by Hibernate Tools 3.1.0.beta5
package com.tcs.sgv.eis.valueobject;
//Comment By Maruthi For import Organisation.
import java.io.Serializable;
import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.deduction.valueobject.HrPayDeducTypeMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrPayNonGovDeduction generated by hbm2java
 */
public class HrPayNonGovDeduction implements Serializable {

	// Fields    

	private long nonGovDeducId;
	private HrEisEmpMst hrEisEmpMst;
	private HrPayDeducTypeMst hrPayDeducTypeMst;
	private long nonGovDeducAmount;
	private String currencynonGovDeducAmount;
	private Date nonGovDeducEfftStartDt;
	private Date nonGovDeducEfftEndDt;
	private String nonGovDeducAccNo ;
	//private Long nonGovDeducPeriod;
	CmnLookupMst cmnLookupMst;
	
	private CmnDatabaseMst cmnDatabaseMst;
	private OrgPostMst orgPostMstByUpdatedByPost;
	private OrgPostMst orgPostMstByCreatedByPost;
	private CmnLocationMst cmnLocationMst;
	private OrgUserMst orgUserMstByUpdatedBy;
	private OrgUserMst orgUserMstByCreatedBy;
	private Date createdDate;	
	private Date updatedDate;
	private long trnCounter;
	
	//added by vaibhav tyagi: start
	private String nonGovType;
	//added by vaibhav tyagi: end
	// Constructors

	
	

	/** default constructor */
	public HrPayNonGovDeduction() {
	}

	/** Full constructor */
	public HrPayNonGovDeduction(long nonGovDeducId,long trnCounter, HrEisEmpMst hrEisEmpMst, HrPayDeducTypeMst hrPayDeducTypeMst, Long nonGovDeducAmount, Date nonGovDeducEfftStartDt, Date nonGovDeducEfftEndDt, CmnLookupMst cmnLookupMst, CmnDatabaseMst cmnDatabaseMst, OrgPostMst orgPostMstByUpdatedByPost, OrgPostMst orgPostMstByCreatedByPost, CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByUpdatedBy, OrgUserMst orgUserMstByCreatedBy, Date createdDate, Date updatedDate,String nonGovDeducAccNo,String nonGovType) {
		super();
		this.nonGovDeducId = nonGovDeducId;
		this.trnCounter = trnCounter;
		this.hrEisEmpMst = hrEisEmpMst;
		this.hrPayDeducTypeMst = hrPayDeducTypeMst;
		this.nonGovDeducAmount = nonGovDeducAmount;
		this.nonGovDeducEfftStartDt = nonGovDeducEfftStartDt;
		this.nonGovDeducEfftEndDt = nonGovDeducEfftEndDt;
		this.cmnLookupMst = cmnLookupMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.nonGovDeducAccNo=nonGovDeducAccNo;
		this.nonGovType=nonGovType;
	}

	/** minimul constructor */
	public HrPayNonGovDeduction(long nonGovDeducId,HrEisEmpMst hrEisEmpMst,
			HrPayDeducTypeMst hrPayDeducTypeMst, long nonGovDeducAmount,
			Date nonGovDeducEfftStartDt, Date nonGovDeducEfftEndDt,
			CmnLookupMst cmnLookupMst, CmnDatabaseMst cmnDatabaseMst ,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByCreatedBy, OrgPostMst orgPostMstByCreatedByPost,
			Date createdDate,String nonGovDeducAccNo,String nonGovType) {
		this.nonGovDeducId = nonGovDeducId;
		this.hrEisEmpMst = hrEisEmpMst;
		this.hrPayDeducTypeMst = hrPayDeducTypeMst;
		this.nonGovDeducAmount = nonGovDeducAmount;
		this.nonGovDeducEfftStartDt = nonGovDeducEfftStartDt;
		this.nonGovDeducEfftEndDt = nonGovDeducEfftEndDt;
		this.nonGovDeducAccNo=nonGovDeducAccNo;
		this.cmnLookupMst = cmnLookupMst;	
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.createdDate = createdDate;
		this.nonGovType = nonGovType;
	}

	// Property accessors
	public long getNonGovDeducId() {
		return this.nonGovDeducId;
	}

	public void setNonGovDeducId(long nonGovDeducId) {
		this.nonGovDeducId = nonGovDeducId;
	}

	public long getNonGovDeducAmount() {
		return this.nonGovDeducAmount;
	}

	public void setNonGovDeducAmount(long nonGovDeducAmount) {
		this.nonGovDeducAmount = nonGovDeducAmount;
	}

	public Date getNonGovDeducEfftStartDt() {
		return this.nonGovDeducEfftStartDt;
	}

	public void setNonGovDeducEfftStartDt(Date nonGovDeducEfftStartDt) {
		this.nonGovDeducEfftStartDt = nonGovDeducEfftStartDt;
	}

	public Date getNonGovDeducEfftEndDt() {
		return this.nonGovDeducEfftEndDt;
	}

	public void setNonGovDeducEfftEndDt(Date nonGovDeducEfftEndDt) {
		this.nonGovDeducEfftEndDt = nonGovDeducEfftEndDt;
	}
	

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}	

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public HrEisEmpMst getHrEisEmpMst() {
		return hrEisEmpMst;
	}

	public void setHrEisEmpMst(HrEisEmpMst hrEisEmpMst) {
		this.hrEisEmpMst = hrEisEmpMst;
	}

	public HrPayDeducTypeMst getHrPayDeducTypeMst() {
		return hrPayDeducTypeMst;
	}

	public void setHrPayDeducTypeMst(HrPayDeducTypeMst hrPayDeducTypeMst) {
		this.hrPayDeducTypeMst = hrPayDeducTypeMst;
	}

	public CmnLookupMst getCmnLookupMst() {
		return cmnLookupMst;
	}

	public void setCmnLookupMst(CmnLookupMst cmnLookupMst) {
		this.cmnLookupMst = cmnLookupMst;
	}
	public long getTrnCounter() {
		return trnCounter;
	}

	public void setTrnCounter(long trnCounter) {
		this.trnCounter = trnCounter;
	}

	//added by vaibhav tyagi: start
	public void setNonGovType(String nonGovType) {
		this.nonGovType = nonGovType;
	}

	public String getNonGovType() {
		return nonGovType;
	}
	//added by vaibhav tyagi: end

	public String getNonGovDeducAccNo() {
		return nonGovDeducAccNo;
	}

	public void setNonGovDeducAccNo(String nonGovDeducAccNo) {
		this.nonGovDeducAccNo = nonGovDeducAccNo;
	}

	public String getCurrencynonGovDeducAmount() {
		return currencynonGovDeducAmount;
	}

	public void setCurrencynonGovDeducAmount(String currencynonGovDeducAmount) {
		this.currencynonGovDeducAmount = currencynonGovDeducAmount;
	}
	
}
