package com.tcs.sgv.onlinebillprep.valueobject;

import java.math.BigDecimal;

/**
 * HstTrnAprvdRqstId generated by hbm2java
 */
public class HstTrnAprvdRqstId implements java.io.Serializable {

	// Fields    

	private BigDecimal trnAprvdRqstId;

	private BigDecimal trnCounter;

	// Constructors

	/** default constructor */
	public HstTrnAprvdRqstId() {
	}

	/** full constructor */
	public HstTrnAprvdRqstId(BigDecimal trnAprvdRqstId, BigDecimal trnCounter) {
		this.trnAprvdRqstId = trnAprvdRqstId;
		this.trnCounter = trnCounter;
	}

	// Property accessors
	public BigDecimal getTrnAprvdRqstId() {
		return this.trnAprvdRqstId;
	}

	public void setTrnAprvdRqstId(BigDecimal trnAprvdRqstId) {
		this.trnAprvdRqstId = trnAprvdRqstId;
	}

	public BigDecimal getTrnCounter() {
		return this.trnCounter;
	}

	public void setTrnCounter(BigDecimal trnCounter) {
		this.trnCounter = trnCounter;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HstTrnAprvdRqstId))
			return false;
		HstTrnAprvdRqstId castOther = (HstTrnAprvdRqstId) other;

		return ((this.getTrnAprvdRqstId() == castOther.getTrnAprvdRqstId()) || (this
				.getTrnAprvdRqstId() != null
				&& castOther.getTrnAprvdRqstId() != null && this
				.getTrnAprvdRqstId().equals(castOther.getTrnAprvdRqstId())))
				&& ((this.getTrnCounter() == castOther.getTrnCounter()) || (this
						.getTrnCounter() != null
						&& castOther.getTrnCounter() != null && this
						.getTrnCounter().equals(castOther.getTrnCounter())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getTrnAprvdRqstId() == null ? 0 : this.getTrnAprvdRqstId()
						.hashCode());
		result = 37
				* result
				+ (getTrnCounter() == null ? 0 : this.getTrnCounter()
						.hashCode());
		return result;
	}

}
