package com.tcs.sgv.pensionpay.valueobject;

// Generated Mar 22, 2011 6:54:11 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * StgCpo generated by hbm2java
 */
public class StgCpo implements java.io.Serializable {

	private Long stgCpoId;
	private Long delvId;
	private String caseStatus;
	private String pnsrFileNo;
	private String applnNo;
	private String pnsrPpoNo;
	private String cpoNo;
	private String commAmt;
	private String cvpAmt;
	private String cpoSancAuNoCode;
	private String cpoSancAuNo;
	private String cpoAgoutNo;
	private String cpoAgoutDate;
	private Long createdBy;
	private Date createdDate;
	private Long updatedBy;
	private Date updatedDate;

	public StgCpo() {
	}

	public StgCpo(Long stgCpoId, Long delvId, Date createdDate) {
		this.stgCpoId = stgCpoId;
		this.delvId = delvId;
		this.createdDate = createdDate;
	}

	public StgCpo(Long stgCpoId, Long delvId, String caseStatus,
			String pnsrFileNo, String applnNo, String pnsrPpoNo, String cpoNo,
			String commAmt, String cvpAmt, String cpoSancAuNoCode,
			String cpoSancAuNo, String cpoAgoutNo, String cpoAgoutDate,
			Long createdBy, Date createdDate, Long updatedBy, Date updatedDate) {
		this.stgCpoId = stgCpoId;
		this.delvId = delvId;
		this.caseStatus = caseStatus;
		this.pnsrFileNo = pnsrFileNo;
		this.applnNo = applnNo;
		this.pnsrPpoNo = pnsrPpoNo;
		this.cpoNo = cpoNo;
		this.commAmt = commAmt;
		this.cvpAmt = cvpAmt;
		this.cpoSancAuNoCode = cpoSancAuNoCode;
		this.cpoSancAuNo = cpoSancAuNo;
		this.cpoAgoutNo = cpoAgoutNo;
		this.cpoAgoutDate = cpoAgoutDate;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	public Long getStgCpoId() {
		return this.stgCpoId;
	}

	public void setStgCpoId(Long stgCpoId) {
		this.stgCpoId = stgCpoId;
	}

	public Long getDelvId() {
		return this.delvId;
	}

	public void setDelvId(Long delvId) {
		this.delvId = delvId;
	}

	public String getCaseStatus() {
		return this.caseStatus;
	}

	public void setCaseStatus(String caseStatus) {
		this.caseStatus = caseStatus;
	}

	public String getPnsrFileNo() {
		return this.pnsrFileNo;
	}

	public void setPnsrFileNo(String pnsrFileNo) {
		this.pnsrFileNo = pnsrFileNo;
	}

	public String getApplnNo() {
		return this.applnNo;
	}

	public void setApplnNo(String applnNo) {
		this.applnNo = applnNo;
	}

	public String getPnsrPpoNo() {
		return this.pnsrPpoNo;
	}

	public void setPnsrPpoNo(String pnsrPpoNo) {
		this.pnsrPpoNo = pnsrPpoNo;
	}

	public String getCpoNo() {
		return this.cpoNo;
	}

	public void setCpoNo(String cpoNo) {
		this.cpoNo = cpoNo;
	}

	public String getCommAmt() {
		return this.commAmt;
	}

	public void setCommAmt(String commAmt) {
		this.commAmt = commAmt;
	}

	public String getCvpAmt() {
		return this.cvpAmt;
	}

	public void setCvpAmt(String cvpAmt) {
		this.cvpAmt = cvpAmt;
	}

	public String getCpoSancAuNoCode() {
		return this.cpoSancAuNoCode;
	}

	public void setCpoSancAuNoCode(String cpoSancAuNoCode) {
		this.cpoSancAuNoCode = cpoSancAuNoCode;
	}

	public String getCpoSancAuNo() {
		return this.cpoSancAuNo;
	}

	public void setCpoSancAuNo(String cpoSancAuNo) {
		this.cpoSancAuNo = cpoSancAuNo;
	}

	public String getCpoAgoutNo() {
		return this.cpoAgoutNo;
	}

	public void setCpoAgoutNo(String cpoAgoutNo) {
		this.cpoAgoutNo = cpoAgoutNo;
	}

	public String getCpoAgoutDate() {
		return this.cpoAgoutDate;
	}

	public void setCpoAgoutDate(String cpoAgoutDate) {
		this.cpoAgoutDate = cpoAgoutDate;
	}

	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
