// default package
// Generated Jul 24, 2007 4:22:30 PM by Hibernate Tools 3.2.0.beta8

package com.tcs.sgv.common.valueobject;

import java.math.BigDecimal;
import java.util.Date;

/**
 * SgvaMonthMst generated by hbm2java
 */
public class SgvaMonthMst implements java.io.Serializable {

	// Fields    

	private BigDecimal monthId;

	private String monthCode;

	private String monthName;

	private String langId;

	private String locId;

	private Date crtDt;

	private String crtUsr;

	private String lstUpdUsr;

	private Date lstUpdDt;

	private Byte monthNo;

	// Constructors

	/** default constructor */
	public SgvaMonthMst() {
	}

	/** minimal constructor */
	public SgvaMonthMst(BigDecimal monthId, String monthCode, String monthName,
			String langId, String locId, Date crtDt) {
		this.monthId = monthId;
		this.monthCode = monthCode;
		this.monthName = monthName;
		this.langId = langId;
		this.locId = locId;
		this.crtDt = crtDt;
	}

	/** full constructor */
	public SgvaMonthMst(BigDecimal monthId, String monthCode, String monthName,
			String langId, String locId, Date crtDt, String crtUsr,
			String lstUpdUsr, Date lstUpdDt, Byte monthNo) {
		this.monthId = monthId;
		this.monthCode = monthCode;
		this.monthName = monthName;
		this.langId = langId;
		this.locId = locId;
		this.crtDt = crtDt;
		this.crtUsr = crtUsr;
		this.lstUpdUsr = lstUpdUsr;
		this.lstUpdDt = lstUpdDt;
		this.monthNo = monthNo;
	}

	// Property accessors
	public BigDecimal getMonthId() {
		return this.monthId;
	}

	public void setMonthId(BigDecimal monthId) {
		this.monthId = monthId;
	}

	public String getMonthCode() {
		return this.monthCode;
	}

	public void setMonthCode(String monthCode) {
		this.monthCode = monthCode;
	}

	public String getMonthName() {
		return this.monthName;
	}

	public void setMonthName(String monthName) {
		this.monthName = monthName;
	}

	public String getLangId() {
		return this.langId;
	}

	public void setLangId(String langId) {
		this.langId = langId;
	}

	public String getLocId() {
		return this.locId;
	}

	public void setLocId(String locId) {
		this.locId = locId;
	}

	public Date getCrtDt() {
		return this.crtDt;
	}

	public void setCrtDt(Date crtDt) {
		this.crtDt = crtDt;
	}

	public String getCrtUsr() {
		return this.crtUsr;
	}

	public void setCrtUsr(String crtUsr) {
		this.crtUsr = crtUsr;
	}

	public String getLstUpdUsr() {
		return this.lstUpdUsr;
	}

	public void setLstUpdUsr(String lstUpdUsr) {
		this.lstUpdUsr = lstUpdUsr;
	}

	public Date getLstUpdDt() {
		return this.lstUpdDt;
	}

	public void setLstUpdDt(Date lstUpdDt) {
		this.lstUpdDt = lstUpdDt;
	}

	public Byte getMonthNo() {
		return this.monthNo;
	}

	public void setMonthNo(Byte monthNo) {
		this.monthNo = monthNo;
	}

}
