package com.tcs.sgv.stamp.valueobject;
// Generated Oct 15, 2007 12:20:22 PM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;

/**
 * StampIndentHdr generated by hbm2java
 */
public class StampIndentHdr implements java.io.Serializable {

	// Fields    

	private BigDecimal indId;

	private Date indFdate;

	private Date indTdate;

	private String indLocCode;

	private String indTypeCode;

	private String indStatus;

	// Constructors

	/** default constructor */
	public StampIndentHdr() {
	}

	/** minimal constructor */
	public StampIndentHdr(BigDecimal indId) {
		this.indId = indId;
	}

	/** full constructor */
	public StampIndentHdr(BigDecimal indId, Date indFdate, Date indTdate,
			String indLocCode, String indTypeCode, String indStatus) {
		this.indId = indId;
		this.indFdate = indFdate;
		this.indTdate = indTdate;
		this.indLocCode = indLocCode;
		this.indTypeCode = indTypeCode;
		this.indStatus = indStatus;
	}

	// Property accessors
	public BigDecimal getIndId() {
		return this.indId;
	}

	public void setIndId(BigDecimal indId) {
		this.indId = indId;
	}

	public Date getIndFdate() {
		return this.indFdate;
	}

	public void setIndFdate(Date indFdate) {
		this.indFdate = indFdate;
	}

	public Date getIndTdate() {
		return this.indTdate;
	}

	public void setIndTdate(Date indTdate) {
		this.indTdate = indTdate;
	}

	public String getIndLocCode() {
		return this.indLocCode;
	}

	public void setIndLocCode(String indLocCode) {
		this.indLocCode = indLocCode;
	}

	public String getIndTypeCode() {
		return this.indTypeCode;
	}

	public void setIndTypeCode(String indTypeCode) {
		this.indTypeCode = indTypeCode;
	}

	public String getIndStatus() {
		return this.indStatus;
	}

	public void setIndStatus(String indStatus) {
		this.indStatus = indStatus;
	}

}
