package com.tcs.sgv.hr.payfixation.valueobject;
// default package
// Generated Sep 29, 2007 9:11:20 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrEssPayfixReqDtls generated by hbm2java
 */
public class HrPayfixReqDtl implements java.io.Serializable {

	// Fields    

	private long reqId;

	private OrgUserMst userId;

	

	private HrPayFixTxn hrPayFixTxn;

	private Long reqType;

	private Long sysCompNewBasicSal;

	private Date sysCompNxtIncrDate;

	private Long userCompNewBasicSal;

	private Date userCompNxtIncrDate;

	private String userRemarks;

	private String approve;

	private CmnDatabaseMst dbId;

	private CmnLocationMst locId;

	private OrgUserMst createdBy;

	private OrgPostMst createdByPost;

	private Date createdDate;

	private OrgUserMst updatedBy;

	private OrgPostMst updatedByPost;

	private Date updatedDate;
	
	private String compFlag;

	// Constructors

	/** default constructor */
	public HrPayfixReqDtl() {
	}

	/** minimal constructor */
	public HrPayfixReqDtl(Long reqId) {
		this.reqId = reqId;
		
	}

	/** full constructor */
	public HrPayfixReqDtl(Long reqId, OrgUserMst userId,
			HrPayFixTxn hrPayFixTxn,
			Long reqType, Long sysCompNewBasicSal,
			Date sysCompNxtIncrDate, Long userCompNewBasicSal,
			Date userCompNxtIncrDate, String userRemarks, String approve,
			CmnDatabaseMst dbId, CmnLocationMst locId, OrgUserMst createdBy,
			OrgPostMst createdByPost, Date createdDate, OrgUserMst updatedBy,
			OrgPostMst updatedByPost, Date updatedDate, String compFlag) {
		this.reqId = reqId;
		this.userId = userId;
		
		this.hrPayFixTxn = hrPayFixTxn;
		this.reqType = reqType;
		this.sysCompNewBasicSal = sysCompNewBasicSal;
		this.sysCompNxtIncrDate = sysCompNxtIncrDate;
		this.userCompNewBasicSal = userCompNewBasicSal;
		this.userCompNxtIncrDate = userCompNxtIncrDate;
		this.userRemarks = userRemarks;
		this.approve = approve;
		this.dbId = dbId;
		this.locId = locId;
		this.createdBy = createdBy;
		this.createdByPost = createdByPost;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedByPost = updatedByPost;
		this.updatedDate = updatedDate;
		this.compFlag = compFlag;
	}

	// Property accessors
	public Long getReqId() {
		return this.reqId;
	}

	public void setReqId(Long reqId) {
		this.reqId = reqId;
	}

	public OrgUserMst getUserId() {
		return this.userId;
	}

	public void setUserId(OrgUserMst userId) {
		this.userId = userId;
	}


	

	public HrPayFixTxn getHrPayFixTxn() {
		return this.hrPayFixTxn;
	}

	public void setHrPayFixTxn(HrPayFixTxn hrPayFixTxn) {
		this.hrPayFixTxn = hrPayFixTxn;
	}

	public Long getReqType() {
		return this.reqType;
	}

	public void setReqType(Long reqType) {
		this.reqType = reqType;
	}

	public Long getSysCompNewBasicSal() {
		return this.sysCompNewBasicSal;
	}

	public void setSysCompNewBasicSal(Long sysCompNewBasicSal) {
		this.sysCompNewBasicSal = sysCompNewBasicSal;
	}

	public Date getSysCompNxtIncrDate() {
		return this.sysCompNxtIncrDate;
	}

	public void setSysCompNxtIncrDate(Date sysCompNxtIncrDate) {
		this.sysCompNxtIncrDate = sysCompNxtIncrDate;
	}

	public Long getUserCompNewBasicSal() {
		return this.userCompNewBasicSal;
	}

	public void setUserCompNewBasicSal(Long userCompNewBasicSal) {
		this.userCompNewBasicSal = userCompNewBasicSal;
	}

	public Date getUserCompNxtIncrDate() {
		return this.userCompNxtIncrDate;
	}

	public void setUserCompNxtIncrDate(Date userCompNxtIncrDate) {
		this.userCompNxtIncrDate = userCompNxtIncrDate;
	}

	public String getUserRemarks() {
		return this.userRemarks;
	}

	public void setUserRemarks(String userRemarks) {
		this.userRemarks = userRemarks;
	}

	public String getApprove() {
		return this.approve;
	}

	public void setApprove(String approve) {
		this.approve = approve;
	}

	public CmnDatabaseMst getDbId() {
		return this.dbId;
	}

	public void setDbId(CmnDatabaseMst dbId) {
		this.dbId = dbId;
	}

	public CmnLocationMst getLocId() {
		return this.locId;
	}

	public void setLocId(CmnLocationMst locId) {
		this.locId = locId;
	}

	public OrgUserMst getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(OrgUserMst createdBy) {
		this.createdBy = createdBy;
	}

	public OrgPostMst getCreatedByPost() {
		return this.createdByPost;
	}

	public void setCreatedByPost(OrgPostMst createdByPost) {
		this.createdByPost = createdByPost;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public OrgUserMst getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(OrgUserMst updatedBy) {
		this.updatedBy = updatedBy;
	}

	public OrgPostMst getUpdatedByPost() {
		return this.updatedByPost;
	}

	public void setUpdatedByPost(OrgPostMst updatedByPost) {
		this.updatedByPost = updatedByPost;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	public void setCompFlag(String compFlag) {
		this.compFlag = compFlag;
	}

	public String getCompFlag() {
		return this.compFlag;
	}

}
