// default package
// Generated Jan 10, 2008 10:22:19 AM by Hibernate Tools 3.2.0.beta8
package com.tcs.sgv.eis.valueobject;
import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrEisEmpProofDtls generated by hbm2java
 */
public class HrEisProofDtl implements java.io.Serializable {

	// Fields    

	private long srNo;

	private CmnLookupMst cmnLookupMst;

	private OrgPostMst orgUserMstByUpdatedByPost;

	private OrgUserMst orgUserMstByCreatedBy;

	private OrgPostMst orgPostMstByCreatedByPost;

	private OrgUserMst orgPostMstByUserId;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private CmnDatabaseMst cmnDatabaseMst;

	private String proofNum;

	private String prooftypeOther;

	private Date issueDate;

	private Date expiryDate;

	private String issuePlace;

	private String issueAuthority;

	private Date createdDate;

	private Date updatedDate;
	
	private CmnLookupMst cmnLookupMstByLicenseType;
	// Constructors

	/** default constructor */
	public HrEisProofDtl() {
	}

	/** minimal constructor */
	public HrEisProofDtl(long srNo, CmnLookupMst cmnLookupMst,
			OrgUserMst orgUserMstByCreatedBy,
			OrgPostMst orgPostMstByCreatedByPost,
			OrgUserMst orgPostMstByUserId, CmnLocationMst cmnLocationMst,
			CmnDatabaseMst cmnDatabaseMst, String proofNum, Date createdDate,CmnLookupMst cmnLookupMstByLicenseType) {
		this.srNo = srNo;
		this.cmnLookupMst = cmnLookupMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgPostMstByUserId = orgPostMstByUserId;
		this.cmnLocationMst = cmnLocationMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.proofNum = proofNum;
		this.createdDate = createdDate;
		this.cmnLookupMstByLicenseType=cmnLookupMstByLicenseType;
	}

	/** full constructor */
	public HrEisProofDtl(long srNo, CmnLookupMst cmnLookupMst,
			OrgPostMst orgUserMstByUpdatedByPost,
			OrgUserMst orgUserMstByCreatedBy,
			OrgPostMst orgPostMstByCreatedByPost,
			OrgUserMst orgPostMstByUserId, CmnLocationMst cmnLocationMst,
			OrgUserMst orgUserMstByUpdatedBy, CmnDatabaseMst cmnDatabaseMst,
			String proofNum, String prooftypeOther, Date issueDate,
			Date expiryDate, String issuePlace, String issueAuthority,
			Date createdDate, Date updatedDate,CmnLookupMst cmnLookupMstByLicenseType) {
		this.srNo = srNo;
		this.cmnLookupMst = cmnLookupMst;
		this.orgUserMstByUpdatedByPost = orgUserMstByUpdatedByPost;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgPostMstByUserId = orgPostMstByUserId;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.proofNum = proofNum;
		this.prooftypeOther = prooftypeOther;
		this.issueDate = issueDate;
		this.expiryDate = expiryDate;
		this.issuePlace = issuePlace;
		this.issueAuthority = issueAuthority;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.cmnLookupMstByLicenseType=cmnLookupMstByLicenseType;
	}

	

	// Property accessors
	public long getSrNo() {
		return this.srNo;
	}

	public void setSrNo(long srNo) {
		this.srNo = srNo;
	}

	public CmnLookupMst getCmnLookupMst() {
		return this.cmnLookupMst;
	}

	public void setCmnLookupMst(CmnLookupMst cmnLookupMst) {
		this.cmnLookupMst = cmnLookupMst;
	}

	public OrgPostMst getOrgUserMstByUpdatedByPost() {
		return this.orgUserMstByUpdatedByPost;
	}

	public void setOrgUserMstByUpdatedByPost(OrgPostMst orgUserMstByUpdatedByPost) {
		this.orgUserMstByUpdatedByPost = orgUserMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return this.orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return this.orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(
			OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgUserMst getOrgPostMstByUserId() {
		return this.orgPostMstByUserId;
	}

	public void setOrgPostMstByUserId(OrgUserMst orgPostMstByUserId) {
		this.orgPostMstByUserId = orgPostMstByUserId;
	}

	public CmnLocationMst getCmnLocationMst() {
		return this.cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return this.orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return this.cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public String getProofNum() {
		return this.proofNum;
	}

	public void setProofNum(String proofNum) {
		this.proofNum = proofNum;
	}

	public String getProoftypeOther() {
		return this.prooftypeOther;
	}

	public void setProoftypeOther(String prooftypeOther) {
		this.prooftypeOther = prooftypeOther;
	}

	public Date getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	public String getIssuePlace() {
		return this.issuePlace;
	}

	public void setIssuePlace(String issuePlace) {
		this.issuePlace = issuePlace;
	}

	public String getIssueAuthority() {
		return this.issueAuthority;
	}

	public void setIssueAuthority(String issueAuthority) {
		this.issueAuthority = issueAuthority;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	public CmnLookupMst getCmnLookupMstByLicenseType() {
		return cmnLookupMstByLicenseType;
	}

	public void setCmnLookupMstByLicenseType(CmnLookupMst cmnLookupMstByLicenseType) {
		this.cmnLookupMstByLicenseType = cmnLookupMstByLicenseType;
	}
}
