package com.tcs.sgv.deduction.valueobject;
// Generated Aug 1, 2007 7:24:36 PM by Hibernate Tools 3.1.0.beta5
//Comment By Maruthi For import Organisation.

import java.util.Date;

import com.tcs.sgv.allowance.valueobject.HrPayArgumentMst;
import com.tcs.sgv.common.payroll.valueobject.HrPayCommissionMst;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrDeducArgumentMpg generated by hbm2java
 */
public class HrDeducArgumentMpg implements java.io.Serializable {

	// Fields    

	private long deducArgueId;

	private HrPayArgumentMst hrPayArgumentMstByCondArgueId;

	private HrPayDeducTypeMst hrPayDeducTypeMst;

	private HrPayArgumentMst hrPayArgumentMstByMainArgueId;

	private String methodName;

	private long arguOrder;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;

	private Date createdDate;
	
	private Date updatedDate;

	private long elementCode;

	private long elementOrder;

	private  HrPayCommissionMst hrPayCommissionMst;
	
	
	// Constructors

	/** default constructor */
	public HrDeducArgumentMpg() {
	}

	/** minimal constructor */
	public HrDeducArgumentMpg(long deducArgueId,
			HrPayDeducTypeMst hrPayDeducTypeMst) {
		this.deducArgueId = deducArgueId;
		this.hrPayDeducTypeMst = hrPayDeducTypeMst;
	}

	/** full constructor */
	public HrDeducArgumentMpg(long deducArgueId,
			HrPayArgumentMst hrPayArgumentMstByCondArgueId,
			HrPayDeducTypeMst hrPayDeducTypeMst,
			HrPayArgumentMst hrPayArgumentMstByMainArgueId, String methodName,
			CmnDatabaseMst cmnDatabaseMst ,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByCreatedBy, OrgPostMst orgPostMstByCreatedByPost,
			Date createdDate, long elementCode,
			long elementOrder) {
		this.deducArgueId = deducArgueId;
		this.hrPayArgumentMstByCondArgueId = hrPayArgumentMstByCondArgueId;
		this.hrPayDeducTypeMst = hrPayDeducTypeMst;
		this.hrPayArgumentMstByMainArgueId = hrPayArgumentMstByMainArgueId;
		this.methodName = methodName;
		this.arguOrder = arguOrder;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.createdDate = createdDate;
		this.elementCode = elementCode;
		this.elementOrder = elementOrder;
	}

	public long getArguOrder() {
		return arguOrder;
	}

	public void setArguOrder(long arguOrder) {
		this.arguOrder = arguOrder;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public long getDeducArgueId() {
		return deducArgueId;
	}

	public void setDeducArgueId(long deducArgueId) {
		this.deducArgueId = deducArgueId;
	}

	public long getElementCode() {
		return elementCode;
	}

	public void setElementCode(long elementCode) {
		this.elementCode = elementCode;
	}

	public long getElementOrder() {
		return elementOrder;
	}

	public void setElementOrder(long elementOrder) {
		this.elementOrder = elementOrder;
	}

	public HrPayArgumentMst getHrPayArgumentMstByCondArgueId() {
		return hrPayArgumentMstByCondArgueId;
	}

	public void setHrPayArgumentMstByCondArgueId(
			HrPayArgumentMst hrPayArgumentMstByCondArgueId) {
		this.hrPayArgumentMstByCondArgueId = hrPayArgumentMstByCondArgueId;
	}

	public HrPayArgumentMst getHrPayArgumentMstByMainArgueId() {
		return hrPayArgumentMstByMainArgueId;
	}

	public void setHrPayArgumentMstByMainArgueId(
			HrPayArgumentMst hrPayArgumentMstByMainArgueId) {
		this.hrPayArgumentMstByMainArgueId = hrPayArgumentMstByMainArgueId;
	}

	public HrPayDeducTypeMst getHrPayDeducTypeMst() {
		return hrPayDeducTypeMst;
	}

	public void setHrPayDeducTypeMst(HrPayDeducTypeMst hrPayDeducTypeMst) {
		this.hrPayDeducTypeMst = hrPayDeducTypeMst;
	}

	public String getMethodName() {
		return methodName;
	}

	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public HrPayCommissionMst getHrPayCommissionMst() {
		return hrPayCommissionMst;
	}

	public void setHrPayCommissionMst(HrPayCommissionMst hrPayCommissionMst) {
		this.hrPayCommissionMst = hrPayCommissionMst;
	}

	// Property accessors
	
}
