package com.tcs.sgv.admin.valueobject;

// Generated Jul 4, 2007 12:05:14 PM by Hibernate Tools 3.1.0.beta5

import com.tcs.sgv.common.valueobject.CmnLanguageMst;

/**
 * HrEisBranchMst generated by hbm2java
 */
public class OrgPostDtl implements java.io.Serializable {

	// Fields    

	private CmnLanguageMst cmnLanguageMst;

	private long postId;

	private String postName;

	// Constructors

	/** default constructor */
	public OrgPostDtl() {
	}
	
	public OrgPostDtl(CmnLanguageMst cmnLanguageMst, long postId,String postName) {
		this.cmnLanguageMst = cmnLanguageMst;
		this.postId = postId;
		this.postName = postName;
	}

		// Property accessors
	public long getPostId() {
		return this.postId;
	}

	public void setPostId(long postId) {
		this.postId = postId;
	}

	public String getPostName() {
		return this.postName;
	}

	public void setPostName(String postName) {
		this.postName = postName;
	}

		public CmnLanguageMst getCmnLanguageMst() {
		return cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	
}
