package com.tcs.sgv.dss.valueobject;
// Generated Aug 14, 2007 3:56:08 PM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashMap;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * RptExpEdpDtls generated by hbm2java
 */
public class RptExpEdpDtls implements java.io.Serializable {

	Log logger = LogFactory.getLog(getClass());
	
	//Fields    

	private BigDecimal expEdpId;

	private BigDecimal expId;

	private String objHd;

	private String edpHd;

	private BigDecimal amount;

	private BigDecimal paymentid;

	private Character edpType;

	private BigDecimal trnExpEdpId;

	private Character clientData;

	private Character active;
	
	private String crtUsr;

	private Date crtDt;


	// Constructors

	/** default constructor */
	public RptExpEdpDtls() 
	{
		this.expEdpId = new BigDecimal(0);
		this.expId = new BigDecimal(0);
		this.objHd = "";
		this.edpHd = "";
		this.amount = new BigDecimal(0);
		this.paymentid = new BigDecimal(0);
		this.edpType = '0';
		this.trnExpEdpId = new BigDecimal(0);
		this.clientData = 'N';
		this.active = 'Y';
		this.crtUsr = "";
		this.crtDt = null;
		
	}
	
	public String toString()
	{
		logger.info("Below are the Values of RptExpEdpDtls Object");
		logger.info("----------------------------------------------");
		logger.info("The value of ExpEdpId is :- "+this.expEdpId );
		logger.info("The value of expId is :- "+this.expId );
		logger.info("The value of objHd is :- "+this.objHd );
		logger.info("The value of edpHd is :- "+this.edpHd );
		logger.info("The value of amount is :- "+this.amount );
		logger.info("The value of paymentid is :- "+this.paymentid );
		logger.info("The value of edpType is :- "+this.edpType );
		logger.info("The value of trnExpEdpId is :- "+this.trnExpEdpId );
		logger.info("The value of clientData is :- "+this.clientData );
		logger.info("The value of active is :- "+this.active );
		logger.info("The value of created User  is :- " + this.crtUsr);
		logger.info("The value of created Date  is :- " + this.crtDt);
		
		return (super.toString());
		
		
	}

	/** minimal constructor */
	public RptExpEdpDtls(BigDecimal expEdpId) {
		this.expEdpId = expEdpId;
	}

	/** full constructor */
	public RptExpEdpDtls(BigDecimal expEdpId, BigDecimal expId, String objHd,
			String edpHd, BigDecimal amount, BigDecimal paymentid,
			Character edpType, BigDecimal trnExpEdpId, Character clientData,
			Character active) {
		this.expEdpId = expEdpId;
		this.expId = expId;
		this.objHd = objHd;
		this.edpHd = edpHd;
		this.amount = amount;
		this.paymentid = paymentid;
		this.edpType = edpType;
		this.trnExpEdpId = trnExpEdpId;
		this.clientData = clientData;
		this.active = active;
		this.crtUsr = crtUsr;
		this.crtDt = crtDt;
	}

	// Property accessors
	public BigDecimal getExpEdpId() {
		return this.expEdpId;
	}

	public void setExpEdpId(BigDecimal expEdpId) {
		this.expEdpId = expEdpId;
	}

	public BigDecimal getExpId() {
		return this.expId;
	}

	public void setExpId(BigDecimal expId) {
		this.expId = expId;
	}

	public String getObjHd() {
		return this.objHd;
	}

	public void setObjHd(String objHd) {
		this.objHd = objHd;
	}

	public String getEdpHd() {
		return this.edpHd;
	}

	public void setEdpHd(String edpHd) {
		this.edpHd = edpHd;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public BigDecimal getPaymentid() {
		return this.paymentid;
	}

	public void setPaymentid(BigDecimal paymentid) {
		this.paymentid = paymentid;
	}

	public Character getEdpType() {
		return this.edpType;
	}

	public void setEdpType(Character edpType) {
		this.edpType = edpType;
	}

	public BigDecimal getTrnExpEdpId() {
		return this.trnExpEdpId;
	}

	public void setTrnExpEdpId(BigDecimal trnExpEdpId) {
		this.trnExpEdpId = trnExpEdpId;
	}

	public Character getClientData() {
		return this.clientData;
	}

	public void setClientData(Character clientData) {
		this.clientData = clientData;
	}

	public Character getActive() {
		return this.active;
	}

	public void setActive(Character active) {
		this.active = active;
	}
	
	public String getCrtUsr() {
		return this.crtUsr;
	}

	public void setCrtUsr(String crtUsr) {
		this.crtUsr = crtUsr;
	}

	public Date getCrtDt() {
		return this.crtDt;
	}

	public void setCrtDt(Date crtDt) {
		this.crtDt = crtDt;
	}

	
	public HashMap validateData()
	{
		boolean flag = true;
		String status = "OK";
		HashMap returnMap = new HashMap();
		
		returnMap.put("flag", true);
		
		return returnMap;
	}

}
