// default package
// Generated Sep 3, 2008 10:32:14 AM by Hibernate Tools 3.1.0.beta5
package com.tcs.sgv.eis.valueobject;

import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrPayPaybillMiscDtls generated by hbm2java
 */
public class HrPayPaybillMiscDtls implements java.io.Serializable {

	// Fields    

	private long id;

	//private long paybillId;

	private long miscId;

	private long totalAmt;

	private long totalInst;

	private long recoveredAmt;

	private long recoveredInst;

	//private long dbId;

	//private long createdBy;

	//private long createdByPost;

	private Date createdDate;

	//private long updatedBy;

	//private long updatedByPost;

	private Date updatedDate;

	//private long locId;
	
	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;

	private HrPayPaybill paybillId;
	
	private long edpTypeId;
	// Constructors

	

	/** default constructor */
	public HrPayPaybillMiscDtls() {
	}

	/** minimal constructor */
	public HrPayPaybillMiscDtls(long id) {
		this.id = id;
	}

	/** full constructor */
	public HrPayPaybillMiscDtls(long id, HrPayPaybill paybillId,
			long miscId, long totalAmt, long totalInst,
			long recoveredAmt, long recoveredInst,Date createdDate, Date updatedDate,
			CmnDatabaseMst cmnDatabaseMst, CmnLocationMst cmnLocationMst,
			OrgUserMst orgUserMstByCreatedBy,OrgPostMst orgPostMstByCreatedByPost,
			OrgUserMst orgUserMstByUpdatedBy, OrgPostMst orgPostMstByUpdatedByPost) {
		this.id = id;
		this.paybillId = paybillId;
		this.miscId = miscId;
		this.totalAmt = totalAmt;
		this.totalInst = totalInst;
		this.recoveredAmt = recoveredAmt;
		this.recoveredInst = recoveredInst;
		this.cmnDatabaseMst=cmnDatabaseMst;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.createdDate = createdDate;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.updatedDate = updatedDate;
	}

	// Property accessors
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	/*public long getPaybillId() {
		return this.paybillId;
	}

	public void setPaybillId(long paybillId) {
		this.paybillId = paybillId;
	}*/

	public long getMiscId() {
		return this.miscId;
	}

	public void setMiscId(long miscId) {
		this.miscId = miscId;
	}

	public long getTotalAmt() {
		return this.totalAmt;
	}

	public void setTotalAmt(long totalAmt) {
		this.totalAmt = totalAmt;
	}

	public long getTotalInst() {
		return this.totalInst;
	}

	public void setTotalInst(long totalInst) {
		this.totalInst = totalInst;
	}

	public long getRecoveredAmt() {
		return this.recoveredAmt;
	}

	public void setRecoveredAmt(long recoveredAmt) {
		this.recoveredAmt = recoveredAmt;
	}

	public long getRecoveredInst() {
		return this.recoveredInst;
	}

	public void setRecoveredInst(long recoveredInst) {
		this.recoveredInst = recoveredInst;
	}

	/*public long getDbId() {
		return this.dbId;
	}

	public void setDbId(long dbId) {
		this.dbId = dbId;
	}

	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	public long getCreatedByPost() {
		return this.createdByPost;
	}

	public void setCreatedByPost(long createdByPost) {
		this.createdByPost = createdByPost;
	}
*/
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/*public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public long getUpdatedByPost() {
		return this.updatedByPost;
	}

	public void setUpdatedByPost(long updatedByPost) {
		this.updatedByPost = updatedByPost;
	}*/

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public HrPayPaybill getPaybillId() {
		return paybillId;
	}

	public void setPaybillId(HrPayPaybill paybillId) {
		this.paybillId = paybillId;
	}

	/*public long getLocId() {
		return this.locId;
	}

	public void setLocId(long locId) {
		this.locId = locId;
	}*/
	
	public long getEdpTypeId() {
		return edpTypeId;
	}

	public void setEdpTypeId(long edpTypeId) {
		this.edpTypeId = edpTypeId;
	}
}
