// default package
// Generated Sep 14, 2009 5:45:33 PM by Hibernate Tools 3.2.0.beta8
package com.tcs.sgv.common.valueobject;
/**
 * HstCmnLocationMstCoddoId generated by hbm2java
 */
public class HstCmnLocationMstCoddoId implements java.io.Serializable {

	// Fields    

	private long locId;

	private Integer trnCounter;

	// Constructors

	/** default constructor */
	public HstCmnLocationMstCoddoId() {
	}

	/** full constructor */
	public HstCmnLocationMstCoddoId(long locId, Integer trnCounter) {
		this.locId = locId;
		this.trnCounter = trnCounter;
	}

	// Property accessors
	public long getLocId() {
		return this.locId;
	}

	public void setLocId(long locId) {
		this.locId = locId;
	}

	public Integer getTrnCounter() {
		return this.trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HstCmnLocationMstCoddoId))
			return false;
		HstCmnLocationMstCoddoId castOther = (HstCmnLocationMstCoddoId) other;

		return (this.getLocId() == castOther.getLocId())
				&& (this.getTrnCounter() == castOther.getTrnCounter());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result +(int) this.getLocId();
		result = 37 * result + this.getTrnCounter();
		return result;
	}

}
