// default package
// Generated Nov 28, 2007 5:34:18 PM by Hibernate Tools 3.1.0.beta5
package com.tcs.sgv.eis.valueobject;

import java.io.Serializable;
import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrPayArgumentMst generated by hbm2java
 */
public class ArgumentMstVO implements Serializable {

	// Fields    

	private long argumentId;

	private String tableName;

	private String selcolName;

	private String condcolName;

	private long parentArgueId;

	
	
	private String path;
	
	private long parentId;



	// Constructors

	/** default constructor */
	public ArgumentMstVO() {
	}

	/** minimal constructor */
	public ArgumentMstVO(long argumentId) {
		this.argumentId = argumentId;
	}

	/** full constructor */
	public ArgumentMstVO(long argumentId, String tableName,
			String selcolName, String condcolName, long parentArgueId,
			//long locId, long dbId, long createdBy,
			CmnDatabaseMst cmnDatabaseMst,CmnLocationMst cmnLocationMst,OrgUserMst orgUserMstByCreatedBy,
			Date createdDate,OrgUserMst orgUserMstByUpdatedBy, Date updatedDate,
			//long createdByPost, long updatedByPost,
			OrgPostMst orgPostMstByCreatedBy,OrgPostMst orgPostMstByUpdatedBy,
			long elementCode,String path,long parentId) {
		this.argumentId = argumentId;
		this.tableName = tableName;
		this.selcolName = selcolName;
		this.condcolName = condcolName;
		this.parentArgueId = parentArgueId;		
		this.path = path;
		this.parentId = parentId;
	}

	// Property accessors
	public long getArgumentId() {
		return this.argumentId;
	}

	public void setArgumentId(long argumentId) {
		this.argumentId = argumentId;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getSelcolName() {
		return this.selcolName;
	}

	public void setSelcolName(String selcolName) {
		this.selcolName = selcolName;
	}

	public String getCondcolName() {
		return this.condcolName;
	}

	public void setCondcolName(String condcolName) {
		this.condcolName = condcolName;
	}

	public long getParentArgueId() {
		return this.parentArgueId;
	}

	public void setParentArgueId(long parentArgueId) {
		this.parentArgueId = parentArgueId;
	}

	/*public String getParentId() {
		return parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}*/

	public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public void setParentId(long parentId) {
		this.parentId = parentId;
	}

	public long getParentId() {
		return parentId;
	}

}
