package com.tcs.sgv.eis.valueobject;

// default package
// Generated Nov 20, 2007 8:49:33 AM by Hibernate Tools 3.2.0.beta8

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;
import java.util.Date;

/**
 * HrEisLanguageProficiency generated by hbm2java
 */
public class HrEisLangPrfcncyDtl implements java.io.Serializable {

	// Fields    

	private long langProfPkId;

	private OrgUserMst orgUserMstByUserId;

	private CmnLookupMst cmnLookupMst;
	
	private CmnLookupMst cmnLookupMstReadProf;
	private CmnLookupMst cmnLookupMstWriteProf;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByCreatedBy;

	private OrgUserMst orgUserMstByUpdatedBy;

	private Date createdDate;

	private Date updatedDate;

	private CmnLookupMst cmnLanguageMstByLanguageId;
	
	private HrEisEmpMst hrEisEmpMst;

	// Constructors

	/** default constructor */
	public HrEisLangPrfcncyDtl() {
	}

	/** minimal constructor */
	public HrEisLangPrfcncyDtl(long langProfPkId) {
		this.langProfPkId = langProfPkId;
	}

	/** full constructor */
	public HrEisLangPrfcncyDtl(long langProfPkId,
			OrgUserMst orgUserMstByUserId, CmnLookupMst cmnLookupMst,CmnLookupMst cmnLookupMstReadProf,
			CmnLookupMst cmnLookupMstWriteProf,CmnDatabaseMst cmnDatabaseMst,
			OrgPostMst orgPostMstByUpdatedByPost,
			OrgPostMst orgPostMstByCreatedByPost,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByCreatedBy,
			OrgUserMst orgUserMstByUpdatedBy, Date createdDate,
			Date updatedDate, CmnLookupMst cmnLanguageMstByLanguageId, HrEisEmpMst hrEisEmpMst) {
		this.langProfPkId = langProfPkId;
		this.orgUserMstByUserId = orgUserMstByUserId;
		this.cmnLookupMst = cmnLookupMst;
		this.cmnLookupMstReadProf = cmnLookupMstReadProf;
		this.cmnLookupMstWriteProf = cmnLookupMstWriteProf;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.cmnLanguageMstByLanguageId = cmnLanguageMstByLanguageId;
		this.hrEisEmpMst = hrEisEmpMst;
	}

	// Property accessors
	public long getLangProfPkId() {
		return this.langProfPkId;
	}

	public void setLangProfPkId(long langProfPkId) {
		this.langProfPkId = langProfPkId;
	}

	public OrgUserMst getOrgUserMstByUserId() {
		return this.orgUserMstByUserId;
	}

	public void setOrgUserMstByUserId(OrgUserMst orgUserMstByUserId) {
		this.orgUserMstByUserId = orgUserMstByUserId;
	}

	public CmnLookupMst getCmnLookupMst() {
		return this.cmnLookupMst;
	}

	public void setCmnLookupMst(CmnLookupMst cmnLookupMst) {
		this.cmnLookupMst = cmnLookupMst;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return this.cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return this.orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(
			OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return this.orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(
			OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public CmnLocationMst getCmnLocationMst() {
		return this.cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return this.orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return this.orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public CmnLookupMst getCmnLanguageMstByLanguageId() {
		return this.cmnLanguageMstByLanguageId;
	}

	public void setCmnLanguageMstByLanguageId(CmnLookupMst cmnLanguageMstByLanguageId) {
		this.cmnLanguageMstByLanguageId = cmnLanguageMstByLanguageId;
	}

	public CmnLookupMst getCmnLookupMstReadProf() {
		return cmnLookupMstReadProf;
	}

	public void setCmnLookupMstReadProf(CmnLookupMst cmnLookupMstReadProf) {
		this.cmnLookupMstReadProf = cmnLookupMstReadProf;
	}

	public CmnLookupMst getCmnLookupMstWriteProf() {
		return cmnLookupMstWriteProf;
	}

	public void setCmnLookupMstWriteProf(CmnLookupMst cmnLookupMstWriteProf) {
		this.cmnLookupMstWriteProf = cmnLookupMstWriteProf;
	}

	public HrEisEmpMst getHrEisEmpMst() {
		return hrEisEmpMst;
	}

	public void setHrEisEmpMst(HrEisEmpMst hrEisEmpMst) {
		this.hrEisEmpMst = hrEisEmpMst;
	}
}
