package com.tcs.sgv.eis.valueobject;

// default package
// Generated Feb 1, 2008 12:16:06 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.Set;

import com.tcs.sgv.common.valueobject.CmnBranchMst;
import com.tcs.sgv.common.valueobject.CmnCityMst;
import com.tcs.sgv.common.valueobject.CmnCountryMst;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.ess.valueobject.OrgDepartmentMst;
import com.tcs.sgv.ess.valueobject.OrgEmpMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;
import com.tcs.sgv.hod.common.valueobject.CmnAddressMst;

//import com.tcs.sgv.eis.valueobject.HrLoanEmpDtls;

/**
 * HrEisEmpMst generated by hbm2java
 */
public class HrEisEmpMst implements java.io.Serializable {

	// Fields    

	private long empId;
	
	private String sevarthEmpCode;

	private OrgPostMst orgPostMst;

	private CmnAddressMst cmnAddressMstByEmpBirthPlaceAddressId;

	private CmnAddressMst cmnAddressMstByEmpPermanentAddressId;

	private CmnLookupMst cmnLanguageMst;

	private OrgEmpMst orgEmpMst;

	private CmnAddressMst cmnAddressMstByEmpNativePlaceAddressId;

	private CmnLookupMst cmnLookupMstByEmpCasteId;

	private CmnDatabaseMst cmnDatabaseMst;

	private CmnLookupMst cmnLookupMstByEmpSubCasteId;

	private CmnAddressMst cmnAddressMstByEmpCurrentAddressId;

	private CmnLookupMst cmnLookupMstByEmpReligionId;

	private CmnLookupMst cmnLookupMstByEmpCategoryId;

	private CmnLookupMst cmnLookupMstByEmpMaritalStatusId;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;

	private HrEisBiometricDtl hrPersonBiometricDtls;

	private Character empGender;

	private String empStatusId;

	private Date empApptLtrDt;

	private String empApptLtrNo;

	private Date empConfDueDt;

	private String empSalDisbMd;

	private CmnCountryMst cmnCountryMstByEmpNationality;

	private CmnLocationMst cmnLocationMst;

	private Date createdDate;

	private Date updatedDate;

	private String empHobby;

	private Long empType;

	private Long empRecruitSrc;

	private String email;

	private Long contactNo;
	
	private Integer trnCounter;
	
	

	//Added by Abhilash For Cadre Information
	private HrEisCadreMst hrEisCadreMst;
	
	private HrEisGroupMst hrEisGroupMst;
	//Ended

	//Added by Abhilash For Branch Information
	private CmnBranchMst cmnBranchMst;
	private CmnLookupMst cmnLookupMstForGisGroup;
	private CmnCityMst cmnCityMst;
	private OrgDepartmentMst orgDepartmentMst;
	private OrgSchemeMstVO orgSchemeMst;
	
	private Date branchJoinDate ;
	private Date cadreJoinDate ;
	private String gisApplicable ;
	private Date membershipDate;
	private String dcpsAcNo;
	private long uidNo;
	private Date dateofinitialappointment;
	
	
	
	//Ended
	/*private Set hrLoanEmpDtlses = new HashSet(0);
	private Set hrEisBankDtlses = new HashSet(0);
	private Set hrLeaveEmpDtlses = new HashSet(0);
*/
	// Constructors


	public CmnBranchMst getCmnBranchMst() {
		return cmnBranchMst;
	}

	public void setCmnBranchMst(CmnBranchMst cmnBranchMst) {
		this.cmnBranchMst = cmnBranchMst;
	}

	public Date getBranchJoinDate() {
		return branchJoinDate;
	}

	public void setBranchJoinDate(Date branchJoinDate) {
		this.branchJoinDate = branchJoinDate;
	}

	public Date getCadreJoinDate() {
		return cadreJoinDate;
	}

	public void setCadreJoinDate(Date cadreJoinDate) {
		this.cadreJoinDate = cadreJoinDate;
	}

	public String getGisApplicable() {
		return gisApplicable;
	}

	public void setGisApplicable(String gisApplicable) {
		this.gisApplicable = gisApplicable;
	}

	

	public Date getMembershipDate() {
		return membershipDate;
	}

	public void setMembershipDate(Date membershipDate) {
		this.membershipDate = membershipDate;
	}

	public String getDcpsAcNo() {
		return dcpsAcNo;
	}

	public void setDcpsAcNo(String dcpsAcNo) {
		this.dcpsAcNo = dcpsAcNo;
	}

	public CmnCityMst getCmnCityMst() {
		return cmnCityMst;
	}

	public void setCmnCityMst(CmnCityMst cmnCityMst) {
		this.cmnCityMst = cmnCityMst;
	}



	

	/** default constructor */
	public HrEisEmpMst() {
	}

	/** minimal constructor */
	public HrEisEmpMst(long empId) {
		this.empId = empId;
	}

	/** full constructor */
	public HrEisEmpMst(long empId, OrgPostMst orgPostMst,
			CmnAddressMst cmnAddressMstByEmpBirthPlaceAddressId,
			CmnAddressMst cmnAddressMstByEmpPermanentAddressId,
			CmnLookupMst cmnLanguageMst, OrgEmpMst orgEmpMst,
			CmnAddressMst cmnAddressMstByEmpNativePlaceAddressId,
			CmnLookupMst cmnLookupMstByEmpCasteId,
			CmnDatabaseMst cmnDatabaseMst,
			CmnLookupMst cmnLookupMstByEmpSubCasteId,
			CmnAddressMst cmnAddressMstByEmpCurrentAddressId,
			CmnLookupMst cmnLookupMstByEmpReligionId,
			CmnLookupMst cmnLookupMstByEmpCategoryId,
			CmnLookupMst cmnLookupMstByEmpMaritalStatusId,
			OrgUserMst orgUserMstByUpdatedBy, OrgUserMst orgUserMstByCreatedBy,
			HrEisBiometricDtl hrPersonBiometricDtls, Character empGender,
			String empStatusId, Date empApptLtrDt, String empApptLtrNo,
			Date empConfDueDt, String empSalDisbMd, CmnCountryMst cmnCountryMstByEmpNationality,
			CmnLocationMst cmnLocationMst, Date createdDate, Date updatedDate, String empHobby,
			Long empType, Long empRecruitSrc, String email, Long contactNo,Set hrLoanEmpDtlses,Set hrLeaveEmpDtlses, Integer trnCounter) {
		this.empId = empId;
		this.orgPostMst = orgPostMst;
		this.cmnAddressMstByEmpBirthPlaceAddressId = cmnAddressMstByEmpBirthPlaceAddressId;
		this.cmnAddressMstByEmpPermanentAddressId = cmnAddressMstByEmpPermanentAddressId;
		this.cmnLanguageMst = cmnLanguageMst;
		this.orgEmpMst = orgEmpMst;
		this.cmnAddressMstByEmpNativePlaceAddressId = cmnAddressMstByEmpNativePlaceAddressId;
		this.cmnLookupMstByEmpCasteId = cmnLookupMstByEmpCasteId;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnLookupMstByEmpSubCasteId = cmnLookupMstByEmpSubCasteId;
		this.cmnAddressMstByEmpCurrentAddressId = cmnAddressMstByEmpCurrentAddressId;
		this.cmnLookupMstByEmpReligionId = cmnLookupMstByEmpReligionId;
		this.cmnLookupMstByEmpCategoryId = cmnLookupMstByEmpCategoryId;
		this.cmnLookupMstByEmpMaritalStatusId = cmnLookupMstByEmpMaritalStatusId;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.hrPersonBiometricDtls = hrPersonBiometricDtls;
		this.empGender = empGender;
		this.empStatusId = empStatusId;
		this.empApptLtrDt = empApptLtrDt;
		this.empApptLtrNo = empApptLtrNo;
		this.empConfDueDt = empConfDueDt;
		this.empSalDisbMd = empSalDisbMd;
		this.cmnCountryMstByEmpNationality = cmnCountryMstByEmpNationality;
		this.cmnLocationMst = cmnLocationMst;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.empHobby = empHobby;
		this.empType = empType;
		this.empRecruitSrc = empRecruitSrc;
		this.email = email;
		/*this.hrLoanEmpDtlses = hrLoanEmpDtlses;
		this.hrLeaveEmpDtlses = hrLeaveEmpDtlses;*/
		this.contactNo = contactNo;
		this.trnCounter = trnCounter;
	}

	// Property accessors
	public long getEmpId() {
		return this.empId;
	}

	public void setEmpId(long empId) {
		this.empId = empId;
	}

	public OrgPostMst getOrgPostMst() {
		return this.orgPostMst;
	}

	public void setOrgPostMst(OrgPostMst orgPostMst) {
		this.orgPostMst = orgPostMst;
	}

	public CmnAddressMst getCmnAddressMstByEmpBirthPlaceAddressId() {
		return this.cmnAddressMstByEmpBirthPlaceAddressId;
	}

	public void setCmnAddressMstByEmpBirthPlaceAddressId(
			CmnAddressMst cmnAddressMstByEmpBirthPlaceAddressId) {
		this.cmnAddressMstByEmpBirthPlaceAddressId = cmnAddressMstByEmpBirthPlaceAddressId;
	}

	public CmnAddressMst getCmnAddressMstByEmpPermanentAddressId() {
		return this.cmnAddressMstByEmpPermanentAddressId;
	}

	public void setCmnAddressMstByEmpPermanentAddressId(
			CmnAddressMst cmnAddressMstByEmpPermanentAddressId) {
		this.cmnAddressMstByEmpPermanentAddressId = cmnAddressMstByEmpPermanentAddressId;
	}

	public CmnLookupMst getCmnLanguageMst() {
		return this.cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLookupMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public OrgEmpMst getOrgEmpMst() {
		return this.orgEmpMst;
	}

	public void setOrgEmpMst(OrgEmpMst orgEmpMst) {
		this.orgEmpMst = orgEmpMst;
	}

	public CmnAddressMst getCmnAddressMstByEmpNativePlaceAddressId() {
		return this.cmnAddressMstByEmpNativePlaceAddressId;
	}

	public void setCmnAddressMstByEmpNativePlaceAddressId(
			CmnAddressMst cmnAddressMstByEmpNativePlaceAddressId) {
		this.cmnAddressMstByEmpNativePlaceAddressId = cmnAddressMstByEmpNativePlaceAddressId;
	}

	public CmnLookupMst getCmnLookupMstByEmpCasteId() {
		return this.cmnLookupMstByEmpCasteId;
	}

	public void setCmnLookupMstByEmpCasteId(
			CmnLookupMst cmnLookupMstByEmpCasteId) {
		this.cmnLookupMstByEmpCasteId = cmnLookupMstByEmpCasteId;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return this.cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLookupMst getCmnLookupMstByEmpSubCasteId() {
		return this.cmnLookupMstByEmpSubCasteId;
	}

	public void setCmnLookupMstByEmpSubCasteId(
			CmnLookupMst cmnLookupMstByEmpSubCasteId) {
		this.cmnLookupMstByEmpSubCasteId = cmnLookupMstByEmpSubCasteId;
	}

	public CmnAddressMst getCmnAddressMstByEmpCurrentAddressId() {
		return this.cmnAddressMstByEmpCurrentAddressId;
	}

	public void setCmnAddressMstByEmpCurrentAddressId(
			CmnAddressMst cmnAddressMstByEmpCurrentAddressId) {
		this.cmnAddressMstByEmpCurrentAddressId = cmnAddressMstByEmpCurrentAddressId;
	}

	public CmnLookupMst getCmnLookupMstByEmpReligionId() {
		return this.cmnLookupMstByEmpReligionId;
	}

	public void setCmnLookupMstByEmpReligionId(
			CmnLookupMst cmnLookupMstByEmpReligionId) {
		this.cmnLookupMstByEmpReligionId = cmnLookupMstByEmpReligionId;
	}

	public CmnLookupMst getCmnLookupMstByEmpCategoryId() {
		return this.cmnLookupMstByEmpCategoryId;
	}

	public void setCmnLookupMstByEmpCategoryId(
			CmnLookupMst cmnLookupMstByEmpCategoryId) {
		this.cmnLookupMstByEmpCategoryId = cmnLookupMstByEmpCategoryId;
	}

	public CmnLookupMst getCmnLookupMstByEmpMaritalStatusId() {
		return this.cmnLookupMstByEmpMaritalStatusId;
	}

	public void setCmnLookupMstByEmpMaritalStatusId(
			CmnLookupMst cmnLookupMstByEmpMaritalStatusId) {
		this.cmnLookupMstByEmpMaritalStatusId = cmnLookupMstByEmpMaritalStatusId;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return this.orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return this.orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public HrEisBiometricDtl getHrPersonBiometricDtls() {
		return this.hrPersonBiometricDtls;
	}

	public void setHrPersonBiometricDtls(
			HrEisBiometricDtl hrPersonBiometricDtls) {
		this.hrPersonBiometricDtls = hrPersonBiometricDtls;
	}

	public Character getEmpGender() {
		return this.empGender;
	}

	public void setEmpGender(Character empGender) {
		this.empGender = empGender;
	}

	public String getEmpStatusId() {
		return this.empStatusId;
	}

	public void setEmpStatusId(String empStatusId) {
		this.empStatusId = empStatusId;
	}

	public Date getEmpApptLtrDt() {
		return this.empApptLtrDt;
	}

	public void setEmpApptLtrDt(Date empApptLtrDt) {
		this.empApptLtrDt = empApptLtrDt;
	}

	public String getEmpApptLtrNo() {
		return this.empApptLtrNo;
	}

	public void setEmpApptLtrNo(String empApptLtrNo) {
		this.empApptLtrNo = empApptLtrNo;
	}

	public Date getEmpConfDueDt() {
		return this.empConfDueDt;
	}

	public void setEmpConfDueDt(Date empConfDueDt) {
		this.empConfDueDt = empConfDueDt;
	}

	public String getEmpSalDisbMd() {
		return this.empSalDisbMd;
	}

	public void setEmpSalDisbMd(String empSalDisbMd) {
		this.empSalDisbMd = empSalDisbMd;
	}

	public CmnCountryMst getCmnCountryMstByEmpNationality() {
		return cmnCountryMstByEmpNationality;
	}

	public void setCmnCountryMstByEmpNationality(
			CmnCountryMst cmnCountryMstByEmpNationality) {
		this.cmnCountryMstByEmpNationality = cmnCountryMstByEmpNationality;
	}
	
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getEmpHobby() {
		return this.empHobby;
	}

	public void setEmpHobby(String empHobby) {
		this.empHobby = empHobby;
	}

	public Long getEmpType() {
		return this.empType;
	}

	public void setEmpType(Long empType) {
		this.empType = empType;
	}

	public Long getEmpRecruitSrc() {
		return this.empRecruitSrc;
	}

	public void setEmpRecruitSrc(Long empRecruitSrc) {
		this.empRecruitSrc = empRecruitSrc;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Long getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(Long contactNo) {
		this.contactNo = contactNo;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}
	
	public Integer getTrnCounter() {
		return trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}
	
	
	//Added by Abhialash for Cadre information
	public HrEisCadreMst getHrEisCadreMst() {
		return hrEisCadreMst;
	}

	public void setHrEisCadreMst(HrEisCadreMst hrEisCadreMst) {
		this.hrEisCadreMst = hrEisCadreMst;
	}

	public HrEisGroupMst getHrEisGroupMst() {
		return hrEisGroupMst;
	}

	public void setHrEisGroupMst(HrEisGroupMst hrEisGroupMst) {
		this.hrEisGroupMst = hrEisGroupMst;
	}

	public Date getDateofinitialappointment() {
		return dateofinitialappointment;
	}

	public void setDateofinitialappointment(Date dateofinitialappointment) {
		this.dateofinitialappointment = dateofinitialappointment;
	}

	public long getUidNo() {
		return uidNo;
	}

	public void setUidNo(long uidNo) {
		this.uidNo = uidNo;
	}

	public OrgDepartmentMst getOrgDepartmentMst() {
		return orgDepartmentMst;
	}

	public void setOrgDepartmentMst(OrgDepartmentMst orgDepartmentMst) {
		this.orgDepartmentMst = orgDepartmentMst;
	}

	public OrgSchemeMstVO getOrgSchemeMst() {
		return orgSchemeMst;
	}

	public void setOrgSchemeMst(OrgSchemeMstVO orgSchemeMst) {
		this.orgSchemeMst = orgSchemeMst;
	}

	public CmnLookupMst getCmnLookupMstForGisGroup() {
		return cmnLookupMstForGisGroup;
	}

	public void setCmnLookupMstForGisGroup(CmnLookupMst cmnLookupMstForGisGroup) {
		this.cmnLookupMstForGisGroup = cmnLookupMstForGisGroup;
	}

	/**
	 * @return the sevarthEmpCode
	 */
	public String getSevarthEmpCode() {
		return sevarthEmpCode;
	}

	/**
	 * @param sevarthEmpCode the sevarthEmpCode to set
	 */
	public void setSevarthEmpCode(String sevarthEmpCode) {
		this.sevarthEmpCode = sevarthEmpCode;
	}

	

	
	
	
	
	/*public Set getHrLoanEmpDtlses() {
		return hrLoanEmpDtlses;
	}

	public void setHrLoanEmpDtlses(Set hrLoanEmpDtlses) {
		this.hrLoanEmpDtlses = hrLoanEmpDtlses;
	}
*/
	/*public Set getHrEisBankDtlses() {
			return this.hrEisBankDtlses;
		}

		public void setHrEisBankDtlses(Set hrEisBankDtlses) {
			this.hrEisBankDtlses = hrEisBankDtlses;
		}
		
		public Set getHrLeaveEmpDtlses() {
			return hrLeaveEmpDtlses;
		}

		public void setHrLeaveEmpDtlses(Set hrLeaveEmpDtlses) {
			this.hrLeaveEmpDtlses = hrLeaveEmpDtlses;
		}
*/
}
