package com.tcs.sgv.eis.valueobject;

// Generated Jul 4, 2007 12:05:14 PM by Hibernate Tools 3.1.0.beta5

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrEisBranchMst generated by hbm2java
 */
public class HrEisBranchMst implements java.io.Serializable {

	// Fields    

	private CmnLanguageMst cmnLanguageMst;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;
	
	
	private long branchId;

	private HrEisBankMst hrEisBankMst;

	private String branchName;

	private String branchCode;

	private String branchAddr;

	private long branchVlgeId;

	private long branchTalId;

	private long branchDistId;

	private long branchStateId;

	private long branchCntryId;

	private Date createdDate;

	

	private Date updatedDate;

	private Set hrEisBankDtlses = new HashSet(0);
	private Long branchTypeCode;
	
	private String micrCode;
	
	private String ifscCode;

	// Constructors

	/** default constructor */
	public HrEisBranchMst() {
	}

	/** minimal constructor */
	public HrEisBranchMst(long branchId, HrEisBankMst hrEisBankMst,
			CmnLanguageMst cmnLanguageMst,
			CmnDatabaseMst cmnDatabaseMst,
			OrgPostMst orgPostMstByCreatedByPost,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByCreatedBy,
			String branchName, String branchCode, String branchAddr,
			long branchVlgeId, long branchTalId, long branchDistId,
			long branchStateId, long branchCntryId,
			Date createdDate,long branchTypeCode) {
		this.branchId = branchId;
		this.hrEisBankMst = hrEisBankMst;
		this.branchName = branchName;
		this.branchCode = branchCode;
		this.branchAddr = branchAddr;
		this.branchVlgeId = branchVlgeId;
		this.branchTalId = branchTalId;
		this.branchDistId = branchDistId;
		this.branchStateId = branchStateId;
		this.branchCntryId = branchCntryId;
		this.cmnLanguageMst = cmnLanguageMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.createdDate = createdDate;
		this.branchTypeCode = branchTypeCode;
		
	}

	/** full constructor */
	public HrEisBranchMst(long branchId, HrEisBankMst hrEisBankMst,
			String branchName, String branchCode, String branchAddr,
			long branchVlgeId, long branchTalId, long branchDistId,
			long branchStateId, long branchCntryId, long langId,
			Date createdDate,CmnLanguageMst cmnLanguageMst,
			CmnDatabaseMst cmnDatabaseMst,
			OrgPostMst orgPostMstByUpdatedByPost,
			OrgPostMst orgPostMstByCreatedByPost,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByUpdatedBy,
			OrgUserMst orgUserMstByCreatedBy,
			Date updatedDate) {
		this.branchId = branchId;
		this.hrEisBankMst = hrEisBankMst;
		this.branchName = branchName;
		this.branchCode = branchCode;
		this.branchAddr = branchAddr;
		this.branchVlgeId = branchVlgeId;
		this.branchTalId = branchTalId;
		this.branchDistId = branchDistId;
		this.branchStateId = branchStateId;
		this.branchCntryId = branchCntryId;		
		this.createdDate = createdDate;		
		this.updatedDate = updatedDate;
		this.cmnLanguageMst = cmnLanguageMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		
	}

	// Property accessors
	public long getBranchId() {
		return this.branchId;
	}

	public void setBranchId(long branchId) {
		this.branchId = branchId;
	}

	public HrEisBankMst getHrEisBankMst() {
		return this.hrEisBankMst;
	}

	public void setHrEisBankMst(HrEisBankMst hrEisBankMst) {
		this.hrEisBankMst = hrEisBankMst;
	}

	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String bankName) {
		this.branchName = bankName;
	}

	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	public String getBranchAddr() {
		return this.branchAddr;
	}

	public void setBranchAddr(String branchAddr) {
		this.branchAddr = branchAddr;
	}

	public long getBranchVlgeId() {
		return this.branchVlgeId;
	}

	public void setBranchVlgeId(long branchVlgeId) {
		this.branchVlgeId = branchVlgeId;
	}

	public long getBranchTalId() {
		return this.branchTalId;
	}

	public void setBranchTalId(long branchTalId) {
		this.branchTalId = branchTalId;
	}

	public long getBranchDistId() {
		return this.branchDistId;
	}

	public void setBranchDistId(long branchDistId) {
		this.branchDistId = branchDistId;
	}

	public long getBranchStateId() {
		return this.branchStateId;
	}

	public void setBranchStateId(long branchStateId) {
		this.branchStateId = branchStateId;
	}

	public long getBranchCntryId() {
		return this.branchCntryId;
	}

	public void setBranchCntryId(long branchCntryId) {
		this.branchCntryId = branchCntryId;
	}

	
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Long getBranchTypeCode() {
		return branchTypeCode;
	}

	public void setBranchTypeCode(Long branchTypeCode) {
		this.branchTypeCode = branchTypeCode;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public Set getHrEisBankDtlses() {
		return this.hrEisBankDtlses;
	}

	public void setHrEisBankDtlses(Set hrEisBankDtlses) {
		this.hrEisBankDtlses = hrEisBankDtlses;
	}
	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public String getMicrCode() {
		return micrCode;
	}

	public void setMicrCode(String micrCode) {
		this.micrCode = micrCode;
	}

	public String getIfscCode() {
		return ifscCode;
	}

	public void setIfscCode(String ifscCode) {
		this.ifscCode = ifscCode;
	}

}
