// default package
// Generated Aug 23, 2007 11:35:44 AM by Hibernate Tools 3.2.0.beta8
package com.tcs.sgv.eis.valueobject;

import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.eis.valueobject.HrEisQuaterTypeMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrEisOtherDtlsHst generated by hbm2java
 */
@SuppressWarnings("serial")
public class HrEisOtherDtlsHst implements java.io.Serializable
{

	// Fields    

	/*private long empId;

	private long empDeptId;

	private long dbId;

	private long createdBy;

	private long createdByPost;*/

	private Date createdDate;

	/*private long updatedBy;

	private long updatedByPost;*/

	private Date updatedDate;

	//private long empSgdId;

	private long otherCurrentBasic;

	private String phyChallenged;

	private long city;

	//private long quaterId;

	//private long incomeTax;

	private double totalSalary;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;

	private HrEisEmpMst hrEisEmpMst;

	private HrEisSgdMpg hrEisSgdMpg;

	//private HrEisDeptMst hrEisDeptMst;

	private HrEisQuaterTypeMst hrQuaterTypeMst;

	private HrEisOtherDtlsHstId id;

	private Date incrementDate;

	private long incomeTax;

	private long medAllowance;
	private long uniformAvailed;

	/*	private String sis1979Flag;
		
		private String othFamilyPlanning;
		
		private int familyPlnAmt;*/

	private int ownHouse;
	//private int isSis;

	private Date commissionAcceptanceDate;

	private int isAvailedHRA;

	// Constructors

	public int getOwnHouse()
	{
		return ownHouse;
	}

	public void setOwnHouse(int ownHouse)
	{
		this.ownHouse = ownHouse;
	}

	/*public String getSis1979Flag() {
		return sis1979Flag;
	}

	public void setSis1979Flag(String sis1979Flag) {
		this.sis1979Flag = sis1979Flag;
	}*/

	public long getMedAllowance()
	{
		return medAllowance;
	}

	public void setMedAllowance(long medAllowance)
	{
		this.medAllowance = medAllowance;
	}

	public long getUniformAvailed()
	{
		return uniformAvailed;
	}

	public void setUniformAvailed(long uniformAvailed)
	{
		this.uniformAvailed = uniformAvailed;
	}

	/** default constructor */
	public HrEisOtherDtlsHst()
	{}

	/** minimal constructor */
	public HrEisOtherDtlsHst(HrEisEmpMst hrEisEmpMst, HrEisOtherDtlsHstId id)
	{
		this.id = id;
		this.hrEisEmpMst = hrEisEmpMst;
	}

	/** full constructor */
	public HrEisOtherDtlsHst(HrEisOtherDtlsHstId id, Date createdDate, Date updatedDate, long otherCurrentBasic, String phyChallenged, long city, CmnDatabaseMst cmnDatabaseMst, OrgPostMst orgPostMstByUpdatedByPost, HrEisQuaterTypeMst hrQuaterTypeMst, OrgPostMst orgPostMstByCreatedByPost, OrgUserMst orgUserMstByCreatedBy, double totalSalary, HrEisEmpMst hrEisEmpMst, HrEisSgdMpg hrEisSgdMpg,//, HrEisDeptMst hrEisDeptMst
			Date commissionAcceptanceDate)
	{

		/*this.empId = empId;
		this.empDeptId = empDeptId;
		this.dbId = dbId;
		this.createdBy = createdBy;
		this.createdByPost = createdByPost;*/
		this.id = id;
		this.createdDate = createdDate;
		/*this.updatedBy = updatedBy;
		this.updatedByPost = updatedByPost;*/
		this.updatedDate = updatedDate;
		//this.empSgdId = empSgdId;
		this.otherCurrentBasic = otherCurrentBasic;
		this.phyChallenged = phyChallenged;
		this.city = city;
		//this.quaterId = quaterId;
		//this.incomeTax = incomeTax;

		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.hrEisEmpMst = hrEisEmpMst;
		this.hrQuaterTypeMst = hrQuaterTypeMst;
		this.hrEisSgdMpg = hrEisSgdMpg;
		this.totalSalary = totalSalary;
		//this.hrEisDeptMst = hrEisDeptMst;
		this.commissionAcceptanceDate = commissionAcceptanceDate;

	}

	// Property accessors

	/*public long getEmpId() {
		return this.empId;
	}

	public void setEmpId(long empId) {
		this.empId = empId;
	}

	public long getEmpDeptId() {
		return this.empDeptId;
	}

	public void setEmpDeptId(long empDeptId) {
		this.empDeptId = empDeptId;
	}

	public long getDbId() {
		return this.dbId;
	}

	public void setDbId(long dbId) {
		this.dbId = dbId;
	}

	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	public long getCreatedByPost() {
		return this.createdByPost;
	}

	public void setCreatedByPost(long createdByPost) {
		this.createdByPost = createdByPost;
	}*/

	public Date getCreatedDate()
	{
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate)
	{
		this.createdDate = createdDate;
	}

	/*public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public long getUpdatedByPost() {
		return this.updatedByPost;
	}

	public void setUpdatedByPost(long updatedByPost) {
		this.updatedByPost = updatedByPost;
	}*/

	public Date getUpdatedDate()
	{
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate)
	{
		this.updatedDate = updatedDate;
	}

	/*public long getEmpSgdId() {
		return this.empSgdId;
	}

	public void setEmpSgdId(long empSgdId) {
		this.empSgdId = empSgdId;
	}*/

	public long getotherCurrentBasic()
	{
		return this.otherCurrentBasic;
	}

	public void setotherCurrentBasic(long otherCurrentBasic)
	{
		this.otherCurrentBasic = otherCurrentBasic;
	}

	public String getPhyChallenged()
	{
		return this.phyChallenged;
	}

	public void setPhyChallenged(String phyChallenged)
	{
		this.phyChallenged = phyChallenged;
	}

	public long getCity()
	{
		return this.city;
	}

	public void setCity(long city)
	{
		this.city = city;
	}

	/*public long getQuaterId() {
		return this.quaterId;
	}

	public void setQuaterId(long quaterId) {
		this.quaterId = quaterId;
	}*/

	/*public long getIncomeTax() {
		return this.incomeTax;
	}

	public void setIncomeTax(long incomeTax) {
		this.incomeTax = incomeTax;
	}*/

	public CmnDatabaseMst getCmnDatabaseMst()
	{
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst)
	{
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	/*public HrEisDeptMst getHrEisDeptMst() {
		return hrEisDeptMst;
	}

	public void setHrEisDeptMst(HrEisDeptMst hrEisDeptMst) {
		this.hrEisDeptMst = hrEisDeptMst;
	}*/

	public HrEisEmpMst getHrEisEmpMst()
	{
		return hrEisEmpMst;
	}

	public void setHrEisEmpMst(HrEisEmpMst hrEisEmpMst)
	{
		this.hrEisEmpMst = hrEisEmpMst;
	}

	public HrEisSgdMpg getHrEisSgdMpg()
	{
		return hrEisSgdMpg;
	}

	public void setHrEisSgdMpg(HrEisSgdMpg hrEisSgdMpg)
	{
		this.hrEisSgdMpg = hrEisSgdMpg;
	}

	public HrEisQuaterTypeMst getHrQuaterTypeMst()
	{
		return hrQuaterTypeMst;
	}

	public void setHrQuaterTypeMst(HrEisQuaterTypeMst hrQuaterTypeMst)
	{
		this.hrQuaterTypeMst = hrQuaterTypeMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost()
	{
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost)
	{
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost()
	{
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost)
	{
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy()
	{
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy)
	{
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy()
	{
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy)
	{
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public HrEisOtherDtlsHstId getId()
	{
		return id;
	}

	public void setId(HrEisOtherDtlsHstId id)
	{
		this.id = id;
	}

	public long getIncomeTax()
	{
		return incomeTax;
	}

	public void setIncomeTax(long incomeTax)
	{
		this.incomeTax = incomeTax;
	}

	public Date getIncrementDate()
	{
		return incrementDate;
	}

	public void setIncrementDate(Date incrementDate)
	{
		this.incrementDate = incrementDate;
	}

	public double getTotalSalary()
	{
		return totalSalary;
	}

	public void setTotalSalary(double totalSalary)
	{
		this.totalSalary = totalSalary;
	}

	/*public String getOthFamilyPlanning() {
		return othFamilyPlanning;
	}

	public void setOthFamilyPlanning(String othFamilyPlanning) {
		this.othFamilyPlanning = othFamilyPlanning;
	}

	public int getFamilyPlnAmt() {
		return familyPlnAmt;
	}

	public void setFamilyPlnAmt(int familyPlnAmt) {
		this.familyPlnAmt = familyPlnAmt;
	}

	public int getIsSis() {
		return isSis;
	}

	public void setIsSis(int isSis) {
		this.isSis = isSis;
	}	*/

	public Date getCommissionAcceptanceDate()
	{
		return commissionAcceptanceDate;
	}

	public void setCommissionAcceptanceDate(Date commissionAcceptanceDate)
	{
		this.commissionAcceptanceDate = commissionAcceptanceDate;
	}

	public void setIsAvailedHRA(int isAvailedHRA)
	{
		this.isAvailedHRA = isAvailedHRA;
	}

	public int getIsAvailedHRA()
	{
		return isAvailedHRA;
	}

}
