package com.tcs.sgv.eis.valueobject;
// Generated Jul 10, 2008 4:27:01 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnAttachmentMst;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgEmpMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrEisEmpChgnameTxn generated by hbm2java
 */
public class HrEisEmpChgnameTxn implements java.io.Serializable, Cloneable {

	// Fields    

	private HrEisEmpChgnameTxnId id;

	private OrgEmpMst orgEmpMst;

	private CmnLanguageMst cmnLanguageMst;

	private CmnDatabaseMst cmnDatabaseMst;

	private CmnAttachmentMst cmnAttachmentMst;

	private OrgPostMst orgPostMst;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMst;

	private String empPrefix;

	private String empFname;

	private String empMname;

	private String empLname;

	private String gazetteNo;

	private Date gazetteDate;

	private Date gazetteEstartDate;

	private String issuingAutho;

	private String actionFlag;

	private Date createdDate;

	// Constructors

	/** default constructor */
	public HrEisEmpChgnameTxn() {
	}

	/** minimal constructor */
	public HrEisEmpChgnameTxn(HrEisEmpChgnameTxnId id, OrgEmpMst orgEmpMst,
			CmnLanguageMst cmnLanguageMst, CmnDatabaseMst cmnDatabaseMst,
			OrgPostMst orgPostMst, CmnLocationMst cmnLocationMst,
			OrgUserMst orgUserMst, String empFname, String empLname,
			String gazetteNo, Date gazetteDate, Date gazetteEstartDate,
			String issuingAutho, Date createdDate) {
		this.id = id;
		this.orgEmpMst = orgEmpMst;
		this.cmnLanguageMst = cmnLanguageMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMst = orgPostMst;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMst = orgUserMst;
		this.empFname = empFname;
		this.empLname = empLname;
		this.gazetteNo = gazetteNo;
		this.gazetteDate = gazetteDate;
		this.gazetteEstartDate = gazetteEstartDate;
		this.issuingAutho = issuingAutho;
		this.createdDate = createdDate;
	}

	/** full constructor */
	public HrEisEmpChgnameTxn(HrEisEmpChgnameTxnId id, OrgEmpMst orgEmpMst,
			CmnLanguageMst cmnLanguageMst, CmnDatabaseMst cmnDatabaseMst,
			CmnAttachmentMst cmnAttachmentMst, OrgPostMst orgPostMst,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMst,
			String empPrefix, String empFname, String empMname,
			String empLname, String gazetteNo, Date gazetteDate,
			Date gazetteEstartDate, String issuingAutho, String actionFlag,
			Date createdDate) {
		this.id = id;
		this.orgEmpMst = orgEmpMst;
		this.cmnLanguageMst = cmnLanguageMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnAttachmentMst = cmnAttachmentMst;
		this.orgPostMst = orgPostMst;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMst = orgUserMst;
		this.empPrefix = empPrefix;
		this.empFname = empFname;
		this.empMname = empMname;
		this.empLname = empLname;
		this.gazetteNo = gazetteNo;
		this.gazetteDate = gazetteDate;
		this.gazetteEstartDate = gazetteEstartDate;
		this.issuingAutho = issuingAutho;
		this.actionFlag = actionFlag;
		this.createdDate = createdDate;
	}

	// Property accessors
	public HrEisEmpChgnameTxnId getId() {
		return this.id;
	}

	public void setId(HrEisEmpChgnameTxnId id) {
		this.id = id;
	}

	public OrgEmpMst getOrgEmpMst() {
		return this.orgEmpMst;
	}

	public void setOrgEmpMst(OrgEmpMst orgEmpMst) {
		this.orgEmpMst = orgEmpMst;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return this.cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return this.cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnAttachmentMst getCmnAttachmentMst() {
		return this.cmnAttachmentMst;
	}

	public void setCmnAttachmentMst(CmnAttachmentMst cmnAttachmentMst) {
		this.cmnAttachmentMst = cmnAttachmentMst;
	}

	public OrgPostMst getOrgPostMst() {
		return this.orgPostMst;
	}

	public void setOrgPostMst(OrgPostMst orgPostMst) {
		this.orgPostMst = orgPostMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return this.cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgUserMst getOrgUserMst() {
		return this.orgUserMst;
	}

	public void setOrgUserMst(OrgUserMst orgUserMst) {
		this.orgUserMst = orgUserMst;
	}

	public String getEmpPrefix() {
		return this.empPrefix;
	}

	public void setEmpPrefix(String empPrefix) {
		this.empPrefix = empPrefix;
	}

	public String getEmpFname() {
		return this.empFname;
	}

	public void setEmpFname(String empFname) {
		this.empFname = empFname;
	}

	public String getEmpMname() {
		return this.empMname;
	}

	public void setEmpMname(String empMname) {
		this.empMname = empMname;
	}

	public String getEmpLname() {
		return this.empLname;
	}

	public void setEmpLname(String empLname) {
		this.empLname = empLname;
	}

	public String getGazetteNo() {
		return this.gazetteNo;
	}

	public void setGazetteNo(String gazetteNo) {
		this.gazetteNo = gazetteNo;
	}

	public Date getGazetteDate() {
		return this.gazetteDate;
	}

	public void setGazetteDate(Date gazetteDate) {
		this.gazetteDate = gazetteDate;
	}

	public Date getGazetteEstartDate() {
		return this.gazetteEstartDate;
	}

	public void setGazetteEstartDate(Date gazetteEstartDate) {
		this.gazetteEstartDate = gazetteEstartDate;
	}

	public String getIssuingAutho() {
		return this.issuingAutho;
	}

	public void setIssuingAutho(String issuingAutho) {
		this.issuingAutho = issuingAutho;
	}

	public String getActionFlag() {
		return this.actionFlag;
	}

	public void setActionFlag(String actionFlag) {
		this.actionFlag = actionFlag;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public HrEisEmpChgnameTxn cloneTake() {
		try {
			return (HrEisEmpChgnameTxn) super.clone();
		} 
		catch(CloneNotSupportedException e) {
			return this;
		}
	}
}
