package com.tcs.sgv.eis.valueobject;
// default package
// Generated Nov 13, 2007 6:33:18 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import com.tcs.sgv.common.valueobject.CmnAttachmentMst;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrEisEmpQualificationTrn generated by hbm2java
 */
public class HrEisQualDtlTxn implements java.io.Serializable {

	// Fields    

	private HrEisQualDtlTxnId id;

	private CmnLookupMst cmnLookupMstByDicipline;

	private CmnAttachmentMst cmnAttachmentMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private long yearOfPassing;

	private CmnLookupMst cmnLookupMstByQualificationId;

	private CmnLocationMst cmnLocationMst;

	private CmnLookupMst cmnLookupMstBySubQualificationId;

	private OrgUserMst orgUserMstByUserId;

	private CmnDatabaseMst cmnDatabaseMst;

	private CmnLookupMst cmnLookupMstByCourseCategory;

	private CmnLookupMst cmnLookupMstByUnitsOfMarks;

	private OrgPostMst orgPostMstByCreatedByPost;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;

	private String uniInstituteBoard;

	private Date createdDate;

	private Date updatedDate;

	private String marksScored;

	private String actionFlag;

	private String requestFlag;

	private String draftFlag;

	private Long rowNumber;
	
	private Long corrsId;
	
	private String checkStatus;

	// Constructors

	/** default constructor */
	public HrEisQualDtlTxn() {
	}

	/** minimal constructor */
	public HrEisQualDtlTxn(HrEisQualDtlTxnId id) {
		this.id = id;
	}

	/** full constructor */
	public HrEisQualDtlTxn(HrEisQualDtlTxnId id,
			CmnLookupMst cmnLookupMstByDicipline,
			CmnAttachmentMst cmnAttachmentMst,
			OrgPostMst orgPostMstByUpdatedByPost,
			long yearOfPassing,
			CmnLookupMst cmnLookupMstByQualificationId,
			CmnLocationMst cmnLocationMst,
			CmnLookupMst cmnLookupMstBySubQualificationId,
			OrgUserMst orgUserMstByUserId, CmnDatabaseMst cmnDatabaseMst,
			CmnLookupMst cmnLookupMstByCourseCategory,
			CmnLookupMst cmnLookupMstByUnitsOfMarks,
			OrgPostMst orgPostMstByCreatedByPost,
			OrgUserMst orgUserMstByUpdatedBy, OrgUserMst orgUserMstByCreatedBy,
			String uniInstituteBoard, Date createdDate, Date updatedDate,
			String marksScored, String actionFlag,
			String requestFlag, String draftFlag, Long rowNumber, Long corrsId, String checkStatus) {
		this.id = id;
		this.cmnLookupMstByDicipline = cmnLookupMstByDicipline;
		this.cmnAttachmentMst = cmnAttachmentMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.yearOfPassing = yearOfPassing;
		this.cmnLookupMstByQualificationId = cmnLookupMstByQualificationId;
		this.cmnLocationMst = cmnLocationMst;
		this.cmnLookupMstBySubQualificationId = cmnLookupMstBySubQualificationId;
		this.orgUserMstByUserId = orgUserMstByUserId;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnLookupMstByCourseCategory = cmnLookupMstByCourseCategory;
		this.cmnLookupMstByUnitsOfMarks = cmnLookupMstByUnitsOfMarks;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.uniInstituteBoard = uniInstituteBoard;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.marksScored = marksScored;
		this.actionFlag = actionFlag;
		this.requestFlag = requestFlag;
		this.draftFlag = draftFlag;
		this.rowNumber = rowNumber;
		this.corrsId = corrsId;
		this.checkStatus = checkStatus;
	}

	// Property accessors
	public HrEisQualDtlTxnId getId() {
		return this.id;
	}

	public void setId(HrEisQualDtlTxnId id) {
		this.id = id;
	}

	public CmnLookupMst getCmnLookupMstByDicipline() {
		return this.cmnLookupMstByDicipline;
	}

	public void setCmnLookupMstByDicipline(CmnLookupMst cmnLookupMstByDicipline) {
		this.cmnLookupMstByDicipline = cmnLookupMstByDicipline;
	}

	public CmnAttachmentMst getCmnAttachmentMst() {
		return this.cmnAttachmentMst;
	}

	public void setCmnAttachmentMst(CmnAttachmentMst cmnAttachmentMst) {
		this.cmnAttachmentMst = cmnAttachmentMst;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return this.orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(
			OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public CmnLookupMst getCmnLookupMstByQualificationId() {
		return this.cmnLookupMstByQualificationId;
	}

	public void setCmnLookupMstByQualificationId(
			CmnLookupMst cmnLookupMstByQualificationId) {
		this.cmnLookupMstByQualificationId = cmnLookupMstByQualificationId;
	}

	public CmnLocationMst getCmnLocationMst() {
		return this.cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public CmnLookupMst getCmnLookupMstBySubQualificationId() {
		return this.cmnLookupMstBySubQualificationId;
	}

	public void setCmnLookupMstBySubQualificationId(
			CmnLookupMst cmnLookupMstBySubQualificationId) {
		this.cmnLookupMstBySubQualificationId = cmnLookupMstBySubQualificationId;
	}

	public OrgUserMst getOrgUserMstByUserId() {
		return this.orgUserMstByUserId;
	}

	public void setOrgUserMstByUserId(OrgUserMst orgUserMstByUserId) {
		this.orgUserMstByUserId = orgUserMstByUserId;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return this.cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLookupMst getCmnLookupMstByCourseCategory() {
		return this.cmnLookupMstByCourseCategory;
	}

	public void setCmnLookupMstByCourseCategory(
			CmnLookupMst cmnLookupMstByCourseCategory) {
		this.cmnLookupMstByCourseCategory = cmnLookupMstByCourseCategory;
	}

	public CmnLookupMst getCmnLookupMstByUnitsOfMarks() {
		return this.cmnLookupMstByUnitsOfMarks;
	}

	public void setCmnLookupMstByUnitsOfMarks(
			CmnLookupMst cmnLookupMstByUnitsOfMarks) {
		this.cmnLookupMstByUnitsOfMarks = cmnLookupMstByUnitsOfMarks;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return this.orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(
			OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return this.orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return this.orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public String getUniInstituteBoard() {
		return this.uniInstituteBoard;
	}

	public void setUniInstituteBoard(String uniInstituteBoard) {
		this.uniInstituteBoard = uniInstituteBoard;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getMarksScored() {
		return this.marksScored;
	}

	public void setMarksScored(String marksScored) {
		this.marksScored = marksScored;
	}

	public String getActionFlag() {
		return this.actionFlag;
	}

	public void setActionFlag(String actionFlag) {
		this.actionFlag = actionFlag;
	}

	public String getRequestFlag() {
		return this.requestFlag;
	}

	public void setRequestFlag(String requestFlag) {
		this.requestFlag = requestFlag;
	}

	public String getDraftFlag() {
		return this.draftFlag;
	}

	public void setDraftFlag(String draftFlag) {
		this.draftFlag = draftFlag;
	}

	public Long getRowNumber() {
		return this.rowNumber;
	}

	public void setRowNumber(Long rowNumber) {
		this.rowNumber = rowNumber;
	}

	public long getYearOfPassing() {
		return yearOfPassing;
	}

	public void setYearOfPassing(long yearOfPassing) {
		this.yearOfPassing = yearOfPassing;
	}

	public String getCheckStatus() {
		return checkStatus;
	}

	public void setCheckStatus(String checkStatus) {
		this.checkStatus = checkStatus;
	}

	public Long getCorrsId() {
		return corrsId;
	}

	public void setCorrsId(Long corrsId) {
		this.corrsId = corrsId;
	}

}
