// default package
// Generated Feb 20, 2008 2:21:06 PM by Hibernate Tools 3.2.0.beta8
package com.tcs.sgv.eis.valueobject;

import java.util.Date;

import com.tcs.sgv.common.payroll.valueobject.HrPayCommissionMst;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrEisScaleMstHst generated by hbm2java
 */
public class HrEisScaleMstHst implements java.io.Serializable {

	// Fields    

	private HrEisScaleMstHstId id;

	private CmnLanguageMst cmnLanguageMst;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;
	
	private HrPayCommissionMst hrPayCommissionMst;
	
	private CmnLookupMst payBandId;
	
	
	
	private String scaleName;

	private String scaleDesc;

	private long scaleStartAmt;

	private long scaleEndAmt;

	private long scaleIncrAmt;
	
	private Date createdDate;
	
	private Date scaleEffFromDt;
	
	private Date scaleEffToDt;
	
	private Date updatedDate;
	
	private Long elementCode;
	
	//private long monthsForIncrement;
	
	//Added by Mrugesh for Bigger Scale Value
	private long scaleHigherIncrAmt;
	
	private long scaleHigherEndAmt;
	//Ended by mrugesh
	
	private long scaleSecondHigherIncrAmt;
	
	private long scaleSecondHigherEndAmt;
	
	private long scaleThirdHigherIncrAmt;
	
	private long scaleThirdHigherEndAmt;

	
	private long scaleGradePay;
	
	private CmnLookupMst payScaleType; //Added by Muneendra for  payScaleType
	
	private Date incrementDate; //Added by Muneendra for  incrementDate3
	
	// Constructors

	public long getScaleGradePay() {
		return scaleGradePay;
	}

	public void setScaleGradePay(long scaleGradePay) {
		this.scaleGradePay = scaleGradePay;
	}

	/** default constructor */
	public HrEisScaleMstHst() {
	}

	/** minimal constructor */
	public HrEisScaleMstHst(HrEisScaleMstHstId id) {
		this.id = id;
	}

	/** full constructor */
	public HrEisScaleMstHst(HrEisScaleMstHstId id,
			String scaleName, String scaleDesc,
			long scaleStartAmt, long scaleEndAmt, long scaleIncrAmt,
			CmnLanguageMst cmnLanguageMst, CmnLocationMst cmnLocationMst, CmnDatabaseMst cmnDatabaseMst, Long elementCode,
			OrgUserMst orgUserMstByCreatedBy, Date createdDate, OrgPostMst orgPostMstByCreatedByPost,
			OrgUserMst orgUserMstByUpdatedBy, Date updatedDate, OrgPostMst orgPostMstByUpdatedByPost, 
			Date scaleEffFromDt, Date scaleEffToDt,long scaleGradePay,CmnLookupMst payScaleType) {
		this.id = id;
		this.scaleName = scaleName;
		this.scaleDesc = scaleDesc;
		this.scaleStartAmt = scaleStartAmt;
		this.scaleEndAmt = scaleEndAmt;
		this.scaleIncrAmt = scaleIncrAmt;
		this.cmnLanguageMst = cmnLanguageMst;
		this.cmnLocationMst = cmnLocationMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.elementCode = elementCode;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.createdDate = createdDate;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.updatedDate = updatedDate;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.scaleEffFromDt = scaleEffFromDt;
		this.scaleEffToDt = scaleEffToDt;
		this.scaleGradePay=scaleGradePay;
		this.payScaleType=payScaleType;
	}

	// Property accessors
	public HrEisScaleMstHstId getId() {
		return this.id;
	}

	public void setId(HrEisScaleMstHstId id) {
		this.id = id;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Long getElementCode() {
		return elementCode;
	}

	public void setElementCode(Long elementCode) {
		this.elementCode = elementCode;
	}

	/*public long getMonthsForIncrement() {
		return monthsForIncrement;
	}

	public void setMonthsForIncrement(long monthsForIncrement) {
		this.monthsForIncrement = monthsForIncrement;
	}*/

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public String getScaleDesc() {
		return scaleDesc;
	}

	public void setScaleDesc(String scaleDesc) {
		this.scaleDesc = scaleDesc;
	}

	public Date getScaleEffFromDt() {
		return scaleEffFromDt;
	}

	public void setScaleEffFromDt(Date scaleEffFromDt) {
		this.scaleEffFromDt = scaleEffFromDt;
	}

	public Date getScaleEffToDt() {
		return scaleEffToDt;
	}

	public void setScaleEffToDt(Date scaleEffToDt) {
		this.scaleEffToDt = scaleEffToDt;
	}

	public long getScaleEndAmt() {
		return scaleEndAmt;
	}

	public void setScaleEndAmt(long scaleEndAmt) {
		this.scaleEndAmt = scaleEndAmt;
	}

	public long getScaleHigherEndAmt() {
		return scaleHigherEndAmt;
	}

	public void setScaleHigherEndAmt(long scaleHigherEndAmt) {
		this.scaleHigherEndAmt = scaleHigherEndAmt;
	}

	public long getScaleHigherIncrAmt() {
		return scaleHigherIncrAmt;
	}

	public void setScaleHigherIncrAmt(long scaleHigherIncrAmt) {
		this.scaleHigherIncrAmt = scaleHigherIncrAmt;
	}

	/**
	 * @return the scaleSecondHigherIncrAmt
	 */
	public long getScaleSecondHigherIncrAmt() {
		return scaleSecondHigherIncrAmt;
	}

	/**
	 * @param scaleSecondHigherIncrAmt the scaleSecondHigherIncrAmt to set
	 */
	public void setScaleSecondHigherIncrAmt(long scaleSecondHigherIncrAmt) {
		this.scaleSecondHigherIncrAmt = scaleSecondHigherIncrAmt;
	}

	/**
	 * @return the scaleSecondHigherEndAmt
	 */
	public long getScaleSecondHigherEndAmt() {
		return scaleSecondHigherEndAmt;
	}

	/**
	 * @param scaleSecondHigherEndAmt the scaleSecondHigherEndAmt to set
	 */
	public void setScaleSecondHigherEndAmt(long scaleSecondHigherEndAmt) {
		this.scaleSecondHigherEndAmt = scaleSecondHigherEndAmt;
	}

	/**
	 * @return the scaleThirdHigherIncrAmt
	 */
	public long getScaleThirdHigherIncrAmt() {
		return scaleThirdHigherIncrAmt;
	}

	/**
	 * @param scaleThirdHigherIncrAmt the scaleThirdHigherIncrAmt to set
	 */
	public void setScaleThirdHigherIncrAmt(long scaleThirdHigherIncrAmt) {
		this.scaleThirdHigherIncrAmt = scaleThirdHigherIncrAmt;
	}

	/**
	 * @return the scaleThirdHigherEndAmt
	 */
	public long getScaleThirdHigherEndAmt() {
		return scaleThirdHigherEndAmt;
	}

	/**
	 * @param scaleThirdHigherEndAmt the scaleThirdHigherEndAmt to set
	 */
	public void setScaleThirdHigherEndAmt(long scaleThirdHigherEndAmt) {
		this.scaleThirdHigherEndAmt = scaleThirdHigherEndAmt;
	}

	public long getScaleIncrAmt() {
		return scaleIncrAmt;
	}

	public void setScaleIncrAmt(long scaleIncrAmt) {
		this.scaleIncrAmt = scaleIncrAmt;
	}

	public String getScaleName() {
		return scaleName;
	}

	public void setScaleName(String scaleName) {
		this.scaleName = scaleName;
	}

	public long getScaleStartAmt() {
		return scaleStartAmt;
	}

	public void setScaleStartAmt(long scaleStartAmt) {
		this.scaleStartAmt = scaleStartAmt;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	public HrPayCommissionMst getHrPayCommissionMst() {
		return hrPayCommissionMst;
	}

	public void setHrPayCommissionMst(HrPayCommissionMst hrPayCommissionMst) {
		this.hrPayCommissionMst = hrPayCommissionMst;
	}

	public CmnLookupMst getPayBandId() {
		return payBandId;
	}

	public void setPayBandId(CmnLookupMst payBandId) {
		this.payBandId = payBandId;
	}
	
	public CmnLookupMst getPayScaleType() {
		return payScaleType;
	}

	public void setPayScaleType(CmnLookupMst payScaleType) {
		this.payScaleType = payScaleType;
	}
	
	public Date getIncrementDate() {
		return incrementDate;
	}

	public void setIncrementDate(Date incrementDate) {
		this.incrementDate = incrementDate;
	}

}//end class