// default package
// Generated Jul 16, 2007 11:24:26 AM by Hibernate Tools 3.2.0.beta8
package com.tcs.sgv.eis.valueobject;

import java.io.Serializable;
import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnBranchMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;

/**
 * HrEisPostDtls generated by hbm2java
 */
public class HrEisPostDtls implements Serializable {

	// Fields    

	private Long hrEisPostDtlsId;

	private OrgPostMst postId;

	private CmnBranchMst branchId;

	private OrgSchemeMstVO OrgSchemeMstVOId;

	private OrgPostMst createdBy;

	private OrgPostMst createdByPost;

	private Date createdDate;

	private OrgPostMst updatedBy;

	private OrgPostMst updatedByPost;

	private Date updatedDate;

	public HrEisPostDtls(Long hrEisPostDtlsId, OrgPostMst postId,
			CmnBranchMst branchId, OrgSchemeMstVO orgSchemeMstVOId,
			OrgPostMst createdBy, OrgPostMst createdByPost, Date createdDate,
			OrgPostMst updatedBy, OrgPostMst updatedByPost, Date updatedDate) {
		super();
		this.hrEisPostDtlsId = hrEisPostDtlsId;
		this.postId = postId;
		this.branchId = branchId;
		OrgSchemeMstVOId = orgSchemeMstVOId;
		this.createdBy = createdBy;
		this.createdByPost = createdByPost;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedByPost = updatedByPost;
		this.updatedDate = updatedDate;
	}

	public HrEisPostDtls() {
		// TODO Auto-generated constructor stub
	}

	public Long getHrEisPostDtlsId() {
		return hrEisPostDtlsId;
	}

	public void setHrEisPostDtlsId(Long hrEisPostDtlsId) {
		this.hrEisPostDtlsId = hrEisPostDtlsId;
	}

	public OrgPostMst getPostId() {
		return postId;
	}

	public void setPostId(OrgPostMst postId) {
		this.postId = postId;
	}

	public CmnBranchMst getBranchId() {
		return branchId;
	}

	public void setBranchId(CmnBranchMst branchId) {
		this.branchId = branchId;
	}

	public OrgSchemeMstVO getOrgSchemeMstVOId() {
		return OrgSchemeMstVOId;
	}

	public void setOrgSchemeMstVOId(OrgSchemeMstVO orgSchemeMstVOId) {
		OrgSchemeMstVOId = orgSchemeMstVOId;
	}

	public OrgPostMst getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(OrgPostMst createdBy) {
		this.createdBy = createdBy;
	}

	public OrgPostMst getCreatedByPost() {
		return createdByPost;
	}

	public void setCreatedByPost(OrgPostMst createdByPost) {
		this.createdByPost = createdByPost;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public OrgPostMst getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(OrgPostMst updatedBy) {
		this.updatedBy = updatedBy;
	}

	public OrgPostMst getUpdatedByPost() {
		return updatedByPost;
	}

	public void setUpdatedByPost(OrgPostMst updatedByPost) {
		this.updatedByPost = updatedByPost;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}	


	
}