package com.tcs.sgv.eis.valueobject;

// default package
// Generated Mar 8, 2008 1:13:59 PM by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;
import com.tcs.sgv.hod.common.valueobject.CmnAddressMst;

/**
 * HrEmpnomineeDtlTxn generated by hbm2java
 */
public class HrEisNomineeDtlTxn implements java.io.Serializable {

	// Fields    

	private HrEisNomineeDtlTxnId id;

	private CmnLookupMst cmnLookupMstByNomnRelation;

	private OrgUserMst orgUserMstByUserId;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private CmnLookupMst cmnLookupMstByNomnBenefitTypeId;

	private CmnAddressMst cmnAddressMstByNomnAddress;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnAddressMst cmnAddressMstByGuardianAddress;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;

	private CmnLookupMst cmnLookupMstByGuardianRelation;

	private String nomnName;

	private Double  nomnSharePercent;

	private Date createdDate;

	private Date updatedDate;

	private Long rowNumber;

	private String draftFlag;

	private CmnLocationMst cmnLocationMst;

	private Date nomnDob;

	private String actionFlag;

	private String requestFlag;

	private String nomnOtherRelation;

	private String nomnMinor;

	private String guardianFirstname;

	private String guardianMiddlename;

	private String guardianLastname;

	private String guardianRelationOther;

	private long familyMemberId;
	
	private Long corrsId;
	
	private String checkStatus;

	// Constructors

	/** default constructor */
	public HrEisNomineeDtlTxn() {
	}

	/** minimal constructor */
	public HrEisNomineeDtlTxn(HrEisNomineeDtlTxnId id,
			OrgUserMst orgUserMstByUserId) {
		this.id = id;
		this.orgUserMstByUserId = orgUserMstByUserId;
	}

	/** full constructor */
	public HrEisNomineeDtlTxn(HrEisNomineeDtlTxnId id,
			CmnLookupMst cmnLookupMstByNomnRelation,
			OrgUserMst orgUserMstByUserId, CmnDatabaseMst cmnDatabaseMst,
			OrgPostMst orgPostMstByUpdatedByPost,
			CmnLookupMst cmnLookupMstByNomnBenefitTypeId,
			CmnAddressMst cmnAddressMstByNomnAddress,
			OrgPostMst orgPostMstByCreatedByPost,
			CmnAddressMst cmnAddressMstByGuardianAddress,
			OrgUserMst orgUserMstByUpdatedBy, OrgUserMst orgUserMstByCreatedBy,
			CmnLookupMst cmnLookupMstByGuardianRelation, String nomnName,
			Double  nomnSharePercent, Date createdDate, Date updatedDate,
			Long rowNumber, String draftFlag, CmnLocationMst cmnLocationMst, Date nomnDob,
			String actionFlag, String requestFlag, String nomnOtherRelation,
			String nomnMinor, String guardianFirstname,
			String guardianMiddlename, String guardianLastname,
			String guardianRelationOther, long familyMemberId, Long corrsId, String checkStatus) {
		this.id = id;
		this.cmnLookupMstByNomnRelation = cmnLookupMstByNomnRelation;
		this.orgUserMstByUserId = orgUserMstByUserId;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.cmnLookupMstByNomnBenefitTypeId = cmnLookupMstByNomnBenefitTypeId;
		this.cmnAddressMstByNomnAddress = cmnAddressMstByNomnAddress;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnAddressMstByGuardianAddress = cmnAddressMstByGuardianAddress;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.cmnLookupMstByGuardianRelation = cmnLookupMstByGuardianRelation;
		this.nomnName = nomnName;
		this.nomnSharePercent = nomnSharePercent;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.rowNumber = rowNumber;
		this.draftFlag = draftFlag;
		this.cmnLocationMst = cmnLocationMst;
		this.nomnDob = nomnDob;
		this.actionFlag = actionFlag;
		this.requestFlag = requestFlag;
		this.nomnOtherRelation = nomnOtherRelation;
		this.nomnMinor = nomnMinor;
		this.guardianFirstname = guardianFirstname;
		this.guardianMiddlename = guardianMiddlename;
		this.guardianLastname = guardianLastname;
		this.guardianRelationOther = guardianRelationOther;
		this.familyMemberId = familyMemberId;
		this.corrsId = corrsId;
		this.checkStatus = checkStatus;
	}

	// Property accessors
	public HrEisNomineeDtlTxnId getId() {
		return this.id;
	}

	public void setId(HrEisNomineeDtlTxnId id) {
		this.id = id;
	}

	public CmnLookupMst getCmnLookupMstByNomnRelation() {
		return this.cmnLookupMstByNomnRelation;
	}

	public void setCmnLookupMstByNomnRelation(
			CmnLookupMst cmnLookupMstByNomnRelation) {
		this.cmnLookupMstByNomnRelation = cmnLookupMstByNomnRelation;
	}

	public OrgUserMst getOrgUserMstByUserId() {
		return this.orgUserMstByUserId;
	}

	public void setOrgUserMstByUserId(OrgUserMst orgUserMstByUserId) {
		this.orgUserMstByUserId = orgUserMstByUserId;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return this.cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return this.orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(
			OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public CmnLookupMst getCmnLookupMstByNomnBenefitTypeId() {
		return this.cmnLookupMstByNomnBenefitTypeId;
	}

	public void setCmnLookupMstByNomnBenefitTypeId(
			CmnLookupMst cmnLookupMstByNomnBenefitTypeId) {
		this.cmnLookupMstByNomnBenefitTypeId = cmnLookupMstByNomnBenefitTypeId;
	}

	public CmnAddressMst getCmnAddressMstByNomnAddress() {
		return this.cmnAddressMstByNomnAddress;
	}

	public void setCmnAddressMstByNomnAddress(
			CmnAddressMst cmnAddressMstByNomnAddress) {
		this.cmnAddressMstByNomnAddress = cmnAddressMstByNomnAddress;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return this.orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(
			OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public CmnAddressMst getCmnAddressMstByGuardianAddress() {
		return this.cmnAddressMstByGuardianAddress;
	}

	public void setCmnAddressMstByGuardianAddress(
			CmnAddressMst cmnAddressMstByGuardianAddress) {
		this.cmnAddressMstByGuardianAddress = cmnAddressMstByGuardianAddress;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return this.orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return this.orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public CmnLookupMst getCmnLookupMstByGuardianRelation() {
		return this.cmnLookupMstByGuardianRelation;
	}

	public void setCmnLookupMstByGuardianRelation(
			CmnLookupMst cmnLookupMstByGuardianRelation) {
		this.cmnLookupMstByGuardianRelation = cmnLookupMstByGuardianRelation;
	}

	public String getNomnName() {
		return this.nomnName;
	}

	public void setNomnName(String nomnName) {
		this.nomnName = nomnName;
	}

	public Double  getNomnSharePercent() {
		return this.nomnSharePercent;
	}

	public void setNomnSharePercent(Double nomnSharePercent) {
		this.nomnSharePercent = nomnSharePercent;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Long getRowNumber() {
		return this.rowNumber;
	}

	public void setRowNumber(Long rowNumber) {
		this.rowNumber = rowNumber;
	}

	public String getDraftFlag() {
		return this.draftFlag;
	}

	public void setDraftFlag(String draftFlag) {
		this.draftFlag = draftFlag;
	}

	public Date getNomnDob() {
		return this.nomnDob;
	}

	public void setNomnDob(Date nomnDob) {
		this.nomnDob = nomnDob;
	}

	public String getActionFlag() {
		return this.actionFlag;
	}

	public void setActionFlag(String actionFlag) {
		this.actionFlag = actionFlag;
	}

	public String getRequestFlag() {
		return this.requestFlag;
	}

	public void setRequestFlag(String requestFlag) {
		this.requestFlag = requestFlag;
	}

	public String getNomnOtherRelation() {
		return this.nomnOtherRelation;
	}

	public void setNomnOtherRelation(String nomnOtherRelation) {
		this.nomnOtherRelation = nomnOtherRelation;
	}

	public String getNomnMinor() {
		return this.nomnMinor;
	}

	public void setNomnMinor(String nomnMinor) {
		this.nomnMinor = nomnMinor;
	}

	public String getGuardianFirstname() {
		return this.guardianFirstname;
	}

	public void setGuardianFirstname(String guardianFirstname) {
		this.guardianFirstname = guardianFirstname;
	}

	public String getGuardianMiddlename() {
		return this.guardianMiddlename;
	}

	public void setGuardianMiddlename(String guardianMiddlename) {
		this.guardianMiddlename = guardianMiddlename;
	}

	public String getGuardianLastname() {
		return this.guardianLastname;
	}

	public void setGuardianLastname(String guardianLastname) {
		this.guardianLastname = guardianLastname;
	}

	public String getGuardianRelationOther() {
		return this.guardianRelationOther;
	}

	public void setGuardianRelationOther(String guardianRelationOther) {
		this.guardianRelationOther = guardianRelationOther;
	}

	public long getFamilyMemberId() {
		return this.familyMemberId;
	}

	public void setFamilyMemberId(long familyMemberId) {
		this.familyMemberId = familyMemberId;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public String getCheckStatus() {
		return checkStatus;
	}

	public void setCheckStatus(String checkStatus) {
		this.checkStatus = checkStatus;
	}

	public Long getCorrsId() {
		return corrsId;
	}

	public void setCorrsId(Long corrsId) {
		this.corrsId = corrsId;
	}
}
