package com.tcs.sgv.eis.valueobject;

// default package
// Generated Oct 30, 2007 8:57:05 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import com.tcs.sgv.common.valueobject.CmnAttachmentMst;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrEisEmpCocurricular generated by hbm2java
 */
public class HrEisCuriculrDtl implements java.io.Serializable {

	

	private long srNo;

	private OrgUserMst orgUserMstByUserId;

	private long yearId;

	private CmnDatabaseMst cmnDatabaseMst;

	private CmnAttachmentMst cmnAttachmentMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private CmnLookupMst cmnLookupMstByCompetedAtId;

	private CmnLookupMst cmnLookupMstBySubCocurricularId;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLookupMst cmnLookupMstByCocurricularId;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByCreatedBy;

	private OrgUserMst orgUserMstByUpdatedBy;

	private String specialAchievement;

	private Date createdDate;

	private Date updatedDate;

	private Integer trnCounter;

	// Constructors

	/** default constructor */
	public HrEisCuriculrDtl() {
	}

	/** minimal constructor */
	public HrEisCuriculrDtl(long srNo, OrgUserMst orgUserMstByUserId) {
		this.srNo = srNo;
		this.orgUserMstByUserId = orgUserMstByUserId;
	}

	/** full constructor */
	public HrEisCuriculrDtl(long srNo, OrgUserMst orgUserMstByUserId,
			long yearId, CmnDatabaseMst cmnDatabaseMst,
			CmnAttachmentMst cmnAttachmentMst,
			OrgPostMst orgPostMstByUpdatedByPost,
			CmnLookupMst cmnLookupMstByCompetedAtId,
			CmnLookupMst cmnLookupMstBySubCocurricularId,
			OrgPostMst orgPostMstByCreatedByPost,
			CmnLookupMst cmnLookupMstByCocurricularId,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByCreatedBy,
			OrgUserMst orgUserMstByUpdatedBy, String specialAchievement,
			Date createdDate, Date updatedDate, Integer trnCounter) {
		this.srNo = srNo;
		this.orgUserMstByUserId = orgUserMstByUserId;
		this.yearId = yearId;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnAttachmentMst = cmnAttachmentMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.cmnLookupMstByCompetedAtId = cmnLookupMstByCompetedAtId;
		this.cmnLookupMstBySubCocurricularId = cmnLookupMstBySubCocurricularId;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnLookupMstByCocurricularId = cmnLookupMstByCocurricularId;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.specialAchievement = specialAchievement;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.trnCounter = trnCounter;
	}

	// Property accessors
	public long getSrNo() {
		return this.srNo;
	}

	public void setSrNo(long srNo) {
		this.srNo = srNo;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return this.cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnAttachmentMst getCmnAttachmentMst() {
		return this.cmnAttachmentMst;
	}

	public void setCmnAttachmentMst(CmnAttachmentMst cmnAttachmentMst) {
		this.cmnAttachmentMst = cmnAttachmentMst;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return this.orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(
			OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public CmnLookupMst getCmnLookupMstByCompetedAtId() {
		return this.cmnLookupMstByCompetedAtId;
	}

	public void setCmnLookupMstByCompetedAtId(
			CmnLookupMst cmnLookupMstByCompetedAtId) {
		this.cmnLookupMstByCompetedAtId = cmnLookupMstByCompetedAtId;
	}

	public CmnLookupMst getCmnLookupMstBySubCocurricularId() {
		return this.cmnLookupMstBySubCocurricularId;
	}

	public void setCmnLookupMstBySubCocurricularId(
			CmnLookupMst cmnLookupMstBySubCocurricularId) {
		this.cmnLookupMstBySubCocurricularId = cmnLookupMstBySubCocurricularId;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return this.orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(
			OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public CmnLookupMst getCmnLookupMstByCocurricularId() {
		return this.cmnLookupMstByCocurricularId;
	}

	public void setCmnLookupMstByCocurricularId(
			CmnLookupMst cmnLookupMstByCocurricularId) {
		this.cmnLookupMstByCocurricularId = cmnLookupMstByCocurricularId;
	}

	public CmnLocationMst getCmnLocationMst() {
		return this.cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return this.orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return this.orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public String getSpecialAchievement() {
		return this.specialAchievement;
	}

	public void setSpecialAchievement(String specialAchievement) {
		this.specialAchievement = specialAchievement;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Integer getTrnCounter() {
		return this.trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}

	public OrgUserMst getOrgUserMstByUserId() {
		return orgUserMstByUserId;
	}

	public void setOrgUserMstByUserId(OrgUserMst orgUserMstByUserId) {
		this.orgUserMstByUserId = orgUserMstByUserId;
	}

	public long getYearId() {
		return yearId;
	}

	public void setYearId(long yearId) {
		this.yearId = yearId;
	}

}
