// default package
// Generated Feb 22, 2008 5:41:39 PM by Hibernate Tools 3.2.0.beta8
package com.tcs.sgv.eis.valueobject;
import java.math.BigDecimal;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;
import java.util.Date;

/**
 * HrEisEmpSrvcexamDtl generated by hbm2java
 */
public class HrEisSrvcexamDtl implements java.io.Serializable {

	// Fields    

	private long empSrvcexamDtlsId;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private CmnLookupMst cmnLookupMstByResultLookupId;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLookupMst cmnLookupMstByExamLookupId;

	private OrgUserMst orgUserMst;

	private CmnLocationMst cmnLocationMst;

	private CmnDatabaseMst cmnDatabaseMst;

	private CmnLookupMst cmnLookupMstByPassingMonthLookupId;

	private CmnLookupMst cmnLookupMstByPreserviceLookupId;

	private CmnLookupMst cmnLookupMstByClassDivLookupId;

	private Long passingYear;

	private double marksObtainted;

	private double marksOutOf;

	private OrgUserMst createdBy;

	private Date createdDate;

	private OrgUserMst updatedBy;

	private Date updatedDate;

	// Constructors

	/** default constructor */
	public HrEisSrvcexamDtl() {
	}

	/** minimal constructor */
	public HrEisSrvcexamDtl(long empSrvcexamDtlsId,
			CmnLookupMst cmnLookupMstByResultLookupId,
			OrgPostMst orgPostMstByCreatedByPost,
			CmnLookupMst cmnLookupMstByExamLookupId, OrgUserMst orgUserMst,
			CmnLocationMst cmnLocationMst, CmnDatabaseMst cmnDatabaseMst,
			CmnLookupMst cmnLookupMstByPreserviceLookupId, OrgUserMst createdBy,
			Date createdDate) {
		this.empSrvcexamDtlsId = empSrvcexamDtlsId;
		this.cmnLookupMstByResultLookupId = cmnLookupMstByResultLookupId;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnLookupMstByExamLookupId = cmnLookupMstByExamLookupId;
		this.orgUserMst = orgUserMst;
		this.cmnLocationMst = cmnLocationMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnLookupMstByPreserviceLookupId = cmnLookupMstByPreserviceLookupId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	/** full constructor */
	public HrEisSrvcexamDtl(long empSrvcexamDtlsId,
			OrgPostMst orgPostMstByUpdatedByPost,
			CmnLookupMst cmnLookupMstByResultLookupId,
			OrgPostMst orgPostMstByCreatedByPost,
			CmnLookupMst cmnLookupMstByExamLookupId, OrgUserMst orgUserMst,
			CmnLocationMst cmnLocationMst, CmnDatabaseMst cmnDatabaseMst,
			CmnLookupMst cmnLookupMstByPassingMonthLookupId,
			CmnLookupMst cmnLookupMstByPreserviceLookupId,
			CmnLookupMst cmnLookupMstByClassDivLookupId, Long passingYear,
			double marksObtainted, double marksOutOf, OrgUserMst createdBy,
			Date createdDate, OrgUserMst updatedBy, Date updatedDate) {
		this.empSrvcexamDtlsId = empSrvcexamDtlsId;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.cmnLookupMstByResultLookupId = cmnLookupMstByResultLookupId;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnLookupMstByExamLookupId = cmnLookupMstByExamLookupId;
		this.orgUserMst = orgUserMst;
		this.cmnLocationMst = cmnLocationMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnLookupMstByPassingMonthLookupId = cmnLookupMstByPassingMonthLookupId;
		this.cmnLookupMstByPreserviceLookupId = cmnLookupMstByPreserviceLookupId;
		this.cmnLookupMstByClassDivLookupId = cmnLookupMstByClassDivLookupId;
		this.passingYear = passingYear;
		this.marksObtainted = marksObtainted;
		this.marksOutOf = marksOutOf;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	// Property accessors
	public long getEmpSrvcexamDtlsId() {
		return this.empSrvcexamDtlsId;
	}

	public void setEmpSrvcexamDtlsId(long empSrvcexamDtlsId) {
		this.empSrvcexamDtlsId = empSrvcexamDtlsId;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return this.orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(
			OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public CmnLookupMst getCmnLookupMstByResultLookupId() {
		return this.cmnLookupMstByResultLookupId;
	}

	public void setCmnLookupMstByResultLookupId(
			CmnLookupMst cmnLookupMstByResultLookupId) {
		this.cmnLookupMstByResultLookupId = cmnLookupMstByResultLookupId;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return this.orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(
			OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public CmnLookupMst getCmnLookupMstByExamLookupId() {
		return this.cmnLookupMstByExamLookupId;
	}

	public void setCmnLookupMstByExamLookupId(
			CmnLookupMst cmnLookupMstByExamLookupId) {
		this.cmnLookupMstByExamLookupId = cmnLookupMstByExamLookupId;
	}

	public OrgUserMst getOrgUserMst() {
		return this.orgUserMst;
	}

	public void setOrgUserMst(OrgUserMst orgUserMst) {
		this.orgUserMst = orgUserMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return this.cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return this.cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLookupMst getCmnLookupMstByPassingMonthLookupId() {
		return this.cmnLookupMstByPassingMonthLookupId;
	}

	public void setCmnLookupMstByPassingMonthLookupId(
			CmnLookupMst cmnLookupMstByPassingMonthLookupId) {
		this.cmnLookupMstByPassingMonthLookupId = cmnLookupMstByPassingMonthLookupId;
	}

	public CmnLookupMst getCmnLookupMstByPreserviceLookupId() {
		return this.cmnLookupMstByPreserviceLookupId;
	}

	public void setCmnLookupMstByPreserviceLookupId(
			CmnLookupMst cmnLookupMstByPreserviceLookupId) {
		this.cmnLookupMstByPreserviceLookupId = cmnLookupMstByPreserviceLookupId;
	}

	public CmnLookupMst getCmnLookupMstByClassDivLookupId() {
		return this.cmnLookupMstByClassDivLookupId;
	}

	public void setCmnLookupMstByClassDivLookupId(
			CmnLookupMst cmnLookupMstByClassDivLookupId) {
		this.cmnLookupMstByClassDivLookupId = cmnLookupMstByClassDivLookupId;
	}

	public Long getPassingYear() {
		return this.passingYear;
	}

	public void setPassingYear(Long passingYear) {
		this.passingYear = passingYear;
	}

	public double getMarksObtainted() {
		return this.marksObtainted;
	}

	public void setMarksObtainted(double marksObtainted) {
		this.marksObtainted = marksObtainted;
	}

	public double getMarksOutOf() {
		return this.marksOutOf;
	}

	public void setMarksOutOf(double marksOutOf) {
		this.marksOutOf = marksOutOf;
	}

	public OrgUserMst getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(OrgUserMst createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public OrgUserMst getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(OrgUserMst updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
