package com.tcs.sgv.eis.valueobject;

// default package
// Generated Mar 8, 2008 1:13:59 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnAttachmentMst;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrEmpqualDtl generated by hbm2java
 */
public class HrEisQualDtl implements java.io.Serializable {

	// Fields    

	private long srNo;

	private CmnLookupMst cmnLookupMstByDicipline;

	private OrgUserMst orgUserMstByUserId;

	private CmnLookupMst cmnLookupMstByCourseCategory;

	private CmnDatabaseMst cmnDatabaseMst;

	private CmnAttachmentMst cmnAttachmentMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private CmnLookupMst cmnLookupMstByUnitsOfMarks;

	private CmnLookupMst cmnLookupMstByQualificationId;

	private OrgPostMst orgPostMstByCreatedByPost;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;

	private CmnLookupMst cmnLookupMstBySubQualificationId;

	private String uniInstituteBoard;

	private Long yearOfPassing;

	private CmnLocationMst cmnLocationMst;

	private Date createdDate;

	private Date updatedDate;

	private String marksScored;

	private String deleteFlag;

	private Integer trnCounter;

	// Constructors

	/** default constructor */
	public HrEisQualDtl() {
	}

	/** minimal constructor */
	public HrEisQualDtl(long srNo, OrgUserMst orgUserMstByUserId) {
		this.srNo = srNo;
		this.orgUserMstByUserId = orgUserMstByUserId;
	}

	/** full constructor 
	 * @param cmnLocationMst */
	public HrEisQualDtl(long srNo, CmnLookupMst cmnLookupMstByDicipline,
			OrgUserMst orgUserMstByUserId,
			CmnLookupMst cmnLookupMstByCourseCategory,
			CmnDatabaseMst cmnDatabaseMst, CmnAttachmentMst cmnAttachmentMst,
			OrgPostMst orgPostMstByUpdatedByPost,
			CmnLookupMst cmnLookupMstByUnitsOfMarks,
			CmnLookupMst cmnLookupMstByQualificationId,
			OrgPostMst orgPostMstByCreatedByPost,
			OrgUserMst orgUserMstByUpdatedBy, OrgUserMst orgUserMstByCreatedBy,
			CmnLookupMst cmnLookupMstBySubQualificationId,
			String uniInstituteBoard, Long yearOfPassing, Long locId,
			Date createdDate, Date updatedDate, String marksScored,
			String deleteFlag, Integer trnCounter, CmnLocationMst cmnLocationMst) {
		this.srNo = srNo;
		this.cmnLookupMstByDicipline = cmnLookupMstByDicipline;
		this.orgUserMstByUserId = orgUserMstByUserId;
		this.cmnLookupMstByCourseCategory = cmnLookupMstByCourseCategory;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnAttachmentMst = cmnAttachmentMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.cmnLookupMstByUnitsOfMarks = cmnLookupMstByUnitsOfMarks;
		this.cmnLookupMstByQualificationId = cmnLookupMstByQualificationId;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.cmnLookupMstBySubQualificationId = cmnLookupMstBySubQualificationId;
		this.uniInstituteBoard = uniInstituteBoard;
		this.yearOfPassing = yearOfPassing;
		this.cmnLocationMst = cmnLocationMst;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.marksScored = marksScored;
		this.deleteFlag = deleteFlag;
		this.trnCounter = trnCounter;
	}

	// Property accessors
	public long getSrNo() {
		return this.srNo;
	}

	public void setSrNo(long srNo) {
		this.srNo = srNo;
	}

	public CmnLookupMst getCmnLookupMstByDicipline() {
		return this.cmnLookupMstByDicipline;
	}

	public void setCmnLookupMstByDicipline(CmnLookupMst cmnLookupMstByDicipline) {
		this.cmnLookupMstByDicipline = cmnLookupMstByDicipline;
	}

	public OrgUserMst getOrgUserMstByUserId() {
		return this.orgUserMstByUserId;
	}

	public void setOrgUserMstByUserId(OrgUserMst orgUserMstByUserId) {
		this.orgUserMstByUserId = orgUserMstByUserId;
	}

	public CmnLookupMst getCmnLookupMstByCourseCategory() {
		return this.cmnLookupMstByCourseCategory;
	}

	public void setCmnLookupMstByCourseCategory(
			CmnLookupMst cmnLookupMstByCourseCategory) {
		this.cmnLookupMstByCourseCategory = cmnLookupMstByCourseCategory;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return this.cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnAttachmentMst getCmnAttachmentMst() {
		return this.cmnAttachmentMst;
	}

	public void setCmnAttachmentMst(CmnAttachmentMst cmnAttachmentMst) {
		this.cmnAttachmentMst = cmnAttachmentMst;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return this.orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(
			OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public CmnLookupMst getCmnLookupMstByUnitsOfMarks() {
		return this.cmnLookupMstByUnitsOfMarks;
	}

	public void setCmnLookupMstByUnitsOfMarks(
			CmnLookupMst cmnLookupMstByUnitsOfMarks) {
		this.cmnLookupMstByUnitsOfMarks = cmnLookupMstByUnitsOfMarks;
	}

	public CmnLookupMst getCmnLookupMstByQualificationId() {
		return this.cmnLookupMstByQualificationId;
	}

	public void setCmnLookupMstByQualificationId(
			CmnLookupMst cmnLookupMstByQualificationId) {
		this.cmnLookupMstByQualificationId = cmnLookupMstByQualificationId;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return this.orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(
			OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return this.orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return this.orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public CmnLookupMst getCmnLookupMstBySubQualificationId() {
		return this.cmnLookupMstBySubQualificationId;
	}

	public void setCmnLookupMstBySubQualificationId(
			CmnLookupMst cmnLookupMstBySubQualificationId) {
		this.cmnLookupMstBySubQualificationId = cmnLookupMstBySubQualificationId;
	}

	public String getUniInstituteBoard() {
		return this.uniInstituteBoard;
	}

	public void setUniInstituteBoard(String uniInstituteBoard) {
		this.uniInstituteBoard = uniInstituteBoard;
	}

	public Long getYearOfPassing() {
		return this.yearOfPassing;
	}

	public void setYearOfPassing(Long yearOfPassing) {
		this.yearOfPassing = yearOfPassing;
	}

	
	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getMarksScored() {
		return this.marksScored;
	}

	public void setMarksScored(String marksScored) {
		this.marksScored = marksScored;
	}

	public String getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public Integer getTrnCounter() {
		return this.trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}

}
