package com.tcs.sgv.eis.valueobject;
// Generated Jul 9, 2007 5:38:35 PM by Hibernate Tools 3.1.0.beta5
//Comment By Maruthi For import Organisation.
import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrEisDesigMst generated by hbm2java
 */
public class HrEisDesigMst implements java.io.Serializable {

	// Fields    

	private long desigId;

	private String desigName;

	private String desigDesc;

	private String desigShortName;

	private long elementCode;

	private CmnLanguageMst cmnLanguageMst;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;

	private Date createdDate;	
	private Date updatedDate;
	// Constructors

	/** default constructor */
	public HrEisDesigMst() {
	}

	/** minimal constructor */
	public HrEisDesigMst(long desigId) {
		this.desigId = desigId;
	}

	/** full constructor */
	public HrEisDesigMst(long desigId, String desigName,
			String desigDesc, String desigShortName,
			long elementCode, CmnLanguageMst cmnLanguageMst,
			CmnDatabaseMst cmnDatabaseMst,
			OrgPostMst orgPostMstByCreatedByPost,OrgUserMst orgUserMstByUpdatedBy,
			OrgPostMst orgPostMstByUpdatedByPost,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByCreatedBy,
			Date createdDate,
			 Date updatedDate) {
		this.desigId = desigId;
		this.desigName = desigName;
		this.desigDesc = desigDesc;
		this.desigShortName = desigShortName;
		this.elementCode = elementCode;
		this.cmnLanguageMst = cmnLanguageMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.createdDate = createdDate;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.updatedDate = updatedDate;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getDesigDesc() {
		return desigDesc;
	}

	public void setDesigDesc(String desigDesc) {
		this.desigDesc = desigDesc;
	}

	public long getDesigId() {
		return desigId;
	}

	public void setDesigId(long desigId) {
		this.desigId = desigId;
	}

	public String getDesigName() {
		return desigName;
	}

	public void setDesigName(String desigName) {
		this.desigName = desigName;
	}

	public String getDesigShortName() {
		return desigShortName;
	}

	public void setDesigShortName(String desigShortName) {
		this.desigShortName = desigShortName;
	}

	public long getElementCode() {
		return elementCode;
	}

	public void setElementCode(long elementCode) {
		this.elementCode = elementCode;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	// Property accessors
	
}
