package com.tcs.sgv.eis.valueobject;

import com.tcs.sgv.eis.valueobject.HrEisQtrMstHstId;

/**
 * HrEisQtrMstHstId generated by hbm2java
 */
public class HrEisQtrMstHstId implements java.io.Serializable {

	// Fields    

	private long quarterId;

	private long trnCounter;

	// Constructors

	/** default constructor */
	public HrEisQtrMstHstId() {
	}

	/** full constructor */
	public HrEisQtrMstHstId(long quarterId, long trnCounter) {
		this.quarterId = quarterId;
		this.trnCounter = trnCounter;
	}

	// Property accessors
	public long getQuarterId() {
		return this.quarterId;
	}

	public void setQuarterId(long quarterId) {
		this.quarterId = quarterId;
	}

	public long getTrnCounter() {
		return this.trnCounter;
	}

	public void setTrnCounter(long trnCounter) {
		this.trnCounter = trnCounter;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HrEisQtrMstHstId))
			return false;
		HrEisQtrMstHstId castOther = (HrEisQtrMstHstId) other;

		return (this.getQuarterId() == castOther.getQuarterId())
				&& (this.getTrnCounter() == castOther.getTrnCounter());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getQuarterId();
		result = 37 * result + (int) this.getTrnCounter();
		return result;
	}

}
