package com.tcs.sgv.eis.valueobject;

// default package
// Generated Mar 8, 2008 1:13:59 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnAttachmentMst;
import com.tcs.sgv.common.valueobject.CmnCountryMst;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.ess.valueobject.OrgDepartmentMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;
import com.tcs.sgv.hod.common.valueobject.CmnAddressMst;

/**
 * HrEmpfamilyDtlTxn generated by hbm2java
 */
public class HrEisFamilyDtlTxn implements java.io.Serializable {

	// Fields    

	private HrEisFamilyDtlTxnId id;

	private CmnLookupMst cmnLookupMstByFmGender;

	private CmnAttachmentMst cmnAttachmentMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private CmnLookupMst cmnLookupMstByFmDeadOrAlive;

	private CmnLookupMst cmnLookupMstByFmRelation;

	private CmnLookupMst cmnLookupMstByFmEmploymentStatus;

	private CmnLookupMst cmnLookupMstByFmMaritalStatus;

	private OrgUserMst orgUserMstByUserId;

	private CmnDatabaseMst cmnDatabaseMst;

	private CmnAddressMst cmnAddressMst;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLookupMst cmnLookupMstByFmQualification;

	private CmnLookupMst cmnLookupMstByFmOccupation;

	private OrgUserMst orgUserMstByCreatedBy;

	private OrgUserMst orgUserMstByUpdatedBy;

	private String fmFirstName;

	private String fmMiddleName;

	private String fmLastName;

	private Date fmDateOfBirth;

	private String fmRemarks;

	private CmnLocationMst cmnLocationMst;

	private Date createdDate;

	private Date updatedDate;

	private String actionFlag;

	private String requestFlag;

	private String draftFlag;

	private Long rowNumber;

	private String fmRelationOther;

	private String companyName;

	private String designation;

	private String annualIncome;

	private String dependentOrNot;

	private Date dateOfDemise;

	private Date startDate;

	private Date endDate;

	private String otherOccupation;
	
	private Long corrsId;
	
	private String checkStatus;
	
	private CmnCountryMst cmnCountryMstByFmNationality;
	
	private OrgDepartmentMst orgDepartmentMstByFmDept;

	private CmnLookupMst cmnLookupMstBySubQualification;
	
	private CmnLookupMst cmnLookupMstByDiscipline;
	
	// Constructors

	/** default constructor */
	public HrEisFamilyDtlTxn() {
	}

	/** minimal constructor */
	public HrEisFamilyDtlTxn(HrEisFamilyDtlTxnId id,
			OrgUserMst orgUserMstByUserId) {
		this.id = id;
		this.orgUserMstByUserId = orgUserMstByUserId;
	}

	/** full constructor */
	public HrEisFamilyDtlTxn(HrEisFamilyDtlTxnId id,
			CmnLookupMst cmnLookupMstByFmGender,
			CmnAttachmentMst cmnAttachmentMst,
			OrgPostMst orgPostMstByUpdatedByPost,
			CmnLookupMst cmnLookupMstByFmDeadOrAlive,
			CmnLookupMst cmnLookupMstByFmRelation,
			CmnLookupMst cmnLookupMstByFmEmploymentStatus,
			CmnLookupMst cmnLookupMstByFmMaritalStatus,
			OrgUserMst orgUserMstByUserId, CmnDatabaseMst cmnDatabaseMst,
			CmnAddressMst cmnAddressMst, OrgPostMst orgPostMstByCreatedByPost,
			CmnLookupMst cmnLookupMstByFmQualification,
			CmnLookupMst cmnLookupMstByFmOccupation,
			OrgUserMst orgUserMstByCreatedBy, OrgUserMst orgUserMstByUpdatedBy,
			String fmFirstName, String fmMiddleName, String fmLastName,
			Date fmDateOfBirth, String fmRemarks, CmnLocationMst cmnLocationMst, Date createdDate,
			Date updatedDate, String actionFlag, String requestFlag,
			String draftFlag, Long rowNumber, String fmRelationOther,
			String companyName, String designation, String annualIncome,
			String dependentOrNot, Date dateOfDemise, Date startDate,
			Date endDate, String otherOccupation ,Long corrsId, String checkStatus,
			CmnCountryMst cmnCountryMstByFmNationality,OrgDepartmentMst orgDepartmentMstByFmDept,
			CmnLookupMst cmnLookupMstBySubQualification,CmnLookupMst cmnLookupMstByDiscipline) {
		this.id = id;
		this.cmnLookupMstByFmGender = cmnLookupMstByFmGender;
		this.cmnAttachmentMst = cmnAttachmentMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.cmnLookupMstByFmDeadOrAlive = cmnLookupMstByFmDeadOrAlive;
		this.cmnLookupMstByFmRelation = cmnLookupMstByFmRelation;
		this.cmnLookupMstByFmEmploymentStatus = cmnLookupMstByFmEmploymentStatus;
		this.cmnLookupMstByFmMaritalStatus = cmnLookupMstByFmMaritalStatus;
		this.orgUserMstByUserId = orgUserMstByUserId;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnAddressMst = cmnAddressMst;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnLookupMstByFmQualification = cmnLookupMstByFmQualification;
		this.cmnLookupMstByFmOccupation = cmnLookupMstByFmOccupation;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.fmFirstName = fmFirstName;
		this.fmMiddleName = fmMiddleName;
		this.fmLastName = fmLastName;
		this.fmDateOfBirth = fmDateOfBirth;
		this.fmRemarks = fmRemarks;
		this.cmnLocationMst = cmnLocationMst;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.actionFlag = actionFlag;
		this.requestFlag = requestFlag;
		this.draftFlag = draftFlag;
		this.rowNumber = rowNumber;
		this.fmRelationOther = fmRelationOther;
		this.companyName = companyName;
		this.designation = designation;
		this.annualIncome = annualIncome;
		this.dependentOrNot = dependentOrNot;
		this.dateOfDemise = dateOfDemise;
		this.startDate = startDate;
		this.endDate = endDate;
		this.otherOccupation = otherOccupation;
		this.corrsId = corrsId;
		this.checkStatus = checkStatus;
		this.cmnCountryMstByFmNationality=cmnCountryMstByFmNationality;
		this.orgDepartmentMstByFmDept=orgDepartmentMstByFmDept;
		this.cmnLookupMstBySubQualification=cmnLookupMstBySubQualification;
		this.cmnLookupMstByDiscipline=cmnLookupMstByDiscipline;
	}

	// Property accessors
	public HrEisFamilyDtlTxnId getId() {
		return this.id;
	}

	public void setId(HrEisFamilyDtlTxnId id) {
		this.id = id;
	}

	public CmnLookupMst getCmnLookupMstByFmGender() {
		return this.cmnLookupMstByFmGender;
	}

	public void setCmnLookupMstByFmGender(CmnLookupMst cmnLookupMstByFmGender) {
		this.cmnLookupMstByFmGender = cmnLookupMstByFmGender;
	}

	public CmnAttachmentMst getCmnAttachmentMst() {
		return this.cmnAttachmentMst;
	}

	public void setCmnAttachmentMst(CmnAttachmentMst cmnAttachmentMst) {
		this.cmnAttachmentMst = cmnAttachmentMst;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return this.orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(
			OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public CmnLookupMst getCmnLookupMstByFmDeadOrAlive() {
		return this.cmnLookupMstByFmDeadOrAlive;
	}

	public void setCmnLookupMstByFmDeadOrAlive(
			CmnLookupMst cmnLookupMstByFmDeadOrAlive) {
		this.cmnLookupMstByFmDeadOrAlive = cmnLookupMstByFmDeadOrAlive;
	}

	public CmnLookupMst getCmnLookupMstByFmRelation() {
		return this.cmnLookupMstByFmRelation;
	}

	public void setCmnLookupMstByFmRelation(
			CmnLookupMst cmnLookupMstByFmRelation) {
		this.cmnLookupMstByFmRelation = cmnLookupMstByFmRelation;
	}

	public CmnLookupMst getCmnLookupMstByFmEmploymentStatus() {
		return this.cmnLookupMstByFmEmploymentStatus;
	}

	public void setCmnLookupMstByFmEmploymentStatus(
			CmnLookupMst cmnLookupMstByFmEmploymentStatus) {
		this.cmnLookupMstByFmEmploymentStatus = cmnLookupMstByFmEmploymentStatus;
	}

	public CmnLookupMst getCmnLookupMstByFmMaritalStatus() {
		return this.cmnLookupMstByFmMaritalStatus;
	}

	public void setCmnLookupMstByFmMaritalStatus(
			CmnLookupMst cmnLookupMstByFmMaritalStatus) {
		this.cmnLookupMstByFmMaritalStatus = cmnLookupMstByFmMaritalStatus;
	}

	public OrgUserMst getOrgUserMstByUserId() {
		return this.orgUserMstByUserId;
	}

	public void setOrgUserMstByUserId(OrgUserMst orgUserMstByUserId) {
		this.orgUserMstByUserId = orgUserMstByUserId;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return this.cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnAddressMst getCmnAddressMst() {
		return this.cmnAddressMst;
	}

	public void setCmnAddressMst(CmnAddressMst cmnAddressMst) {
		this.cmnAddressMst = cmnAddressMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return this.orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(
			OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public CmnLookupMst getCmnLookupMstByFmQualification() {
		return this.cmnLookupMstByFmQualification;
	}

	public void setCmnLookupMstByFmQualification(
			CmnLookupMst cmnLookupMstByFmQualification) {
		this.cmnLookupMstByFmQualification = cmnLookupMstByFmQualification;
	}

	public CmnLookupMst getCmnLookupMstByFmOccupation() {
		return this.cmnLookupMstByFmOccupation;
	}

	public void setCmnLookupMstByFmOccupation(
			CmnLookupMst cmnLookupMstByFmOccupation) {
		this.cmnLookupMstByFmOccupation = cmnLookupMstByFmOccupation;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return this.orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return this.orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public String getFmFirstName() {
		return this.fmFirstName;
	}

	public void setFmFirstName(String fmFirstName) {
		this.fmFirstName = fmFirstName;
	}

	public String getFmMiddleName() {
		return this.fmMiddleName;
	}

	public void setFmMiddleName(String fmMiddleName) {
		this.fmMiddleName = fmMiddleName;
	}

	public String getFmLastName() {
		return this.fmLastName;
	}

	public void setFmLastName(String fmLastName) {
		this.fmLastName = fmLastName;
	}

	public Date getFmDateOfBirth() {
		return this.fmDateOfBirth;
	}

	public void setFmDateOfBirth(Date fmDateOfBirth) {
		this.fmDateOfBirth = fmDateOfBirth;
	}

	public String getFmRemarks() {
		return this.fmRemarks;
	}

	public void setFmRemarks(String fmRemarks) {
		this.fmRemarks = fmRemarks;
	}

	

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getActionFlag() {
		return this.actionFlag;
	}

	public void setActionFlag(String actionFlag) {
		this.actionFlag = actionFlag;
	}

	public String getRequestFlag() {
		return this.requestFlag;
	}

	public void setRequestFlag(String requestFlag) {
		this.requestFlag = requestFlag;
	}

	public String getDraftFlag() {
		return this.draftFlag;
	}

	public void setDraftFlag(String draftFlag) {
		this.draftFlag = draftFlag;
	}

	public Long getRowNumber() {
		return this.rowNumber;
	}

	public void setRowNumber(Long rowNumber) {
		this.rowNumber = rowNumber;
	}

	public String getFmRelationOther() {
		return this.fmRelationOther;
	}

	public void setFmRelationOther(String fmRelationOther) {
		this.fmRelationOther = fmRelationOther;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getAnnualIncome() {
		return this.annualIncome;
	}

	public void setAnnualIncome(String annualIncome) {
		this.annualIncome = annualIncome;
	}

	public String getDependentOrNot() {
		return this.dependentOrNot;
	}

	public void setDependentOrNot(String dependentOrNot) {
		this.dependentOrNot = dependentOrNot;
	}

	public Date getDateOfDemise() {
		return this.dateOfDemise;
	}

	public void setDateOfDemise(Date dateOfDemise) {
		this.dateOfDemise = dateOfDemise;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getOtherOccupation() {
		return this.otherOccupation;
	}

	public void setOtherOccupation(String otherOccupation) {
		this.otherOccupation = otherOccupation;
	}

	public String getCheckStatus() {
		return checkStatus;
	}

	public void setCheckStatus(String checkStatus) {
		this.checkStatus = checkStatus;
	}

	public Long getCorrsId() {
		return corrsId;
	}

	public void setCorrsId(Long corrsId) {
		this.corrsId = corrsId;
	}
	
	public CmnCountryMst getCmnCountryMstByFmNationality() {
		return cmnCountryMstByFmNationality;
	}

	public void setCmnCountryMstByFmNationality(
			CmnCountryMst cmnCountryMstByFmNationality) {
		this.cmnCountryMstByFmNationality = cmnCountryMstByFmNationality;
	}

	public OrgDepartmentMst getOrgDepartmentMstByFmDept() {
		return orgDepartmentMstByFmDept;
	}

	public void setOrgDepartmentMstByFmDept(
			OrgDepartmentMst orgDepartmentMstByFmDept) {
		this.orgDepartmentMstByFmDept = orgDepartmentMstByFmDept;
	}
	
	public CmnLookupMst getCmnLookupMstByDiscipline() {
		return cmnLookupMstByDiscipline;
	}

	public void setCmnLookupMstByDiscipline(CmnLookupMst cmnLookupMstByDiscipline) {
		this.cmnLookupMstByDiscipline = cmnLookupMstByDiscipline;
	}

	public CmnLookupMst getCmnLookupMstBySubQualification() {
		return cmnLookupMstBySubQualification;
	}

	public void setCmnLookupMstBySubQualification(
			CmnLookupMst cmnLookupMstBySubQualification) {
		this.cmnLookupMstBySubQualification = cmnLookupMstBySubQualification;
	}

}
