package com.tcs.sgv.eis.valueobject;

import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
* HrEisBankDtls generated by hbm2java
*/
public class HrEmpTraMpg implements java.io.Serializable {

	// Fields    


	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;
	
	private CmnLocationMst cmnLocationMst;
	
	private long id;

	private HrEisEmpMst hrEisEmpMst;
	
	private long distance;

	private String vehicalAvailed;

	private Date vehicalAvailDate;

	private Date vehicalLeaveDate;
	
	private CmnLookupMst vehicalType;
	
	private String vehicalNo;
	
	private Date createdDate;

	private Date updatedDate;

	private Integer trnCounter;

	// Constructors
	/** default constructor */
	public HrEmpTraMpg() {
	}

	/** minimal constructor */
	public HrEmpTraMpg(long id) {
		this.id = id;
	}

	/** full constructor */
	public HrEmpTraMpg(long id,HrEisEmpMst hrEisEmpMst,
			long distance,String vehicalAvailed,
			Date vehicalAvailDate,Date vehicalLeaveDate,
			CmnLookupMst vehicalType,String vehicalNo,
			CmnLanguageMst cmnLanguageMst,
			CmnDatabaseMst cmnDatabaseMst,
			OrgPostMst orgPostMstByCreatedByPost,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByCreatedBy
			) {
		this.id = id;
		this.hrEisEmpMst =hrEisEmpMst ;
		this.distance=distance;
		this.vehicalAvailed=vehicalAvailed;
		this.vehicalAvailDate=vehicalAvailDate;
		this.vehicalLeaveDate=vehicalLeaveDate;
		this.vehicalType=vehicalType;
		this.vehicalNo=vehicalNo;
		this.createdDate = createdDate;	
		this.cmnLocationMst = cmnLocationMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;	
	}

	//Property accessors

	public Integer getTrnCounter() {
		return trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}
	
	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public long getDistance() {
		return distance;
	}

	public void setDistance(long distance) {
		this.distance = distance;
	}

	public HrEisEmpMst getHrEisEmpMst() {
		return hrEisEmpMst;
	}

	public void setHrEisEmpMst(HrEisEmpMst hrEisEmpMst) {
		this.hrEisEmpMst = hrEisEmpMst;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Date getVehicalAvailDate() {
		return vehicalAvailDate;
	}

	public void setVehicalAvailDate(Date vehicalAvailDate) {
		this.vehicalAvailDate = vehicalAvailDate;
	}

	public String getVehicalAvailed() {
		return vehicalAvailed;
	}

	public void setVehicalAvailed(String vehicalAvailed) {
		this.vehicalAvailed = vehicalAvailed;
	}

	public Date getVehicalLeaveDate() {
		return vehicalLeaveDate;
	}

	public void setVehicalLeaveDate(Date vehicalLeaveDate) {
		this.vehicalLeaveDate = vehicalLeaveDate;
	}

	public String getVehicalNo() {
		return vehicalNo;
	}

	public void setVehicalNo(String vehicalNo) {
		this.vehicalNo = vehicalNo;
	}

	public CmnLookupMst getVehicalType() {
		return vehicalType;
	}

	public void setVehicalType(CmnLookupMst vehicalType) {
		this.vehicalType = vehicalType;
	}

	
	}
