// default package
// Generated Oct 30, 2007 6:33:32 PM by Hibernate Tools 3.1.0.beta5
package com.tcs.sgv.eis.valueobject;

import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrInvestTypeMst generated by hbm2java
 */
public class HrInvestTypeMst implements java.io.Serializable {

	// Fields    

	private long investTypeId;

	private String investName;

	private String investDesc;	
	
	private HrItSectionMst hrItSectionMst;

	private Date startDate;

	private Date endDate;

	private long investTypeCode;

	private long activateFlag;

	private CmnLanguageMst cmnLanguageMst;
	
	private CmnDatabaseMst cmnDatabaseMst;
	
	private OrgUserMst orgUserMstByCreatedBy;
	
	private OrgUserMst orgUserMstByUpdatedBy;
	
	private OrgPostMst orgPostMstByCreatedByPost;
	
	private OrgPostMst orgPostMstByUpdatedByPost;
	
	private Date createdDate;

	private Date updatedDate;

	// Constructors

	/** default constructor */
	public HrInvestTypeMst() {
	}

	/** minimal constructor */
	public HrInvestTypeMst(long investTypeId, //long sectId,
			HrItSectionMst hrItSectionMst,
			Date startDate, CmnLanguageMst cmnLanguageMst, long investTypeCode,
			long activateFlag, CmnDatabaseMst cmnDatabaseMst, OrgUserMst orgUserMstByCreatedBy,
			OrgPostMst orgPostMstByCreatedByPost, Date createdDate) {
		this.investTypeId = investTypeId;
		//this.sectId = sectId;
		this.hrItSectionMst = hrItSectionMst;
		this.startDate = startDate;
		this.cmnLanguageMst = cmnLanguageMst;
		this.investTypeCode = investTypeCode;
		this.activateFlag = activateFlag;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.createdDate = createdDate;
	}

	/** full constructor */
	public HrInvestTypeMst(long investTypeId, String investName,
			String investDesc, HrItSectionMst hrItSectionMst, Date startDate, Date endDate,
			CmnLanguageMst cmnLanguageMst, long investTypeCode,
			long activateFlag, CmnDatabaseMst cmnDatabaseMst, OrgUserMst orgUserMstByCreatedBy,
			OrgPostMst orgPostMstByCreatedByPost, Date createdDate, OrgUserMst orgUserMstByUpdatedBy,
			OrgPostMst orgPostMstByUpdatedByPost, Date updatedDate) {
		this.investTypeId = investTypeId;
		this.investName = investName;
		this.investDesc = investDesc;
		this.hrItSectionMst = hrItSectionMst;
		this.startDate = startDate;
		this.endDate = endDate;
		this.cmnLanguageMst = cmnLanguageMst;
		this.investTypeCode = investTypeCode;
		this.activateFlag = activateFlag;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.createdDate = createdDate;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.updatedDate = updatedDate;
	}

	// Property accessors
	public long getInvestTypeId() {
		return this.investTypeId;
	}

	public void setInvestTypeId(long investTypeId) {
		this.investTypeId = investTypeId;
	}

	public String getInvestName() {
		return this.investName;
	}

	public void setInvestName(String investName) {
		this.investName = investName;
	}

	public String getInvestDesc() {
		return this.investDesc;
	}

	public void setInvestDesc(String investDesc) {
		this.investDesc = investDesc;
	}

	public HrItSectionMst getHrItSectionMst() {
		return hrItSectionMst;
	}

	public void setHrItSectionMst(HrItSectionMst hrItSectionMst) {
		this.hrItSectionMst = hrItSectionMst;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	
	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public long getInvestTypeCode() {
		return this.investTypeCode;
	}

	public void setInvestTypeCode(long investTypeCode) {
		this.investTypeCode = investTypeCode;
	}

	public long getActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(long activateFlag) {
		this.activateFlag = activateFlag;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
