// default package
// Generated Oct 30, 2007 6:33:45 PM by Hibernate Tools 3.1.0.beta5
package com.tcs.sgv.eis.valueobject;
import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrInvestEmpDtls generated by hbm2java
 */
public class HrInvestEmpDtls implements java.io.Serializable {

	// Fields    

	private long investDtlsId;		
	private HrInvestTypeMst hrInvestTypeMst;	
	private HrEisEmpMst hrEisEmpMst; 
	private Date investDate;
	private long amount;
	private String currencyamount;
	private String policyNo;
	private String proofSubmitFlag;
	private String approvalFlag;
	private CmnDatabaseMst cmnDatabaseMst;	
	private OrgUserMst orgUserMstByCreatedBy;	
	private OrgUserMst orgUserMstByUpdatedBy;	
	private OrgPostMst orgPostMstByCreatedByPost;	
	private OrgPostMst orgPostMstByUpdatedByPost;
	private Date createdDate;	
	private Date updatedDate;

	// Constructors

	/** default constructor */
	public HrInvestEmpDtls() {
	}

	/** minimal constructor */
	public HrInvestEmpDtls(long investDtlsId,// long investTypeId,
			HrInvestTypeMst hrInvestTypeMst,
			HrEisEmpMst hrEisEmpMst, Date investDate, long amount,
			String proofSubmitFlag, String approvalFlag, CmnDatabaseMst cmnDatabaseMst, OrgUserMst orgUserMstByCreatedBy, 
			OrgPostMst orgPostMstByCreatedByPost, Date createdDate) {
		this.investDtlsId = investDtlsId;
		this.hrInvestTypeMst = hrInvestTypeMst;
		this.hrEisEmpMst = hrEisEmpMst;
		this.investDate = investDate;
		this.amount = amount;
		this.proofSubmitFlag = proofSubmitFlag;
		this.approvalFlag = approvalFlag;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.createdDate = createdDate;
	}

	/** full constructor */
	public HrInvestEmpDtls(long investDtlsId,// long investTypeId,
			HrInvestTypeMst hrInvestTypeMst,
			HrEisEmpMst hrEisEmpMst, Date investDate, long amount,
			String policyNo, String proofSubmitFlag, String approvalFlag,
			CmnDatabaseMst cmnDatabaseMst, OrgUserMst orgUserMstByCreatedBy, OrgPostMst orgPostMstByCreatedByPost,
			Date createdDate, OrgUserMst orgUserMstByUpdatedBy, OrgPostMst orgPostMstByUpdatedByPost,
			Date updatedDate) {
		this.investDtlsId = investDtlsId;
		this.hrInvestTypeMst = hrInvestTypeMst;
		this.hrEisEmpMst = hrEisEmpMst;
		this.investDate = investDate;
		this.amount = amount;
		this.policyNo = policyNo;
		this.proofSubmitFlag = proofSubmitFlag;
		this.approvalFlag = approvalFlag;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.createdDate = createdDate;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.updatedDate = updatedDate;
	}

	// Property accessors
	public long getInvestDtlsId() {
		return this.investDtlsId;
	}

	public void setInvestDtlsId(long investDtlsId) {
		this.investDtlsId = investDtlsId;
	}

	public HrInvestTypeMst getHrInvestTypeMst() {
		return hrInvestTypeMst;
	}

	public void setHrInvestTypeMst(HrInvestTypeMst hrInvestTypeMst) {
		this.hrInvestTypeMst = hrInvestTypeMst;
	}
	
	public HrEisEmpMst getHrEisEmpMst() {
		return hrEisEmpMst;
	}

	public void setHrEisEmpMst(HrEisEmpMst hrEisEmpMst) {
		this.hrEisEmpMst = hrEisEmpMst;
	}

	public Date getInvestDate() {
		return this.investDate;
	}

	public void setInvestDate(Date investDate) {
		this.investDate = investDate;
	}

	public long getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	public String getProofSubmitFlag() {
		return this.proofSubmitFlag;
	}

	public void setProofSubmitFlag(String proofSubmitFlag) {
		this.proofSubmitFlag = proofSubmitFlag;
	}

	public String getApprovalFlag() {
		return this.approvalFlag;
	}

	public void setApprovalFlag(String approvalFlag) {
		this.approvalFlag = approvalFlag;
	}

	

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public String getCurrencyamount() {
		return currencyamount;
	}

	public void setCurrencyamount(String currencyamount) {
		this.currencyamount = currencyamount;
	}

}
