// default package
// Generated Oct 30, 2007 6:32:30 PM by Hibernate Tools 3.1.0.beta5
package com.tcs.sgv.eis.valueobject;


import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrItSectionMst generated by hbm2java
 */
public class HrItSectionMst implements java.io.Serializable {

	// Fields    

	private long sectId;

	private String sectCode;

	private String sectName;

	private String sectDesc;

	private Date startDate;

	private Date endDate;

	private CmnLanguageMst cmnLanguageMst;
	
	private CmnDatabaseMst cmnDatabaseMst;
	
	private OrgUserMst orgUserMstByCreatedBy;
	
	private OrgUserMst orgUserMstByUpdatedBy;
	
	private OrgPostMst orgPostMstByCreatedByPost;
	
	private OrgPostMst orgPostMstByUpdatedByPost;

	private long sectTypeCode;

	private long activateFlag;	

	private Date createdDate;	

	private Date updatedDate;

	// Constructors

	/** default constructor */
	public HrItSectionMst() {
	}

	/** minimal constructor */
	public HrItSectionMst(long sectId, String sectCode,
			Date startDate, CmnLanguageMst cmnLanguageMst, long sectTypeCode,
			long activateFlag, OrgUserMst orgUserMstByCreatedBy,
			OrgPostMst orgPostMstByCreatedByPost, Date createdDate) {
		this.sectId = sectId;
		this.sectCode = sectCode;
		this.startDate = startDate;
		this.cmnLanguageMst = cmnLanguageMst;
		this.sectTypeCode = sectTypeCode;
		this.activateFlag = activateFlag;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.createdDate = createdDate;
	}

	/** full constructor */
	public HrItSectionMst(long sectId, String sectCode,
			String sectName, String sectDesc, Date startDate, Date endDate,
			CmnLanguageMst cmnLanguageMst, long sectTypeCode,
			long activateFlag, CmnDatabaseMst cmnDatabaseMst, OrgUserMst orgUserMstByCreatedBy,
			OrgPostMst orgPostMstByCreatedByPost, Date createdDate, OrgUserMst orgUserMstByUpdatedBy,
			OrgPostMst orgPostMstByUpdatedByPost, Date updatedDate) {
		this.sectId = sectId;
		this.sectCode = sectCode;
		this.sectName = sectName;
		this.sectDesc = sectDesc;
		this.startDate = startDate;
		this.endDate = endDate;
		this.cmnLanguageMst = cmnLanguageMst;
		this.sectTypeCode = sectTypeCode;
		this.activateFlag = activateFlag;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.createdDate = createdDate;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.updatedDate = updatedDate;
	}

	// Property accessors
	public long getSectId() {
		return this.sectId;
	}

	public void setSectId(long sectId) {
		this.sectId = sectId;
	}

	public String getSectCode() {
		return this.sectCode;
	}

	public void setSectCode(String sectCode) {
		this.sectCode = sectCode;
	}

	public String getSectName() {
		return this.sectName;
	}

	public void setSectName(String sectName) {
		this.sectName = sectName;
	}

	public String getSectDesc() {
		return this.sectDesc;
	}

	public void setSectDesc(String sectDesc) {
		this.sectDesc = sectDesc;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	

	public long getSectTypeCode() {
		return this.sectTypeCode;
	}

	public void setSectTypeCode(long sectTypeCode) {
		this.sectTypeCode = sectTypeCode;
	}

	public long getActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(long activateFlag) {
		this.activateFlag = activateFlag;
	}

	

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}	

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
