// default package
// Generated Nov 7, 2007 10:16:04 AM by Hibernate Tools 3.1.0.beta5
package com.tcs.sgv.eis.valueobject;

import java.util.Date;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrItExemptTypeMst generated by hbm2java
 */
public class HrItExemptTypeMst implements java.io.Serializable {

	// Fields    

	private long itexemptTypeId;
	private String itexemptName;
	private String itexemptDesc;
	private long sectId;
	private long itexemptTypeCode;
	private long activateFlag;
	private Date startDate;
	private Date endDate;	
	private Date createdDate;
	private Date updatedDate;	
	private CmnLanguageMst cmnLanguageMst;
	private CmnDatabaseMst cmnDatabaseMst;	
	private OrgUserMst orgUserMstByCreatedBy;	
	private OrgUserMst orgUserMstByUpdatedBy;	
	private OrgPostMst orgPostMstByCreatedByPost;
	private OrgPostMst orgPostMstByUpdatedByPost;

	// Constructors

	/** default constructor */
	public HrItExemptTypeMst() {
	}

	/** minimal constructor */
	public HrItExemptTypeMst(long itexemptTypeId, String itexemptName,
			long sectId, long itexemptTypeCode,
			long activateFlag, Date startDate,Date createdDate,
			CmnLanguageMst cmnLanguageMst,OrgUserMst orgUserMstByCreatedBy,
			OrgPostMst orgPostMstByCreatedByPost,CmnDatabaseMst cmnDatabaseMst) {
		this.itexemptTypeId = itexemptTypeId;
		this.itexemptName = itexemptName;
		this.sectId = sectId;
		this.itexemptTypeCode = itexemptTypeCode;
		this.activateFlag = activateFlag;
		this.startDate = startDate;
		this.cmnLanguageMst = cmnLanguageMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.createdDate = createdDate;
	}

	/** full constructor */
	public HrItExemptTypeMst(long itexemptTypeId, String itexemptName,
			String itexemptDesc, long sectId,
			long itexemptTypeCode, long activateFlag,
			Date startDate, Date endDate,Date createdDate,Date updatedDate,
			CmnLanguageMst cmnLanguageMst,OrgUserMst orgUserMstByCreatedBy,
			OrgPostMst orgPostMstByCreatedByPost,CmnDatabaseMst cmnDatabaseMst,
			OrgUserMst orgUserMstByUpdatedBy,OrgPostMst orgPostMstByUpdatedByPost) {
		this.itexemptTypeId = itexemptTypeId;
		this.itexemptName = itexemptName;
		this.itexemptDesc = itexemptDesc;
		this.sectId = sectId;
		this.itexemptTypeCode = itexemptTypeCode;
		this.activateFlag = activateFlag;
		this.startDate = startDate;
		this.endDate = endDate;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.cmnLanguageMst = cmnLanguageMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	// Property accessors
	public long getItexemptTypeId() {
		return this.itexemptTypeId;
	}

	public void setItexemptTypeId(long itexemptTypeId) {
		this.itexemptTypeId = itexemptTypeId;
	}

	public String getItexemptName() {
		return this.itexemptName;
	}

	public void setItexemptName(String itexemptName) {
		this.itexemptName = itexemptName;
	}

	public String getItexemptDesc() {
		return this.itexemptDesc;
	}

	public void setItexemptDesc(String itexemptDesc) {
		this.itexemptDesc = itexemptDesc;
	}

	public long getSectId() {
		return this.sectId;
	}

	public void setSectId(long sectId) {
		this.sectId = sectId;
	}

	public long getItexemptTypeCode() {
		return this.itexemptTypeCode;
	}

	public void setItexemptTypeCode(long itexemptTypeCode) {
		this.itexemptTypeCode = itexemptTypeCode;
	}

	public long getActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(long activateFlag) {
		this.activateFlag = activateFlag;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

}
