// default package
// Generated Aug 3, 2007 9:47:32 AM by Hibernate Tools 3.2.0.beta8
package com.tcs.sgv.eis.valueobject;


import java.util.Date;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;



/**
 * HrLoanEmpIntRecoverDtls generated by hbm2java
 */
public class HrLoanEmpIntRecoverDtls implements java.io.Serializable {

	// Fields    

	private long intRecoverId;

	private HrLoanEmpDtls hrLoanEmpDtls;

	private long totalRecoveredInt;

	private long totalRecoveredIntInst;

	private Date createdDate;

	private Date updatedDate;
	
	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;
	
	private Integer trnCounter;

	// Constructors

	/** default constructor */
	public HrLoanEmpIntRecoverDtls() {
	}

	/** minimal constructor */
	public HrLoanEmpIntRecoverDtls(long intRecoverId,
			HrLoanEmpDtls hrLoanEmpDtls, long totalRecoveredInt,
			long totalRecoveredIntInst, Date createdDate,CmnDatabaseMst cmnDatabaseMst,CmnLocationMst 
			cmnLocationMst, OrgUserMst orgUserMstByCreatedBy, 
			OrgPostMst orgPostMstByCreatedByPost){
		this.intRecoverId = intRecoverId;
		this.hrLoanEmpDtls = hrLoanEmpDtls;
		this.totalRecoveredInt = totalRecoveredInt;
		this.totalRecoveredIntInst = totalRecoveredIntInst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		
	}

	/** full constructor */
	public HrLoanEmpIntRecoverDtls(long intRecoverId,
			HrLoanEmpDtls hrLoanEmpDtls, long totalRecoveredInt,
			long totalRecoveredIntInst,Date createdDate,Date updatedDate,
			CmnDatabaseMst cmnDatabaseMst,CmnLocationMst 
			cmnLocationMst, OrgUserMst orgUserMstByCreatedBy, 
			OrgPostMst orgPostMstByCreatedByPost,
			OrgUserMst orgUserMstByUpdatedBy,  OrgPostMst orgPostMstByUpdatedByPost,Integer trnCounter) {
		this.intRecoverId = intRecoverId;
		this.hrLoanEmpDtls = hrLoanEmpDtls;
		this.totalRecoveredInt = totalRecoveredInt;
		this.totalRecoveredIntInst = totalRecoveredIntInst;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.trnCounter = trnCounter;
	}

	// Property accessors
	public long getIntRecoverId() {
		return this.intRecoverId;
	}

	public void setIntRecoverId(long intRecoverId) {
		this.intRecoverId = intRecoverId;
	}

	public HrLoanEmpDtls getHrLoanEmpDtls() {
		return this.hrLoanEmpDtls;
	}

	public void setHrLoanEmpDtls(HrLoanEmpDtls hrLoanEmpDtls) {
		this.hrLoanEmpDtls = hrLoanEmpDtls;
	}

	public long getTotalRecoveredInt() {
		return this.totalRecoveredInt;
	}

	public void setTotalRecoveredInt(long totalRecoveredInt) {
		this.totalRecoveredInt = totalRecoveredInt;
	}

	public long getTotalRecoveredIntInst() {
		return this.totalRecoveredIntInst;
	}

	public void setTotalRecoveredIntInst(long totalRecoveredIntInst) {
		this.totalRecoveredIntInst = totalRecoveredIntInst;
	}

		public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public Integer getTrnCounter() {
		return trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}

}
