package com.tcs.sgv.eis.valueobject;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.tcs.sgv.common.loan.valueobject.HrLoanAdvMst;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;


/**
 * HrLoanEmpDtls generated by hbm2java
 */
public class HrLoanEmpDtls implements java.io.Serializable {

	// Fields    

	private long empLoanId;

	private HrEisEmpMst hrEisEmpMst;

	private HrLoanAdvMst hrLoanAdvMst;

	private long loanPrinAmt;

	private String currencyloanPrinAmt;
	private String currencyloanInterestAmt;
	private long loanInterestAmt;

	private long loanPrinInstNo;

	private long loanIntInstNo;

	private long loanPrinEmiAmt;
	
	private long loanIntEmiAmt;

	private String loanAccountNo;

	private Date loanDate;
	
	private String loanSancOrderNo;
	
	private Date loanSancOrderdate;
	/*added by khushal*/
	/**
	 * @return the loanSancOrderdate
	 */
	public Date getLoanSancOrderdate() {
		return loanSancOrderdate;
	}

	/**
	 * @param loanSancOrderdate the loanSancOrderdate to set
	 */
	public void setLoanSancOrderdate(Date loanSancOrderDate) {
		this.loanSancOrderdate = loanSancOrderDate;
	}
/*ended by khushal*/
	private Date createdDate;
	
	private Date updatedDate;
	
	private String voucherNo;
	
	private Date voucherDate;
	
	
	
	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;
	
	private Set hrLoanEmpPrinRecoverDtlses = new HashSet(0);
	
	private Set hrLoanEmpIntRecoverDtlses = new HashSet(0);
	
	private Integer trnCounter;
	
	private Integer loanActivateFlag;
	
	private Integer isApproved;

	// Constructors
	//added By Javed
	private Long loanOddinstno;
	private Long loanOddinstAmt;
	private int mulLoanRecoveryMode;
	private String mulLoanRecRemarks;
	private int mulLoanInstRecvd;
	private Long mulLoanAmtRecvd;
	
	private String orderno;
	private Date orderDate;
	
	/** default constructor */
	public HrLoanEmpDtls() {
	}

	/** minimal constructor */
	public HrLoanEmpDtls(long empLoanId, HrEisEmpMst hrEisEmpMst,
			HrLoanAdvMst hrLoanAdvMst, long loanPrinAmt,
			long loanInterestAmt, long loanPrinInstNo,String loanSancOrderNo,
			long loanIntInstNo, long loanPrinEmiAmt,long loanIntEmiAmt,
			String loanAccountNo, Date loanDate, CmnDatabaseMst cmnDatabaseMst,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByCreatedBy, OrgPostMst orgPostMstByCreatedByPost,
			Date createdDate,Set hrLoanEmpPrinRecoverDtlses,Set hrLoanEmpIntRecoverDtlses,Integer loanActivateFlag,
			Long loanOddinstno,Long loanOddinstAmt,Date loanSancOrderdate) {
		this.empLoanId = empLoanId;
		this.hrEisEmpMst = hrEisEmpMst;
		this.hrLoanAdvMst = hrLoanAdvMst;
		this.loanPrinAmt = loanPrinAmt;
		this.loanInterestAmt = loanInterestAmt;
		this.loanPrinInstNo = loanPrinInstNo;
		this.loanIntInstNo = loanIntInstNo;
		this.loanPrinEmiAmt = loanPrinEmiAmt;
		this.loanAccountNo = loanAccountNo;
		this.loanDate = loanDate;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.createdDate = createdDate;
		this.hrLoanEmpPrinRecoverDtlses = hrLoanEmpPrinRecoverDtlses;
		this.hrLoanEmpIntRecoverDtlses = hrLoanEmpIntRecoverDtlses;
		this.loanIntEmiAmt = loanIntEmiAmt;
		this.loanSancOrderNo = loanSancOrderNo;
		this.loanActivateFlag = loanActivateFlag;
		this.loanOddinstno = loanOddinstno;
		this.loanOddinstAmt = loanOddinstAmt;
		this.loanSancOrderdate=loanSancOrderdate;
	}

	/** full constructor */
	public HrLoanEmpDtls(long empLoanId, HrEisEmpMst hrEisEmpMst,
			HrLoanAdvMst hrLoanAdvMst, long loanPrinAmt,
			long loanInterestAmt, long loanPrinInstNo,String loanSancOrderNo,
			long loanIntInstNo, long loanPrinEmiAmt,long loanIntEmiAmt,
			String loanAccountNo, Date loanDate, CmnDatabaseMst cmnDatabaseMst,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByCreatedBy, OrgPostMst orgPostMstByCreatedByPost,
			Date createdDate, OrgUserMst orgUserMstByUpdatedBy,  OrgPostMst orgPostMstByUpdatedByPost,
			Date updatedDate,Set hrLoanEmpPrinRecoverDtlses,Set hrLoanEmpIntRecoverDtlses,Integer trnCounter,Integer loanActivateFlag,
			Long loanOddinstno,Long loanOddinstAmt) {
		this.empLoanId = empLoanId;
		this.hrEisEmpMst = hrEisEmpMst;
		this.hrLoanAdvMst = hrLoanAdvMst;
		this.loanPrinAmt = loanPrinAmt;
		this.loanInterestAmt = loanInterestAmt;
		this.loanPrinInstNo = loanPrinInstNo;
		this.loanIntInstNo = loanIntInstNo;
		this.loanPrinEmiAmt = loanPrinEmiAmt;
		this.loanAccountNo = loanAccountNo;
		this.loanDate = loanDate;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.createdDate = createdDate;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.updatedDate = updatedDate;
		this.hrLoanEmpPrinRecoverDtlses = hrLoanEmpPrinRecoverDtlses;
		this.hrLoanEmpIntRecoverDtlses = hrLoanEmpIntRecoverDtlses;
		this.trnCounter = trnCounter;
		this.loanIntEmiAmt = loanIntEmiAmt;
		this.loanSancOrderNo = loanSancOrderNo;
		this.loanActivateFlag = loanActivateFlag;
		this.loanOddinstno = loanOddinstno;
		this.loanOddinstAmt = loanOddinstAmt;
	}

	// Property accessors
	public long getEmpLoanId() {
		return this.empLoanId;
	}

	public void setEmpLoanId(long empLoanId) {
		this.empLoanId = empLoanId;
	}

	public HrEisEmpMst getHrEisEmpMst() {
		return this.hrEisEmpMst;
	}

	public void setHrEisEmpMst(HrEisEmpMst hrEisEmpMst) {
		this.hrEisEmpMst = hrEisEmpMst;
	}

	public HrLoanAdvMst getHrLoanAdvMst() {
		return this.hrLoanAdvMst;
	}

	public void setHrLoanAdvMst(HrLoanAdvMst hrLoanAdvMst) {
		this.hrLoanAdvMst = hrLoanAdvMst;
	}

	public long getLoanPrinAmt() {
		return this.loanPrinAmt;
	}

	public void setLoanPrinAmt(long loanPrinAmt) {
		this.loanPrinAmt = loanPrinAmt;
	}

	public long getLoanInterestAmt() {
		return this.loanInterestAmt;
	}

	public void setLoanInterestAmt(long loanInterestAmt) {
		this.loanInterestAmt = loanInterestAmt;
	}

	public long getLoanPrinInstNo() {
		return this.loanPrinInstNo;
	}

	public void setLoanPrinInstNo(long loanPrinInstNo) {
		this.loanPrinInstNo = loanPrinInstNo;
	}

	public long getLoanIntInstNo() {
		return this.loanIntInstNo;
	}

	public void setLoanIntInstNo(long loanIntInstNo) {
		this.loanIntInstNo = loanIntInstNo;
	}

	

	public String getLoanAccountNo() {
		return this.loanAccountNo;
	}

	public void setLoanAccountNo(String loanAccountNo) {
		this.loanAccountNo = loanAccountNo;
	}

	public Date getLoanDate() {
		return this.loanDate;
	}

	public void setLoanDate(Date loanDate) {
		this.loanDate = loanDate;
	}

	/*public long getDbId() {
		return this.dbId;
	}

	public void setDbId(long dbId) {
		this.dbId = dbId;
	}

	public long getLocId() {
		return this.locId;
	}

	public void setLocId(long locId) {
		this.locId = locId;
	}

	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	public long getCreatedByPost() {
		return this.createdByPost;
	}

	public void setCreatedByPost(long createdByPost) {
		this.createdByPost = createdByPost;
	}*/

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/*public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public long getUpdatedByPost() {
		return this.updatedByPost;
	}

	public void setUpdatedByPost(long updatedByPost) {
		this.updatedByPost = updatedByPost;
	}*/

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	
	
	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}
	
	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}
	

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public Set getHrLoanEmpIntRecoverDtlses() {
		return hrLoanEmpIntRecoverDtlses;
	}

	public void setHrLoanEmpIntRecoverDtlses(Set hrLoanEmpIntRecoverDtlses) {
		this.hrLoanEmpIntRecoverDtlses = hrLoanEmpIntRecoverDtlses;
	}

	public Set getHrLoanEmpPrinRecoverDtlses() {
		return hrLoanEmpPrinRecoverDtlses;
	}

	public void setHrLoanEmpPrinRecoverDtlses(Set hrLoanEmpPrinRecoverDtlses) {
		this.hrLoanEmpPrinRecoverDtlses = hrLoanEmpPrinRecoverDtlses;
	}

	public Integer getTrnCounter() {
		return trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}

	public long getLoanIntEmiAmt() {
		return loanIntEmiAmt;
	}

	public void setLoanIntEmiAmt(long loanIntEmiAmt) {
		this.loanIntEmiAmt = loanIntEmiAmt;
	}

	public long getLoanPrinEmiAmt() {
		return loanPrinEmiAmt;
	}

	public void setLoanPrinEmiAmt(long loanPrinEmiAmt) {
		this.loanPrinEmiAmt = loanPrinEmiAmt;
	}

	public String getLoanSancOrderNo() {
		return loanSancOrderNo;
	}

	public void setLoanSancOrderNo(String loanSancOrderNo) {
		this.loanSancOrderNo = loanSancOrderNo;
	}

	public Integer getLoanActivateFlag() {
		return loanActivateFlag;
	}

	public void setLoanActivateFlag(Integer loanActivateFlag) {
		this.loanActivateFlag = loanActivateFlag;
	}

	public String getCurrencyloanPrinAmt() {
		return currencyloanPrinAmt;
	}

	public void setCurrencyloanPrinAmt(String currencyloanPrinAmt) {
		this.currencyloanPrinAmt = currencyloanPrinAmt;
	}

	public String getCurrencyloanInterestAmt() {
		return currencyloanInterestAmt;
	}

	public void setCurrencyloanInterestAmt(String currencyloanInterestAmt) {
		this.currencyloanInterestAmt = currencyloanInterestAmt;
	}

	public Integer getIsApproved() {
		return isApproved;
	}

	public void setIsApproved(Integer isApproved) {
		this.isApproved = isApproved;
	}

	public Long getLoanOddinstno() {
		return loanOddinstno;
	}

	public void setLoanOddinstno(Long loanOddinstno) {
		this.loanOddinstno = loanOddinstno;
	}

	public Long getLoanOddinstAmt() {
		return loanOddinstAmt;
	}

	public void setLoanOddinstAmt(Long loanOddinstAmt) {
		this.loanOddinstAmt = loanOddinstAmt;
	}

	/**
	 * @return the voucherNo
	 */
	public String getVoucherNo() {
		return voucherNo;
	}

	/**
	 * @param voucherNo the voucherNo to set
	 */
	public void setVoucherNo(String voucherNo) {
		this.voucherNo = voucherNo;
	}

	/**
	 * @return the voucherDate
	 */
	public Date getVoucherDate() {
		return voucherDate;
	}

	/**
	 * @param voucherDate the voucherDate to set
	 */
	public void setVoucherDate(Date voucherDate) {
		this.voucherDate = voucherDate;
	}
	public int getMulLoanRecoveryMode() {
		return mulLoanRecoveryMode;
	}

	public void setMulLoanRecoveryMode(int mulLoanRecoveryMode) {
		this.mulLoanRecoveryMode = mulLoanRecoveryMode;
	}

	public String getMulLoanRecRemarks() {
		return mulLoanRecRemarks;
	}

	public void setMulLoanRecRemarks(String mulLoanRecRemarks) {
		this.mulLoanRecRemarks = mulLoanRecRemarks;
	}

	public int getMulLoanInstRecvd() {
		return mulLoanInstRecvd;
	}

	public void setMulLoanInstRecvd(int mulLoanInstRecvd) {
		this.mulLoanInstRecvd = mulLoanInstRecvd;
	}

	public Long getMulLoanAmtRecvd() {
		return mulLoanAmtRecvd;
	}

	public void setMulLoanAmtRecvd(Long mulLoanAmtRecvd) {
		this.mulLoanAmtRecvd = mulLoanAmtRecvd;
	}	
	
	public String getOrderno()
	{
		return orderno;
	}

	public void setOrderno(String orderno)
	{
		this.orderno = orderno;
	}

	public Date getOrderDate()
	{
		return orderDate;
	}

	public void setOrderDate(Date orderDate)
	{
		this.orderDate = orderDate;
	}
}
