package com.tcs.sgv.eis.valueobject;
// Generated Oct 17, 2007 6:59:46 PM by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.eis.valueobject.HrEisEmpMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;
/**
 * HrMiscRecoverDtls generated by hbm2java
 */
public class HrMiscRecoverDtls implements java.io.Serializable {

	// Fields    

	private long miscId;

	//private long empId;

	private long recoverAmt;
	
	private String currencyrecoverAmt;

	private String reason;

	private Date recoverDate;

	/*private long dbId;

	private long locId;

	private long langId;*/

	private long elementCode;

	/*private long createdBy;

	private long createdByPost;*/

	private Date createdDate;

	/*private long updatedBy;

	private long updatedByPost;*/

	private Date updatedDate;
	
	private CmnLanguageMst cmnLanguageMst;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;

	private HrEisEmpMst hrEisEmpMst;
	
	private Integer trnCounter;
	
	private long attachment_Id;
	
	private long total_amount;
	
	private long installment;
	
	private Date recoverEndDate;
	
	private long edpTypeId;
	
	private Integer miscActivateFlag;
	
	private int tot_recv_amt;
	
	private int tot_recv_inst;
	// Constructors

	/** default constructor */
	public HrMiscRecoverDtls() {
	}

	/** minimal constructor */
	public HrMiscRecoverDtls(long miscId) {
		this.miscId = miscId;
	}

	/** full constructor */
	public HrMiscRecoverDtls(long miscId, HrEisEmpMst hrEisEmpMst,
			long recoverAmt, String reason, Date recoverDate,
			Date createdDate,Date updatedDate,long elementCode,
			CmnLanguageMst cmnLanguageMst, CmnLocationMst cmnLocationMst, CmnDatabaseMst cmnDatabaseMst, 
			OrgUserMst orgUserMstByCreatedBy,
			OrgPostMst orgPostMstByCreatedByPost,
			OrgUserMst orgUserMstByUpdatedBy,OrgPostMst orgPostMstByUpdatedByPost) {
		this.miscId = miscId;
		this.hrEisEmpMst = hrEisEmpMst;
		this.recoverAmt = recoverAmt;
		this.reason = reason;
		this.recoverDate = recoverDate;
		/*this.dbId = dbId;
		this.locId = locId;
		this.langId = langId;*/
		this.elementCode = elementCode;
		/*this.createdBy = createdBy;
		this.createdByPost = createdByPost;*/
		this.createdDate = createdDate;
		/*this.updatedBy = updatedBy;
		this.updatedByPost = updatedByPost;*/
		this.updatedDate = updatedDate;
		this.cmnLanguageMst = cmnLanguageMst; 
		this.cmnLocationMst = cmnLocationMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}
	

	// Property accessors
	public long getMiscId() {
		return this.miscId;
	}

	public void setMiscId(long miscId) {
		this.miscId = miscId;
	}

	/*public long getEmpId() {
		return this.empId;
	}

	public void setEmpId(long empId) {
		this.empId = empId;
	}*/

	public long getRecoverAmt() {
		return this.recoverAmt;
	}

	public void setRecoverAmt(long recoverAmt) {
		this.recoverAmt = recoverAmt;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public Date getRecoverDate() {
		return this.recoverDate;
	}

	public void setRecoverDate(Date recoverDate) {
		this.recoverDate = recoverDate;
	}

	/*public long getDbId() {
		return this.dbId;
	}

	public void setDbId(long dbId) {
		this.dbId = dbId;
	}

	public long getLocId() {
		return this.locId;
	}

	public void setLocId(long locId) {
		this.locId = locId;
	}

	public long getLangId() {
		return this.langId;
	}

	public void setLangId(long langId) {
		this.langId = langId;
	}*/

	public long getElementCode() {
		return this.elementCode;
	}

	public void setElementCode(long elementCode) {
		this.elementCode = elementCode;
	}

	/*public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	public long getCreatedByPost() {
		return this.createdByPost;
	}

	public void setCreatedByPost(long createdByPost) {
		this.createdByPost = createdByPost;
	}*/

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/*public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public long getUpdatedByPost() {
		return this.updatedByPost;
	}

	public void setUpdatedByPost(long updatedByPost) {
		this.updatedByPost = updatedByPost;
	}*/

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public HrEisEmpMst getHrEisEmpMst() {
		return hrEisEmpMst;
	}

	public void setHrEisEmpMst(HrEisEmpMst hrEisEmpMst) {
		this.hrEisEmpMst = hrEisEmpMst;
	}

	public Integer getTrnCounter() {
		return trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}

	public long getAttachment_Id() {
		return attachment_Id;
	}

	public void setAttachment_Id(long attachment_Id) {
		this.attachment_Id = attachment_Id;
	}

	public long getInstallment() {
		return installment;
	}

	public void setInstallment(long installment) {
		this.installment = installment;
	}

	public Date getRecoverEndDate() {
		return recoverEndDate;
	}

	public void setRecoverEndDate(Date recoverEndDate) {
		this.recoverEndDate = recoverEndDate;
	}

	public long getTotal_amount() {
		return total_amount;
	}

	public void setTotal_amount(long total_amount) {
		this.total_amount = total_amount;
	}

	public long getEdpTypeId() {
		return edpTypeId;
	}

	public void setEdpTypeId(long edpTypeId) {
		this.edpTypeId = edpTypeId;
	}

	public Integer getMiscActivateFlag() {
		return miscActivateFlag;
	}

	public void setMiscActivateFlag(Integer miscActivateFlag) {
		this.miscActivateFlag = miscActivateFlag;
	}

	public int getTot_recv_amt() {
		return tot_recv_amt;
	}

	public void setTot_recv_amt(int tot_recv_amt) {
		this.tot_recv_amt = tot_recv_amt;
	}

	public int getTot_recv_inst() {
		return tot_recv_inst;
	}

	public void setTot_recv_inst(int tot_recv_inst) {
		this.tot_recv_inst = tot_recv_inst;
	}

	public String getCurrencyrecoverAmt() {
		return currencyrecoverAmt;
	}

	public void setCurrencyrecoverAmt(String currencyrecoverAmt) {
		this.currencyrecoverAmt = currencyrecoverAmt;
	}
	

}
