package com.tcs.sgv.eis.valueobject;

// // Generated 7 Jun, 2012 2:12:49 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * HrPaybillTrnLog generated by hbm2java
 */
public class HrPaybillTrnLog implements java.io.Serializable
{

	private long hrPaybillTrnLogId;
	private long paybillHeadMpgId;
	private long billNo;
	private Date generationStartTime;
	private Date generationEndTime;
	private Date approvalStartTime;
	private Date approvalEndTime;
	private Date createdDate;
	private Long createdBy;

	public HrPaybillTrnLog()
	{}

	public HrPaybillTrnLog(long hrPaybillTrnLogId, long paybillHeadMpgId, long billNo)
	{
		this.hrPaybillTrnLogId = hrPaybillTrnLogId;
		this.paybillHeadMpgId = paybillHeadMpgId;
		this.billNo = billNo;
	}

	public HrPaybillTrnLog(long hrPaybillTrnLogId, long paybillHeadMpgId, long billNo, Date generationStartTime, Date generationEndTime, Date approvalStartTime, Date approvalEndTime, Date createdDate, Long createdBy)
	{
		this.hrPaybillTrnLogId = hrPaybillTrnLogId;
		this.paybillHeadMpgId = paybillHeadMpgId;
		this.billNo = billNo;
		this.generationStartTime = generationStartTime;
		this.generationEndTime = generationEndTime;
		this.approvalStartTime = approvalStartTime;
		this.approvalEndTime = approvalEndTime;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	public long getHrPaybillTrnLogId()
	{
		return this.hrPaybillTrnLogId;
	}

	public void setHrPaybillTrnLogId(long hrPaybillTrnLogId)
	{
		this.hrPaybillTrnLogId = hrPaybillTrnLogId;
	}

	public long getPaybillHeadMpgId()
	{
		return this.paybillHeadMpgId;
	}

	public void setPaybillHeadMpgId(long paybillHeadMpgId)
	{
		this.paybillHeadMpgId = paybillHeadMpgId;
	}

	public long getBillNo()
	{
		return this.billNo;
	}

	public void setBillNo(long billNo)
	{
		this.billNo = billNo;
	}

	public Date getGenerationStartTime()
	{
		return this.generationStartTime;
	}

	public void setGenerationStartTime(Date generationStartTime)
	{
		this.generationStartTime = generationStartTime;
	}

	public Date getGenerationEndTime()
	{
		return this.generationEndTime;
	}

	public void setGenerationEndTime(Date generationEndTime)
	{
		this.generationEndTime = generationEndTime;
	}

	public Date getApprovalStartTime()
	{
		return this.approvalStartTime;
	}

	public void setApprovalStartTime(Date approvalStartTime)
	{
		this.approvalStartTime = approvalStartTime;
	}

	public Date getApprovalEndTime()
	{
		return this.approvalEndTime;
	}

	public void setApprovalEndTime(Date approvalEndTime)
	{
		this.approvalEndTime = approvalEndTime;
	}

	public Date getCreatedDate()
	{
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate)
	{
		this.createdDate = createdDate;
	}

	public Long getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy)
	{
		this.createdBy = createdBy;
	}

}
