package com.tcs.sgv.eis.valueobject;

// default package
// Generated Jan 8, 2008 8:59:30 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgGradeMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;
/**
 * HrGpfBalanceDtls generated by hbm2java
 */
public class HrPayGpfBalanceDtls implements java.io.Serializable {

	// Fields    
	private long userId;

	private OrgUserMst orgUserMstByUpdatedByUser;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgUserMst orgUserMstByCreatedByUser;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;
	
	private OrgGradeMst orgGradeMst;

	private String gpfAccNo;
	
	private Integer trnCounter;

	private Date createdDate;

	private Date updatedDate;
	
	private String pfSeries;
	
	

	// Constructors

	/**
	 * @return the pfSeries
	 */
	public String getPfSeries() {
		return pfSeries;
	}

	/**
	 * @param pfSeries the pfSeries to set
	 */
	public void setPfSeries(String pfSeries) {
		this.pfSeries = pfSeries;
	}

	/** default constructor */
	public HrPayGpfBalanceDtls() {
	}

	/** minimal constructor */
	public HrPayGpfBalanceDtls(long userId, String gpfAccNo) {
		this.userId = userId;
		this.gpfAccNo = gpfAccNo;
	}

	/** full constructor */
	public HrPayGpfBalanceDtls(long userId, OrgUserMst orgUserMstByUpdatedByUser,
			CmnDatabaseMst cmnDatabaseMst,
			OrgPostMst orgPostMstByUpdatedByPost,
			OrgUserMst orgUserMstByCreatedByUser,
			OrgPostMst orgPostMstByCreatedByPost,
			OrgGradeMst orgGradeMst, 
			CmnLocationMst cmnLocationMst, String gpfAccNo,
			Integer trnCounter, Date createdDate, Date updatedDate) {
		this.userId = userId;
		this.orgUserMstByUpdatedByUser = orgUserMstByUpdatedByUser;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.orgUserMstByCreatedByUser = orgUserMstByCreatedByUser;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnLocationMst = cmnLocationMst;
		this.gpfAccNo = gpfAccNo;
		this.trnCounter = trnCounter;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.orgGradeMst=orgGradeMst;
	}

	// Property accessors
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public OrgUserMst getOrgUserMstByUpdatedByUser() {
		return this.orgUserMstByUpdatedByUser;
	}

	public void setOrgUserMstByUpdatedByUser(
			OrgUserMst orgUserMstByUpdatedByUser) {
		this.orgUserMstByUpdatedByUser = orgUserMstByUpdatedByUser;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return this.cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return this.orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(
			OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedByUser() {
		return this.orgUserMstByCreatedByUser;
	}

	public void setOrgUserMstByCreatedByUser(
			OrgUserMst orgUserMstByCreatedByUser) {
		this.orgUserMstByCreatedByUser = orgUserMstByCreatedByUser;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return this.orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(
			OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public CmnLocationMst getCmnLocationMst() {
		return this.cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public String getGpfAccNo() {
		return this.gpfAccNo;
	}

	public void setGpfAccNo(String gpfAccNo) {
		this.gpfAccNo = gpfAccNo;
	}


	public Integer getTrnCounter() {
		return this.trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public OrgGradeMst getOrgGradeMst() {
		return orgGradeMst;
	}

	public void setOrgGradeMst(OrgGradeMst orgGradeMst) {
		this.orgGradeMst = orgGradeMst;
	}
}
