package com.tcs.sgv.eis.valueobject;
// Generated Jul 18, 2007 5:37:48 PM by Hibernate Tools 3.1.0.beta5

import java.util.Date;

import com.tcs.sgv.allowance.valueobject.HrPayAllowTypeMst;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrPayEmpallowMpg generated by hbm2java
 */
public class HrPayEmpallowMpg implements java.io.Serializable {

	// Fields    

	private long allowCode;

	private HrEisEmpMst hrEisEmpMst;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByCreatedBy;

	private OrgUserMst orgUserMstByUpdatedBy;

	private HrPayAllowTypeMst hrPayAllowTypeMst;

	private double empAllowAmount;

	private long empCurrentStatus;

	private Date createdDate;

	private Date updatedDate;
	
	private Integer trnCounter;
	
	private long month;
	
	private long year;
	

	// Constructors

	/** default constructor */
	public HrPayEmpallowMpg() {
	}

	/** minimal constructor */
	public HrPayEmpallowMpg(long allowCode, HrEisEmpMst hrEisEmpMst) {
		this.allowCode = allowCode;
		this.hrEisEmpMst = hrEisEmpMst;
	}

	/** full constructor */
	public HrPayEmpallowMpg(long allowCode, HrEisEmpMst hrEisEmpMst,
			CmnDatabaseMst cmnDatabaseMst,
			OrgPostMst orgPostMstByUpdatedByPost,
			OrgPostMst orgPostMstByCreatedByPost,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByCreatedBy,
			OrgUserMst orgUserMstByUpdatedBy,
			HrPayAllowTypeMst hrPayAllowTypeMst, double empAllowAmount,
			long empCurrentStatus, Date createdDate, Date updatedDate,Integer trnCounter) {
		this.allowCode = allowCode;
		this.hrEisEmpMst = hrEisEmpMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.hrPayAllowTypeMst = hrPayAllowTypeMst;
		this.empAllowAmount = empAllowAmount;
		this.empCurrentStatus = empCurrentStatus;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.trnCounter = trnCounter;
	}

	// Property accessors
	public long getAllowCode() {
		return this.allowCode;
	}

	public void setAllowCode(long allowCode) {
		this.allowCode = allowCode;
	}

	public HrEisEmpMst getHrEisEmpMst() {
		return this.hrEisEmpMst;
	}

	public void setHrEisEmpMst(HrEisEmpMst hrEisEmpMst) {
		this.hrEisEmpMst = hrEisEmpMst;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return this.cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return this.orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(
			OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return this.orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(
			OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public CmnLocationMst getCmnLocationMst() {
		return this.cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return this.orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return this.orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public HrPayAllowTypeMst getHrPayAllowTypeMst() {
		return this.hrPayAllowTypeMst;
	}

	public void setHrPayAllowTypeMst(HrPayAllowTypeMst hrPayAllowTypeMst) {
		this.hrPayAllowTypeMst = hrPayAllowTypeMst;
	}

	public double getEmpAllowAmount() {
		return this.empAllowAmount;
	}

	public void setEmpAllowAmount(double empAllowAmount) {
		this.empAllowAmount = empAllowAmount;
	}

	public long getEmpCurrentStatus() {
		return this.empCurrentStatus;
	}

	public void setEmpCurrentStatus(long empCurrentStatus) {
		this.empCurrentStatus = empCurrentStatus;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Integer getTrnCounter() {
		return trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}

	public long getMonth() {
		return month;
	}

	public void setMonth(long month) {
		this.month = month;
	}

	public long getYear() {
		return year;
	}

	public void setYear(long year) {
		this.year = year;
	}

}
