package com.tcs.sgv.eis.valueobject;
// Generated Jun 30, 2009 11:53:29 AM by Hibernate Tools 3.2.0.beta8


import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

import com.tcs.sgv.dcps.valueobject.DdoOffice;;


/**
 * HrPayOfficepostMpg generated by hbm2java
 */
public class HrPayOfficepostMpg implements java.io.Serializable 
{

	// Fields    
	private long officePostId;
	private OrgPostMst orgPostMstByUpdatedByPost;
	private OrgPostMst orgPostMstByCreatedByPost;
	private OrgUserMst orgUserMstByUpdatedBy;
	private OrgUserMst orgUserMstByCreatedBy;
	
	private DdoOffice  ddoOffice;
	private OrgPostMst orgPostMstByPostId;
	
	private CmnLocationMst cmnLocationMst;
	private CmnDatabaseMst cmnDatabaseMst;
	
	
	
	private Date startDate;
	private Date endDate;
	private Date createdDate;
	private Date updatedDate;
	/**
	 * @return the officePostId
	 */
	public long getOfficePostId() {
		return officePostId;
	}
	/**
	 * @param officePostId the officePostId to set
	 */
	public void setOfficePostId(long officePostId) {
		this.officePostId = officePostId;
	}
	/**
	 * @return the orgPostMstByUpdatedByPost
	 */
	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}
	/**
	 * @param orgPostMstByUpdatedByPost the orgPostMstByUpdatedByPost to set
	 */
	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}
	/**
	 * @return the orgPostMstByCreatedByPost
	 */
	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}
	/**
	 * @param orgPostMstByCreatedByPost the orgPostMstByCreatedByPost to set
	 */
	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}
	/**
	 * @return the orgUserMstByUpdatedBy
	 */
	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}
	/**
	 * @param orgUserMstByUpdatedBy the orgUserMstByUpdatedBy to set
	 */
	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}
	/**
	 * @return the orgUserMstByCreatedBy
	 */
	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}
	/**
	 * @param orgUserMstByCreatedBy the orgUserMstByCreatedBy to set
	 */
	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}
	/**
	 * @return the ddoOffice
	 */
	public DdoOffice getDdoOffice() {
		return ddoOffice;
	}
	/**
	 * @param ddoOffice the ddoOffice to set
	 */
	public void setDdoOffice(DdoOffice ddoOffice) {
		this.ddoOffice = ddoOffice;
	}
	/**
	 * @return the orgPostMstByPostId
	 */
	public OrgPostMst getOrgPostMstByPostId() {
		return orgPostMstByPostId;
	}
	/**
	 * @param orgPostMstByPostId the orgPostMstByPostId to set
	 */
	public void setOrgPostMstByPostId(OrgPostMst orgPostMstByPostId) {
		this.orgPostMstByPostId = orgPostMstByPostId;
	}
	/**
	 * @return the cmnLocationMst
	 */
	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}
	/**
	 * @param cmnLocationMst the cmnLocationMst to set
	 */
	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}
	/**
	 * @return the cmnDatabaseMst
	 */
	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}
	/**
	 * @param cmnDatabaseMst the cmnDatabaseMst to set
	 */
	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}
	/**
	 * @return the startDate
	 */
	public Date getStartDate() {
		return startDate;
	}
	/**
	 * @param startDate the startDate to set
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	/**
	 * @return the endDate
	 */
	public Date getEndDate() {
		return endDate;
	}
	/**
	 * @param endDate the endDate to set
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	/**
	 * @return the createdDate
	 */
	public Date getCreatedDate() {
		return createdDate;
	}
	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	/**
	 * @return the updatedDate
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}
	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	


}

