// default package
// Generated Aug 25, 2007 12:43:11 PM by Hibernate Tools 3.2.0.beta8

package com.tcs.sgv.eis.valueobject;
import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnAttachmentMst;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrPayVpfDtlsHst generated by hbm2java
 */
public class HrPayVpfDtlsHst implements java.io.Serializable {

	// Fields    

	private HrPayVpfDtlsHstId id;

	//private long empId;

	private long vpfAmt;

	/*private long dbId;

	private long createdBy;

	private long createdByPost;*/

	private Date createdDate;

	/*private long updatedBy;

	private long updatedByPost;*/

	private Date updatedDate;
	
	private CmnDatabaseMst cmnDatabaseMst;
	private OrgPostMst orgPostMstByUpdatedByPost;
	private OrgPostMst orgPostMstByCreatedByPost;
	private CmnLocationMst cmnLocationMst;
	private OrgUserMst orgUserMstByCreatedBy;
	private OrgUserMst orgUserMstByUpdatedBy;
	private HrEisEmpMst hrEisEmpMst;
	private Integer zerovpfMonths;
	private CmnAttachmentMst cmnAttachmentMst;
	//private long locId;

	// Constructors


	/** default constructor */
	public HrPayVpfDtlsHst() {
	}

	/** minimal constructor */
	public HrPayVpfDtlsHst(HrPayVpfDtlsHstId id) {
		this.id = id;
	}

	/** full constructor */
	public HrPayVpfDtlsHst(HrPayVpfDtlsHstId id,long vpfAmt,Date createdDate,Date updatedDate,
			HrEisEmpMst hrEisEmpMst,CmnDatabaseMst cmnDatabaseMst,
			OrgPostMst orgPostMstByUpdatedByPost,
			OrgPostMst orgPostMstByCreatedByPost,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByCreatedBy,
			OrgUserMst orgUserMstByUpdatedBy,CmnAttachmentMst cmnAttachmentMst) {
		this.id = id;
		//this.empId = empId;
		this.vpfAmt = vpfAmt;
		/*this.dbId = dbId;
		this.createdBy = createdBy;
		this.createdByPost = createdByPost;*/
		this.createdDate = createdDate;
		/*this.updatedBy = updatedBy;
		this.updatedByPost = updatedByPost;*/
		this.updatedDate = updatedDate;
		//this.locId = locId;
		this.hrEisEmpMst = hrEisEmpMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.cmnAttachmentMst=cmnAttachmentMst;
	}

	// Property accessors
	public HrPayVpfDtlsHstId getId() {
		return this.id;
	}

	public void setId(HrPayVpfDtlsHstId id) {
		this.id = id;
	}

	/*public long getEmpId() {
		return this.empId;
	}

	public void setEmpId(long empId) {
		this.empId = empId;
	}*/

	public long getVpfAmt() {
		return this.vpfAmt;
	}

	public void setVpfAmt(long vpfAmt) {
		this.vpfAmt = vpfAmt;
	}

	/*public long getDbId() {
		return this.dbId;
	}

	public void setDbId(long dbId) {
		this.dbId = dbId;
	}

	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	public long getCreatedByPost() {
		return this.createdByPost;
	}

	public void setCreatedByPost(long createdByPost) {
		this.createdByPost = createdByPost;
	}*/

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/*public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public long getUpdatedByPost() {
		return this.updatedByPost;
	}

	public void setUpdatedByPost(long updatedByPost) {
		this.updatedByPost = updatedByPost;
	}*/

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public HrEisEmpMst getHrEisEmpMst() {
		return hrEisEmpMst;
	}

	public void setHrEisEmpMst(HrEisEmpMst hrEisEmpMst) {
		this.hrEisEmpMst = hrEisEmpMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public Integer getZerovpfMonths() {
		return zerovpfMonths;
	}

	public void setZerovpfMonths(Integer zerovpfMonths) {
		this.zerovpfMonths = zerovpfMonths;
	}
	
	public CmnAttachmentMst getCmnAttachmentMst() {
		return cmnAttachmentMst;
	}

	public void setCmnAttachmentMst(CmnAttachmentMst cmnAttachmentMst) {
		this.cmnAttachmentMst = cmnAttachmentMst;
	}

	/*public long getLocId() {
		return this.locId;
	}

	public void setLocId(long locId) {
		this.locId = locId;
	}*/
	
	

}
