// default package
// Generated Aug 4, 2007 11:58:13 AM by Hibernate Tools 3.1.0.beta5
package com.tcs.sgv.eis.valueobject;


import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnAttachmentMst;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrPayVpfDtls generated by hbm2java
 */
public class HrPayVpfDtls implements java.io.Serializable {

	// Fields    

	private long payVpfId;
	private HrEisEmpMst hrEisEmpMst;
	private long vpfAmt;
	private String currencyvpfAmt;
	private CmnDatabaseMst cmnDatabaseMst;
	private OrgPostMst orgPostMstByUpdatedByPost;
	private OrgPostMst orgPostMstByCreatedByPost;
	private CmnLocationMst cmnLocationMst;
	private OrgUserMst orgUserMstByCreatedBy;
	private OrgUserMst orgUserMstByUpdatedBy;
	private Date createdDate;
	private Date updatedDate;
	private Integer trnCounter;
	private Integer zerovpfMonths;
	private CmnAttachmentMst cmnAttachmentMst;
	// Constructors

	/** default constructor */
	public HrPayVpfDtls() {
	}

	/** minimal constructor */
	public HrPayVpfDtls(long payVpfId) {
		this.payVpfId = payVpfId;
	}

	/** full constructor */
	public HrPayVpfDtls(long payVpfId, HrEisEmpMst hrEisEmpMst,
			long vpfAmt, CmnDatabaseMst cmnDatabaseMst,
			OrgPostMst orgPostMstByUpdatedByPost,
			OrgPostMst orgPostMstByCreatedByPost,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByCreatedBy,
			OrgUserMst orgUserMstByUpdatedBy,Date createdDate, Date updatedDate,Integer trnCounter,CmnAttachmentMst cmnAttachmentMst) {
		this.payVpfId = payVpfId;
		this.hrEisEmpMst = hrEisEmpMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.trnCounter = trnCounter;
		this.cmnAttachmentMst=cmnAttachmentMst;
	}

	

	// Property accessors
	public long getPayVpfId() {
		return this.payVpfId;
	}
	public void setPayVpfId(long payVpfId) {
		this.payVpfId = payVpfId;
	}	
	public long getVpfAmt() {
		return this.vpfAmt;
	}
	public void setVpfAmt(long vpfAmt) {
		this.vpfAmt = vpfAmt;
	}	
	public Date getCreatedDate() {
		return this.createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Date getUpdatedDate() {
		return this.updatedDate;
	}
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}
	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}
	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}
	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}
	public HrEisEmpMst getHrEisEmpMst() {
		return hrEisEmpMst;
	}
	public void setHrEisEmpMst(HrEisEmpMst hrEisEmpMst) {
		this.hrEisEmpMst = hrEisEmpMst;
	}
	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}
	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}
	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}
	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}
	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}
	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}
	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}
	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public Integer getTrnCounter() {
		return trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}

	public Integer getZerovpfMonths() {
		return zerovpfMonths;
	}

	public void setZerovpfMonths(Integer zerovpfMonths) {
		this.zerovpfMonths = zerovpfMonths;
	}
	public CmnAttachmentMst getCmnAttachmentMst() {
		return cmnAttachmentMst;
	}

	public void setCmnAttachmentMst(CmnAttachmentMst cmnAttachmentMst) {
		this.cmnAttachmentMst = cmnAttachmentMst;
	}

	public String getCurrencyvpfAmt() {
		return currencyvpfAmt;
	}

	public void setCurrencyvpfAmt(String currencyvpfAmt) {
		this.currencyvpfAmt = currencyvpfAmt;
	}

}
