package com.tcs.sgv.eis.valueobject;

// default package
// Generated Oct 9, 2007 12:43:12 PM by Hibernate Tools 3.2.0.beta8


import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrPayOrderMst generated by hbm2java
 */
public class HrPayOrderMst implements java.io.Serializable {

	// Fields    

	private long orderId;

	private String orderName;

	private Date orderDate;
	
	private Date endDate;	// End Date of the Order.
	
	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;

	private Date createdDate;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private Date updatedDate;
	
	private Integer trnCounter;
	
	private String locationCode;
	
	private CmnLanguageMst cmnLanguageMst;

	private long attachment_Id;
	private long grtype;
	
	// Constructors

	
	/** default constructor */
	public HrPayOrderMst() {
	}

	

	public long getGrtype()
	{
		return grtype;
	}



	public void setGrtype(long grtype)
	{
		this.grtype = grtype;
	}



	/** minimal constructor */
	public HrPayOrderMst(long orderId) {
		this.orderId = orderId;
	}

	/** full constructor */
	public HrPayOrderMst(long orderId, String orderName, Date orderDate,Date endDate,
			OrgUserMst orgUserMstByCreatedBy , OrgPostMst orgPostMstByCreatedByPost, Date createdDate,
			OrgUserMst orgUserMstByUpdatedBy, OrgPostMst orgPostMstByUpdatedByPost , Date updatedDate , Integer trnCounter,String locationCode,CmnLanguageMst cmnLanguageMst) {
		this.orderId = orderId;
		this.orderName = orderName;
		this.orderDate = orderDate;
		this.endDate = endDate;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.createdDate = createdDate;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.updatedDate = updatedDate;
		this.trnCounter = trnCounter;
		this.cmnLanguageMst = cmnLanguageMst;
		this.locationCode=locationCode;
	}

	// Property accessors
	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	public String getOrderName() {
		return this.orderName;
	}

	public void setOrderName(String orderName) {
		this.orderName = orderName;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	

	public void setOrgPostMstByUpdatedByPost(
			OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}
	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return this.orgPostMstByUpdatedByPost;
	}
	
	

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}
	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return this.orgUserMstByUpdatedBy;
	}
	
	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}
	
	public OrgUserMst getOrgUserMstByCreatedBy() {
		return this.orgUserMstByCreatedBy;
	}

	
	public void setOrgPostMstByCreatedByPost(
			OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}
	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return this.orgPostMstByCreatedByPost;
	}
	
	public Integer getTrnCounter() {
		return trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public String getLocationCode() {
		return locationCode;
	}

	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}

	public long getAttachment_Id() {
		return attachment_Id;
	}

	public void setAttachment_Id(long attachment_Id) {
		this.attachment_Id = attachment_Id;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
