package com.tcs.sgv.eis.valueobject;
// Generated Aug 13, 2007 3:20:54 PM by Hibernate Tools 3.1.0.beta5


import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrPayPaybill generated by hbm2java
 */
public class HrPayPaybill implements java.io.Serializable {

	// Fields    


	
	private long id;

	private String empLname;
	private String accNo;

	public String getAccNo() {
		return accNo;
	}

	public void setAccNo(String accNo) {
		this.accNo = accNo;
	}
	
	public String getEmpLname()
	{
		return empLname;
	}

	public void setEmpLname(String empLname)
	{
		this.empLname = empLname;
	}
	
	private long scaleId;

	public long getScaleId()
	{
		return scaleId;
	}

	public void setScaleId(long scaleId)
	{
		this.scaleId = scaleId;
	}

	/*private double deduc5050;
	public double getDeduc5050() {
		return deduc5050;
	}

	public void setDeduc5050(double deduc5050) {
		this.deduc5050 = deduc5050;
	}

	public double getDeduc5051() {
		return deduc5051;
	}

	public void setDeduc5051(double deduc5051) {
		this.deduc5051 = deduc5051;
	}

	public double getDeduc5052() {
		return deduc5052;
	}

	public void setDeduc5052(double deduc5052) {
		this.deduc5052 = deduc5052;
	}

	public double getDeduc5053() {
		return deduc5053;
	}

	public void setDeduc5053(double deduc5053) {
		this.deduc5053 = deduc5053;
	}

	public double getDeduc5054() {
		return deduc5054;
	}

	public void setDeduc5054(double deduc5054) {
		this.deduc5054 = deduc5054;
	}

	public double getDeduc5055() {
		return deduc5055;
	}

	public void setDeduc5055(double deduc5055) {
		this.deduc5055 = deduc5055;
	}

	public double getDeduc5056() {
		return deduc5056;
	}

	public void setDeduc5056(double deduc5056) {
		this.deduc5056 = deduc5056;
	}

	public double getDeduc5057() {
		return deduc5057;
	}

	public void setDeduc5057(double deduc5057) {
		this.deduc5057 = deduc5057;
	}

	public double getDeduc5058() {
		return deduc5058;
	}

	public void setDeduc5058(double deduc5058) {
		this.deduc5058 = deduc5058;
	}

	public double getDeduc5059() {
		return deduc5059;
	}

	public void setDeduc5059(double deduc5059) {
		this.deduc5059 = deduc5059;
	}
*/
	private double deduc9134;
	private double deduc5051;
	private double deduc5052;
	private double deduc5053;
	private double deduc5054;
	private double deduc5055;
	private double deduc5056;
	private double deduc5057;
	private double deduc5058;
	private double deduc5059;	
	private double allow1179;
	private double allow1185;
	private double allow9184;
	private double deduc9135;  /// Revenue stamp 
	
	public double getDeduc9135() {
		return deduc9135;
	}
	public void setDeduc9135(double deduc9135) {
		this.deduc9135 = deduc9135;
	}
	public double getDeduc9134() {
		return deduc9134;
	}

	public void setDeduc9134(double deduc9134) {
		this.deduc9134 = deduc9134;
	}
	
	public double getAllow9184() {
		return allow9184;
	}

	public void setAllow9184(double allow9184) {
		this.allow9184 = allow9184;
	}

	public double getAllow1185() {
		return allow1185;
	}

	public void setAllow1185(double allow1185) {
		this.allow1185 = allow1185;
	}

	public double getAllow1179()
	{
		return allow1179;
	}

	public void setAllow1179(double allow1179)
	{
		this.allow1179 = allow1179;
	}

	private HrEisEmpMst hrEisEmpMst;

	private long psrNo;		// PSR NO.
	private double month;

	private double year;

	private double allow0101;//personal pay
	private double allow0102;//special pay

	private double basic0101;//pay of officer
	private double basic0102;//pay of establishment

	//private double ls;
//	private double le;
	
	private double allow1159;
	private double allow1160;
	
	/**
	 * @return the allow1159
	 */
	public double getAllow1159() {
		return allow1159;
	}

	/**
	 * @param allow1159 the allow1159 to set
	 */
	public void setAllow1159(double allow1159) {
		this.allow1159 = allow1159;
	}

	/**
	 * @return the allow1160
	 */
	public double getAllow1160() {
		return allow1160;
	}

	/**
	 * @param allow1160 the allow1160 to set
	 */
	public void setAllow1160(double allow1160) {
		this.allow1160 = allow1160;
	}

	private double allow0119;//DP
	private double allow0120;//DP_GAZZETED
	private double allow0103;//DA
	private double allow0110;//HRA
	private double allow0105;//ltc
	private double allow0111;//CLA
	private double allow0104;//other allowance
	private double allow0107;//MA
	private double allow0108;//bonus
	private double allow1301;//WA
//	private double allow5006;//other charges
	private double allow0113;//TrA
	
	
	//added by Ankit - Maha Payroll
	private double allow1003; //Technical Allowance
	//ended
	//added by Amish -15th OCT Maha Payrolls
	private double allow1161;//Refreshment Allowance
	//ended

	private double adv5701;//Fes.Adv
	private double adv5801;//Food Adv
	
	//private double adv7057;//Fes.Adv
	//private double adv7058;//Food Adv
	
	private double deduc0101;//PayRecovery
	
	private double deduc9999; //DA in GPF
	private double deduc9998; //DA in GPF-IV
	
	private double grossAmt;
	//private double slo;
	private double it;
	private double surcharge;
	
	private double deduc9510;//IT
	private double deduc9550;//HRR
	private double deduc9560;//rent building
	//private double deduc9530;//PLI
//	private double deduc9540;//bli
	private double deduc9570;//PT
	//private double deduc9580;//SIS_GIS
	//private double deduc9581;//SisIF
	//private double deduc9582;//SisSF
	private double deduc9583;//AISIF
	//private double deduc9584;//AisSF
	private double deduc9670;//PF
	
	
	private double allow1147;
	private double allow1148;
	private double allow1149;
	private double allow1150;
	private double allow1151;
	private double allow1152;
	private double allow1153;
	private double allow1154;
	private double allow1155;
	private double allow1156;
	private double allow1157;
	private double allow1158;
	
	
	/**
	 * @return the deduc9670
	 */
	public double getDeduc9670() {
		return deduc9670;
	}

	/**
	 * @param deduc9670 the deduc9670 to set
	 */
	public void setDeduc9670(double deduc9670) {
		this.deduc9670 = deduc9670;
	}

	private double adv9670;//GPF advance

	//private double loan9592;//carSctMopedAdv;
	//private double loanInt9592;//carSctMopedInt;

	//private double loan9740;//ocaCycleAdv;
	//private double loanInt9740;//ocaCycleInt;

	private double loan9591;//hbaHb;
	//private double loanInt9591;//hbaInt;

	private double loan9720;//fanA;
	//private double loanInt9720;//fanInt
	
	private double deduc9780;//jeepR;
	private double deduc9910;//Misc recovery
	private double deduc9911; // JanJulGIS

	private double gpay0101;//Grade Pay
	
	//private double gpfIv;
	private double deduc9531;

	private double totalDed;

	private double netTotal;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByCreatedBy;

	private Date createdDate;	
	
	private Integer trnCounter;
	
	//Added by Paurav for identifying Paybill entries generated at same time
	private long paybillGrpId;
	//Ended By Paurav
	
	private double advIV9670;
	
	private OrgPostMst orgPostMst;
	
	//private long approveFlag;
	
	private Date approveRejectDate;
	
	private double deduc9534;	// CPF
	
	//private double deduc9620; // AIS PF
	
	private double deduc9535;//DCPS Delay
	private double deduc9536;//DCPS Pay
	private double deduc9537;//DCPS DA
	
	private double allow1006;
	private double allow1007;// arm 
	private double allow1008;//BMI
	private double allow1009;//cash
	private double allow1010;//CID
	private double allow1011;//conveyance
	
	
	

	private double allow1012;//emergency
	private double allow1013;//esis
	private double allow1014;//extra lecture
	
	private double allow1015;//fitness
	private double allow1016;//awards
	private double allow1017;//kit maintenance
	
	private double allow1018;//lisence
	private double allow1019;//mechanical
	private double allow1020;//medical education
	private double allow1021;//mess
	
	private double allow1022;//naxel
	private double allow1023;//non practicing
	private double allow1024;//sumptuary
	private double allow1025;//project
	private double allow1026;//special duty
	private double allow1027;//additional pay
	private double allow1028;//uniform
	
	
	private double allow1029;//PG
	private double allow1030;//family palnning
	private double allow1031;//hilly allowance
	private double allow1032;//tribal area allowance
	private double allow1033;//ats30
	private double allow1034;//ats50
	private double allow1035;//force25
	private double allow1036;//force100
	
	private double allow9912;//Central TA
	private double allow9913;//Central DA
	private double allow1163;//Peon Allowance 
	
	//Allowance configured in March End at GO Live
	
	public double getAllow1177() {
		return allow1177;
	}

	public void setAllow1177(double allow1177) {
		this.allow1177 = allow1177;
	}

	public double getAllow1176() {
		return allow1176;
	}

	public void setAllow1176(double allow1176) {
		this.allow1176 = allow1176;
	}

	public double getAllow1175() {
		return allow1175;
	}

	public void setAllow1175(double allow1175) {
		this.allow1175 = allow1175;
	}

	public double getAllow1174() {
		return allow1174;
	}

	public void setAllow1174(double allow1174) {
		this.allow1174 = allow1174;
	}

	public double getAllow1173() {
		return allow1173;
	}

	public void setAllow1173(double allow1173) {
		this.allow1173 = allow1173;
	}

	public double getAllow1172() {
		return allow1172;
	}

	public void setAllow1172(double allow1172) {
		this.allow1172 = allow1172;
	}

	public double getAllow1171() {
		return allow1171;
	}

	public void setAllow1171(double allow1171) {
		this.allow1171 = allow1171;
	}

	public double getAllow1170() {
		return allow1170;
	}

	public void setAllow1170(double allow1170) {
		this.allow1170 = allow1170;
	}

	public double getAllow1169() {
		return allow1169;
	}

	public void setAllow1169(double allow1169) {
		this.allow1169 = allow1169;
	}

	public double getAllow1168() {
		return allow1168;
	}

	public void setAllow1168(double allow1168) {
		this.allow1168 = allow1168;
	}

	public double getAllow1167() {
		return allow1167;
	}

	public void setAllow1167(double allow1167) {
		this.allow1167 = allow1167;
	}

	public double getAllow1166() {
		return allow1166;
	}

	public void setAllow1166(double allow1166) {
		this.allow1166 = allow1166;
	}

	public double getAllow1165() {
		return allow1165;
	}

	public void setAllow1165(double allow1165) {
		this.allow1165 = allow1165;
	}
	private double allow9186;
	private double allow1177;//CPF
	private double allow1176; //SPECIAL_PAY_PILOT
	private double allow1175; //MILITERY_PILOT
	private double allow1174; //OUTFIT_PILOT
	private double allow1173; //FLYING_ALLOW_PILOT
	private double allow1172; //INSPECTION_PILOT
	private double allow1171; //QUALIFICATION_PILOT
	private double allow1170; //INSTRUCTIONAL_PILOT
	private double allow1169; //FLYING_PAY_PILOT
	private double allow1168; //KIT_PILOT
	private double allow1167; //CHPL_PILOT
	private double allow1166; //RT_PILOT
	private double allow1165; //INCENTIVE_BDDS
	private double allow1178;//basic arr
	//Allowace Ends
//	private double deduc9914;//GIS Arrear
	
	
	
	public double getAllow1178()
	{
		return allow1178;
	}

	public void setAllow1178(double allow1178)
	{
		this.allow1178 = allow1178;
	}

	/**
	 * @return the allow1163
	 */
	public double getAllow1163() {
		return allow1163;
	}

	/**
	 * @param allow1163 the allow1163 to set
	 */
	public void setAllow1163(double allow1163) {
		this.allow1163 = allow1163;
	}

	
	public double getAllow9186() {
		return allow9186;
	}

	public void setAllow9186(double allow9186) {
		this.allow9186 = allow9186;
	}

	/*
	*//**
	 * @return the deduc9914
	 *//*
	public double getDeduc9914() {
		return deduc9914;
	}

	*//**
	 * @param deduc9914 the deduc9914 to set
	 *//*
	public void setDeduc9914(double deduc9914) {
		this.deduc9914 = deduc9914;
	}
*/
	/**
	 * @return the allow9912
	 */
	public double getAllow9912() {
		return allow9912;
	}

	/**
	 * @param allow9912 the allow9912 to set
	 */
	public void setAllow9912(double allow9912) {
		this.allow9912 = allow9912;
	}

	
	/**
	 * @return the allow9913
	 */
	public double getAllow9913() {
		return allow9913;
	}

	/**
	 * @param allow9913 the allow9913 to set
	 */
	public void setAllow9913(double allow9913) {
		this.allow9913 = allow9913;
	}

	private double deduc1037;
	private double deduc1038;
	private double deduc1039;
	private double deduc1040;
	private double deduc1041;
	private double deduc1042;
	 ///MSLI
	
	
	private double deduc9701;
	private double deduc9702;
	private double deduc9703;
	private double deduc9704;
	private double deduc9705;
	private double deduc9706;
	private double deduc9707;
	private double deduc9708;
	private double deduc9709;
	private double deduc9710;
	private double deduc9711;
	private double deduc9712;
	private double deduc9713;
	
	// for NPS employer deduction
	private double deduc9142;
	
	

	/**
	 * @return the adv5060
	 */
	public double getAdv5060() {
		return adv5060;
	}

	/**
	 * @param adv5060 the adv5060 to set
	 */
	public void setAdv5060(double adv5060) {
		this.adv5060 = adv5060;
	}

	/**
	 * @return the loan5061
	 */
	
	private double adv5060;
	
	
	private double loan5051;
	private double loanInt5051;
	private double loan5056;
	private double loanInt5056;
	private double loan5057;
	private double loanInt5057;
	private double loan5058;
	private double loanInt5058;
	/**
	 * @return the loan5051
	 */
	public double getLoan5051() {
		return loan5051;
	}

	/**
	 * @param loan5051 the loan5051 to set
	 */
	public void setLoan5051(double loan5051) {
		this.loan5051 = loan5051;
	}

	/**
	 * @return the loanInt5051
	 */
	public double getLoanInt5051() {
		return loanInt5051;
	}

	/**
	 * @param loanInt5051 the loanInt5051 to set
	 */
	public void setLoanInt5051(double loanInt5051) {
		this.loanInt5051 = loanInt5051;
	}

	/**
	 * @return the loan5056
	 */
	public double getLoan5056() {
		return loan5056;
	}

	/**
	 * @param loan5056 the loan5056 to set
	 */
	public void setLoan5056(double loan5056) {
		this.loan5056 = loan5056;
	}

	/**
	 * @return the loanInt5056
	 */
	public double getLoanInt5056() {
		return loanInt5056;
	}

	/**
	 * @param loanInt5056 the loanInt5056 to set
	 */
	public void setLoanInt5056(double loanInt5056) {
		this.loanInt5056 = loanInt5056;
	}

	/**
	 * @return the loan5057
	 */
	public double getLoan5057() {
		return loan5057;
	}

	/**
	 * @param loan5057 the loan5057 to set
	 */
	public void setLoan5057(double loan5057) {
		this.loan5057 = loan5057;
	}

	/**
	 * @return the loanInt5057
	 */
	public double getLoanInt5057() {
		return loanInt5057;
	}

	/**
	 * @param loanInt5057 the loanInt5057 to set
	 */
	public void setLoanInt5057(double loanInt5057) {
		this.loanInt5057 = loanInt5057;
	}

	/**
	 * @return the loan5058
	 */
	public double getLoan5058() {
		return loan5058;
	}

	/**
	 * @param loan5058 the loan5058 to set
	 */
	public void setLoan5058(double loan5058) {
		this.loan5058 = loan5058;
	}

	/**
	 * @return the loanInt5058
	 */
	public double getLoanInt5058() {
		return loanInt5058;
	}

	/**
	 * @param loanInt5058 the loanInt5058 to set
	 */
	public void setLoanInt5058(double loanInt5058) {
		this.loanInt5058 = loanInt5058;
	}

	/**
	 * @return the loan5060
	 */
	public double getLoan5060() {
		return loan5060;
	}

	/**
	 * @param loan5060 the loan5060 to set
	 */
	public void setLoan5060(double loan5060) {
		this.loan5060 = loan5060;
	}

	/**
	 * @return the loanInt5060
	 */
	public double getLoanInt5060() {
		return loanInt5060;
	}

	/**
	 * @param loanInt5060 the loanInt5060 to set
	 */
	public void setLoanInt5060(double loanInt5060) {
		this.loanInt5060 = loanInt5060;
	}

	/**
	 * @return the loan5061
	 */
	public double getLoan5061() {
		return loan5061;
	}

	/**
	 * @param loan5061 the loan5061 to set
	 */
	public void setLoan5061(double loan5061) {
		this.loan5061 = loan5061;
	}

	/**
	 * @return the loanInt5061
	 */
	public double getLoanInt5061() {
		return loanInt5061;
	}

	/**
	 * @param loanInt5061 the loanInt5061 to set
	 */
	public void setLoanInt5061(double loanInt5061) {
		this.loanInt5061 = loanInt5061;
	}

	/**
	 * @return the loan5064
	 */
	public double getLoan5064() {
		return loan5064;
	}

	/**
	 * @param loan5064 the loan5064 to set
	 */
	public void setLoan5064(double loan5064) {
		this.loan5064 = loan5064;
	}

	/**
	 * @return the loanInt5064
	 */
	public double getLoanInt5064() {
		return loanInt5064;
	}

	/**
	 * @param loanInt5064 the loanInt5064 to set
	 */
	public void setLoanInt5064(double loanInt5064) {
		this.loanInt5064 = loanInt5064;
	}

	/**
	 * @return the loan5065
	 */
	public double getLoan5065() {
		return loan5065;
	}

	/**
	 * @param loan5065 the loan5065 to set
	 */
	public void setLoan5065(double loan5065) {
		this.loan5065 = loan5065;
	}

	/**
	 * @return the loanInt5065
	 */
	public double getLoanInt5065() {
		return loanInt5065;
	}

	/**
	 * @param loanInt5065 the loanInt5065 to set
	 */
	public void setLoanInt5065(double loanInt5065) {
		this.loanInt5065 = loanInt5065;
	}

	/**
	 * @return the loan5066
	 */
	public double getLoan5066() {
		return loan5066;
	}

	/**
	 * @param loan5066 the loan5066 to set
	 */
	public void setLoan5066(double loan5066) {
		this.loan5066 = loan5066;
	}

	/**
	 * @return the loanInt5066
	 */
	public double getLoanInt5066() {
		return loanInt5066;
	}

	/**
	 * @param loanInt5066 the loanInt5066 to set
	 */
	public void setLoanInt5066(double loanInt5066) {
		this.loanInt5066 = loanInt5066;
	}

	/**
	 * @return the loan5067
	 */
	public double getLoan5067() {
		return loan5067;
	}

	/**
	 * @param loan5067 the loan5067 to set
	 */
	public void setLoan5067(double loan5067) {
		this.loan5067 = loan5067;
	}

	/**
	 * @return the loanInt5067
	 */
	public double getLoanInt5067() {
		return loanInt5067;
	}

	/**
	 * @param loanInt5067 the loanInt5067 to set
	 */
	public void setLoanInt5067(double loanInt5067) {
		this.loanInt5067 = loanInt5067;
	}

	/**
	 * @return the adv5052
	 */
	public double getAdv5052() {
		return adv5052;
	}

	/**
	 * @param adv5052 the adv5052 to set
	 */
	public void setAdv5052(double adv5052) {
		this.adv5052 = adv5052;
	}

	/**
	 * @return the adv5053
	 */
	public double getAdv5053() {
		return adv5053;
	}

	/**
	 * @param adv5053 the adv5053 to set
	 */
	public void setAdv5053(double adv5053) {
		this.adv5053 = adv5053;
	}

	/**
	 * @return the adv5054
	 */
	public double getAdv5054() {
		return adv5054;
	}

	/**
	 * @param adv5054 the adv5054 to set
	 */
	public void setAdv5054(double adv5054) {
		this.adv5054 = adv5054;
	}

	/**
	 * @return the adv5055
	 */
	public double getAdv5055() {
		return adv5055;
	}

	/**
	 * @param adv5055 the adv5055 to set
	 */
	public void setAdv5055(double adv5055) {
		this.adv5055 = adv5055;
	}

	/**
	 * @return the adv5059
	 */
	public double getAdv5059() {
		return adv5059;
	}

	/**
	 * @param adv5059 the adv5059 to set
	 */
	public void setAdv5059(double adv5059) {
		this.adv5059 = adv5059;
	}

	/**
	 * @return the adv5062
	 */
	public double getAdv5062() {
		return adv5062;
	}

	/**
	 * @param adv5062 the adv5062 to set
	 */
	public void setAdv5062(double adv5062) {
		this.adv5062 = adv5062;
	}

	/**
	 * @return the adv5063
	 */
	public double getAdv5063() {
		return adv5063;
	}

	/**
	 * @param adv5063 the adv5063 to set
	 */
	public void setAdv5063(double adv5063) {
		this.adv5063 = adv5063;
	}

	/**
	 * @return the adv5068
	 */
	public double getAdv5068() {
		return adv5068;
	}

	/**
	 * @param adv5068 the adv5068 to set
	 */
	public void setAdv5068(double adv5068) {
		this.adv5068 = adv5068;
	}

	private double loan5060;
	private double loanInt5060;
	private double loan5061;
	private double loanInt5061;
	private double loan5064;
	private double loanInt5064;
	private double loan5065;
	private double loanInt5065;
	private double loan5066;
	private double loanInt5066;
	private double loan5067;
	private double loanInt5067;
	
	private double adv5052;
	private double adv5053;
	private double adv5054;
	private double adv5055;
	private double adv5059;
	private double adv5062;
	private double adv5063;
	private double adv5068;
	
	
	
	
	
	
	public double getDeduc1037() {
		return deduc1037;
	}

	public void setDeduc1037(double deduc1037) {
		this.deduc1037 = deduc1037;
	}

	public double getDeduc1038() {
		return deduc1038;
	}

	public void setDeduc1038(double deduc1038) {
		this.deduc1038 = deduc1038;
	}

	public double getDeduc1039() {
		return deduc1039;
	}

	public void setDeduc1039(double deduc1039) {
		this.deduc1039 = deduc1039;
	}

	public double getDeduc1040() {
		return deduc1040;
	}

	public void setDeduc1040(double deduc1040) {
		this.deduc1040 = deduc1040;
	}

	public double getDeduc1041() {
		return deduc1041;
	}

	public void setDeduc1041(double deduc1041) {
		this.deduc1041 = deduc1041;
	}

	public double getDeduc1042() {
		return deduc1042;
	}

	public void setDeduc1042(double deduc1042) {
		this.deduc1042 = deduc1042;
	}

	public double getDeduc9709() {
		return deduc9709;
	}

	public void setDeduc9709(double deduc9709) {
		this.deduc9709 = deduc9709;
	}


	/**
	 * @return the allow1012
	 */
	public double getAllow1012() {
		return allow1012;
	}

	/**
	 * @param allow1012 the allow1012 to set
	 */
	public void setAllow1012(double allow1012) {
		this.allow1012 = allow1012;
	}

	/**
	 * @return the allow1013
	 */
	public double getAllow1013() {
		return allow1013;
	}

	/**
	 * @param allow1013 the allow1013 to set
	 */
	public void setAllow1013(double allow1013) {
		this.allow1013 = allow1013;
	}

	/**
	 * @return the allow1014
	 */
	public double getAllow1014() {
		return allow1014;
	}

	/**
	 * @param allow1014 the allow1014 to set
	 */
	public void setAllow1014(double allow1014) {
		this.allow1014 = allow1014;
	}

	/**
	 * @return the allow1015
	 */
	public double getAllow1015() {
		return allow1015;
	}

	/**
	 * @param allow1015 the allow1015 to set
	 */
	public void setAllow1015(double allow1015) {
		this.allow1015 = allow1015;
	}

	/**
	 * @return the allow1016
	 */
	public double getAllow1016() {
		return allow1016;
	}

	/**
	 * @param allow1016 the allow1016 to set
	 */
	public void setAllow1016(double allow1016) {
		this.allow1016 = allow1016;
	}

	/**
	 * @return the allow1017
	 */
	public double getAllow1017() {
		return allow1017;
	}

	/**
	 * @param allow1017 the allow1017 to set
	 */
	public void setAllow1017(double allow1017) {
		this.allow1017 = allow1017;
	}

	/**
	 * @return the allow1018
	 */
	public double getAllow1018() {
		return allow1018;
	}

	/**
	 * @param allow1018 the allow1018 to set
	 */
	public void setAllow1018(double allow1018) {
		this.allow1018 = allow1018;
	}

	/**
	 * @return the allow1019
	 */
	public double getAllow1019() {
		return allow1019;
	}

	/**
	 * @param allow1019 the allow1019 to set
	 */
	public void setAllow1019(double allow1019) {
		this.allow1019 = allow1019;
	}

	/**
	 * @return the allow1020
	 */
	public double getAllow1020() {
		return allow1020;
	}

	/**
	 * @param allow1020 the allow1020 to set
	 */
	public void setAllow1020(double allow1020) {
		this.allow1020 = allow1020;
	}

	/**
	 * @return the allow1021
	 */
	public double getAllow1021() {
		return allow1021;
	}

	/**
	 * @param allow1021 the allow1021 to set
	 */
	public void setAllow1021(double allow1021) {
		this.allow1021 = allow1021;
	}

	/**
	 * @return the allow1022
	 */
	public double getAllow1022() {
		return allow1022;
	}

	/**
	 * @param allow1022 the allow1022 to set
	 */
	public void setAllow1022(double allow1022) {
		this.allow1022 = allow1022;
	}

	/**
	 * @return the allow1023
	 */
	public double getAllow1023() {
		return allow1023;
	}

	/**
	 * @param allow1023 the allow1023 to set
	 */
	public void setAllow1023(double allow1023) {
		this.allow1023 = allow1023;
	}

	/**
	 * @return the allow1024
	 */
	public double getAllow1024() {
		return allow1024;
	}

	/**
	 * @param allow1024 the allow1024 to set
	 */
	public void setAllow1024(double allow1024) {
		this.allow1024 = allow1024;
	}

	/**
	 * @return the allow1025
	 */
	public double getAllow1025() {
		return allow1025;
	}

	/**
	 * @param allow1025 the allow1025 to set
	 */
	public void setAllow1025(double allow1025) {
		this.allow1025 = allow1025;
	}

	/**
	 * @return the allow1026
	 */
	public double getAllow1026() {
		return allow1026;
	}

	/**
	 * @param allow1026 the allow1026 to set
	 */
	public void setAllow1026(double allow1026) {
		this.allow1026 = allow1026;
	}

	/**
	 * @return the allow1027
	 */
	public double getAllow1027() {
		return allow1027;
	}

	/**
	 * @param allow1027 the allow1027 to set
	 */
	public void setAllow1027(double allow1027) {
		this.allow1027 = allow1027;
	}

	/**
	 * @return the allow1028
	 */
	public double getAllow1028() {
		return allow1028;
	}

	/**
	 * @param allow1028 the allow1028 to set
	 */
	public void setAllow1028(double allow1028) {
		this.allow1028 = allow1028;
	}

	
	/**
	 * @return the allow1007
	 */
	public double getAllow1007() {
		return allow1007;
	}

	/**
	 * @param allow1007 the allow1007 to set
	 */
	public void setAllow1007(double allow1007) {
		this.allow1007 = allow1007;
	}

	/**
	 * @return the allow1008
	 */
	public double getAllow1008() {
		return allow1008;
	}

	/**
	 * @param allow1008 the allow1008 to set
	 */
	public void setAllow1008(double allow1008) {
		this.allow1008 = allow1008;
	}

	/**
	 * @return the allow1009
	 */
	public double getAllow1009() {
		return allow1009;
	}

	/**
	 * @param allow1009 the allow1009 to set
	 */
	public void setAllow1009(double allow1009) {
		this.allow1009 = allow1009;
	}

	/**
	 * @return the allow1010
	 */
	public double getAllow1010() {
		return allow1010;
	}

	/**
	 * @param allow1010 the allow1010 to set
	 */
	public void setAllow1010(double allow1010) {
		this.allow1010 = allow1010;
	}

	/**
	 * @return the allow1011
	 */
	public double getAllow1011() {
		return allow1011;
	}

	/**
	 * @param allow1011 the allow1011 to set
	 */
	public void setAllow1011(double allow1011) {
		this.allow1011 = allow1011;
	}

	
	 /**
	 * @return the allow1006
	 */
	public double getAllow1006() {
		return allow1006;
	}

	/**
	 * @param allow1006 the allow1006 to set
	 */
	public void setAllow1006(double allow1006) {
		this.allow1006 = allow1006;
	}

	/**
	 * @return the allow1161
	 */
	public double getAllow1161() {
		return allow1161;
	}

	/**
	 * @param allow1161 the allow1161 to set
	 */
	public void setAllow1161(double allow1161) {
		this.allow1161 = allow1161;
	}

	private double deduc1004;//Central gis
	 /**
	 * @return the deduc1004
	 */
	public double getDeduc1004() {
		return deduc1004;
	}

	/**
	 * @param deduc1004 the deduc1004 to set
	 */
	public void setDeduc1004(double deduc1004) {
		this.deduc1004 = deduc1004;
	}

	private double deduc1005;//gis
   /**
	 * @return the deduc1005
	 */
	public double getDeduc1005() {
		return deduc1005;
	}

	/**
	 * @param deduc1005 the deduc1005 to set
	 */
	public void setDeduc1005(double deduc1005) {
		this.deduc1005 = deduc1005;
	}

	 private double deduc1002;//gis(ifs)
	   
	   
		
		public double getDeduc1002() {
		return deduc1002;
	}

	public void setDeduc1002(double deduc1002) {
		this.deduc1002 = deduc1002;
	}
	
	private double deduc1000;//gis(ips)
	
	public double getDeduc1000() {
		return deduc1000;
	}

	public void setDeduc1000(double deduc1000) {
		this.deduc1000 = deduc1000;
	}
	  private double deduc1001;//gis(ias)
	   
		
		public double getDeduc1001() {
		return deduc1001;
	}

	public void setDeduc1001(double deduc1001) {
		this.deduc1001 = deduc1001;
	}

	
		
	public double getGpay0101() {
		return gpay0101;
	}

	public void setGpay0101(double gpay0101) {
		this.gpay0101 = gpay0101;
	}
	
	public long getOtherTrnCntr() {
		return otherTrnCntr;
	}

	public void setOtherTrnCntr(long otherTrnCntr) {
		this.otherTrnCntr = otherTrnCntr;
	}

	public HrEisOtherDtls getHrEisOtherDtls() {
		return hrEisOtherDtls;
	}

	public void setHrEisOtherDtls(HrEisOtherDtls hrEisOtherDtls) {
		this.hrEisOtherDtls = hrEisOtherDtls;
	}

	private long otherTrnCntr;
	
	private HrEisOtherDtls hrEisOtherDtls;

	
	
	// Constructors

	/*public long getApproveFlag() {
		return approveFlag;
	}
*/
	/*public void setApproveFlag(long approveFlag) {
		this.approveFlag = approveFlag;
	}*/

	public Date getApproveRejectDate() {
		return approveRejectDate;
	}

	public void setApproveRejectDate(Date approveRejectDate) {
		this.approveRejectDate = approveRejectDate;
	}

	public OrgPostMst getOrgPostMst() {
		return orgPostMst;
	}

	public void setOrgPostMst(OrgPostMst orgPostMst) {
		this.orgPostMst = orgPostMst;
	}

	/** default constructor */
	public HrPayPaybill() {
	}

	/** minimal constructor */
	public HrPayPaybill(long id, HrEisEmpMst hrEisEmpMst,
			double month, double year) {
		this.id = id;
		this.hrEisEmpMst = hrEisEmpMst;
		this.month = month;
		this.year = year;
	}

	/** full constructor */
	public HrPayPaybill(long id, HrEisEmpMst hrEisEmpMst,long psrNo,
			double month, double year, double perSplPay,
			double lsLe, double allow0119,
			double allow0103, double allow0110, double allow0111,
			double allow0107, double allow1301, double allow0113,
			double adv5701, double adv5801, double deduc0101,
			double grossAmt, double slo, double itSurcharge,
			double deduc9550, double deduc9530, double deduc9570,
			double deduc9580, double deduc9581, double deduc9582,
			double deduc9583, double deduc9584, double deduc9670,
			double loan9592, double loan9740,
			double loan9591, double loan9720, double deduc9780,
			double deduc9531, double totalDed, double netTotal,
			double gpay0101 ,
			CmnDatabaseMst cmnDatabaseMst,
			OrgPostMst orgPostMstByCreatedByPost,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByCreatedBy,
			Date createdDate,Integer trnCounter,long paybillGrpId,double deduc9999,double deduc9998
			) {
		this.id = id;
		this.psrNo = psrNo;
		this.hrEisEmpMst = hrEisEmpMst;
		this.month = month;
		this.year = year;
		this.allow0101 = perSplPay;		
		//this.le = lsLe;
		this.allow0119 = allow0119;
		this.allow0103 = allow0103;
		this.allow0110 = allow0110;
		this.allow0111 = allow0111;
		this.allow0107 = allow0107;
		this.allow1301 = allow1301;
		this.allow0113 = allow0113;
		this.adv5701 = adv5701;
		this.adv5801 = adv5801;
		this.deduc0101 = deduc0101;
		this.grossAmt = grossAmt;
		//this.slo = slo;
		this.it = itSurcharge;
		this.deduc9550 = deduc9550;
		//this.deduc9530 = deduc9530;
		this.deduc9570 = deduc9570;
		//this.deduc9580 = deduc9580;
		//this.deduc9581 = deduc9581;
		//this.deduc9582 = deduc9582;
		this.deduc9583 = deduc9583;
		//this.deduc9584 = deduc9584;
		this.deduc9670 = deduc9670;
		//this.loan9592 = loan9592;
		//this.loan9740 = loan9740;
		this.loan9591 = loan9591;
		this.loan9720 = loan9720;
		this.deduc9780 = deduc9780;
		//this.gpfIv = gpfIv;
		this.deduc9531=deduc9531;
		this.totalDed = totalDed;
		this.netTotal = netTotal;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.createdDate = createdDate;
		this.trnCounter = trnCounter;
		this.paybillGrpId = paybillGrpId;
		this.deduc9999 = deduc9999;
		this.deduc9998 = deduc9998;
		this.gpay0101=gpay0101;
		
	}
//	 Property accessors

	

	public double getDeduc9998() {
		return deduc9998;
	}

	public void setDeduc9998(double deduc9998) {
		this.deduc9998 = deduc9998;
	}

	public double getDeduc9999() {
		return deduc9999;
	}

	public void setDeduc9999(double deduc9999) {
		this.deduc9999 = deduc9999;
	}

	public double getAdv5701() {
		return adv5701;
	}

	public void setAdv5701(double adv5701) {
		this.adv5701 = adv5701;
	}

	public double getAdv5801() {
		return adv5801;
	}

	public void setAdv5801(double adv5801) {
		this.adv5801 = adv5801;
	}

	public double getAdv9670() {
		return adv9670;
	}

	public void setAdv9670(double adv9670) {
		this.adv9670 = adv9670;
	}

	public double getAllow0103() {
		return allow0103;
	}

	public void setAllow0103(double allow0103) {
		this.allow0103 = allow0103;
	}

	public double getAllow0104() {
		return allow0104;
	}

	public void setAllow0104(double allow0104) {
		this.allow0104 = allow0104;
	}

	public double getAllow0105() {
		return allow0105;
	}

	public void setAllow0105(double allow0105) {
		this.allow0105 = allow0105;
	}

	public double getAllow0107() {
		return allow0107;
	}

	public void setAllow0107(double allow0107) {
		this.allow0107 = allow0107;
	}

	public double getAllow0108() {
		return allow0108;
	}

	public void setAllow0108(double allow0108) {
		this.allow0108 = allow0108;
	}

	public double getAllow0110() {
		return allow0110;
	}

	public void setAllow0110(double allow0110) {
		this.allow0110 = allow0110;
	}

	public double getAllow0111() {
		return allow0111;
	}

	public void setAllow0111(double allow0111) {
		this.allow0111 = allow0111;
	}

	public double getAllow0113() {
		return allow0113;
	}

	public void setAllow0113(double allow0113) {
		this.allow0113 = allow0113;
	}

	public double getAllow0119() {
		return allow0119;
	}

	public void setAllow0119(double allow0119) {
		this.allow0119 = allow0119;
	}

	public double getAllow1301() {
		return allow1301;
	}

	public void setAllow1301(double allow1301) {
		this.allow1301 = allow1301;
	}
/*
	public double getAllow5006() {
		return allow5006;
	}

	public void setAllow5006(double allow5006) {
		this.allow5006 = allow5006;
	}
*/
	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/*public double getDeduc9530() {
		return deduc9530;
	}

	public void setDeduc9530(double deduc9530) {
		this.deduc9530 = deduc9530;
	}*/

	/*public double getDeduc9540() {
		return deduc9540;
	}

	public void setDeduc9540(double deduc9540) {
		this.deduc9540 = deduc9540;
	}*/

	public double getDeduc9550() {
		return deduc9550;
	}

	public void setDeduc9550(double deduc9550) {
		this.deduc9550 = deduc9550;
	}

	public double getDeduc9570() {
		return deduc9570;
	}

	public void setDeduc9570(double deduc9570) {
		this.deduc9570 = deduc9570;
	}

/*	public double getDeduc9580() {
		return deduc9580;
	}

	public void setDeduc9580(double deduc9580) {
		this.deduc9580 = deduc9580;
	}*/

	/*public double getDeduc9581() {
		return deduc9581;
	}

	public void setDeduc9581(double deduc9581) {
		this.deduc9581 = deduc9581;
	}
*/
	/*public double getDeduc9582() {
		return deduc9582;
	}

	public void setDeduc9582(double deduc9582) {
		this.deduc9582 = deduc9582;
	}*/

	public double getDeduc9583() {
		return deduc9583;
	}

	public void setDeduc9583(double deduc9583) {
		this.deduc9583 = deduc9583;
	}

	/*public double getDeduc9584() {
		return deduc9584;
	}

	public void setDeduc9584(double deduc9584) {
		this.deduc9584 = deduc9584;
	}*/

	/*public double getDeduc9670() {
		return deduc9670;
	}

	public void setDeduc9670(double deduc9670) {
		this.deduc9670 = deduc9670;
	}
*/
	public double getDeduc9910() {
		return deduc9910;
	}

	public void setDeduc9910(double deduc9910) {
		this.deduc9910 = deduc9910;
	}

	

	/*public double getGpfIv() {
		return gpfIv;
	}

	public void setGpfIv(double gpfIv) {
		this.gpfIv = gpfIv;
	}*/

	/**
	 * @return the deduc9911
	 */
	public double getDeduc9911() {
		return deduc9911;
	}

	/**
	 * @param deduc9911 the deduc9911 to set
	 */
	public void setDeduc9911(double deduc9911) {
		this.deduc9911 = deduc9911;
	}

	public double getGrossAmt() {
		return grossAmt;
	}

	public void setGrossAmt(double grossAmt) {
		this.grossAmt = grossAmt;
	}

	public HrEisEmpMst getHrEisEmpMst() {
		return hrEisEmpMst;
	}

	public void setHrEisEmpMst(HrEisEmpMst hrEisEmpMst) {
		this.hrEisEmpMst = hrEisEmpMst;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public double getIt() {
		return it;
	}

	public void setIt(double it) {
		this.it = it;
	}

	/*public double getLe() {
		return le;
	}

	public void setLe(double le) {
		this.le = le;
	}
*/
	public double getLoan9591() {
		return loan9591;
	}

	public void setLoan9591(double loan9591) {
		this.loan9591 = loan9591;
	}

	/*public double getLoan9592() {
		return loan9592;
	}

	public void setLoan9592(double loan9592) {
		this.loan9592 = loan9592;
	}*/

	public double getLoan9720() {
		return loan9720;
	}

	public void setLoan9720(double loan9720) {
		this.loan9720 = loan9720;
	}

	/*public double getLoan9740() {
		return loan9740;
	}

	public void setLoan9740(double loan9740) {
		this.loan9740 = loan9740;
	}
*/

	/*public double getLs() {
		return ls;
	}

	public void setLs(double ls) {
		this.ls = ls;
	}
*/
	public double getMonth() {
		return month;
	}

	public void setMonth(double month) {
		this.month = month;
	}

	public double getNetTotal() {
		return netTotal;
	}

	public void setNetTotal(double netTotal) {
		this.netTotal = netTotal;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public double getAllow0101() {
		return allow0101;
	}

	public void setAllow0101(double allow0101) {
		this.allow0101 = allow0101;
	}

	public double getAllow0102() {
		return allow0102;
	}

	public void setAllow0102(double allow0102) {
		this.allow0102 = allow0102;
	}

	/*public double getSlo() {
		return slo;
	}

	public void setSlo(double slo) {
		this.slo = slo;
	}*/

	public double getSurcharge() {
		return surcharge;
	}

	public void setSurcharge(double surcharge) {
		this.surcharge = surcharge;
	}

	public double getTotalDed() {
		return totalDed;
	}

	public void setTotalDed(double totalDed) {
		this.totalDed = totalDed;
	}

	public double getYear() {
		return year;
	}

	public void setYear(double year) {
		this.year = year;
	}

	public double getDeduc9560() {
		return deduc9560;
	}

	public void setDeduc9560(double deduc9560) {
		this.deduc9560 = deduc9560;
	}

	public double getDeduc9531() {
		return deduc9531;
	}

	public void setDeduc9531(double deduc9531) {
		this.deduc9531 = deduc9531;
	}

	public Integer getTrnCounter() {
		return trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}

	public double getBasic0101() {
		return basic0101;
	}

	public void setBasic0101(double basic0101) {
		this.basic0101 = basic0101;
	}

	public double getBasic0102() {
		return basic0102;
	}

	public void setBasic0102(double basic0102) {
		this.basic0102 = basic0102;
	}

	public double getAllow0120() {
		return allow0120;
	}

	public void setAllow0120(double allow0120) {
		this.allow0120 = allow0120;
	}

	public long getPaybillGrpId() {
		return paybillGrpId;
	}

	public void setPaybillGrpId(long paybillGrpId) {
		this.paybillGrpId = paybillGrpId;
	}

/*	public double getLoanInt9591() {
		return loanInt9591;
	}

	public void setLoanInt9591(double loanInt9591) {
		this.loanInt9591 = loanInt9591;
	}
*/
	/*public double getLoanInt9592() {
		return loanInt9592;
	}

	public void setLoanInt9592(double loanInt9592) {
		this.loanInt9592 = loanInt9592;
	}
*/
/*	public double getLoanInt9720() {
		return loanInt9720;
	}

	public void setLoanInt9720(double loanInt9720) {
		this.loanInt9720 = loanInt9720;
	}
*/
/*	public double getLoanInt9740() {
		return loanInt9740;
	}

	public void setLoanInt9740(double loanInt9740) {
		this.loanInt9740 = loanInt9740;
	}
*/

	public double getAdvIV9670() {
		return advIV9670;
	}

	public void setAdvIV9670(double advIV9670) {
		this.advIV9670 = advIV9670;
	}

/*	public double getDeduc9620() {
		return deduc9620;
	}

	public void setDeduc9620(double deduc9620) {
		this.deduc9620 = deduc9620;
	}*/

	public double getDeduc9534() {
		return deduc9534;
	}

	public void setDeduc9534(double deduc9534) {
		this.deduc9534 = deduc9534;
	}

	public double getDeduc9780() {
		return deduc9780;
	}

	public void setDeduc9780(double deduc9780) {
		this.deduc9780 = deduc9780;
	}

	/*public double getAdv7057() {
		return adv7057;
	}

	public void setAdv7057(double adv7057) {
		this.adv7057 = adv7057;
	}*/
/*
	public double getAdv7058() {
		return adv7058;
	}

	public void setAdv7058(double adv7058) {
		this.adv7058 = adv7058;
	}
*/
	public double getDeduc0101() {
		return deduc0101;
	}

	public void setDeduc0101(double deduc0101) {
		this.deduc0101 = deduc0101;
	}

	public long getPsrNo() {
		return psrNo;
	}

	public void setPsrNo(long psrNo) {
		this.psrNo = psrNo;
	}

	/**
	 * @return the allow1003
	 */
	public double getAllow1003() {
		return allow1003;
	}

	/**
	 * @param allow1003 the allow1003 to set
	 */
	public void setAllow1003(double allow1003) {
		this.allow1003 = allow1003;
	}

	public double getAllow1029() {
		return allow1029;
	}

	public void setAllow1029(double allow1029) {
		this.allow1029 = allow1029;
	}

	public double getAllow1030() {
		return allow1030;
	}

	public void setAllow1030(double allow1030) {
		this.allow1030 = allow1030;
	}

	public double getAllow1031() {
		return allow1031;
	}

	public void setAllow1031(double allow1031) {
		this.allow1031 = allow1031;
	}

	public double getAllow1032() {
		return allow1032;
	}

	public void setAllow1032(double allow1032) {
		this.allow1032 = allow1032;
	}

	public double getAllow1033() {
		return allow1033;
	}

	public void setAllow1033(double allow1033) {
		this.allow1033 = allow1033;
	}

	public double getAllow1034() {
		return allow1034;
	}

	public void setAllow1034(double allow1034) {
		this.allow1034 = allow1034;
	}

	public double getAllow1035() {
		return allow1035;
	}

	public void setAllow1035(double allow1035) {
		this.allow1035 = allow1035;
	}

	public double getAllow1036() {
		return allow1036;
	}

	public void setAllow1036(double allow1036) {
		this.allow1036 = allow1036;
	}

	public double getDeduc9510() {
		return deduc9510;
	}

	public void setDeduc9510(double deduc9510) {
		this.deduc9510 = deduc9510;
	}



	/**
	 * @return the deduc5051
	 */
	public double getDeduc5051() {
		return deduc5051;
	}

	/**
	 * @param deduc5051 the deduc5051 to set
	 */
	public void setDeduc5051(double deduc5051) {
		this.deduc5051 = deduc5051;
	}

	/**
	 * @return the deduc5052
	 */
	public double getDeduc5052() {
		return deduc5052;
	}

	/**
	 * @param deduc5052 the deduc5052 to set
	 */
	public void setDeduc5052(double deduc5052) {
		this.deduc5052 = deduc5052;
	}

	/**
	 * @return the deduc5053
	 */
	public double getDeduc5053() {
		return deduc5053;
	}

	/**
	 * @param deduc5053 the deduc5053 to set
	 */
	public void setDeduc5053(double deduc5053) {
		this.deduc5053 = deduc5053;
	}

	/**
	 * @return the deduc5054
	 */
	public double getDeduc5054() {
		return deduc5054;
	}

	/**
	 * @param deduc5054 the deduc5054 to set
	 */
	public void setDeduc5054(double deduc5054) {
		this.deduc5054 = deduc5054;
	}

	/**
	 * @return the deduc5055
	 */
	public double getDeduc5055() {
		return deduc5055;
	}

	/**
	 * @param deduc5055 the deduc5055 to set
	 */
	public void setDeduc5055(double deduc5055) {
		this.deduc5055 = deduc5055;
	}

	/**
	 * @return the deduc5056
	 */
	public double getDeduc5056() {
		return deduc5056;
	}

	/**
	 * @param deduc5056 the deduc5056 to set
	 */
	public void setDeduc5056(double deduc5056) {
		this.deduc5056 = deduc5056;
	}

	/**
	 * @return the deduc5057
	 */
	public double getDeduc5057() {
		return deduc5057;
	}

	/**
	 * @param deduc5057 the deduc5057 to set
	 */
	public void setDeduc5057(double deduc5057) {
		this.deduc5057 = deduc5057;
	}

	/**
	 * @return the deduc5058
	 */
	public double getDeduc5058() {
		return deduc5058;
	}

	/**
	 * @param deduc5058 the deduc5058 to set
	 */
	public void setDeduc5058(double deduc5058) {
		this.deduc5058 = deduc5058;
	}

	/**
	 * @return the deduc5059
	 */
	public double getDeduc5059() {
		return deduc5059;
	}

	/**
	 * @param deduc5059 the deduc5059 to set
	 */
	public void setDeduc5059(double deduc5059) {
		this.deduc5059 = deduc5059;
	}

	/**
	 * @return the adv5050
	 */
	/**
	 * @return the loanInt5059
	 */
	/*public double getLoanInt5059() {
		return loanInt5059;
	}

	*//**
	 * @param loanInt5059 the loanInt5059 to set
	 *//*
	public void setLoanInt5059(double loanInt5059) {
		this.loanInt5059 = loanInt5059;
	}
*/
	/**
	 * @return the adv5055
	 */
	
	/**
	 * @return the deduc9701
	 */
	public double getDeduc9701() {
		return deduc9701;
	}

	/**
	 * @param deduc9701 the deduc9701 to set
	 */
	public void setDeduc9701(double deduc9701) {
		this.deduc9701 = deduc9701;
	}

	/**
	 * @return the deduc9702
	 */
	public double getDeduc9702() {
		return deduc9702;
	}

	/**
	 * @param deduc9702 the deduc9702 to set
	 */
	public void setDeduc9702(double deduc9702) {
		this.deduc9702 = deduc9702;
	}

	/**
	 * @return the deduc9703
	 */
	public double getDeduc9703() {
		return deduc9703;
	}

	/**
	 * @param deduc9703 the deduc9703 to set
	 */
	public void setDeduc9703(double deduc9703) {
		this.deduc9703 = deduc9703;
	}

	/**
	 * @return the deduc9704
	 */
	public double getDeduc9704() {
		return deduc9704;
	}

	/**
	 * @param deduc9704 the deduc9704 to set
	 */
	public void setDeduc9704(double deduc9704) {
		this.deduc9704 = deduc9704;
	}

	/**
	 * @return the deduc9705
	 */
	public double getDeduc9705() {
		return deduc9705;
	}

	/**
	 * @param deduc9705 the deduc9705 to set
	 */
	public void setDeduc9705(double deduc9705) {
		this.deduc9705 = deduc9705;
	}

	/**
	 * @return the deduc9706
	 */
	public double getDeduc9706() {
		return deduc9706;
	}

	/**
	 * @param deduc9706 the deduc9706 to set
	 */
	public void setDeduc9706(double deduc9706) {
		this.deduc9706 = deduc9706;
	}

	/**
	 * @return the deduc9707
	 */
	public double getDeduc9707() {
		return deduc9707;
	}

	/**
	 * @param deduc9707 the deduc9707 to set
	 */
	public void setDeduc9707(double deduc9707) {
		this.deduc9707 = deduc9707;
	}

	/**
	 * @return the deduc9708
	 */
	public double getDeduc9708() {
		return deduc9708;
	}

	/**
	 * @param deduc9708 the deduc9708 to set
	 */
	public void setDeduc9708(double deduc9708) {
		this.deduc9708 = deduc9708;
	}

	/**
	 * @return the deduc9710
	 */
	public double getDeduc9710() {
		return deduc9710;
	}

	/**
	 * @param deduc9710 the deduc9710 to set
	 */
	public void setDeduc9710(double deduc9710) {
		this.deduc9710 = deduc9710;
	}

	/**
	 * @return the deduc9711
	 */
	public double getDeduc9711() {
		return deduc9711;
	}

	/**
	 * @param deduc9711 the deduc9711 to set
	 */
	public void setDeduc9711(double deduc9711) {
		this.deduc9711 = deduc9711;
	}

	/**
	 * @return the deduc9712
	 */
	public double getDeduc9712() {
		return deduc9712;
	}

	/**
	 * @param deduc9712 the deduc9712 to set
	 */
	public void setDeduc9712(double deduc9712) {
		this.deduc9712 = deduc9712;
	}

	/**
	 * @return the deduc9713
	 */
	public double getDeduc9713() {
		return deduc9713;
	}

	/**
	 * @param deduc9713 the deduc9713 to set
	 */
	public void setDeduc9713(double deduc9713) {
		this.deduc9713 = deduc9713;
	}

	/**
	 * @return the allow1147
	 */
	public double getAllow1147() {
		return allow1147;
	}

	/**
	 * @param allow1147 the allow1147 to set
	 */
	public void setAllow1147(double allow1147) {
		this.allow1147 = allow1147;
	}

	/**
	 * @return the allow1148
	 */
	public double getAllow1148() {
		return allow1148;
	}

	/**
	 * @param allow1148 the allow1148 to set
	 */
	public void setAllow1148(double allow1148) {
		this.allow1148 = allow1148;
	}

	/**
	 * @return the allow1149
	 */
	public double getAllow1149() {
		return allow1149;
	}

	/**
	 * @param allow1149 the allow1149 to set
	 */
	public void setAllow1149(double allow1149) {
		this.allow1149 = allow1149;
	}

	/**
	 * @return the allow1150
	 */
	public double getAllow1150() {
		return allow1150;
	}

	/**
	 * @param allow1150 the allow1150 to set
	 */
	public void setAllow1150(double allow1150) {
		this.allow1150 = allow1150;
	}

	/**
	 * @return the allow1151
	 */
	public double getAllow1151() {
		return allow1151;
	}

	/**
	 * @param allow1151 the allow1151 to set
	 */
	public void setAllow1151(double allow1151) {
		this.allow1151 = allow1151;
	}

	/**
	 * @return the allow1152
	 */
	public double getAllow1152() {
		return allow1152;
	}

	/**
	 * @param allow1152 the allow1152 to set
	 */
	public void setAllow1152(double allow1152) {
		this.allow1152 = allow1152;
	}

	/**
	 * @return the allow1153
	 */
	public double getAllow1153() {
		return allow1153;
	}

	/**
	 * @param allow1153 the allow1153 to set
	 */
	public void setAllow1153(double allow1153) {
		this.allow1153 = allow1153;
	}

	/**
	 * @return the allow1154
	 */
	public double getAllow1154() {
		return allow1154;
	}

	/**
	 * @param allow1154 the allow1154 to set
	 */
	public void setAllow1154(double allow1154) {
		this.allow1154 = allow1154;
	}

	/**
	 * @return the allow1155
	 */
	public double getAllow1155() {
		return allow1155;
	}

	/**
	 * @param allow1155 the allow1155 to set
	 */
	public void setAllow1155(double allow1155) {
		this.allow1155 = allow1155;
	}

	/**
	 * @return the allow1156
	 */
	public double getAllow1156() {
		return allow1156;
	}

	/**
	 * @param allow1156 the allow1156 to set
	 */
	public void setAllow1156(double allow1156) {
		this.allow1156 = allow1156;
	}

	/**
	 * @return the allow1157
	 */
	public double getAllow1157() {
		return allow1157;
	}

	/**
	 * @param allow1157 the allow1157 to set
	 */
	public void setAllow1157(double allow1157) {
		this.allow1157 = allow1157;
	}

	/**
	 * @return the allow1158
	 */
	public double getAllow1158() {
		return allow1158;
	}

	/**
	 * @param allow1158 the allow1158 to set
	 */
	public void setAllow1158(double allow1158) {
		this.allow1158 = allow1158;
	}

	/**
	 * @return the deduc9535
	 */
	public double getDeduc9535() {
		return deduc9535;
	}

	private double deduc9140;
	private double deduc9141;
	/**
	 * @param deduc9535 the deduc9535 to set
	 */
	public void setDeduc9535(double deduc9535) {
		this.deduc9535 = deduc9535;
	}

	/**
	 * @return the deduc9536
	 */
	public double getDeduc9536() {
		return deduc9536;
	}

	/**
	 * @param deduc9536 the deduc9536 to set
	 */
	public void setDeduc9536(double deduc9536) {
		this.deduc9536 = deduc9536;
	}

	/**
	 * @return the deduc9537
	 */
	public double getDeduc9537() {
		return deduc9537;
	}

	/**
	 * @param deduc9537 the deduc9537 to set
	 */
	public void setDeduc9537(double deduc9537) {
		this.deduc9537 = deduc9537;
	}

	public double getDeduc9141() {
		return deduc9141;
	}

	public void setDeduc9141(double deduc9141) {
		this.deduc9141 = deduc9141;
	}

	public double getDeduc9140() {
		return deduc9140;
	}

	public void setDeduc9140(double deduc9140) {
		this.deduc9140 = deduc9140;
	}
	


	//Addede by sunitha for TA Arrears : End
	private double allow9207;//7PC DA	
	public double getAllow9207() {
		return allow9207;
	}

	public void setAllow9207(double allow9207) {
		this.allow9207 = allow9207;
	}
	private double allow9208;//EMPR NPS Allowances	
	private double allow9212;//seven PC TA  Allowances	
	private double allow9213;//7th PC GPF Arrears
	private double allow9214;//7th PC DCPS Arrears	
	private double allow9215;//7th PC TA Arrears
	private double deduc9216;//7th PC GPF Arrears Deduction	
	private double deduc9217;//7th PC GPF Arrears Deduction	
	private double deduc9218;//7th PC GPF Arrears Deduction	
	
	
	private double grossNew;
	private double totalDedAdjustNew;
	private double grossSal;

	public double getGrossNew() {
		return grossNew;
	}

	public void setGrossNew(double grossNew) {
		this.grossNew = grossNew;
	}

	public double getTotalDedAdjustNew() {
		return totalDedAdjustNew;
	}

	public void setTotalDedAdjustNew(double totalDedAdjustNew) {
		this.totalDedAdjustNew = totalDedAdjustNew;
	}

	public double getGrossSal() {
		return grossSal;
	}

	public void setGrossSal(double grossSal) {
		this.grossSal = grossSal;
	}

	public double getAllow9208() {
		return allow9208;
	}

	public void setAllow9208(double allow9208) {
		this.allow9208 = allow9208;
	}

	public double getAllow9212() {
		return allow9212;
	}

	public void setAllow9212(double allow9212) {
		this.allow9212 = allow9212;
	}

	public double getAllow9213() {
		return allow9213;
	}

	public void setAllow9213(double allow9213) {
		this.allow9213 = allow9213;
	}

	public double getAllow9214() {
		return allow9214;
	}

	public void setAllow9214(double allow9214) {
		this.allow9214 = allow9214;
	}

	public double getAllow9215() {
		return allow9215;
	}

	public void setAllow9215(double allow9215) {
		this.allow9215 = allow9215;
	}

	public double getDeduc9216() {
		return deduc9216;
	}

	public void setDeduc9216(double deduc9216) {
		this.deduc9216 = deduc9216;
	}

	public double getDeduc9217() {
		return deduc9217;
	}

	public void setDeduc9217(double deduc9217) {
		this.deduc9217 = deduc9217;
	}
	
	public void setDeduc9218(double deduc9218) {
		this.deduc9218=deduc9218;
	}
	
	public double getDeduc9218() {
		return deduc9218;
	}

	public void setDeduc9142(double deduc9142) {
		this.deduc9142 = deduc9142;
	}

	public double getDeduc9142() {
		return deduc9142;
	}
	
}
