// default package
// Generated Aug 23, 2007 4:08:29 PM by Hibernate Tools 3.1.0.beta5
package com.tcs.sgv.eis.valueobject;

import java.io.Serializable;
import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.deduction.valueobject.HrPayDeducTypeMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrPayNonGovDeduction generated by hbm2java
 */
public class HrPayNonGovDeductionHst implements Serializable {

	// Fields    
	private HrPayNonGovDeductionHstId id;
	private long nonGovDeducId;
	private HrEisEmpMst hrEisEmpMst;
	private HrPayDeducTypeMst hrPayDeducTypeMst;
	private long nonGovDeducAmount;
	private Date nonGovDeducEfftStartDt;
	private Date nonGovDeducEfftEndDt;
	private String nonGovDeducAccNo ;
	//private Long nonGovDeducPeriod;
	CmnLookupMst cmnLookupMst;
	private CmnDatabaseMst cmnDatabaseMst;
	private OrgPostMst orgPostMstByUpdatedByPost;
	private OrgPostMst orgPostMstByCreatedByPost;
	private CmnLocationMst cmnLocationMst;
	private OrgUserMst orgUserMstByUpdatedBy;
	private OrgUserMst orgUserMstByCreatedBy;
	private Date createdDate;	
	private Date updatedDate;
	
	// Constructors

	
	/** default constructor */
	public HrPayNonGovDeductionHst() {
	}

	/** Full constructor */
	public HrPayNonGovDeductionHst(HrPayNonGovDeductionHstId id,long nonGovDeducId, HrEisEmpMst hrEisEmpMst, HrPayDeducTypeMst hrPayDeducTypeMst, Long nonGovDeducAmount, Date nonGovDeducEfftStartDt, Date nonGovDeducEfftEndDt, CmnLookupMst cmnLookupMst, CmnDatabaseMst cmnDatabaseMst, OrgPostMst orgPostMstByUpdatedByPost, OrgPostMst orgPostMstByCreatedByPost, CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByUpdatedBy, OrgUserMst orgUserMstByCreatedBy, Date createdDate, Date updatedDate,String nonGovDeducAccNo ) {
		this.id = id;
		
		this.hrEisEmpMst = hrEisEmpMst;
		this.hrPayDeducTypeMst = hrPayDeducTypeMst;
		this.nonGovDeducAmount = nonGovDeducAmount;
		this.nonGovDeducEfftStartDt = nonGovDeducEfftStartDt;
		this.nonGovDeducEfftEndDt = nonGovDeducEfftEndDt;
		this.nonGovDeducAccNo=nonGovDeducAccNo;
		this.cmnLookupMst = cmnLookupMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	/** minimal constructor */
	public HrPayNonGovDeductionHst(HrPayNonGovDeductionHstId id) {
		this.id = id;
	}

	// Property accessors
	public long getNonGovDeducId() {
		return this.nonGovDeducId;
	}

	public void setNonGovDeducId(long nonGovDeducId) {
		this.nonGovDeducId = nonGovDeducId;
	}

	public long getNonGovDeducAmount() {
		return this.nonGovDeducAmount;
	}

	public void setNonGovDeducAmount(long nonGovDeducAmount) {
		this.nonGovDeducAmount = nonGovDeducAmount;
	}

	public Date getNonGovDeducEfftStartDt() {
		return this.nonGovDeducEfftStartDt;
	}

	public void setNonGovDeducEfftStartDt(Date nonGovDeducEfftStartDt) {
		this.nonGovDeducEfftStartDt = nonGovDeducEfftStartDt;
	}

	public Date getNonGovDeducEfftEndDt() {
		return this.nonGovDeducEfftEndDt;
	}

	public void setNonGovDeducEfftEndDt(Date nonGovDeducEfftEndDt) {
		this.nonGovDeducEfftEndDt = nonGovDeducEfftEndDt;
	}
	

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}	

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public HrEisEmpMst getHrEisEmpMst() {
		return hrEisEmpMst;
	}

	public void setHrEisEmpMst(HrEisEmpMst hrEisEmpMst) {
		this.hrEisEmpMst = hrEisEmpMst;
	}

	public HrPayDeducTypeMst getHrPayDeducTypeMst() {
		return hrPayDeducTypeMst;
	}

	public void setHrPayDeducTypeMst(HrPayDeducTypeMst hrPayDeducTypeMst) {
		this.hrPayDeducTypeMst = hrPayDeducTypeMst;
	}

	public CmnLookupMst getCmnLookupMst() {
		return cmnLookupMst;
	}

	public void setCmnLookupMst(CmnLookupMst cmnLookupMst) {
		this.cmnLookupMst = cmnLookupMst;
	}

	public HrPayNonGovDeductionHstId getId() {
		return id;
	}

	public void setId(HrPayNonGovDeductionHstId id) {
		this.id = id;
	}

	public String getNonGovDeducAccNo() {
		return nonGovDeducAccNo;
	}

	public void setNonGovDeducAccNo(String nonGovDeducAccNo) {
		this.nonGovDeducAccNo = nonGovDeducAccNo;
	}

	
}
