// default package
// Generated Aug 17, 2007 10:37:46 AM by Hibernate Tools 3.2.0.beta8
package com.tcs.sgv.eis.valueobject;
//Comment By Maruthi For import Organisation.

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * RltBillTypeEdp generated by hbm2java
 */
public class RltBillTypeEdp implements java.io.Serializable {

	// Fields    

	private long typeEdpId;

	private long subjectId;

	private String objHdCode;

	private String edpCode;

	private String edpDesc;

	private String addDedFlag;

	private String edpCategory;

	private CmnLanguageMst cmnLanguageMst;

	private long activateFlag;

	private Date startDate;

	private Date endDate;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;

	private Date createdDate;

	private Date updatedDate;

	private String expRcpRev;

	private String edpShortName;

	private Set hrPayEdpCompoMpgs = new HashSet(0);
	
	private String edpMethodName;

	//Added by Paurav
	private String expRcpRec;
	//Ended by Paurav

	// Constructors

	/** default constructor */
	public RltBillTypeEdp() {
	}

	/** minimal constructor */
	public RltBillTypeEdp(long typeEdpId, long subjectId,
			String edpCode, String addDedFlag,
			long activateFlag,String expRcpRec) {
		this.typeEdpId = typeEdpId;
		this.subjectId = subjectId;
		this.edpCode = edpCode;
		this.addDedFlag = addDedFlag;
		this.activateFlag = activateFlag;
		this.expRcpRec = expRcpRec;
	}

	/** full constructor */
	public RltBillTypeEdp(long typeEdpId, long subjectId,
			String objHdCode, String edpCode, String edpDesc,
			String addDedFlag, String edpCategory,
			long activateFlag, Date startDate,
			Date endDate, CmnLanguageMst cmnLanguageMst,
			CmnDatabaseMst cmnDatabaseMst,
			OrgPostMst orgPostMstByCreatedByPost,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByCreatedBy,
			Date createdDate,OrgUserMst orgUserMstByUpdatedBy,OrgPostMst orgPostMstByUpdatedByPost,
			 Date updatedDate, String expRcpRev, String edpShortName,
			Set hrPayEdpCompoMpgs,String expRcpRec) {
		this.typeEdpId = typeEdpId;
		this.subjectId = subjectId;
		this.objHdCode = objHdCode;
		this.edpCode = edpCode;
		this.edpDesc = edpDesc;
		this.addDedFlag = addDedFlag;
		this.edpCategory = edpCategory;
		this.activateFlag = activateFlag;
		this.startDate = startDate;
		this.endDate = endDate;
		this.cmnLanguageMst = cmnLanguageMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.createdDate = createdDate;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.updatedDate = updatedDate;
		this.expRcpRev = expRcpRev;
		this.edpShortName = edpShortName;
		this.hrPayEdpCompoMpgs = hrPayEdpCompoMpgs;
		this.expRcpRec = expRcpRec;
	}

	// Property accessors
	public String getEdpMethodName() {
		return edpMethodName;
	}

	public void setEdpMethodName(String edpMethodName) {
		this.edpMethodName = edpMethodName;
	}

	public long getTypeEdpId() {
		return this.typeEdpId;
	}

	
	public void setTypeEdpId(long typeEdpId) {
		this.typeEdpId = typeEdpId;
	}

	public long getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(long subjectId) {
		this.subjectId = subjectId;
	}

	public String getObjHdCode() {
		return this.objHdCode;
	}

	public void setObjHdCode(String objHdCode) {
		this.objHdCode = objHdCode;
	}

	public String getEdpCode() {
		return this.edpCode;
	}

	public void setEdpCode(String edpCode) {
		this.edpCode = edpCode;
	}

	public String getEdpDesc() {
		return this.edpDesc;
	}

	public void setEdpDesc(String edpDesc) {
		this.edpDesc = edpDesc;
	}

	public String getAddDedFlag() {
		return this.addDedFlag;
	}

	public void setAddDedFlag(String addDedFlag) {
		this.addDedFlag = addDedFlag;
	}

	public String getEdpCategory() {
		return this.edpCategory;
	}

	public void setEdpCategory(String edpCategory) {
		this.edpCategory = edpCategory;
	}

	public long getActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(long activateFlag) {
		this.activateFlag = activateFlag;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getExpRcpRev() {
		return this.expRcpRev;
	}

	public void setExpRcpRev(String expRcpRev) {
		this.expRcpRev = expRcpRev;
	}

	public String getEdpShortName() {
		return this.edpShortName;
	}

	public void setEdpShortName(String edpShortName) {
		this.edpShortName = edpShortName;
	}

	public Set getHrPayEdpCompoMpgs() {
		return this.hrPayEdpCompoMpgs;
	}

	public void setHrPayEdpCompoMpgs(Set hrPayEdpCompoMpgs) {
		this.hrPayEdpCompoMpgs = hrPayEdpCompoMpgs;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getExpRcpRec() {
		return expRcpRec;
	}

	public void setExpRcpRec(String expRcpRec) {
		this.expRcpRec = expRcpRec;
	}

}
