package com.tcs.sgv.eis.zp.zpAdminOffice.valueobject;
// Generated Jul 23, 2012 4:42:54 PM by Hibernate Tools 3.2.0.CR1


import java.util.Date;

/**
 * ZpAdminOfficeMst generated by hbm2java
 */
public class ZpAdminOfficeMst  implements java.io.Serializable {


     private long ofcId;
     private String officeName;
     private String officeCode;
     private Long langId;
     private Long createdBy;
     private Date createdDate;
     private Long updatedBy;
     private Date updatedDate;
     private Long createdByPost;
     private Long updatedByPost;
     private String schemeCode;
     private String grNo;
     private Date grDate;
     private String dcpsOffName;

    public ZpAdminOfficeMst() {
    }

	
    public ZpAdminOfficeMst(long ofcId) {
        this.ofcId = ofcId;
    }
    public ZpAdminOfficeMst(long ofcId, String officeName, String officeCode, Long langId, Long createdBy, Date createdDate, Long updatedBy, Date updatedDate, Long createdByPost, Long updatedByPost) {
       this.ofcId = ofcId;
       this.officeName = officeName;
       this.officeCode = officeCode;
       this.langId = langId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
       this.createdByPost = createdByPost;
       this.updatedByPost = updatedByPost;
    }
   
    public ZpAdminOfficeMst(long ofcId, String officeName, String officeCode, Long langId, Long createdBy, Date createdDate, Long updatedBy, Date updatedDate, Long createdByPost, Long updatedByPost,String schemeCode,String grNo,Date grDate,String offName) {
        this.ofcId = ofcId;
        this.officeName = officeName;
        this.officeCode = officeCode;
        this.langId = langId;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.updatedBy = updatedBy;
        this.updatedDate = updatedDate;
        this.createdByPost = createdByPost;
        this.updatedByPost = updatedByPost;
        this.schemeCode=schemeCode;
        this.grNo=grNo;
        this.grDate=grDate;
        this.dcpsOffName=offName;
     }
    
    public String getdcpsOffName() {
        return this.dcpsOffName;
    }
    
    public void setdcpsOffName(String dcpsOffName) {
        this.dcpsOffName = dcpsOffName;
    }
    
    public Date getgrDate() {
        return this.grDate;
    }
    
    public void setgrDate(Date grDate) {
        this.grDate = grDate;
    }
    
    public String getgrNo() {
        return this.grNo;
    }
    
    public void setgrNo(String grNo) {
        this.grNo = grNo;
    }
    
    public String getschemeCode() {
        return this.schemeCode;
    }
    
    public void setschemeCode(String schemeCode) {
        this.schemeCode = schemeCode;
    }
    
    public long getOfcId() {
        return this.ofcId;
    }
    
    public void setOfcId(long ofcId) {
        this.ofcId = ofcId;
    }
    public String getOfficeName() {
        return this.officeName;
    }
    
    public void setOfficeName(String officeName) {
        this.officeName = officeName;
    }
    public String getOfficeCode() {
        return this.officeCode;
    }
    
    public void setOfficeCode(String officeCode) {
        this.officeCode = officeCode;
    }
    public Long getLangId() {
        return this.langId;
    }
    
    public void setLangId(Long langId) {
        this.langId = langId;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public Long getCreatedByPost() {
        return this.createdByPost;
    }
    
    public void setCreatedByPost(Long createdByPost) {
        this.createdByPost = createdByPost;
    }
    public Long getUpdatedByPost() {
        return this.updatedByPost;
    }
    
    public void setUpdatedByPost(Long updatedByPost) {
        this.updatedByPost = updatedByPost;
    }




}


