// default package
// Generated Nov 22, 2007 6:16:17 PM by Hibernate Tools 3.2.0.beta8
package com.tcs.sgv.eis.valueobject;

import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.common.valueobject.MstScheme;
import com.tcs.sgv.dcps.valueobject.MstDcpsBillGroup;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * PaybillHeadMpg generated by hbm2java
 */
public class PaybillHeadMpg implements java.io.Serializable {

	// Fields    
	
	private long id;

	private long hrPayPaybill;

	private MstScheme mstScheme;
	
	private CmnDatabaseMst cmnDatabaseMst;
	private OrgPostMst orgPostMstByUpdatedByPost;
	private OrgPostMst orgPostMstByCreatedByPost;
	private CmnLocationMst cmnLocationMst;
	private OrgUserMst orgUserMstByUpdatedBy;
	private OrgUserMst orgUserMstByCreatedBy;	

	private Date updatedDate;
	
	private Date createdDate;
	//private HrPayArrearPaybill arrearBillId;
	private CmnLookupMst billTypeId;
	private MstDcpsBillGroup billNo;
	
	private long approveFlag;
	private double month;
	private double year;
    private String headChargable;
    
    private long billGrossAmt;
    private long billNetAmt;
    
    private long voucherNumber;
    private Date voucherDate;
    //private long billCategory;
     private long noOfEmp; //	//added by Saurabh S
    
   
    private long billCategory;

	public long getBillCategory() {
		return billCategory;
	}

	public void setBillCategory(long billCategory) {
		this.billCategory = billCategory;
	}
	// Constructors

	/*public HrPayArrearPaybill getArrearBillId() {
		return arrearBillId;
	}

	public void setArrearBillId(HrPayArrearPaybill arrearBillId) {
		this.arrearBillId = arrearBillId;
	}*/

	//added by Saurabh S
	public long getNoOfEmp() {
		return noOfEmp;
	}

	public void setNoOfEmp(long noOfEmp) {
		this.noOfEmp = noOfEmp;
	}
 /*
	public long getBillCategory() {
		return billCategory;
	}

	public void setBillCategory(long billCategory) {
		this.billCategory = billCategory;
	}*/

	/**
	 * @return the voucherNumber
	 */
	public long getVoucherNumber() {
		return voucherNumber;
	}

	/**
	 * @param voucherNumber the voucherNumber to set
	 */
	public void setVoucherNumber(long voucherNumber) {
		this.voucherNumber = voucherNumber;
	}

	/**
	 * @return the voucherDate
	 */
	public Date getVoucherDate() {
		return voucherDate;
	}

	/**
	 * @param voucherDate the voucherDate to set
	 */
	public void setVoucherDate(Date voucherDate) {
		this.voucherDate = voucherDate;
	}

	public String getHeadChargable() {
		return headChargable;
	}

	public void setHeadChargable(String headChargable) {
		this.headChargable = headChargable;
	}

	/** default constructor */
	public PaybillHeadMpg() {
	}

	/** minimal constructor */
	public PaybillHeadMpg(long id) {
		this.id = id;
	}

	/** full constructor */
	public PaybillHeadMpg(long id, long paybillId,
			long subheadId, long billCategory, long locId,
			long dbId, long createdBy, Date createdDate,
			long updatedBy, Date updatedDate, long createdByPost,
			long updatedByPost) {
		this.id = id;			
		
		this.createdDate = createdDate;
		
		this.updatedDate = updatedDate;
		
	}

	// Property accessors
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
		

	
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	
	public long getHrPayPaybill() {
		return hrPayPaybill;
	}

	public void setHrPayPaybill(long hrPayPaybill) {
		this.hrPayPaybill = hrPayPaybill;
	}
	
	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public long getApproveFlag() {
		return approveFlag;
	}

	public void setApproveFlag(long approveFlag) {
		this.approveFlag = approveFlag;
	}

	public MstDcpsBillGroup getBillNo() {
		return billNo;
	}

	public void setBillNo(MstDcpsBillGroup billNo) {
		this.billNo = billNo;
	}

	public CmnLookupMst getBillTypeId() {
		return billTypeId;
	}

	public void setBillTypeId(CmnLookupMst billTypeId) {
		this.billTypeId = billTypeId;
	}

	public double getMonth() {
		return month;
	}

	public void setMonth(double month) {
		this.month = month;
	}

	public double getYear() {
		return year;
	}

	public void setYear(double year) {
		this.year = year;
	}

	/**
	 * @return the mstScheme
	 */
	public MstScheme getMstScheme() {
		return mstScheme;
	}

	/**
	 * @param mstScheme the mstScheme to set
	 */
	public void setMstScheme(MstScheme mstScheme) {
		this.mstScheme = mstScheme;
	}

	/**
	 * @return the billGrossAmt
	 */
	public long getBillGrossAmt() {
		return billGrossAmt;
	}

	/**
	 * @param billGrossAmt the billGrossAmt to set
	 */
	public void setBillGrossAmt(long billGrossAmt) {
		this.billGrossAmt = billGrossAmt;
	}

	/**
	 * @return the billNetAmt
	 */
	public long getBillNetAmt() {
		return billNetAmt;
	}

	/**
	 * @param billNetAmt the billNetAmt to set
	 */
	public void setBillNetAmt(long billNetAmt) {
		this.billNetAmt = billNetAmt;
	}

	private String reasonForRejection;

	public String getReasonForRejection() {
		return reasonForRejection;
	}

	public void setReasonForRejection(String reasonForRejection) {
		this.reasonForRejection = reasonForRejection;
	}
}
