package com.tcs.sgv.eis.valueobject;


// Generated Aug 18, 2007 3:00:38 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.dcps.valueobject.MstDcpsBillGroup;
import com.tcs.sgv.eis.valueobject.HrEisQuaterTypeMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrPayPayslip generated by hbm2java
 */
public class HrPayPayslip implements java.io.Serializable {

	Log logger = LogFactory.getLog(getClass());

    private long paySlipId;
    private HrPayPaybill hrPayPaybill;
	private HrEisEmpMst hrEisEmpMst;
	private long month;
	private long year;
	private MstDcpsBillGroup mstDcpsBillGroup;
	private Date paySlipDate;
	private HrEisQuaterTypeMst hrQuaterTypeMst;
	private long incrementAmt;
	private String itAccNo;
	private String gpfAccNo;
	private String tokenNo;
	
	private long basicPay;

	private long daOnTa;
	public long getDaOnTa()
	{
		return daOnTa;
	}
	public void setDaOnTa(long daOnTa)
	{
		logger.info("daOnTa **********"+daOnTa);
		this.daOnTa = daOnTa;
	}

        private long overtimeAllow;
        
        public long getOvertimeAllow() {
                return overtimeAllow;
        }
        public void setOvertimeAllow(long overtimeAllow) {
        	
        	logger.info("overtimeAllow **********"+overtimeAllow);
                this.overtimeAllow = overtimeAllow;
        }


	private long splPay=0;
	private long perPay=0;
	private long da=0;
	private long cla=0;
	private long hra=0;
	private long ma=0;
	private long dp=0;

	private long ITax=0;
	private long hrr=0;
	private long PTax=0;
	/*Added By Tejashree */
	private long DA_7PC;
	
	public long getDA_7PC() {
		return DA_7PC;
	}
	public void setDA_7PC(long dA_7PC) {
		DA_7PC = dA_7PC;
	}
	/*ended by Tejashree*/
	private long revenueStamp;
	
	public long getRevenueStamp() {
		return revenueStamp;
	}
	public void setRevenueStamp(long revenueStamp) {
		this.revenueStamp = revenueStamp;
	}
	
	private long grossAmt=0;
	private long netTotal=0;
	
	private Integer trnCounter=0;
	
	private Date createdDate;

	private Date updatedDate;
	
	private CmnLanguageMst cmnLanguageMst;
	
	private CmnLocationMst cmnLocationMst;
	
	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;
	
	//manish started
	
	
	//allowances
	private long	ta=0;
	/**
	 * @return the paySlipId
	 */
	
	
	private long	arma=0;
	private long	armouera=0;
	private long	bmia=0;
	private long	casha=0;
	private long	conva=0;
	private long	cida=0;
	private long	ea=0;
	private long	esisa=0;
	private long	ela=0;
	private long	fita=0;
	private long	gaa=0;
	private long	kma=0;
	private long	lfa=0;
	private long	mecha=0;
	private long	mea=0;
	private long	naa=0;
	private long	mesha=0;
	private long	npa=0;
	private long	suma=0;
	private long	pa=0;
	private long	sda=0;
	private long	oa=0;
	private long	ap=0;
	private long	ua=0;
	private long	techa=0;
	private long	taa=0;
	private long	ha=0;
	private long	pg=0;
	private long	ats30=0;
	private long	ats50=0;
	private long	force100=0;
	private long	force25=0;
	private long	fpa=0;
	private long	taforsixth=0;
	private long 	refAllow=0; // refreshment Allowance
	private long 	peonAllow=0;
	
	




	private long 	addDa=0;
	private long	addHra=0;
	private long	daArr=0;
	private long	tempCla=0;
	private long	frana=0;
	private long	tempHra=0;
	private long	lta=0;
	private long	medstu=0;
	private long	perTra=0;
	private long	tempTa=0;
	private long	wa=0;
	private long	oas=0;
	
	private long wriPay=0;
	
	
	private long cta=0;//Central TA
	private long centralDA=0;//Central DA
	
	private long specialPayPilot=0;   
	private long militeryPilot=0;     
	private long outfirPilot=0;       
	private long flyingAllowPilot=0;  
	private long inspectionPilot=0;   
	private long qualificationPilot=0;
	private long instructionalPilot=0;
	private long flyingPayPilot=0;    
	private long kitPilot=0;          
	private long chplPilot=0;         
	private long rltPilot=0;          
	private long incentiveBdds=0; 
	private long cpf=0; 
	private long basicArr=0;

	
	public long getBasicArr()
	{
		return basicArr;
	}
	public void setBasicArr(long basicArr)
	{
		this.basicArr = basicArr;
	}
	/**
	 * @return the peonAllow
	 */
	public long getPeonAllow() {
		return peonAllow;
	}
	/**
	 * @param peonAllow the peonAllow to set
	 */
	public void setPeonAllow(long peonAllow) {
		this.peonAllow = peonAllow;
	}
	//private long gisArrear;
	
	
	
	/**
	 * @return the gisArrear
	 *//*
	public long getGisArrear() {
		return gisArrear;
	}
	*//**
	 * @param gisArrear the gisArrear to set
	 *//*
	public void setGisArrear(long gisArrear) {
		this.gisArrear = gisArrear;
	}*/
	/**
	 * @return the cta
	 */
	public long getCta() {
		return cta;
	}
	/**
	 * @param cta the cta to set
	 */
	public void setCta(long cta) {
		this.cta = cta;
	}
	
	
	/**
	 * @return the centralDA
	 */
	public long getCentralDA() {
		return centralDA;
	}
	/**
	 * @param centralDA the centralDA to set
	 */
	public void setCentralDA(long centralDA) {
		this.centralDA = centralDA;
	}
	/**
	 * @return the wriPay
	 */
	public long getWriPay() {
		return wriPay;
	}
	/**
	 * @param wriPay the wriPay to set
	 */
	public void setWriPay(long wriPay) {
		this.wriPay = wriPay;
	}
	/**
	 * @return the addDa
	 */
	public long getAddDa() {
		return addDa;
	}
	/**
	 * @param addDa the addDa to set
	 */
	public void setAddDa(long addDa) {
		this.addDa = addDa;
	}
	/**
	 * @return the refAllow
	 */
	public long getRefAllow() {
		return refAllow;
	}
	/**
	 * @param refAllow the refAllow to set
	 */
	public void setRefAllow(long refAllow) {
		this.refAllow = refAllow;
	}
	/**
	 * @return the addHra
	 */
	public long getAddHra() {
		return addHra;
	}
	/**
	 * @param addHra the addHra to set
	 */
	public void setAddHra(long addHra) {
		this.addHra = addHra;
	}
	/**
	 * @return the daArr
	 */
	public long getDaArr() {
		return daArr;
	}
	/**
	 * @param daArr the daArr to set
	 */
	public void setDaArr(long daArr) {
		this.daArr = daArr;
	}
	/**
	 * @return the tempCla
	 */
	public long getTempCla() {
		return tempCla;
	}
	/**
	 * @param tempCla the tempCla to set
	 */
	public void setTempCla(long tempCla) {
		this.tempCla = tempCla;
	}
	/**
	 * @return the frana
	 */
	public long getFrana() {
		return frana;
	}
	/**
	 * @param frana the frana to set
	 */
	public void setFrana(long frana) {
		this.frana = frana;
	}
	/**
	 * @return the tempHra
	 */
	public long getTempHra() {
		return tempHra;
	}
	/**
	 * @param tempHra the tempHra to set
	 */
	public void setTempHra(long tempHra) {
		this.tempHra = tempHra;
	}
	/**
	 * @return the lta
	 */
	public long getLta() {
		return lta;
	}
	/**
	 * @param lta the lta to set
	 */
	public void setLta(long lta) {
		this.lta = lta;
	}
	/**
	 * @return the medstu
	 */
	public long getMedstu() {
		return medstu;
	}
	/**
	 * @param medstu the medstu to set
	 */
	public void setMedstu(long medstu) {
		this.medstu = medstu;
	}
	/**
	 * @return the perTra
	 */
	public long getPerTra() {
		return perTra;
	}
	/**
	 * @param perTra the perTra to set
	 */
	public void setPerTra(long perTra) {
		this.perTra = perTra;
	}
	/**
	 * @return the tempTa
	 */
	public long getTempTa() {
		return tempTa;
	}
	/**
	 * @param tempTa the tempTa to set
	 */
	public void setTempTa(long tempTa) {
		this.tempTa = tempTa;
	}
	/**
	 * @return the wa
	 */
	public long getWa() {
		return wa;
	}
	/**
	 * @param wa the wa to set
	 */
	public void setWa(long wa) {
		this.wa = wa;
	}
	/**
	 * @return the oas
	 */
	public long getOas() {
		return oas;
	}
	/**
	 * @param oas the oas to set
	 */
	public void setOas(long oas) {
		this.oas = oas;
	}

	
	
	
	//deductions 
	private long	gpfgrpd=0;
	private long	pli=0;
	private long	dcps=0;
	private long	gpfgrpbac=0;
	private long	gpfiasos=0;
	private long	gpfias=0;
	private long	gpfips=0;
	private long	gpfifs=0;
	private long	servc=0;
	private long	otherd=0;
	private long	gisias=0;
	private long	gisips=0;
	private long	gisifs=0;
	private long	gis=0;
	private long	cgegis=0;
	private long  	dcpsDelay=0;
	private long 	dcpsPay=0;
	private long 	dcpsDA=0;
	
	private long	giszp=0;
	private long	gpfabcmr=0;
	private long	gpfdmr=0;
	private long	gpfiasmr=0;
	private long	gpfipsmr=0;
	private long	gpfifsmr=0;
	private long	hrrarr=0;
	private long	janjulgisa=0;
	private long	janjulgis=0;
	private long	msli=0;
	private long	or=0;
	private long	ptarr=0;
	private long	odtr=0;
	
	
	
	
	//loans
	private long	otherVehical=0;
	private long	hbaLand=0;
	private long	mcaLand=0;
	//100
	private long	coHsgSoc=0;
	private long	compAdvance=0;
	private long	hbaAis=0;
	private long	mcaAis=0;
	private long	compAis=0;
	private long	otherAdv=0;
	private long	hbaHouse=0;
	
	private long	otherVehicalInt=0;
	private long	hbaLandInt=0;
	private long	mcaLandInt=0;
	//
	private long	coHsgSocInt=0;
	private long	compAdvanceInt=0;
	private long	hbaAisInt=0;
	private long	mcaAisInt=0;
	private long	compAisInt=0;
	private long	otherAdvInt=0;
	private long	hbaHouseInt=0;
	//advances
	
	private long	payAdv;
	/**
	 * @return the otherVehicalInt
	 */
	public long getOtherVehicalInt() {
		return otherVehicalInt;
	}
	/**
	 * @param otherVehicalInt the otherVehicalInt to set
	 */
	public void setOtherVehicalInt(long otherVehicalInt) {
		this.otherVehicalInt = otherVehicalInt;
	}
	/**
	 * @return the hbaLandInt
	 */
	public long getHbaLandInt() {
		return hbaLandInt;
	}
	/**
	 * @param hbaLandInt the hbaLandInt to set
	 */
	public void setHbaLandInt(long hbaLandInt) {
		this.hbaLandInt = hbaLandInt;
	}
	/**
	 * @return the mcaLandInt
	 */
	public long getMcaLandInt() {
		return mcaLandInt;
	}
	/**
	 * @param mcaLandInt the mcaLandInt to set
	 */
	public void setMcaLandInt(long mcaLandInt) {
		this.mcaLandInt = mcaLandInt;
	}
	/**
	 * @return the coHsgSocInt
	 */
	public long getCoHsgSocInt() {
		return coHsgSocInt;
	}
	/**
	 * @param coHsgSocInt the coHsgSocInt to set
	 */
	public void setCoHsgSocInt(long coHsgSocInt) {
		this.coHsgSocInt = coHsgSocInt;
	}
	/**
	 * @return the compAdvanceInt
	 */
	public long getCompAdvanceInt() {
		return compAdvanceInt;
	}
	/**
	 * @param compAdvanceInt the compAdvanceInt to set
	 */
	public void setCompAdvanceInt(long compAdvanceInt) {
		this.compAdvanceInt = compAdvanceInt;
	}
	/**
	 * @return the hbaAisInt
	 */
	public long getHbaAisInt() {
		return hbaAisInt;
	}
	/**
	 * @param hbaAisInt the hbaAisInt to set
	 */
	public void setHbaAisInt(long hbaAisInt) {
		this.hbaAisInt = hbaAisInt;
	}
	/**
	 * @return the mcaAisInt
	 */
	public long getMcaAisInt() {
		return mcaAisInt;
	}
	/**
	 * @param mcaAisInt the mcaAisInt to set
	 */
	public void setMcaAisInt(long mcaAisInt) {
		this.mcaAisInt = mcaAisInt;
	}
	/**
	 * @return the compAisInt
	 */
	public long getCompAisInt() {
		return compAisInt;
	}
	/**
	 * @param compAisInt the compAisInt to set
	 */
	public void setCompAisInt(long compAisInt) {
		this.compAisInt = compAisInt;
	}
	/**
	 * @return the otherAdvInt
	 */
	public long getOtherAdvInt() {
		return otherAdvInt;
	}
	/**
	 * @param otherAdvInt the otherAdvInt to set
	 */
	public void setOtherAdvInt(long otherAdvInt) {
		this.otherAdvInt = otherAdvInt;
	}
	/**
	 * @return the hbaHouseInt
	 */
	public long getHbaHouseInt() {
		return hbaHouseInt;
	}
	/**
	 * @param hbaHouseInt the hbaHouseInt to set
	 */
	public void setHbaHouseInt(long hbaHouseInt) {
		this.hbaHouseInt = hbaHouseInt;
	}




	private long	FA=0;
	private long	TA=0;
	private long	GPFADVABC=0;
	private long	GPFADVD=0;
	private long	GPFIASAdv=0;
	private long	GPFOSAdv=0;
	private long	ExcPayRcAdv=0;

	
	public long getPaySlipId() {
		return paySlipId;
	}
	/**
	 * @param paySlipId the paySlipId to set
	 */
	public void setPaySlipId(long paySlipId) {
		

		
		this.paySlipId = paySlipId;
	}
	/**
	 * @return the hrPayPaybill
	 */
	public HrPayPaybill getHrPayPaybill() {
		return hrPayPaybill;
	}
	/**
	 * @param hrPayPaybill the hrPayPaybill to set
	 */
	public void setHrPayPaybill(HrPayPaybill hrPayPaybill) {
		this.hrPayPaybill = hrPayPaybill;
	}
	/**
	 * @return the hrEisEmpMst
	 */
	public HrEisEmpMst getHrEisEmpMst() {
		return hrEisEmpMst;
	}
	/**
	 * @param hrEisEmpMst the hrEisEmpMst to set
	 */
	public void setHrEisEmpMst(HrEisEmpMst hrEisEmpMst) {
		this.hrEisEmpMst = hrEisEmpMst;
	}
	/**
	 * @return the month
	 */
	public long getMonth() {
		return month;
	}
	/**
	 * @param month the month to set
	 */
	public void setMonth(long month) {
		this.month = month;
	}
	/**
	 * @return the year
	 */
	public long getYear() {
		return year;
	}
	/**
	 * @param year the year to set
	 */
	public void setYear(long year) {
		this.year = year;
	}
	/**
	 * @return the mstDcpsBillGroup
	 */
	public MstDcpsBillGroup getMstDcpsBillGroup() {
		return mstDcpsBillGroup;
	}
	/**
	 * @param mstDcpsBillGroup the mstDcpsBillGroup to set
	 */
	public void setMstDcpsBillGroup(MstDcpsBillGroup mstDcpsBillGroup) {
		logger.info("mstDcpsBillGroup ******"+mstDcpsBillGroup.getDcpsDdoBillGroupId());
		this.mstDcpsBillGroup = mstDcpsBillGroup;
	}
	/**
	 * @return the paySlipDate
	 */
	public Date getPaySlipDate() {
		return paySlipDate;
	}
	/**
	 * @param paySlipDate the paySlipDate to set
	 */
	public void setPaySlipDate(Date paySlipDate) {
		this.paySlipDate = paySlipDate;
	}
	/**
	 * @return the hrQuaterTypeMst
	 */
	public HrEisQuaterTypeMst getHrQuaterTypeMst() {
		 
		return hrQuaterTypeMst;
	}
	/**
	 * @param hrQuaterTypeMst the hrQuaterTypeMst to set
	 */
	public void setHrQuaterTypeMst(HrEisQuaterTypeMst hrQuaterTypeMst) {
		//logger.info("hrQuaterTypeMst ******"+hrQuaterTypeMst.getQuaId());
		this.hrQuaterTypeMst = hrQuaterTypeMst;
	}
	/**
	 * @return the incrementAmt
	 */
	public long getIncrementAmt() {
		return incrementAmt;
	}
	/**
	 * @param incrementAmt the incrementAmt to set
	 */
	public void setIncrementAmt(long incrementAmt) {
		this.incrementAmt = incrementAmt;
	}
	/**
	 * @return the itAccNo
	 */
	public String getItAccNo() {
		return itAccNo;
	}
	/**
	 * @param itAccNo the itAccNo to set
	 */
	public void setItAccNo(String itAccNo) {
		this.itAccNo = itAccNo;
	}
	/**
	 * @return the gpfAccNo
	 */
	public String getGpfAccNo() {
		return gpfAccNo;
	}
	/**
	 * @param gpfAccNo the gpfAccNo to set
	 */
	public void setGpfAccNo(String gpfAccNo) {
		this.gpfAccNo = gpfAccNo;
	}
	/**
	 * @return the tokenNo
	 */
	public String getTokenNo() {
		return tokenNo;
	}
	/**
	 * @param tokenNo the tokenNo to set
	 */
	public void setTokenNo(String tokenNo) {
		this.tokenNo = tokenNo;
	}
	/**
	 * @return the basicPay
	 */
	public long getBasicPay() {
		return basicPay;
	}
	/**
	 * @param basicPay the basicPay to set
	 */
	public void setBasicPay(long basicPay) {
		this.basicPay = basicPay;
	}
	/**
	 * @return the splPay
	 */
	public long getSplPay() {
		return splPay;
	}
	/**
	 * @param splPay the splPay to set
	 */
	public void setSplPay(long splPay) {
		this.splPay = splPay;
	}
	/**
	 * @return the perPay
	 */
	public long getPerPay() {
		return perPay;
	}
	/**
	 * @param perPay the perPay to set
	 */
	public void setPerPay(long perPay) {
		this.perPay = perPay;
	}
	/**
	 * @return the da
	 */
	public long getDa() {
		return da;
	}
	/**
	 * @param da the da to set
	 */
	public void setDa(long da) {
		this.da = da;
	}
	/**
	 * @return the cla
	 */
	public long getCla() {
		return cla;
	}
	/**
	 * @param cla the cla to set
	 */
	public void setCla(long cla) {
		this.cla = cla;
	}
	/**
	 * @return the hra
	 */
	public long getHra() {
		return hra;
	}
	/**
	 * @param hra the hra to set
	 */
	public void setHra(long hra) {
		this.hra = hra;
	}
	public long getSpecialPayPilot() {
		return specialPayPilot;
	}
	public void setSpecialPayPilot(long specialPayPilot) {
		this.specialPayPilot = specialPayPilot;
	}
	public long getMiliteryPilot() {
		return militeryPilot;
	}
	public void setMiliteryPilot(long militeryPilot) {
		this.militeryPilot = militeryPilot;
	}
	public long getOutfirPilot() {
		return outfirPilot;
	}
	public void setOutfirPilot(long outfirPilot) {
		this.outfirPilot = outfirPilot;
	}
	public long getFlyingAllowPilot() {
		return flyingAllowPilot;
	}
	public void setFlyingAllowPilot(long flyingAllowPilot) {
		this.flyingAllowPilot = flyingAllowPilot;
	}
	public long getInspectionPilot() {
		return inspectionPilot;
	}
	public void setInspectionPilot(long inspectionPilot) {
		this.inspectionPilot = inspectionPilot;
	}
	public long getQualificationPilot() {
		return qualificationPilot;
	}
	public void setQualificationPilot(long qualificationPilot) {
		this.qualificationPilot = qualificationPilot;
	}
	public long getInstructionalPilot() {
		return instructionalPilot;
	}
	public void setInstructionalPilot(long instructionalPilot) {
		this.instructionalPilot = instructionalPilot;
	}
	public long getFlyingPayPilot() {
		return flyingPayPilot;
	}
	public void setFlyingPayPilot(long flyingPayPilot) {
		this.flyingPayPilot = flyingPayPilot;
	}
	public long getKitPilot() {
		return kitPilot;
	}
	public void setKitPilot(long kitPilot) {
		this.kitPilot = kitPilot;
	}
	public long getChplPilot() {
		return chplPilot;
	}
	public void setChplPilot(long chplPilot) {
		this.chplPilot = chplPilot;
	}
	public long getRltPilot() {
		return rltPilot;
	}
	public void setRltPilot(long rltPilot) {
		this.rltPilot = rltPilot;
	}
	public long getIncentiveBdds() {
		return incentiveBdds;
	}
	public void setIncentiveBdds(long incentiveBdds) {
		this.incentiveBdds = incentiveBdds;
	}
	public long getCpf() {
		return cpf;
	}
	public void setCpf(long cpf) {
		this.cpf = cpf;
	}
	/**
	 * @return the ma
	 */
	public long getMa() {
		return ma;
	}
	/**
	 * @param ma the ma to set
	 */
	public void setMa(long ma) {
		this.ma = ma;
	}
	/**
	 * @return the dp
	 */
	public long getDp() {
		return dp;
	}
	/**
	 * @param dp the dp to set
	 */
	public void setDp(long dp) {
		this.dp = dp;
	}
	/**
	 * @return the iTax
	 */
	public long getITax() {
		return ITax;
	}
	/**
	 * @param tax the iTax to set
	 */
	public void setITax(long tax) {
		ITax = tax;
	}
	/**
	 * @return the hrr
	 */
	public long getHrr() {
		return hrr;
	}
	/**
	 * @param hrr the hrr to set
	 */
	public void setHrr(long hrr) {
		this.hrr = hrr;
	}
	/**
	 * @return the pTax
	 */
	public long getPTax() {
		return PTax;
	}
	/**
	 * @param tax the pTax to set
	 */
	public void setPTax(long tax) {
		PTax = tax;
	}
	/**
	 * @return the grossAmt
	 */
	public long getGrossAmt() {
		return grossAmt;
	}
	/**
	 * @param grossAmt the grossAmt to set
	 */
	public void setGrossAmt(long grossAmt) {
		this.grossAmt = grossAmt;
	}
	/**
	 * @return the netTotal
	 */
	public long getNetTotal() {
		return netTotal;
	}
	/**
	 * @param netTotal the netTotal to set
	 */
	public void setNetTotal(long netTotal) {
		this.netTotal = netTotal;
	}
	/**
	 * @return the trnCounter
	 */
	public Integer getTrnCounter() {
		return trnCounter;
	}
	/**
	 * @param trnCounter the trnCounter to set
	 */
	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}
	/**
	 * @return the createdDate
	 */
	public Date getCreatedDate() {
		return createdDate;
	}
	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	/**
	 * @return the updatedDate
	 */
	public Date getUpdatedDate() {
		return updatedDate;
	}
	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	/**
	 * @return the cmnLanguageMst
	 */
	public CmnLanguageMst getCmnLanguageMst() {
		return cmnLanguageMst;
	}
	/**
	 * @param cmnLanguageMst the cmnLanguageMst to set
	 */
	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}
	/**
	 * @return the cmnLocationMst
	 */
	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}
	/**
	 * @param cmnLocationMst the cmnLocationMst to set
	 */
	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}
	/**
	 * @return the cmnDatabaseMst
	 */
	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}
	/**
	 * @param cmnDatabaseMst the cmnDatabaseMst to set
	 */
	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}
	/**
	 * @return the orgPostMstByUpdatedByPost
	 */
	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		
		return orgPostMstByUpdatedByPost;
	}
	/**
	 * @param orgPostMstByUpdatedByPost the orgPostMstByUpdatedByPost to set
	 */
	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		logger.info("orgPostMstByUpdatedByPost ******"+orgPostMstByUpdatedByPost.getPostId());
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}
	/**
	 * @return the orgPostMstByCreatedByPost
	 */
	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}
	/**
	 * @param orgPostMstByCreatedByPost the orgPostMstByCreatedByPost to set
	 */
	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}
	/**
	 * @return the orgUserMstByUpdatedBy
	 */
	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}
	/**
	 * @param orgUserMstByUpdatedBy the orgUserMstByUpdatedBy to set
	 */
	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		logger.info("orgUserMstByUpdatedBy ******"+orgUserMstByUpdatedBy.getUserId());
		
		
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}
	/**
	 * @return the orgUserMstByCreatedBy
	 */
	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}
	/**
	 * @param orgUserMstByCreatedBy the orgUserMstByCreatedBy to set
	 */
	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}
	/**
	 * @return the ta
	 */
	public long getTa() {
		return ta;
	}
	/**
	 * @param ta the ta to set
	 */
	public void setTa(long ta) {
		this.ta = ta;
	}
	/**
	 * @return the arma
	 */
	public long getArma() {
		return arma;
	}
	/**
	 * @param arma the arma to set
	 */
	public void setArma(long arma) {
		this.arma = arma;
	}
	/**
	 * @return the armouera
	 */
	public long getArmouera() {
		return armouera;
	}
	/**
	 * @param armouera the armouera to set
	 */
	public void setArmouera(long armouera) {
		this.armouera = armouera;
	}
	/**
	 * @return the bmia
	 */
	public long getBmia() {
		return bmia;
	}
	/**
	 * @param bmia the bmia to set
	 */
	public void setBmia(long bmia) {
		this.bmia = bmia;
	}
	/**
	 * @return the casha
	 */
	public long getCasha() {
		return casha;
	}
	/**
	 * @param casha the casha to set
	 */
	public void setCasha(long casha) {
		this.casha = casha;
	}
	/**
	 * @return the conva
	 */
	public long getConva() {
		return conva;
	}
	/**
	 * @param conva the conva to set
	 */
	public void setConva(long conva) {
		this.conva = conva;
	}
	/**
	 * @return the cida
	 */
	public long getCida() {
		return cida;
	}
	/**
	 * @param cida the cida to set
	 */
	public void setCida(long cida) {
		this.cida = cida;
	}
	/**
	 * @return the ea
	 */
	public long getEa() {
		return ea;
	}
	/**
	 * @param ea the ea to set
	 */
	public void setEa(long ea) {
		this.ea = ea;
	}
	/**
	 * @return the esisa
	 */
	public long getEsisa() {
		return esisa;
	}
	/**
	 * @param esisa the esisa to set
	 */
	public void setEsisa(long esisa) {
		this.esisa = esisa;
	}
	/**
	 * @return the ela
	 */
	public long getEla() {
		return ela;
	}
	/**
	 * @param ela the ela to set
	 */
	public void setEla(long ela) {
		this.ela = ela;
	}
	/**
	 * @return the fita
	 */
	public long getFita() {
		return fita;
	}
	/**
	 * @param fita the fita to set
	 */
	public void setFita(long fita) {
		this.fita = fita;
	}
	/**
	 * @return the gaa
	 */
	public long getGaa() {
		return gaa;
	}
	/**
	 * @param gaa the gaa to set
	 */
	public void setGaa(long gaa) {
		this.gaa = gaa;
	}
	/**
	 * @return the kma
	 */
	public long getKma() {
		return kma;
	}
	/**
	 * @param kma the kma to set
	 */
	public void setKma(long kma) {
		this.kma = kma;
	}
	/**
	 * @return the lfa
	 */
	public long getLfa() {
		return lfa;
	}
	/**
	 * @param lfa the lfa to set
	 */
	public void setLfa(long lfa) {
		this.lfa = lfa;
	}
	/**
	 * @return the mecha
	 */
	public long getMecha() {
		return mecha;
	}
	/**
	 * @param mecha the mecha to set
	 */
	public void setMecha(long mecha) {
		this.mecha = mecha;
	}
	/**
	 * @return the mea
	 */
	public long getMea() {
		return mea;
	}
	/**
	 * @param mea the mea to set
	 */
	public void setMea(long mea) {
		this.mea = mea;
	}
	/**
	 * @return the naa
	 */
	public long getNaa() {
		return naa;
	}
	/**
	 * @param naa the naa to set
	 */
	public void setNaa(long naa) {
		this.naa = naa;
	}
	/**
	 * @return the mesha
	 */
	public long getMesha() {
		return mesha;
	}
	/**
	 * @param mesha the mesha to set
	 */
	public void setMesha(long mesha) {
		this.mesha = mesha;
	}
	/**
	 * @return the npa
	 */
	public long getNpa() {
		return npa;
	}
	/**
	 * @param npa the npa to set
	 */
	public void setNpa(long npa) {
		this.npa = npa;
	}
	/**
	 * @return the suma
	 */
	public long getSuma() {
		return suma;
	}
	/**
	 * @param suma the suma to set
	 */
	public void setSuma(long suma) {
		this.suma = suma;
	}
	/**
	 * @return the pa
	 */
	public long getPa() {
		return pa;
	}
	/**
	 * @param pa the pa to set
	 */
	public void setPa(long pa) {
		this.pa = pa;
	}
	/**
	 * @return the sda
	 */
	public long getSda() {
		return sda;
	}
	/**
	 * @param sda the sda to set
	 */
	public void setSda(long sda) {
		this.sda = sda;
	}
	/**
	 * @return the oa
	 */
	public long getOa() {
		return oa;
	}
	/**
	 * @param oa the oa to set
	 */
	public void setOa(long oa) {
		this.oa = oa;
	}
	/**
	 * @return the ap
	 */
	public long getAp() {
		return ap;
	}
	/**
	 * @param ap the ap to set
	 */
	public void setAp(long ap) {
		this.ap = ap;
	}
	/**
	 * @return the ua
	 */
	public long getUa() {
		return ua;
	}
	/**
	 * @param ua the ua to set
	 */
	public void setUa(long ua) {
		this.ua = ua;
	}
	/**
	 * @return the techa
	 */
	public long getTecha() {
		return techa;
	}
	/**
	 * @param techa the techa to set
	 */
	public void setTecha(long techa) {
		this.techa = techa;
	}
	/**
	 * @return the taa
	 */
	public long getTaa() {
		return taa;
	}
	/**
	 * @param taa the taa to set
	 */
	public void setTaa(long taa) {
		this.taa = taa;
	}
	/**
	 * @return the ha
	 */
	public long getHa() {
		return ha;
	}
	/**
	 * @param ha the ha to set
	 */
	public void setHa(long ha) {
		this.ha = ha;
	}
	/**
	 * @return the pg
	 */
	public long getPg() {
		return pg;
	}
	/**
	 * @param pg the pg to set
	 */
	public void setPg(long pg) {
		this.pg = pg;
	}
	/**
	 * @return the ats30
	 */
	public long getAts30() {
		return ats30;
	}
	/**
	 * @param ats30 the ats30 to set
	 */
	public void setAts30(long ats30) {
		this.ats30 = ats30;
	}
	/**
	 * @return the ats50
	 */
	public long getAts50() {
		return ats50;
	}
	/**
	 * @param ats50 the ats50 to set
	 */
	public void setAts50(long ats50) {
		this.ats50 = ats50;
	}
	/**
	 * @return the force100
	 */
	public long getForce100() {
		return force100;
	}
	/**
	 * @param force100 the force100 to set
	 */
	public void setForce100(long force100) {
		this.force100 = force100;
	}
	/**
	 * @return the force25
	 */
	public long getForce25() {
		return force25;
	}
	/**
	 * @param force25 the force25 to set
	 */
	public void setForce25(long force25) {
		this.force25 = force25;
	}
	/**
	 * @return the fpa
	 */
	public long getFpa() {
		return fpa;
	}
	/**
	 * @param fpa the fpa to set
	 */
	public void setFpa(long fpa) {
		this.fpa = fpa;
	}
	/**
	 * @return the taforsixth
	 */
	public long getTaforsixth() {
		return taforsixth;
	}
	/**
	 * @param taforsixth the taforsixth to set
	 */
	public void setTaforsixth(long taforsixth) {
		this.taforsixth = taforsixth;
	}
	/**
	 * @return the gpfgrpd
	 */
	public long getGpfgrpd() {
		return gpfgrpd;
	}
	/**
	 * @param gpfgrpd the gpfgrpd to set
	 */
	public void setGpfgrpd(long gpfgrpd) {
		this.gpfgrpd = gpfgrpd;
	}
	/**
	 * @return the pli
	 */
	public long getPli() {
		return pli;
	}
	/**
	 * @param pli the pli to set
	 */
	public void setPli(long pli) {
		this.pli = pli;
	}
	/**
	 * @return the dcps
	 */
	public long getDcps() {
		return dcps;
	}
	/**
	 * @param dcps the dcps to set
	 */
	public void setDcps(long dcps) {
		this.dcps = dcps;
	}
	/**
	 * @return the dcpsDelay
	 */
	public long getDcpsDelay() {
		return dcpsDelay;
	}
	/**
	 * @param dcpsDelay the dcpsDelay to set
	 */
	public void setDcpsDelay(long dcpsDelay) {
		this.dcpsDelay = dcpsDelay;
	}
	/**
	 * @return the dcpsPay
	 */
	public long getDcpsPay() {
		return dcpsPay;
	}
	/**
	 * @param dcpsPay the dcpsPay to set
	 */
	public void setDcpsPay(long dcpsPay) {
		this.dcpsPay = dcpsPay;
	}
	/**
	 * @return the dcpsDA
	 */
	public long getDcpsDA() {
		return dcpsDA;
	}
	/**
	 * @param dcpsDA the dcpsDA to set
	 */
	public void setDcpsDA(long dcpsDA) {
		this.dcpsDA = dcpsDA;
	}
	/**
	 * @return the gpfgrpbac
	 */
	public long getGpfgrpbac() {
		return gpfgrpbac;
	}
	/**
	 * @param gpfgrpbac the gpfgrpbac to set
	 */
	public void setGpfgrpbac(long gpfgrpbac) {
		this.gpfgrpbac = gpfgrpbac;
	}
	/**
	 * @return the gpfiasos
	 */
	public long getGpfiasos() {
		return gpfiasos;
	}
	/**
	 * @param gpfiasos the gpfiasos to set
	 */
	public void setGpfiasos(long gpfiasos) {
		this.gpfiasos = gpfiasos;
	}
	/**
	 * @return the gpfias
	 */
	public long getGpfias() {
		return gpfias;
	}
	/**
	 * @param gpfias the gpfias to set
	 */
	public void setGpfias(long gpfias) {
		this.gpfias = gpfias;
	}
	/**
	 * @return the gpfips
	 */
	public long getGpfips() {
		return gpfips;
	}
	/**
	 * @param gpfips the gpfips to set
	 */
	public void setGpfips(long gpfips) {
		this.gpfips = gpfips;
	}
	/**
	 * @return the gpfifs
	 */
	public long getGpfifs() {
		return gpfifs;
	}
	/**
	 * @param gpfifs the gpfifs to set
	 */
	public void setGpfifs(long gpfifs) {
		this.gpfifs = gpfifs;
	}
	/**
	 * @return the servc
	 */
	public long getServc() {
		return servc;
	}
	/**
	 * @param servc the servc to set
	 */
	public void setServc(long servc) {
		this.servc = servc;
	}
	/**
	 * @return the otherd
	 */
	public long getOtherd() {
		return otherd;
	}
	/**
	 * @param otherd the otherd to set
	 */
	public void setOtherd(long otherd) {
		this.otherd = otherd;
	}
	/**
	 * @return the gisias
	 */
	public long getGisias() {
		return gisias;
	}
	/**
	 * @param gisias the gisias to set
	 */
	public void setGisias(long gisias) {
		this.gisias = gisias;
	}
	/**
	 * @return the gisips
	 */
	public long getGisips() {
		return gisips;
	}
	/**
	 * @param gisips the gisips to set
	 */
	public void setGisips(long gisips) {
		this.gisips = gisips;
	}
	/**
	 * @return the gisifs
	 */
	public long getGisifs() {
		return gisifs;
	}
	/**
	 * @param gisifs the gisifs to set
	 */
	public void setGisifs(long gisifs) {
		this.gisifs = gisifs;
	}
	/**
	 * @return the gis
	 */
	public long getGis() {
		return gis;
	}
	/**
	 * @param gis the gis to set
	 */
	public void setGis(long gis) {
		this.gis = gis;
	}
	/**
	 * @return the cgegis
	 */
	public long getCgegis() {
		return cgegis;
	}
	/**
	 * @param cgegis the cgegis to set
	 */
	public void setCgegis(long cgegis) {
		this.cgegis = cgegis;
	}
	/**
	 * @return the giszp
	 */
	public long getGiszp() {
		return giszp;
	}
	/**
	 * @param giszp the giszp to set
	 */
	public void setGiszp(long giszp) {
		this.giszp = giszp;
	}
	/**
	 * @return the gpfabcmr
	 */
	public long getGpfabcmr() {
		return gpfabcmr;
	}
	/**
	 * @param gpfabcmr the gpfabcmr to set
	 */
	public void setGpfabcmr(long gpfabcmr) {
		this.gpfabcmr = gpfabcmr;
	}
	/**
	 * @return the gpfdmr
	 */
	public long getGpfdmr() {
		return gpfdmr;
	}
	/**
	 * @param gpfdmr the gpfdmr to set
	 */
	public void setGpfdmr(long gpfdmr) {
		this.gpfdmr = gpfdmr;
	}
	/**
	 * @return the gpfiasmr
	 */
	public long getGpfiasmr() {
		return gpfiasmr;
	}
	/**
	 * @param gpfiasmr the gpfiasmr to set
	 */
	public void setGpfiasmr(long gpfiasmr) {
		this.gpfiasmr = gpfiasmr;
	}
	/**
	 * @return the gpfipsmr
	 */
	public long getGpfipsmr() {
		return gpfipsmr;
	}
	/**
	 * @param gpfipsmr the gpfipsmr to set
	 */
	public void setGpfipsmr(long gpfipsmr) {
		this.gpfipsmr = gpfipsmr;
	}
	/**
	 * @return the gpfifsmr
	 */
	public long getGpfifsmr() {
		return gpfifsmr;
	}
	/**
	 * @param gpfifsmr the gpfifsmr to set
	 */
	public void setGpfifsmr(long gpfifsmr) {
		this.gpfifsmr = gpfifsmr;
	}
	/**
	 * @return the hrrarr
	 */
	public long getHrrarr() {
		return hrrarr;
	}
	/**
	 * @param hrrarr the hrrarr to set
	 */
	public void setHrrarr(long hrrarr) {
		this.hrrarr = hrrarr;
	}
	/**
	 * @return the janjulgisa
	 */
	public long getJanjulgisa() {
		return janjulgisa;
	}
	/**
	 * @param janjulgisa the janjulgisa to set
	 */
	public void setJanjulgisa(long janjulgisa) {
		this.janjulgisa = janjulgisa;
	}
	/**
	 * @return the janjulgis
	 */
	public long getJanjulgis() {
		return janjulgis;
	}
	/**
	 * @param janjulgis the janjulgis to set
	 */
	public void setJanjulgis(long janjulgis) {
		this.janjulgis = janjulgis;
	}
	/**
	 * @return the msli
	 */
	public long getMsli() {
		return msli;
	}
	/**
	 * @param msli the msli to set
	 */
	public void setMsli(long msli) {
		this.msli = msli;
	}
	/**
	 * @return the or
	 */
	public long getOr() {
		return or;
	}
	/**
	 * @param or the or to set
	 */
	public void setOr(long or) {
		this.or = or;
	}
	/**
	 * @return the ptarr
	 */
	public long getPtarr() {
		return ptarr;
	}
	/**
	 * @param ptarr the ptarr to set
	 */
	public void setPtarr(long ptarr) {
		this.ptarr = ptarr;
	}
	/**
	 * @return the odtr
	 */
	public long getOdtr() {
		return odtr;
	}
	/**
	 * @param odtr the odtr to set
	 */
	public void setOdtr(long odtr) {
		this.odtr = odtr;
	}
	/**
	 * @return the otherVehical
	 */
	public long getOtherVehical() {
		return otherVehical;
	}
	/**
	 * @param otherVehical the otherVehical to set
	 */
	public void setOtherVehical(long otherVehical) {
		this.otherVehical = otherVehical;
	}
	/**
	 * @return the hbaLand
	 */
	public long getHbaLand() {
		return hbaLand;
	}
	/**
	 * @param hbaLand the hbaLand to set
	 */
	public void setHbaLand(long hbaLand) {
		this.hbaLand = hbaLand;
	}
	/**
	 * @return the mcaLand
	 */
	public long getMcaLand() {
		return mcaLand;
	}
	/**
	 * @param mcaLand the mcaLand to set
	 */
	public void setMcaLand(long mcaLand) {
		this.mcaLand = mcaLand;
	}
	/**
	 * @return the coHsgSoc
	 */
	public long getCoHsgSoc() {
		return coHsgSoc;
	}
	/**
	 * @param coHsgSoc the coHsgSoc to set
	 */
	public void setCoHsgSoc(long coHsgSoc) {
		this.coHsgSoc = coHsgSoc;
	}
	/**
	 * @return the compAdvance
	 */
	public long getCompAdvance() {
		return compAdvance;
	}
	/**
	 * @param compAdvance the compAdvance to set
	 */
	public void setCompAdvance(long compAdvance) {
		this.compAdvance = compAdvance;
	}
	/**
	 * @return the hbaAis
	 */
	public long getHbaAis() {
		return hbaAis;
	}
	/**
	 * @param hbaAis the hbaAis to set
	 */
	public void setHbaAis(long hbaAis) {
		this.hbaAis = hbaAis;
	}
	/**
	 * @return the mcaAis
	 */
	public long getMcaAis() {
		return mcaAis;
	}
	/**
	 * @param mcaAis the mcaAis to set
	 */
	public void setMcaAis(long mcaAis) {
		this.mcaAis = mcaAis;
	}
	/**
	 * @return the compAis
	 */
	public long getCompAis() {
		return compAis;
	}
	/**
	 * @param compAis the compAis to set
	 */
	public void setCompAis(long compAis) {
		this.compAis = compAis;
	}
	/**
	 * @return the otherAdv
	 */
	public long getOtherAdv() {
		return otherAdv;
	}
	/**
	 * @param otherAdv the otherAdv to set
	 */
	public void setOtherAdv(long otherAdv) {
		this.otherAdv = otherAdv;
	}
	/**
	 * @return the hbaHouse
	 */
	public long getHbaHouse() {
		return hbaHouse;
	}
	/**
	 * @param hbaHouse the hbaHouse to set
	 */
	public void setHbaHouse(long hbaHouse) {
		this.hbaHouse = hbaHouse;
	}
	/**
	 * @return the payAdv
	 */
	public long getPayAdv() {
		return payAdv;
	}
	/**
	 * @param payAdv the payAdv to set
	 */
	public void setPayAdv(long payAdv) {
		this.payAdv = payAdv;
	}
	/**
	 * @return the fA
	 */
	public long getFA() {
		return FA;
	}
	/**
	 * @param fa the fA to set
	 */
	public void setFA(long fa) {
		FA = fa;
	}
	/**
	 * @return the tA
	 */
	public long getTA() {
		return TA;
	}
	/**
	 * @param ta the tA to set
	 */
	public void setTA(long ta) {
		TA = ta;
	}
	/**
	 * @return the gPFADVABC
	 */
	public long getGPFADVABC() {
		return GPFADVABC;
	}
	/**
	 * @param gpfadvabc the gPFADVABC to set
	 */
	public void setGPFADVABC(long gpfadvabc) {
		GPFADVABC = gpfadvabc;
	}
	/**
	 * @return the gPFADVD
	 */
	public long getGPFADVD() {
		return GPFADVD;
	}
	/**
	 * @param gpfadvd the gPFADVD to set
	 */
	public void setGPFADVD(long gpfadvd) {
		GPFADVD = gpfadvd;
	}
	/**
	 * @return the gPFIASAdv
	 */
	public long getGPFIASAdv() {
		return GPFIASAdv;
	}
	/**
	 * @param adv the gPFIASAdv to set
	 */
	public void setGPFIASAdv(long adv) {
		GPFIASAdv = adv;
	}
	/**
	 * @return the gPFOSAdv
	 */
	public long getGPFOSAdv() {
		return GPFOSAdv;
	}
	/**
	 * @param adv the gPFOSAdv to set
	 */
	public void setGPFOSAdv(long adv) {
		GPFOSAdv = adv;
	}
	/**
	 * @return the excPayRcAdv
	 */
	public long getExcPayRcAdv() {
		return ExcPayRcAdv;
	}
	/**
	 * @param excPayRcAdv the excPayRcAdv to set
	 */
	public void setExcPayRcAdv(long excPayRcAdv) {
		ExcPayRcAdv = excPayRcAdv;
	}
	  	
	private long transAllowArr;
	
	public long getTransAllowArr() {
		return transAllowArr;
	}
	public void setTransAllowArr(long transAllowArr) {
		this.transAllowArr = transAllowArr;
	}
	
private long groupAcciPolicy;
	
	public long getGroupAcciPolicy() {
		return groupAcciPolicy;
	}
	public void setGroupAcciPolicy(long groupAcciPolicy) {
		this.groupAcciPolicy = groupAcciPolicy;
	}

	private long cpfContribution;
	private long cpfEmployee;
	private long cpfEmployer;

	public long getCpfEmployee() {
		return cpfEmployee;
	}
	public void setCpfEmployee(long cpfEmployee) {
		this.cpfEmployee = cpfEmployee;
	}
	public long getCpfEmployer() {
		return cpfEmployer;
	}
	public void setCpfEmployer(long cpfEmployer) {
		this.cpfEmployer = cpfEmployer;
	}
	public long getCpfContribution() {
		return cpfContribution;
	}
	public void setCpfContribution(long cpfContribution) {
		this.cpfContribution = cpfContribution;
	}
	//added by lekhchand  seven pc TA
		private long SVNPC_TA;
	public long getSVNPC_TA() {
		return SVNPC_TA;
	}
	public void setSVNPC_TA(long sVNPC_TA) {
		SVNPC_TA = sVNPC_TA;
	}
// added lekhchand by gpf and ta arrear component 04112022
	private long SVNPC_GPF_ARR;//7th PC GPF Arrears
	private long SVNPC_DCPS_ARR;//7th PC DCPS Arrears	
	private long SVNPC_TA_ARR;//7th PC TA Arrears
	private long SVNPC_GPF_ARR_DEDU;//7th PC GPF Arrears Deduction	
	private long SVNPC_GPF_RECO;//7th PC GPF Arrears Deduction	
	private long SVNPC_DCPS_RECO;//7th PC GPF Arrears Deduction	
	public long getSVNPC_GPF_ARR() {
		return SVNPC_GPF_ARR;
	}
	public void setSVNPC_GPF_ARR(long sVNPC_GPF_ARR) {
		SVNPC_GPF_ARR = sVNPC_GPF_ARR;
	}
	public long getSVNPC_DCPS_ARR() {
		return SVNPC_DCPS_ARR;
	}
	public void setSVNPC_DCPS_ARR(long sVNPC_DCPS_ARR) {
		SVNPC_DCPS_ARR = sVNPC_DCPS_ARR;
	}
	public long getSVNPC_TA_ARR() {
		return SVNPC_TA_ARR;
	}
	public void setSVNPC_TA_ARR(long sVNPC_TA_ARR) {
		SVNPC_TA_ARR = sVNPC_TA_ARR;
	}
	public long getSVNPC_GPF_ARR_DEDU() {
		return SVNPC_GPF_ARR_DEDU;
	}
	public void setSVNPC_GPF_ARR_DEDU(long sVNPC_GPF_ARR_DEDU) {
		SVNPC_GPF_ARR_DEDU = sVNPC_GPF_ARR_DEDU;
	}
	public long getSVNPC_GPF_RECO() {
		return SVNPC_GPF_RECO;
	}
	public void setSVNPC_GPF_RECO(long sVNPC_GPF_RECO) {
		SVNPC_GPF_RECO = sVNPC_GPF_RECO;
	}
	public long getSVNPC_DCPS_RECO() {
		return SVNPC_DCPS_RECO;
	} 
	public void setSVNPC_DCPS_RECO(long sVNPC_DCPS_RECO) {
		SVNPC_DCPS_RECO = sVNPC_DCPS_RECO;
	}
		
	private long npsNpsAllowance;
	 
	public long getNpsNpsAllowance() {
		return npsNpsAllowance;
	}
	public void setNpsNpsAllowance(long npsNpsAllowance) {
		this.npsNpsAllowance = npsNpsAllowance;
	}

	private long npsDeduction;
	public long getNpsDeduction() {
		return npsDeduction;
	}
	public void setNpsDeduction(long npsDeduction) {
		this.npsDeduction = npsDeduction;
	}
	
		
}
