package com.tcs.sgv.stamp.valueobject;
// Generated Oct 15, 2007 12:20:22 PM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;

/**
 * StampIndentDtls generated by hbm2java
 */
public class StampIndentDtls implements java.io.Serializable {

	// Fields    

	private BigDecimal indDtlsId;

	private BigDecimal indId;

	private Byte indGrpCode;

	private Integer indDnmCode;

	private Integer indQty;

	private Integer indPqty;

	private Integer indRqty;

	private String indRemarks;

	private String indConsolidate;

	private BigDecimal indPrevStock;

	private Integer indPrevRcpt;

	private Integer indPrevIssued;

	private BigDecimal indPrevClosingBal;

	private BigDecimal indPrevQtyDue;

	// Constructors

	/** default constructor */
	public StampIndentDtls() {
	}

	/** minimal constructor */
	public StampIndentDtls(BigDecimal indDtlsId, BigDecimal indId) {
		this.indDtlsId = indDtlsId;
		this.indId = indId;
	}

	/** full constructor */
	public StampIndentDtls(BigDecimal indDtlsId, BigDecimal indId,
			Byte indGrpCode, Integer indDnmCode, Integer indQty,
			Integer indPqty, Integer indRqty, String indRemarks,
			String indConsolidate, BigDecimal indPrevStock,
			Integer indPrevRcpt, Integer indPrevIssued,
			BigDecimal indPrevClosingBal, BigDecimal indPrevQtyDue) {
		this.indDtlsId = indDtlsId;
		this.indId = indId;
		this.indGrpCode = indGrpCode;
		this.indDnmCode = indDnmCode;
		this.indQty = indQty;
		this.indPqty = indPqty;
		this.indRqty = indRqty;
		this.indRemarks = indRemarks;
		this.indConsolidate = indConsolidate;
		this.indPrevStock = indPrevStock;
		this.indPrevRcpt = indPrevRcpt;
		this.indPrevIssued = indPrevIssued;
		this.indPrevClosingBal = indPrevClosingBal;
		this.indPrevQtyDue = indPrevQtyDue;
	}

	// Property accessors
	public BigDecimal getIndDtlsId() {
		return this.indDtlsId;
	}

	public void setIndDtlsId(BigDecimal indDtlsId) {
		this.indDtlsId = indDtlsId;
	}

	public BigDecimal getIndId() {
		return this.indId;
	}

	public void setIndId(BigDecimal indId) {
		this.indId = indId;
	}

	public Byte getIndGrpCode() {
		return this.indGrpCode;
	}

	public void setIndGrpCode(Byte indGrpCode) {
		this.indGrpCode = indGrpCode;
	}

	public Integer getIndDnmCode() {
		return this.indDnmCode;
	}

	public void setIndDnmCode(Integer indDnmCode) {
		this.indDnmCode = indDnmCode;
	}

	public Integer getIndQty() {
		return this.indQty;
	}

	public void setIndQty(Integer indQty) {
		this.indQty = indQty;
	}

	public Integer getIndPqty() {
		return this.indPqty;
	}

	public void setIndPqty(Integer indPqty) {
		this.indPqty = indPqty;
	}

	public Integer getIndRqty() {
		return this.indRqty;
	}

	public void setIndRqty(Integer indRqty) {
		this.indRqty = indRqty;
	}

	public String getIndRemarks() {
		return this.indRemarks;
	}

	public void setIndRemarks(String indRemarks) {
		this.indRemarks = indRemarks;
	}

	public String getIndConsolidate() {
		return this.indConsolidate;
	}

	public void setIndConsolidate(String indConsolidate) {
		this.indConsolidate = indConsolidate;
	}

	public BigDecimal getIndPrevStock() {
		return this.indPrevStock;
	}

	public void setIndPrevStock(BigDecimal indPrevStock) {
		this.indPrevStock = indPrevStock;
	}

	public Integer getIndPrevRcpt() {
		return this.indPrevRcpt;
	}

	public void setIndPrevRcpt(Integer indPrevRcpt) {
		this.indPrevRcpt = indPrevRcpt;
	}

	public Integer getIndPrevIssued() {
		return this.indPrevIssued;
	}

	public void setIndPrevIssued(Integer indPrevIssued) {
		this.indPrevIssued = indPrevIssued;
	}

	public BigDecimal getIndPrevClosingBal() {
		return this.indPrevClosingBal;
	}

	public void setIndPrevClosingBal(BigDecimal indPrevClosingBal) {
		this.indPrevClosingBal = indPrevClosingBal;
	}

	public BigDecimal getIndPrevQtyDue() {
		return this.indPrevQtyDue;
	}

	public void setIndPrevQtyDue(BigDecimal indPrevQtyDue) {
		this.indPrevQtyDue = indPrevQtyDue;
	}

}
