package com.tcs.sgv.common.loan.valueobject;

// Generated Jul 27, 2007 2:58:32 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;
 /**
 * HrLoanAdvMst generated by hbm2java
 */
public class HrLoanAdvMst {

	// Fields    

	private long loanAdvId;

	private String loanAdvName;

	private long maxNoInstallAmt;

	private long maxNoInstInterest;
	
	private long minNoInstInterest;
	

	
	


	/**
	 * @return the minNoInstInterest
	 */
	public long getMinNoInstInterest() {
		return minNoInstInterest;
	}

	/**
	 * @param minNoInstInterest the minNoInstInterest to set
	 */
	public void setMinNoInstInterest(long minNoInstInterest) {
		this.minNoInstInterest = minNoInstInterest;
	}

	private Long parentLoanId;
	

	private Date createdDate;

	

	private Date updatedDate;

	
	
	
	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;
	
	private CmnLanguageMst cmnLanguageMst;
	
	private Set hrLoanEmpDtlses = new HashSet(0);
	
	private Set hrLoanEmpPrinRecoverDtlses = new HashSet(0);
	
	private Set hrLoanEmpIntRecoverDtlses = new HashSet(0);
	
	long elementCode;
	
	private CmnLookupMst displayGroup;
	// Constructors

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	/** default constructor */
	public HrLoanAdvMst() {
	}

	/** minimal constructor */
	public HrLoanAdvMst(long loanAdvId) {
		this.loanAdvId = loanAdvId;
	}
	
	
	/** full constructor */
	public HrLoanAdvMst(long loanAdvId, String loanAdvName,
			long maxNoInstallAmt, long maxNoInstInterest,long minNoInstInterest,Long parentLoanId,
			CmnLanguageMst cmnLanguageMst,
			long dbId, long locId, long createdBy,
			Date createdDate, long createdByPost, long updatedBy,
			Date updatedDate, long updatedByPost,Set hrLoanEmpDtlses,Set hrLoanEmpPrinRecoverDtlses,
			Set hrLoanEmpIntRecoverDtlses) {
		this.loanAdvId = loanAdvId;
		this.loanAdvName = loanAdvName;
		this.maxNoInstallAmt = maxNoInstallAmt;
		this.maxNoInstInterest = maxNoInstInterest;	
		this.minNoInstInterest = minNoInstInterest;	
		this.parentLoanId = parentLoanId;
		this.createdDate = createdDate;				
		this.updatedDate = updatedDate;	
		
		
		this.cmnLanguageMst = cmnLanguageMst;
		
	}

	// Property accessors
	public long getLoanAdvId() {
		return this.loanAdvId;
	}

	public void setLoanAdvId(long loanAdvId) {
		this.loanAdvId = loanAdvId;
	}

	public String getLoanAdvName() {
		return this.loanAdvName;
	}

	public void setLoanAdvName(String loanAdvName) {
		this.loanAdvName = loanAdvName;
	}

	public long getMaxNoInstallAmt() {
		return this.maxNoInstallAmt;
	}

	public void setMaxNoInstallAmt(long maxNoInstallAmt) {
		this.maxNoInstallAmt = maxNoInstallAmt;
	}

	public long getMaxNoInstInterest() {
		return this.maxNoInstInterest;
	}

	public void setMaxNoInstInterest(long maxNoInstInterest) {
		this.maxNoInstInterest = maxNoInstInterest;
	}

	
	public Long getParentLoanId() {
		return parentLoanId;
	}

	public void setParentLoanId(Long parentLoanId) {
		this.parentLoanId = parentLoanId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public long getElementCode() {
		return elementCode;
	}

	public void setElementCode(long elementCode) {
		this.elementCode = elementCode;
	}

	public Set getHrLoanEmpDtlses() {
		return hrLoanEmpDtlses;
	}

	public void setHrLoanEmpDtlses(Set hrLoanEmpDtlses) {
		this.hrLoanEmpDtlses = hrLoanEmpDtlses;
	}

	public Set getHrLoanEmpIntRecoverDtlses() {
		return hrLoanEmpIntRecoverDtlses;
	}

	public void setHrLoanEmpIntRecoverDtlses(Set hrLoanEmpIntRecoverDtlses) {
		this.hrLoanEmpIntRecoverDtlses = hrLoanEmpIntRecoverDtlses;
	}

	public Set getHrLoanEmpPrinRecoverDtlses() {
		return hrLoanEmpPrinRecoverDtlses;
	}

	public void setHrLoanEmpPrinRecoverDtlses(Set hrLoanEmpPrinRecoverDtlses) {
		this.hrLoanEmpPrinRecoverDtlses = hrLoanEmpPrinRecoverDtlses;
	}

	/**
	 * @return the deductionBy
	 */
	public CmnLookupMst getDisplayGroup() {
		return displayGroup;
	}

	/**
	 * @param deductionBy the deductionBy to set
	 */
	public void setDisplayGroup(CmnLookupMst displayGroup) {
		this.displayGroup = displayGroup;
	}


	
	
}
