// Generated Oct 5, 2007 5:48:42 AM by Hibernate Tools 3.2.0.beta8
package com.tcs.sgv.payfixation.valueobject;

import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrPayfixMst generated by hbm2java
 */
@SuppressWarnings("serial")
public class HrPayfixMst implements java.io.Serializable
{

	// Fields    
	private Long payfixId;
	private OrgUserMst userId;

	private Date payFixDate;

	private Date nxtIncrDate;

	private String remarks;

	private String status;

	private CmnLanguageMst cmnLanguageMst;

	private CmnDatabaseMst cmnDatabaseMst;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstCreatedBy;

	private OrgPostMst orgPostMstCreatedByPost;

	private Date createdDate;

	private OrgUserMst orgUserMstUpdatedBy;

	private OrgPostMst orgPostMstUpdatedByPost;

	private Date updatedDate;

	private Long newBasic;

	private String incrementOrderNo;

	private Date incrementOrderDate;

	private Long oldBasic;

	private int activateFlag;

	private Long trnCounter;

	private Long payCommissionId;

	// Constructors

	public Long getPayCommissionId()
	{
		return payCommissionId;
	}

	public void setPayCommissionId(Long payCommissionId)
	{
		this.payCommissionId = payCommissionId;
	}

	public Long getTrnCounter()
	{
		return trnCounter;
	}

	public void setTrnCounter(Long trnCounter)
	{
		this.trnCounter = trnCounter;
	}

	/** default constructor */
	public HrPayfixMst()
	{}

	/** minimal constructor */
	public HrPayfixMst(OrgUserMst userId)
	{
		this.userId = userId;
	}

	/** full constructor */
	public HrPayfixMst(OrgUserMst userId, Date payFixDate, Date nxtIncrDate, String remarks, String status, CmnLanguageMst cmnLanguageMst, CmnDatabaseMst cmnDatabaseMst, CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstCreatedBy, OrgPostMst orgPostMstCreatedByPost, Date createdDate, OrgUserMst orgUserMstUpdatedBy, OrgPostMst orgPostMstUpdatedByPost, Date updatedDate, Long newBasic, String incrementOrderNo, Date incrementOrderDate, Long oldBasic)
	{
		this.userId = userId;
		this.payFixDate = payFixDate;
		this.nxtIncrDate = nxtIncrDate;
		this.remarks = remarks;
		this.status = status;
		this.cmnLanguageMst = cmnLanguageMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstCreatedBy = orgUserMstCreatedBy;
		this.orgPostMstCreatedByPost = orgPostMstCreatedByPost;
		this.createdDate = createdDate;
		this.orgUserMstUpdatedBy = orgUserMstUpdatedBy;
		this.orgPostMstUpdatedByPost = orgPostMstUpdatedByPost;
		this.updatedDate = updatedDate;

		this.newBasic = newBasic;
		this.incrementOrderNo = incrementOrderNo;
		this.incrementOrderDate = incrementOrderDate;
		this.oldBasic = oldBasic;
	}

	/**
	 * @return the payfixId
	 */
	public Long getPayfixId()
	{
		return payfixId;
	}

	/**
	 * @param payfixId the payfixId to set
	 */
	public void setPayfixId(Long payfixId)
	{
		this.payfixId = payfixId;
	}

	/**
	 * @return the userId
	 */
	public OrgUserMst getUserId()
	{
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(OrgUserMst userId)
	{
		this.userId = userId;
	}

	/**
	 * @return the payFixDate
	 */
	public Date getPayFixDate()
	{
		return payFixDate;
	}

	/**
	 * @param payFixDate the payFixDate to set
	 */
	public void setPayFixDate(Date payFixDate)
	{
		this.payFixDate = payFixDate;
	}

	/**
	 * @return the nxtIncrDate
	 */
	public Date getNxtIncrDate()
	{
		return nxtIncrDate;
	}

	/**
	 * @param nxtIncrDate the nxtIncrDate to set
	 */
	public void setNxtIncrDate(Date nxtIncrDate)
	{
		this.nxtIncrDate = nxtIncrDate;
	}

	/**
	 * @return the remarks
	 */
	public String getRemarks()
	{
		return remarks;
	}

	/**
	 * @param remarks the remarks to set
	 */
	public void setRemarks(String remarks)
	{
		this.remarks = remarks;
	}

	/**
	 * @return the status
	 */
	public String getStatus()
	{
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(String status)
	{
		this.status = status;
	}

	/**
	 * @return the cmnLanguageMst
	 */
	public CmnLanguageMst getCmnLanguageMst()
	{
		return cmnLanguageMst;
	}

	/**
	 * @param cmnLanguageMst the cmnLanguageMst to set
	 */
	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst)
	{
		this.cmnLanguageMst = cmnLanguageMst;
	}

	/**
	 * @return the cmnDatabaseMst
	 */
	public CmnDatabaseMst getCmnDatabaseMst()
	{
		return cmnDatabaseMst;
	}

	/**
	 * @param cmnDatabaseMst the cmnDatabaseMst to set
	 */
	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst)
	{
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	/**
	 * @return the cmnLocationMst
	 */
	public CmnLocationMst getCmnLocationMst()
	{
		return cmnLocationMst;
	}

	/**
	 * @param cmnLocationMst the cmnLocationMst to set
	 */
	public void setCmnLocationMst(CmnLocationMst cmnLocationMst)
	{
		this.cmnLocationMst = cmnLocationMst;
	}

	/**
	 * @return the orgUserMstCreatedBy
	 */
	public OrgUserMst getOrgUserMstCreatedBy()
	{
		return orgUserMstCreatedBy;
	}

	/**
	 * @param orgUserMstCreatedBy the orgUserMstCreatedBy to set
	 */
	public void setOrgUserMstCreatedBy(OrgUserMst orgUserMstCreatedBy)
	{
		this.orgUserMstCreatedBy = orgUserMstCreatedBy;
	}

	/**
	 * @return the orgPostMstCreatedByPost
	 */
	public OrgPostMst getOrgPostMstCreatedByPost()
	{
		return orgPostMstCreatedByPost;
	}

	/**
	 * @param orgPostMstCreatedByPost the orgPostMstCreatedByPost to set
	 */
	public void setOrgPostMstCreatedByPost(OrgPostMst orgPostMstCreatedByPost)
	{
		this.orgPostMstCreatedByPost = orgPostMstCreatedByPost;
	}

	/**
	 * @return the createdDate
	 */
	public Date getCreatedDate()
	{
		return createdDate;
	}

	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate)
	{
		this.createdDate = createdDate;
	}

	/**
	 * @return the orgUserMstUpdatedBy
	 */
	public OrgUserMst getOrgUserMstUpdatedBy()
	{
		return orgUserMstUpdatedBy;
	}

	/**
	 * @param orgUserMstUpdatedBy the orgUserMstUpdatedBy to set
	 */
	public void setOrgUserMstUpdatedBy(OrgUserMst orgUserMstUpdatedBy)
	{
		this.orgUserMstUpdatedBy = orgUserMstUpdatedBy;
	}

	/**
	 * @return the orgPostMstUpdatedByPost
	 */
	public OrgPostMst getOrgPostMstUpdatedByPost()
	{
		return orgPostMstUpdatedByPost;
	}

	/**
	 * @param orgPostMstUpdatedByPost the orgPostMstUpdatedByPost to set
	 */
	public void setOrgPostMstUpdatedByPost(OrgPostMst orgPostMstUpdatedByPost)
	{
		this.orgPostMstUpdatedByPost = orgPostMstUpdatedByPost;
	}

	/**
	 * @return the updatedDate
	 */
	public Date getUpdatedDate()
	{
		return updatedDate;
	}

	/**
	 * @param updatedDate the updatedDate to set
	 */
	public void setUpdatedDate(Date updatedDate)
	{
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the newBasic
	 */
	public Long getNewBasic()
	{
		return newBasic;
	}

	/**
	 * @param newBasic the newBasic to set
	 */
	public void setNewBasic(Long newBasic)
	{
		this.newBasic = newBasic;
	}

	/**
	 * @return the incrementOrderNo
	 */
	public String getIncrementOrderNo()
	{
		return incrementOrderNo;
	}

	/**
	 * @param incrementOrderNo the incrementOrderNo to set
	 */
	public void setIncrementOrderNo(String incrementOrderNo)
	{
		this.incrementOrderNo = incrementOrderNo;
	}

	/**
	 * @return the incrementOrderDate
	 */
	public Date getIncrementOrderDate()
	{
		return incrementOrderDate;
	}

	/**
	 * @param incrementOrderDate the incrementOrderDate to set
	 */
	public void setIncrementOrderDate(Date incrementOrderDate)
	{
		this.incrementOrderDate = incrementOrderDate;
	}

	/**
	 * @return the oldBasic
	 */
	public Long getOldBasic()
	{
		return oldBasic;
	}

	/**
	 * @param oldBasic the oldBasic to set
	 */
	public void setOldBasic(Long oldBasic)
	{
		this.oldBasic = oldBasic;
	}

	/**
	 * @return the activateFlag
	 */
	public int getActivateFlag()
	{
		return activateFlag;
	}

	/**
	 * @param activateFlag the activateFlag to set
	 */
	public void setActivateFlag(int activateFlag)
	{
		this.activateFlag = activateFlag;
	}

}
