package com.tcs.sgv.payfixation.valueobject;

// default package
// Generated 16 Jun, 2012 3:01:09 PM by Hibernate Tools 3.2.2.GA

/**
 * HrPayfixMstHstId generated by hbm2java
 */
@SuppressWarnings("serial")
public class HrPayfixMstHstId implements java.io.Serializable
{

	private long payfixId;
	private long trnCounter;

	public HrPayfixMstHstId()
	{}

	public HrPayfixMstHstId(long payfixId, long trnCounter)
	{
		this.payfixId = payfixId;
		this.trnCounter = trnCounter;
	}

	public long getPayfixId()
	{
		return this.payfixId;
	}

	public void setPayfixId(long payfixId)
	{
		this.payfixId = payfixId;
	}

	public long getTrnCounter()
	{
		return this.trnCounter;
	}

	public void setTrnCounter(long trnCounter)
	{
		this.trnCounter = trnCounter;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HrPayfixMstHstId))
			return false;
		HrPayfixMstHstId castOther = (HrPayfixMstHstId) other;

		return (this.getPayfixId() == castOther.getPayfixId()) && (this.getTrnCounter() == castOther.getTrnCounter());
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result + (int) this.getPayfixId();
		result = 37 * result + (int) this.getTrnCounter();
		return result;
	}

}
