package com.tcs.sgv.common.valueobject;

// Generated May 28, 2007 3:09:55 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * MstAttachment generated by hbm2java
 */
public class MstAttachment implements java.io.Serializable {

	// Fields    

	private long attachId;

	private String attachDesc;

	private long attachType;

	private Long langId;

	private long activateFlag;

	private Date startDate;

	private Date endDate;

	private Long createdUserId;

	private Long createdPostId;

	private Date createdDate;

	private Long updatedUserId;

	private Long updatedPostId;

	private Date updatedDate;

	private Long locId;

	private Long dbId;

	// Constructors

	/** default constructor */
	public MstAttachment() {
	}

	/** minimal constructor */
	public MstAttachment(long attachId, long attachType, long activateFlag) {
		this.attachId = attachId;
		this.attachType = attachType;
		this.activateFlag = activateFlag;
	}

	/** full constructor */
	public MstAttachment(long attachId, String attachDesc, long attachType,
			Long langId, long activateFlag, Date startDate, Date endDate,
			Long createdUserId, Long createdPostId, Date createdDate,
			Long updatedUserId, Long updatedPostId, Date updatedDate,
			Long locId, Long dbId) {
		this.attachId = attachId;
		this.attachDesc = attachDesc;
		this.attachType = attachType;
		this.langId = langId;
		this.activateFlag = activateFlag;
		this.startDate = startDate;
		this.endDate = endDate;
		this.createdUserId = createdUserId;
		this.createdPostId = createdPostId;
		this.createdDate = createdDate;
		this.updatedUserId = updatedUserId;
		this.updatedPostId = updatedPostId;
		this.updatedDate = updatedDate;
		this.locId = locId;
		this.dbId = dbId;
	}

	// Property accessors
	public long getAttachId() {
		return this.attachId;
	}

	public void setAttachId(long attachId) {
		this.attachId = attachId;
	}

	public String getAttachDesc() {
		return this.attachDesc;
	}

	public void setAttachDesc(String attachDesc) {
		this.attachDesc = attachDesc;
	}

	public long getAttachType() {
		return this.attachType;
	}

	public void setAttachType(long attachType) {
		this.attachType = attachType;
	}

	public Long getLangId() {
		return this.langId;
	}

	public void setLangId(Long langId) {
		this.langId = langId;
	}

	public long getActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(long activateFlag) {
		this.activateFlag = activateFlag;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Long getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(Long createdUserId) {
		this.createdUserId = createdUserId;
	}

	public Long getCreatedPostId() {
		return this.createdPostId;
	}

	public void setCreatedPostId(Long createdPostId) {
		this.createdPostId = createdPostId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Long getUpdatedUserId() {
		return this.updatedUserId;
	}

	public void setUpdatedUserId(Long updatedUserId) {
		this.updatedUserId = updatedUserId;
	}

	public Long getUpdatedPostId() {
		return this.updatedPostId;
	}

	public void setUpdatedPostId(Long updatedPostId) {
		this.updatedPostId = updatedPostId;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Long getLocId() {
		return this.locId;
	}

	public void setLocId(Long locId) {
		this.locId = locId;
	}

	public Long getDbId() {
		return this.dbId;
	}

	public void setDbId(Long dbId) {
		this.dbId = dbId;
	}

}
