// default package
// Generated Aug 25, 2007 11:15:04 AM by Hibernate Tools 3.2.0.beta8
package com.tcs.sgv.eis.valueobject;


/**
 * HrPayEmpallowMpgHstId generated by hbm2java
 */
public class HrPayEmpallowMpgHstId implements java.io.Serializable {

	// Fields    

	private long allowCode;

	private Integer trnCounter;

	// Constructors

	/** default constructor */
	public HrPayEmpallowMpgHstId() {
	}

	/** full constructor */
	public HrPayEmpallowMpgHstId(long allowCode, Integer trnCounter) {
		this.allowCode = allowCode;
		this.trnCounter = trnCounter;
	}

	// Property accessors
	public long getAllowCode() {
		return this.allowCode;
	}

	public void setAllowCode(long allowCode) {
		this.allowCode = allowCode;
	}

	public Integer getTrnCounter() {
		return this.trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HrPayEmpallowMpgHstId))
			return false;
		HrPayEmpallowMpgHstId castOther = (HrPayEmpallowMpgHstId) other;

		return ((new Long(this.getAllowCode()) == castOther.getAllowCode()) || (new Long(this
				.getAllowCode()) != null
				&& new Long(castOther.getAllowCode()) != null && new Long(this.getAllowCode())
				.equals(castOther.getAllowCode())))
				&& (this.getTrnCounter() == castOther.getTrnCounter());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (new Long(getAllowCode()) == null ? 0 : new Long(this.getAllowCode()).hashCode());
		result = 37 * result + (int) this.getTrnCounter();
		return result;
	}

}
