package com.tcs.sgv.common.valueobject;

// Generated May 30, 2007 8:00:09 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * RltLocationDepartment generated by hbm2java
 */
public class RltLocationDepartment implements java.io.Serializable {

	// Fields    

	private long locDeptId;

	private String locCode;

	private String departmentId;

	private String langId;

	private long createdUserId;

	private long createdPostId;

	private Date createdDate;

	private Long updatedUserId;

	private Long updatedPostId;

	private Date updatedDate;

	private Long dbId;

	// Constructors

	/** default constructor */
	public RltLocationDepartment() {
	}

	/** minimal constructor */
	public RltLocationDepartment(long locDeptId, String departmentId,
			String langId, long createdUserId, long createdPostId,
			Date createdDate) {
		this.locDeptId = locDeptId;
		this.departmentId = departmentId;
		this.langId = langId;
		this.createdUserId = createdUserId;
		this.createdPostId = createdPostId;
		this.createdDate = createdDate;
	}

	/** full constructor */
	public RltLocationDepartment(long locDeptId, String locCode,
			String departmentId, String langId, long createdUserId,
			long createdPostId, Date createdDate, Long updatedUserId,
			Long updatedPostId, Date updatedDate, Long dbId) {
		this.locDeptId = locDeptId;
		this.locCode = locCode;
		this.departmentId = departmentId;
		this.langId = langId;
		this.createdUserId = createdUserId;
		this.createdPostId = createdPostId;
		this.createdDate = createdDate;
		this.updatedUserId = updatedUserId;
		this.updatedPostId = updatedPostId;
		this.updatedDate = updatedDate;
		this.dbId = dbId;
	}

	// Property accessors
	public long getLocDeptId() {
		return this.locDeptId;
	}

	public void setLocDeptId(long locDeptId) {
		this.locDeptId = locDeptId;
	}

	public String getLocCode() {
		return this.locCode;
	}

	public void setLocCode(String locCode) {
		this.locCode = locCode;
	}

	public String getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

	public String getLangId() {
		return this.langId;
	}

	public void setLangId(String langId) {
		this.langId = langId;
	}

	public long getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(long createdUserId) {
		this.createdUserId = createdUserId;
	}

	public long getCreatedPostId() {
		return this.createdPostId;
	}

	public void setCreatedPostId(long createdPostId) {
		this.createdPostId = createdPostId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Long getUpdatedUserId() {
		return this.updatedUserId;
	}

	public void setUpdatedUserId(Long updatedUserId) {
		this.updatedUserId = updatedUserId;
	}

	public Long getUpdatedPostId() {
		return this.updatedPostId;
	}

	public void setUpdatedPostId(Long updatedPostId) {
		this.updatedPostId = updatedPostId;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Long getDbId() {
		return this.dbId;
	}

	public void setDbId(Long dbId) {
		this.dbId = dbId;
	}

}
