// default package
// Generated Aug 17, 2007 10:37:46 AM by Hibernate Tools 3.2.0.beta8
package com.tcs.sgv.eis.valueobject;
import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;


/**
 * HrPayEdpCompoMpg generated by hbm2java
 */
public class HrPayEdpCompoMpg implements java.io.Serializable {

	// Fields    

	private long id;

	private RltBillTypeEdp rltBillTypeEdp;

	private long cmnLookupId;

	private String typeId;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByCreatedBy;

	private Date createdDate;
	
	private long isOneTime;
	
	private long subDtlHead;
	
	private long headOfAcc;
	
	private long displayOrder;
	// Constructors

	
	/**
	 * @return the displayOrder
	 */
	public long getDisplayOrder() {
		return displayOrder;
	}

	/**
	 * @param displayOrder the displayOrder to set
	 */
	public void setDisplayOrder(long displayOrder) {
		this.displayOrder = displayOrder;
	}

	/** default constructor */
	public HrPayEdpCompoMpg() {
	}

	/** minimal constructor */
	public HrPayEdpCompoMpg(long id) {
		this.id = id;
	}

	/** full constructor */
	public HrPayEdpCompoMpg(long id, RltBillTypeEdp rltBillTypeEdp,
			long cmnLookupId, String typeId,  CmnDatabaseMst cmnDatabaseMst,
			CmnLocationMst cmnLocationMst, OrgPostMst orgPostMstByCreatedByPost, OrgUserMst orgUserMstByCreatedBy,
			Date createdDate,long subDtlHead) {
		this.id = id;
		this.rltBillTypeEdp = rltBillTypeEdp;
		this.cmnLookupId = cmnLookupId;
		this.typeId = typeId;
		this.cmnLocationMst = cmnLocationMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.createdDate = createdDate;
		this.subDtlHead = subDtlHead;
	}

	// Property accessors
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public RltBillTypeEdp getRltBillTypeEdp() {
		return this.rltBillTypeEdp;
	}

	public void setRltBillTypeEdp(RltBillTypeEdp rltBillTypeEdp) {
		this.rltBillTypeEdp = rltBillTypeEdp;
	}

	public long getCmnLookupId() {
		return this.cmnLookupId;
	}

	public void setCmnLookupId(long cmnLookupId) {
		this.cmnLookupId = cmnLookupId;
	}

	public String getTypeId() {
		return this.typeId;
	}

	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	
	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public long getIsOneTime() {
		return isOneTime;
	}

	public void setIsOneTime(long isOneTime) {
		this.isOneTime = isOneTime;
	}

	public long getSubDtlHead() {
		return subDtlHead;
	}

	public void setSubDtlHead(long subDtlHead) {
		this.subDtlHead = subDtlHead;
	}

	public long getHeadOfAcc() {
		return headOfAcc;
	}

	public void setHeadOfAcc(long headOfAcc) {
		this.headOfAcc = headOfAcc;
	}

}
