 
package com.tcs.sgv.dss.valueobject;
// Generated Sep 18, 2007 9:13:10 AM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * RptPaymentDtls generated by hbm2java
 */
public class RptPaymentDtls implements java.io.Serializable {

	// Fields    
	Log logger = LogFactory.getLog(getClass());


	private BigDecimal paymentId;

	private String deptCode;

	private String officeCode;

	private String tsryCode;

	private String ddoCode;

	private String partyCode;

	private String chqTypeCode;

	private BigDecimal chqNo;

	private Date chqClrDt;

	private BigDecimal finYrId;

	private BigDecimal amount;

	private String bankCode;

	private String chqStatusCode;

	private Date chqStatusDt;

	private String partyName;

	private Character clientData;

	private Character active;
	
	private String crtUsr;

	private Date crtDt;


	// Constructors

	/** default constructor */
	public RptPaymentDtls()
	{
		this.paymentId = new BigDecimal(0);
		this.deptCode = "";
		this.officeCode = "";
		this.tsryCode = "";
		this.ddoCode = "";
		this.partyCode = "";
		this.chqTypeCode = "";
		this.chqNo = new BigDecimal(0);
		this.chqClrDt = null;
		this.finYrId = new BigDecimal(0);
		this.amount = new BigDecimal(0);
		this.bankCode = "";
		this.chqStatusCode = "";
		this.chqStatusDt = null;
		this.active = 'Y';
		this.partyName = "";
		this.clientData = 'N';
		this.crtUsr = "";
		this.crtDt = null;
	}

	/** minimal constructor */
	public RptPaymentDtls(BigDecimal paymentId) {
		this.paymentId = paymentId;
	}

	/** full constructor */
	public RptPaymentDtls(BigDecimal paymentId, String deptCode,
			String officeCode, String tsryCode, String ddoCode,
			String partyCode, String chqTypeCode, BigDecimal chqNo,
			Date chqClrDt, BigDecimal finYrId, BigDecimal amount,
			String bankCode, String chqStatusCode, Date chqStatusDt,
			String partyName, Character clientData, Character active,
			String crtUsr, Date crtDt) {
		this.paymentId = paymentId;
		this.deptCode = deptCode;
		this.officeCode = officeCode;
		this.tsryCode = tsryCode;
		this.ddoCode = ddoCode;
		this.partyCode = partyCode;
		this.chqTypeCode = chqTypeCode;
		this.chqNo = chqNo;
		this.chqClrDt = chqClrDt;
		this.finYrId = finYrId;
		this.amount = amount;
		this.bankCode = bankCode;
		this.chqStatusCode = chqStatusCode;
		this.chqStatusDt = chqStatusDt;
		this.partyName = partyName;
		this.clientData = clientData;
		this.active = active;
		this.crtUsr = crtUsr;
		this.crtDt = crtDt;
	}



	
	public String toString()
	{
		logger.info("Below is the values of RptPaymentDtls Object");
		logger.info("--------------------------------------------------");
		logger.info("The value of paymentId is :- " + this.paymentId);
		logger.info("The value of deptCode is :- " + this.deptCode);
		logger.info("The value of officeCode is :- " + this.officeCode);
		logger.info("The value of tsryCode is :- " + this.tsryCode);
		logger.info("The value of ddoCode is :- " + this.ddoCode);
		logger.info("The value of partyCode is :- " + this.partyCode);
		logger.info("The value of chqTypeCode is :- " + this.chqTypeCode);
		logger.info("The value of chqNo is :- " + this.chqNo);
		logger.info("The value of chqClrDt is :- " + this.chqClrDt);
		logger.info("The value of finYrId is :- " + this.finYrId);
		logger.info("The value of amount is :- " + this.amount);
		logger.info("The value of bankCode is :- " + this.bankCode);
		logger.info("The value of chqStatusCode is :- " + this.chqStatusCode);
		logger.info("The value of chqStatusDt is :- " + this.chqStatusDt);
		logger.info("The value of active is :- " + this.active);
		logger.info("The value of partyName is :- " + this.partyName);
		logger.info("The value of clientData is :- " + this.clientData);
		logger.info("The value of created User  is :- " + this.crtUsr);
		logger.info("The value of created Date  is :- " + this.crtDt);
		
		
		
		return (super.toString());
		
	}
		

	// Property accessors
	public BigDecimal getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(BigDecimal paymentId) {
		this.paymentId = paymentId;
	}

	public String getDeptCode() {
		return this.deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	public String getOfficeCode() {
		return this.officeCode;
	}

	public void setOfficeCode(String officeCode) {
		this.officeCode = officeCode;
	}

	public String getTsryCode() {
		return this.tsryCode;
	}

	public void setTsryCode(String tsryCode) {
		this.tsryCode = tsryCode;
	}

	public String getDdoCode() {
		return this.ddoCode;
	}

	public void setDdoCode(String ddoCode) {
		this.ddoCode = ddoCode;
	}

	public String getPartyCode() {
		return this.partyCode;
	}

	public void setPartyCode(String partyCode) {
		this.partyCode = partyCode;
	}

	public String getChqTypeCode() {
		return this.chqTypeCode;
	}

	public void setChqTypeCode(String chqTypeCode) {
		this.chqTypeCode = chqTypeCode;
	}

	public BigDecimal getChqNo() {
		return this.chqNo;
	}

	public void setChqNo(BigDecimal chqNo) {
		this.chqNo = chqNo;
	}

	public Date getChqClrDt() {
		return this.chqClrDt;
	}

	public void setChqClrDt(Date chqClrDt) {
		this.chqClrDt = chqClrDt;
	}

	public BigDecimal getFinYrId() {
		return this.finYrId;
	}

	public void setFinYrId(BigDecimal finYrId) {
		this.finYrId = finYrId;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	public String getChqStatusCode() {
		return this.chqStatusCode;
	}

	public void setChqStatusCode(String chqStatusCode) {
		this.chqStatusCode = chqStatusCode;
	}

	public Date getChqStatusDt() {
		return this.chqStatusDt;
	}

	public void setChqStatusDt(Date chqStatusDt) {
		this.chqStatusDt = chqStatusDt;
	}

	public String getPartyName() {
		return this.partyName;
	}

	public void setPartyName(String partyName) {
		this.partyName = partyName;
	}

	public Character getClientData() {
		return this.clientData;
	}

	public void setClientData(Character clientData) {
		this.clientData = clientData;
	}

	public Character getActive() {
		return this.active;
	}

	public void setActive(Character active) {
		this.active = active;
	}
	
	public String getCrtUsr() {
		return this.crtUsr;
	}

	public void setCrtUsr(String crtUsr) {
		this.crtUsr = crtUsr;
	}

	public Date getCrtDt() {
		return this.crtDt;
	}

	public void setCrtDt(Date crtDt) {
		this.crtDt = crtDt;
	}


	
	public Map validateData()
	{
		boolean flag = true;
		String status = "OK";
		HashMap returnMap = new HashMap();
		
		returnMap.put("flag", true);
		returnMap.put("Status", status);
		
		return returnMap;
	}


}
