package com.tcs.sgv.allowance.valueobject;
// Generated Jul 16, 2007 1:01:36 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

import com.tcs.sgv.common.payroll.valueobject.HrPayCommissionMst;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrPayExpressionMst generated by hbm2java
 */
public class HrPayExpressionMst implements java.io.Serializable {

	// Fields  
	


	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLanguageMst cmnLanguageMst;
	
	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;
	
	private HrPayAllowTypeMst hrPayAllowTypeMst;

	private long ruleId;

	private String ruleDescription;

	private String ruleExpression;

	//private String ruleValue;
	
	private Long ruleValue;

	private long isactive;

	private Date ruleEffStartDate;

	private Date ruleEffEndDate;

	//private long allowId;
	
	private long ruleCode;

	
	private Date createdDate;

	
	
	private Date updatedDate;
	
	private HrPayCommissionMst hrPayCommissionMst;

	// Constructors

	/** default constructor */
	public HrPayExpressionMst() {
	}

	/** minimal constructor */
	public HrPayExpressionMst(long ruleId) {
		this.ruleId = ruleId;
	}

	/** full constructor */
	public HrPayExpressionMst(long ruleId, String ruleDescription,
			String ruleExpression, //String ruleValue,
			Long ruleValue,
			long isactive, Date ruleEffStartDate, Date ruleEffEndDate,
			HrPayAllowTypeMst hrPayAllowTypeMst,
			/*long allowId,*/ CmnDatabaseMst cmnDatabaseMst, CmnLocationMst cmnLocationMst,
			OrgUserMst orgUserMstByCreatedBy, OrgPostMst orgPostMstByCreatedByPost, Date createdDate,
			OrgUserMst orgUserMstByUpdatedBy, CmnLanguageMst cmnLanguageMst,OrgPostMst orgPostMstByUpdatedByPost, Date updatedDate,long ruleCode) {
		this.ruleId = ruleId;
		this.ruleDescription = ruleDescription;
		this.ruleExpression = ruleExpression;
		this.ruleValue = ruleValue;
		this.isactive = isactive;
		this.ruleEffStartDate = ruleEffStartDate;
		this.ruleEffEndDate = ruleEffEndDate;
		this.hrPayAllowTypeMst = hrPayAllowTypeMst;
		this.cmnDatabaseMst=cmnDatabaseMst;
		this.cmnLanguageMst=cmnLanguageMst;
		this.orgPostMstByCreatedByPost=orgPostMstByCreatedByPost;
		this.orgPostMstByUpdatedByPost=orgPostMstByUpdatedByPost;
		this.orgUserMstByCreatedBy=orgUserMstByCreatedBy;
		this.orgUserMstByUpdatedBy=orgUserMstByUpdatedBy;
		//this.allowId = allowId;
		this.createdDate = createdDate;		
		this.updatedDate = updatedDate;
		this.ruleCode = ruleCode;
		this.cmnLocationMst= cmnLocationMst;
		
	}

	// Property accessors
	
	public long getRuleCode() {
		return ruleCode;
	}

	public void setRuleCode(long ruleCode) {
		this.ruleCode = ruleCode;
	}

	public HrPayCommissionMst getHrPayCommissionMst() {
		return hrPayCommissionMst;
	}

	public void setHrPayCommissionMst(HrPayCommissionMst hrPayCommissionMst) {
		this.hrPayCommissionMst = hrPayCommissionMst;
	}

	
	public long getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(long ruleId) {
		this.ruleId = ruleId;
	}

	public String getRuleDescription() {
		return this.ruleDescription;
	}

	public void setRuleDescription(String ruleDescription) {
		this.ruleDescription = ruleDescription;
	}

	public String getRuleExpression() {
		return this.ruleExpression;
	}

	public void setRuleExpression(String ruleExpression) {
		this.ruleExpression = ruleExpression;
	}

	/*public String getRuleValue() {
		return this.ruleValue;
	}

	public void setRuleValue(String ruleValue) {
		this.ruleValue = ruleValue;
	}*/

	public long getIsactive() {
		return this.isactive;
	}

	public void setIsactive(long isactive) {
		this.isactive = isactive;
	}

	public Date getRuleEffStartDate() {
		return this.ruleEffStartDate;
	}

	public void setRuleEffStartDate(Date ruleEffStartDate) {
		this.ruleEffStartDate = ruleEffStartDate;
	}

	public Date getRuleEffEndDate() {
		return this.ruleEffEndDate;
	}

	public void setRuleEffEndDate(Date ruleEffEndDate) {
		this.ruleEffEndDate = ruleEffEndDate;
	}

	/*public long getAllowId() {
		return this.allowId;
	}

	public void setAllowId(long allowId) {
		this.allowId = allowId;
	}*/

	
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

		public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public HrPayAllowTypeMst getHrPayAllowTypeMst() {
		return hrPayAllowTypeMst;
	}

	public void setHrPayAllowTypeMst(HrPayAllowTypeMst hrPayAllowTypeMst) {
		this.hrPayAllowTypeMst = hrPayAllowTypeMst;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public long getruleCode() {
		return ruleCode;
	}

	public void setruleCode(long ruleCode) {
		this.ruleCode = ruleCode;
	}

	public Long getRuleValue() {
		return ruleValue;
	}

	public void setRuleValue(Long ruleValue) {
		this.ruleValue = ruleValue;
	}

	
}
