package com.tcs.sgv.allowance.valueobject;
// Generated Jul 22, 2007 3:26:22 PM by Hibernate Tools 3.1.0.beta5

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrPayAllowTypeMst generated by hbm2java
 */
public class HrPayAllowTypeMst implements java.io.Serializable {

	// Fields    

	private long allowCode;

	private String allowName;
	
	private String allowDisplayName;

	private String allowDesc;
	
	private CmnLanguageMst cmnLanguageMst;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;

	private Date createdDate;
	
	private Date updatedDate;

	private long allowTypeCode;

	private Set hrAllowArgumentMpgs = new HashSet(0);
	
	private long sequence_no;
	
	private long payCommissionId;
	
	private long allwDedId;

	// Constructors

	public long getAllwDedId()
	{
		return allwDedId;
	}

	public void setAllwDedId(long allwDedId)
	{
		this.allwDedId = allwDedId;
	}

	/** default constructor */
	public HrPayAllowTypeMst() {
	}

	/** minimal constructor */
	public HrPayAllowTypeMst(long allowCode) {
		this.allowCode = allowCode;
	}

	/** full constructor */
	public HrPayAllowTypeMst(long allowCode, String allowName,
			String allowDesc,
			CmnLanguageMst cmnLanguageMst,
			CmnDatabaseMst cmnDatabaseMst,
			OrgPostMst orgPostMstByCreatedByPost,
			CmnLocationMst cmnLocationMst, OrgUserMst orgUserMstByCreatedBy,
			Date createdDate, 

			Date updatedDate, long allowTypeCode, Set hrAllowArgumentMpgs) {
		this.allowCode = allowCode;
		this.allowName = allowName;
		this.allowDesc = allowDesc;
		this.cmnLanguageMst = cmnLanguageMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	
		this.createdDate = createdDate;
		
		this.updatedDate = updatedDate;
		this.allowTypeCode = allowTypeCode;
		this.hrAllowArgumentMpgs = hrAllowArgumentMpgs;
	}

	public long getAllowCode() {
		return allowCode;
	}

	public void setAllowCode(long allowCode) {
		this.allowCode = allowCode;
	}

	public String getAllowDesc() {
		return allowDesc;
	}

	public void setAllowDesc(String allowDesc) {
		this.allowDesc = allowDesc;
	}

	public String getAllowName() {
		return allowName;
	}

	public void setAllowName(String allowName) {
		this.allowName = allowName;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public long getAllowTypeCode() {
		return allowTypeCode;
	}

	public void setAllowTypeCode(long allowTypeCode) {
		this.allowTypeCode = allowTypeCode;
	}

	public Set getHrAllowArgumentMpgs() {
		return hrAllowArgumentMpgs;
	}

	public void setHrAllowArgumentMpgs(Set hrAllowArgumentMpgs) {
		this.hrAllowArgumentMpgs = hrAllowArgumentMpgs;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getAllowDisplayName() {
		return allowDisplayName;
	}

	public void setAllowDisplayName(String allowDisplayName) {
		this.allowDisplayName = allowDisplayName;
	}

	public long getSequence_no() {
		return sequence_no;
	}

	public void setSequence_no(long sequence_no) {
		this.sequence_no = sequence_no;
	}

	public long getPayCommissionId() {
		return payCommissionId;
	}

	public void setPayCommissionId(long payCommissionId) {
		this.payCommissionId = payCommissionId;
	}

	// Property accessors
	
	
	
}
