package com.tcs.sgv.eis.valueobject;

// Generated Jul 16, 2007 11:53:29 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.eis.valueobject.HrEisQuaterTypeMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrEisOtherDtls generated by hbm2java
 */
@SuppressWarnings("serial")
public class HrEisOtherDtls implements java.io.Serializable
{

	// Fields    

	//private CmnLanguageMst cmnLanguageMst;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	//private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;

	private String phyChallenged;
	private long city;

	private double totalSalary;

	private long otherId;

	private HrEisEmpMst hrEisEmpMst;

	private HrEisSgdMpg hrEisSgdMpg;

	//private HrEisDeptMst hrEisDeptMst;

	private HrEisQuaterTypeMst hrQuaterTypeMst;

	private long otherCurrentBasic;
	

	private long oldBasic;

	
	private long incomeTax;

	private Date createdDate;

	private Date updatedDate;

	private Date incrementDate;

	//Added by Paurav for Medical Allowance
	private long medAllowance;
	private long uniformAvailed;
	//Ended by Paurav

//	private String sis1979Flag;

	// Constructors
	private Integer trnCounter;

	//private String othFamilyPlanning;

	//private int familyPlnAmt;

	private int ownHouse;

	//	private int isSis;

	private Date commissionAcceptanceDate;

	private int isAvailedHRA;

	/*private int atsIncentive30;
	
	private int atsIncentive50;

	private int force1Incentive100;
	
	private int force1Incentive25;	
	*/

	public long getOtherCurrentBasic()
	{
		return otherCurrentBasic;
	}

	public void setOtherCurrentBasic(long otherCurrentBasic)
	{
		this.otherCurrentBasic = otherCurrentBasic;
	}

	
	
	/*ublic int getAtsIncentive30() {
		return atsIncentive30;
	}


	public void setAtsIncentive30(int atsIncentive30) {
		this.atsIncentive30 = atsIncentive30;
	}


	public int getAtsIncentive50() {
		return atsIncentive50;
	}


	public void setAtsIncentive50(int atsIncentive50) {
		this.atsIncentive50 = atsIncentive50;
	}


	public int getForce1Incentive100() {
		return force1Incentive100;
	}


	public void setForce1Incentive100(int force1Incentive100) {
		this.force1Incentive100 = force1Incentive100;
	}


	public int getForce1Incentive25() {
		return force1Incentive25;
	}


	public void setForce1Incentive25(int force1Incentive25) {
		this.force1Incentive25 = force1Incentive25;
	}


	public int getOwnHouse() {
		return ownHouse;
	}


	public void setOwnHouse(int ownHouse) {
		this.ownHouse = ownHouse;
	}
	*/

	public long getOldBasic() {
		return oldBasic;
	}

	public void setOldBasic(long oldBasic) {
		this.oldBasic = oldBasic;
	}

	public int getOwnHouse()
	{
		return ownHouse;
	}

	public void setOwnHouse(int ownHouse)
	{
		this.ownHouse = ownHouse;
	}

	public long getUniformAvailed()
	{
		return uniformAvailed;
	}

	public void setUniformAvailed(long uniformAvailed)
	{
		this.uniformAvailed = uniformAvailed;
	}
	
	/*Added By shivram*/
	long sevenBasicAmt;
	
	public long getSevenBasicAmt() {
		return sevenBasicAmt;
	}
	public void setSevenBasicAmt(long sevenBasicAmt) {
		this.sevenBasicAmt = sevenBasicAmt;
	}
	/*---Ended By Shivram*/

	/** default constructor */
	public HrEisOtherDtls()
	{}

	/**  minimal constructor */
	public HrEisOtherDtls(CmnDatabaseMst cmnDatabaseMst, OrgPostMst orgPostMstByUpdatedByPost, HrEisQuaterTypeMst hrQuaterTypeMst, OrgPostMst orgPostMstByCreatedByPost, OrgUserMst orgUserMstByCreatedBy, long otherId, HrEisEmpMst hrEisEmpMst, HrEisSgdMpg hrEisSgdMpg, HrEisDeptMst hrEisDeptMst, double totalSalary, long otherCurrentBasic, Date createdDate, int isAvailedHRA)
	{
		super();
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.otherId = otherId;
		this.hrEisEmpMst = hrEisEmpMst;
		this.hrQuaterTypeMst = hrQuaterTypeMst;
		this.hrEisSgdMpg = hrEisSgdMpg;
		//this.hrEisDeptMst = hrEisDeptMst;
		this.otherCurrentBasic = otherCurrentBasic;
		this.createdDate = createdDate;
		this.totalSalary = totalSalary;
		this.isAvailedHRA = isAvailedHRA;
	}

	/**  full constructor */
	public HrEisOtherDtls(CmnDatabaseMst cmnDatabaseMst, OrgPostMst orgPostMstByUpdatedByPost, OrgPostMst orgPostMstByCreatedByPost, HrEisQuaterTypeMst hrQuaterTypeMst, OrgUserMst orgUserMstByUpdatedBy, OrgUserMst orgUserMstByCreatedBy, long otherId, HrEisEmpMst hrEisEmpMst, HrEisSgdMpg hrEisSgdMpg,
	//	HrEisDeptMst hrEisDeptMst, 
			double totalSalary, long otherCurrentBasic, Date createdDate, Date updatedDate, Integer trnCounter, Date commissionAcceptanceDate, int isAvailedHRA)
	{
		super();
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.otherId = otherId;
		this.hrEisEmpMst = hrEisEmpMst;
		this.hrQuaterTypeMst = hrQuaterTypeMst;
		this.hrEisSgdMpg = hrEisSgdMpg;
		//this.hrEisDeptMst = hrEisDeptMst;
		this.otherCurrentBasic = otherCurrentBasic;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.trnCounter = trnCounter;
		this.totalSalary = totalSalary;
		this.commissionAcceptanceDate = commissionAcceptanceDate;
		this.isAvailedHRA = isAvailedHRA;
	}

	// Property accessors
	public long getOtherId()
	{
		return this.otherId;
	}

	public void setOtherId(long otherId)
	{
		this.otherId = otherId;
	}

	/*public HrEisDeptMst getHrEisDeptMst() {
		return hrEisDeptMst;
	}

	public void setHrEisDeptMst(HrEisDeptMst hrEisDeptMst) {
		this.hrEisDeptMst = hrEisDeptMst;
	}*/

	public HrEisEmpMst getHrEisEmpMst()
	{
		return hrEisEmpMst;
	}

	public void setHrEisEmpMst(HrEisEmpMst hrEisEmpMst)
	{
		this.hrEisEmpMst = hrEisEmpMst;
	}

	public long getotherCurrentBasic()
	{
		return this.otherCurrentBasic;
	}

	public void setotherCurrentBasic(long otherCurrentBasic)
	{
		this.otherCurrentBasic = otherCurrentBasic;
	}

	public Date getCreatedDate()
	{
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate)
	{
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate()
	{
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate)
	{
		this.updatedDate = updatedDate;
	}

	public CmnDatabaseMst getCmnDatabaseMst()
	{
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst)
	{
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost()
	{
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost)
	{
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost()
	{
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost)
	{
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy()
	{
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy)
	{
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy()
	{
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy)
	{
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public HrEisSgdMpg getHrEisSgdMpg()
	{
		return hrEisSgdMpg;
	}

	public void setHrEisSgdMpg(HrEisSgdMpg hrEisSgdMpg)
	{
		this.hrEisSgdMpg = hrEisSgdMpg;
	}

	public long getCity()
	{
		return city;
	}

	public void setCity(long city)
	{
		this.city = city;
	}

	public String getPhyChallenged()
	{
		return phyChallenged;
	}

	public void setPhyChallenged(String phyChallenged)
	{
		this.phyChallenged = phyChallenged;
	}

	public HrEisQuaterTypeMst getHrQuaterTypeMst()
	{
		return hrQuaterTypeMst;
	}

	public void setHrQuaterTypeMst(HrEisQuaterTypeMst hrQuaterTypeMst)
	{
		this.hrQuaterTypeMst = hrQuaterTypeMst;
	}

	public long getIncomeTax()
	{
		return incomeTax;
	}

	public void setIncomeTax(long incomeTax)
	{
		this.incomeTax = incomeTax;
	}

	public Date getIncrementDate()
	{
		return incrementDate;
	}

	public void setIncrementDate(Date incrementDate)
	{
		this.incrementDate = incrementDate;
	}

	public long getMedAllowance()
	{
		return medAllowance;
	}

	public void setMedAllowance(long medAllowance)
	{
		this.medAllowance = medAllowance;
	}

	public Integer getTrnCounter()
	{
		return trnCounter;
	}

	public void setTrnCounter(Integer trnCounter)
	{
		this.trnCounter = trnCounter;
	}

	public double getTotalSalary()
	{
		return totalSalary;
	}

	public void setTotalSalary(double totalSalary)
	{
		this.totalSalary = totalSalary;
	}

	/*
		public String getSis1979Flag() {
			return sis1979Flag;
		}


		public void setSis1979Flag(String sis1979Flag) {
			this.sis1979Flag = sis1979Flag;
		}

	*/
	/*public String getOthFamilyPlanning() {
		return othFamilyPlanning;
	}


	public void setOthFamilyPlanning(String othFamilyPlanning) {
		this.othFamilyPlanning = othFamilyPlanning;
	}*/

	/*	public int getFamilyPlnAmt() {
			return familyPlnAmt;
		}


		public void setFamilyPlnAmt(int familyPlnAmt) {
			this.familyPlnAmt = familyPlnAmt;
		}


		public int getIsSis() {
			return isSis;
		}


		public void setIsSis(int isSis) {
			this.isSis = isSis;
		}*/

	public Date getCommissionAcceptanceDate()
	{
		return commissionAcceptanceDate;
	}

	public void setCommissionAcceptanceDate(Date commissionAcceptanceDate)
	{
		this.commissionAcceptanceDate = commissionAcceptanceDate;
	}

	public void setIsAvailedHRA(int isAvailedHRA)
	{
		this.isAvailedHRA = isAvailedHRA;
	}

	public int getIsAvailedHRA()
	{
		return isAvailedHRA;
	}
	
	/*Added By Mani*/
	private long otherCurrentSevenBasic;
	public void setOtherCurrentSevenBasic(long otherCurrentSevenBasic)
	 {
	   this.otherCurrentSevenBasic = otherCurrentSevenBasic;
	 }
	 
	 public long getOtherCurrentSevenBasic()
	 {
	   return this.otherCurrentSevenBasic;
	 }
	/*Ended By Mani*/

}
