package com.tcs.sgv.eis.valueobject;
// Generated Jun 28, 2011 5:45:58 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

import com.tcs.sgv.ess.valueobject.OrgEmpMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrPayEmpSalaryTxn generated by hbm2java
 */
@SuppressWarnings("serial")
public class HrPayEmpSalaryTxn implements java.io.Serializable {

	private long empSalId;
	//private HrPayAllowDedMst hrPayAllowDedMst;
	private OrgEmpMst empId;
	private BigDecimal amount;
	private int active;
	private Integer trnCounter;

	private OrgUserMst orgUserMstByCrtdBy;
	private OrgPostMst orgPostMstByCrtdByPost;
	private OrgUserMst orgUserMstByUpdBy;
	private OrgPostMst orgPostMstByUpdByPost;
	private Date crtdDate;
	private Date updDate;
// For CustomVO
	private String payCompName;
	//private long empCode; 
	private long allwDedCode;
	
	
	public HrPayEmpSalaryTxn() {
	}


	public HrPayEmpSalaryTxn(long empSalId, OrgEmpMst empId, BigDecimal amount,
			int active, Integer trnCounter, OrgUserMst orgUserMstByCrtdBy,
			OrgPostMst orgPostMstByCrtdByPost, OrgUserMst orgUserMstByUpdBy,
			OrgPostMst orgPostMstByUpdByPost, Date crtdDate, Date updDate,
			String payCompName, long allwDedCode) {
		super();
		this.empSalId = empSalId;
		this.empId = empId;
		this.amount = amount;
		this.active = active;
		this.trnCounter = trnCounter;
		this.orgUserMstByCrtdBy = orgUserMstByCrtdBy;
		this.orgPostMstByCrtdByPost = orgPostMstByCrtdByPost;
		this.orgUserMstByUpdBy = orgUserMstByUpdBy;
		this.orgPostMstByUpdByPost = orgPostMstByUpdByPost;
		this.crtdDate = crtdDate;
		this.updDate = updDate;
		this.payCompName = payCompName;
		this.allwDedCode = allwDedCode;
	}


	public long getEmpSalId() {
		return empSalId;
	}


	public void setEmpSalId(long empSalId) {
		this.empSalId = empSalId;
	}


	public OrgEmpMst getEmpId() {
		return empId;
	}


	public void setEmpId(OrgEmpMst empId) {
		this.empId = empId;
	}


	public BigDecimal getAmount() {
		return amount;
	}


	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}


	public int getActive() {
		return active;
	}


	public void setActive(int active) {
		this.active = active;
	}


	public Integer getTrnCounter() {
		return trnCounter;
	}


	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}


	public OrgUserMst getOrgUserMstByCrtdBy() {
		return orgUserMstByCrtdBy;
	}


	public void setOrgUserMstByCrtdBy(OrgUserMst orgUserMstByCrtdBy) {
		this.orgUserMstByCrtdBy = orgUserMstByCrtdBy;
	}


	public OrgPostMst getOrgPostMstByCrtdByPost() {
		return orgPostMstByCrtdByPost;
	}


	public void setOrgPostMstByCrtdByPost(OrgPostMst orgPostMstByCrtdByPost) {
		this.orgPostMstByCrtdByPost = orgPostMstByCrtdByPost;
	}


	public OrgUserMst getOrgUserMstByUpdBy() {
		return orgUserMstByUpdBy;
	}


	public void setOrgUserMstByUpdBy(OrgUserMst orgUserMstByUpdBy) {
		this.orgUserMstByUpdBy = orgUserMstByUpdBy;
	}


	public OrgPostMst getOrgPostMstByUpdByPost() {
		return orgPostMstByUpdByPost;
	}


	public void setOrgPostMstByUpdByPost(OrgPostMst orgPostMstByUpdByPost) {
		this.orgPostMstByUpdByPost = orgPostMstByUpdByPost;
	}


	public Date getCrtdDate() {
		return crtdDate;
	}


	public void setCrtdDate(Date crtdDate) {
		this.crtdDate = crtdDate;
	}


	public Date getUpdDate() {
		return updDate;
	}


	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}


	public String getPayCompName() {
		return payCompName;
	}


	public void setPayCompName(String payCompName) {
		this.payCompName = payCompName;
	}


	public long getAllwDedCode() {
		return allwDedCode;
	}


	public void setAllwDedCode(long allwDedCode) {
		this.allwDedCode = allwDedCode;
	}

	
		
}
