package com.tcs.sgv.payfixation.valueobject;

// default package
// Generated 16 Jun, 2012 3:01:09 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrPayfixMstHst generated by hbm2java
 */
@SuppressWarnings("serial")
public class HrPayfixMstHst implements java.io.Serializable
{

	private HrPayfixMstHstId id;
	private OrgUserMst orgUserMstCreatedBy;
	private CmnLanguageMst cmnLanguageMst;
	private CmnLocationMst cmnLocationMst;
	private OrgUserMst userId;
	private OrgPostMst orgPostMstByUpdatedByPost;
	private OrgUserMst orgUserMstUpdatedBy;
	private CmnDatabaseMst cmnDatabaseMst;
	private OrgPostMst orgPostMstCreatedByPost;
	private Date payFixDate;
	private Date nxtIncrDate;
	private String remarks;
	private Date updatedDate;
	private Date createdDate;
	private String status;
	private Long newBasic;
	private String incrementOrderNo;
	private Long oldBasic;
	private Integer activateFlag;
	private Date incrementOrderDate;
	private Long payCommissionId;

	public HrPayfixMstHst()
	{}

	public HrPayfixMstHst(HrPayfixMstHstId id, OrgUserMst orgUserMstCreatedBy, CmnLanguageMst cmnLanguageMst, CmnLocationMst cmnLocationMst, OrgUserMst userId, CmnDatabaseMst cmnDatabaseMst, OrgPostMst orgPostMstCreatedByPost, Date payFixDate, Date nxtIncrDate, Date createdDate)
	{
		this.id = id;
		this.orgUserMstCreatedBy = orgUserMstCreatedBy;
		this.cmnLanguageMst = cmnLanguageMst;
		this.cmnLocationMst = cmnLocationMst;
		this.userId = userId;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstCreatedByPost = orgPostMstCreatedByPost;
		this.payFixDate = payFixDate;
		this.nxtIncrDate = nxtIncrDate;
		this.createdDate = createdDate;
	}

	public HrPayfixMstHst(HrPayfixMstHstId id, OrgUserMst orgUserMstCreatedBy, CmnLanguageMst cmnLanguageMst, CmnLocationMst cmnLocationMst, OrgUserMst userId, OrgPostMst orgPostMstByUpdatedByPost, OrgUserMst orgUserMstUpdatedBy, CmnDatabaseMst cmnDatabaseMst, OrgPostMst orgPostMstCreatedByPost, Date payFixDate, Date nxtIncrDate, String remarks, Date updatedDate, Date createdDate, String status, Long newBasic, String incrementOrderNo, Long oldBasic, Integer activateFlag, Date incrementOrderDate)
	{
		this.id = id;
		this.orgUserMstCreatedBy = orgUserMstCreatedBy;
		this.cmnLanguageMst = cmnLanguageMst;
		this.cmnLocationMst = cmnLocationMst;
		this.userId = userId;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.orgUserMstUpdatedBy = orgUserMstUpdatedBy;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgPostMstCreatedByPost = orgPostMstCreatedByPost;
		this.payFixDate = payFixDate;
		this.nxtIncrDate = nxtIncrDate;
		this.remarks = remarks;
		this.updatedDate = updatedDate;
		this.createdDate = createdDate;
		this.status = status;
		this.newBasic = newBasic;
		this.incrementOrderNo = incrementOrderNo;
		this.oldBasic = oldBasic;
		this.activateFlag = activateFlag;
		this.incrementOrderDate = incrementOrderDate;
	}

	public HrPayfixMstHstId getId()
	{
		return this.id;
	}

	public void setId(HrPayfixMstHstId id)
	{
		this.id = id;
	}

	public OrgUserMst getOrgUserMstCreatedBy()
	{
		return this.orgUserMstCreatedBy;
	}

	public void setOrgUserMstCreatedBy(OrgUserMst orgUserMstCreatedBy)
	{
		this.orgUserMstCreatedBy = orgUserMstCreatedBy;
	}

	public CmnLanguageMst getCmnLanguageMst()
	{
		return this.cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst)
	{
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public CmnLocationMst getCmnLocationMst()
	{
		return this.cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst)
	{
		this.cmnLocationMst = cmnLocationMst;
	}

	public OrgUserMst getUserId()
	{
		return this.userId;
	}

	public void setUserId(OrgUserMst userId)
	{
		this.userId = userId;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost()
	{
		return this.orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost)
	{
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstUpdatedBy()
	{
		return this.orgUserMstUpdatedBy;
	}

	public void setOrgUserMstUpdatedBy(OrgUserMst orgUserMstUpdatedBy)
	{
		this.orgUserMstUpdatedBy = orgUserMstUpdatedBy;
	}

	public CmnDatabaseMst getCmnDatabaseMst()
	{
		return this.cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst)
	{
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public OrgPostMst getOrgPostMstCreatedByPost()
	{
		return this.orgPostMstCreatedByPost;
	}

	public void setOrgPostMstCreatedByPost(OrgPostMst orgPostMstCreatedByPost)
	{
		this.orgPostMstCreatedByPost = orgPostMstCreatedByPost;
	}

	public Date getPayFixDate()
	{
		return this.payFixDate;
	}

	public void setPayFixDate(Date payFixDate)
	{
		this.payFixDate = payFixDate;
	}

	public Date getNxtIncrDate()
	{
		return this.nxtIncrDate;
	}

	public void setNxtIncrDate(Date nxtIncrDate)
	{
		this.nxtIncrDate = nxtIncrDate;
	}

	public String getRemarks()
	{
		return this.remarks;
	}

	public void setRemarks(String remarks)
	{
		this.remarks = remarks;
	}

	public Date getUpdatedDate()
	{
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate)
	{
		this.updatedDate = updatedDate;
	}

	public Date getCreatedDate()
	{
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate)
	{
		this.createdDate = createdDate;
	}

	public String getStatus()
	{
		return this.status;
	}

	public void setStatus(String status)
	{
		this.status = status;
	}

	public Long getNewBasic()
	{
		return this.newBasic;
	}

	public void setNewBasic(Long newBasic)
	{
		this.newBasic = newBasic;
	}

	public String getIncrementOrderNo()
	{
		return this.incrementOrderNo;
	}

	public void setIncrementOrderNo(String incrementOrderNo)
	{
		this.incrementOrderNo = incrementOrderNo;
	}

	public Long getOldBasic()
	{
		return this.oldBasic;
	}

	public void setOldBasic(Long oldBasic)
	{
		this.oldBasic = oldBasic;
	}

	public Integer getActivateFlag()
	{
		return this.activateFlag;
	}

	public void setActivateFlag(Integer activateFlag)
	{
		this.activateFlag = activateFlag;
	}

	public Date getIncrementOrderDate()
	{
		return this.incrementOrderDate;
	}

	public void setIncrementOrderDate(Date incrementOrderDate)
	{
		this.incrementOrderDate = incrementOrderDate;
	}

	public Long getPayCommissionId()
	{
		return payCommissionId;
	}

	public void setPayCommissionId(Long payCommissionId)
	{
		this.payCommissionId = payCommissionId;
	}

}
