// default package
// Generated Feb 12, 2008 4:37:40 PM by Hibernate Tools 3.2.0.beta8

package com.tcs.sgv.eis.valueobject;
import java.util.Date;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLanguageMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrMiscRecoverDtlsHst generated by hbm2java
 */
public class HrMiscRecoverDtlsHst implements java.io.Serializable {

	// Fields    

	private HrMiscRecoverDtlsHstId id;

	//private long empId;

	private long recoverAmt;

	private String reason;

	private Date recoverDate;

	/*private long dbId;

	private long locId;

	private long langId;*/

	private long elementCode;

	/*private long createdBy;

	private long createdByPost;*/

	private Date createdDate;

	/*private long updatedBy;

	private long updatedByPost;*/

	private Date updatedDate;
	
	private CmnLanguageMst cmnLanguageMst;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;

	private HrEisEmpMst hrEisEmpMst;
	
	private long attachment_Id;
	
	private long total_amount;
	
	private long installment;
	
	private Date recoverEndDate;
	
	private long edpTypeId;
	
	private Integer miscActivateFlag;
	
	private int tot_recv_amt;
	
	private int tot_recv_inst;

	// Constructors

	/** default constructor */
	public HrMiscRecoverDtlsHst() {
	}

	/** minimal constructor */
	public HrMiscRecoverDtlsHst(HrMiscRecoverDtlsHstId id) {
		this.id = id;
	}

	/** full constructor */
	public HrMiscRecoverDtlsHst(HrMiscRecoverDtlsHstId id,
			HrEisEmpMst hrEisEmpMst,
			long recoverAmt, String reason, Date recoverDate,
			Date createdDate,Date updatedDate,long elementCode,
			CmnLanguageMst cmnLanguageMst, CmnLocationMst cmnLocationMst, CmnDatabaseMst cmnDatabaseMst, 
			OrgUserMst orgUserMstByCreatedBy,
			OrgPostMst orgPostMstByCreatedByPost,
			OrgUserMst orgUserMstByUpdatedBy,OrgPostMst orgPostMstByUpdatedByPost) {
		this.id = id;
		this.hrEisEmpMst = hrEisEmpMst;
		this.recoverAmt = recoverAmt;
		this.reason = reason;
		this.recoverDate = recoverDate;
		/*this.dbId = dbId;
		this.locId = locId;
		this.langId = langId;*/
		this.elementCode = elementCode;
		/*this.createdBy = createdBy;
		this.createdByPost = createdByPost;*/
		this.createdDate = createdDate;
		/*this.updatedBy = updatedBy;
		this.updatedByPost = updatedByPost;*/
		this.updatedDate = updatedDate;
		this.cmnLanguageMst = cmnLanguageMst; 
		this.cmnLocationMst = cmnLocationMst;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	// Property accessors
	public HrMiscRecoverDtlsHstId getId() {
		return this.id;
	}

	public void setId(HrMiscRecoverDtlsHstId id) {
		this.id = id;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLanguageMst getCmnLanguageMst() {
		return cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLanguageMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public long getElementCode() {
		return elementCode;
	}

	public void setElementCode(long elementCode) {
		this.elementCode = elementCode;
	}

	public HrEisEmpMst getHrEisEmpMst() {
		return hrEisEmpMst;
	}

	public void setHrEisEmpMst(HrEisEmpMst hrEisEmpMst) {
		this.hrEisEmpMst = hrEisEmpMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public long getRecoverAmt() {
		return recoverAmt;
	}

	public void setRecoverAmt(long recoverAmt) {
		this.recoverAmt = recoverAmt;
	}

	public Date getRecoverDate() {
		return recoverDate;
	}

	public void setRecoverDate(Date recoverDate) {
		this.recoverDate = recoverDate;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public long getAttachment_Id() {
		return attachment_Id;
	}

	public void setAttachment_Id(long attachment_Id) {
		this.attachment_Id = attachment_Id;
	}

	public long getEdpTypeId() {
		return edpTypeId;
	}

	public void setEdpTypeId(long edpTypeId) {
		this.edpTypeId = edpTypeId;
	}

	public long getInstallment() {
		return installment;
	}

	public void setInstallment(long installment) {
		this.installment = installment;
	}

	public Date getRecoverEndDate() {
		return recoverEndDate;
	}

	public void setRecoverEndDate(Date recoverEndDate) {
		this.recoverEndDate = recoverEndDate;
	}

	public long getTotal_amount() {
		return total_amount;
	}

	public void setTotal_amount(long total_amount) {
		this.total_amount = total_amount;
	}

	public Integer getMiscActivateFlag() {
		return miscActivateFlag;
	}

	public void setMiscActivateFlag(Integer miscActivateFlag) {
		this.miscActivateFlag = miscActivateFlag;
	}

	public int getTot_recv_amt() {
		return tot_recv_amt;
	}

	public void setTot_recv_amt(int tot_recv_amt) {
		this.tot_recv_amt = tot_recv_amt;
	}

	public int getTot_recv_inst() {
		return tot_recv_inst;
	}

	public void setTot_recv_inst(int tot_recv_inst) {
		this.tot_recv_inst = tot_recv_inst;
	}

	
}
