package com.tcs.sgv.eis.valueobject;

// default package
// Generated Aug 14, 2008 6:45:59 AM by Hibernate Tools 3.1.0.beta5


import java.util.Date;



import com.tcs.sgv.common.loan.valueobject.HrLoanAdvMst;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.eis.valueobject.HrPayPaybill;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;


/**
 * HrPayPaybillLoanDtls generated by hbm2java
 */
public class HrPayPaybillLoanDtls implements java.io.Serializable {

	// Fields    

	private long id;

	private HrPayPaybill paybillId;

	private HrLoanAdvMst hrLoanAdvMst;

	private CmnLookupMst recoveryType;

	private long totalAmt;

	private long totalInst;

	private long recoveredAmt;

	private long recoveredInst;

	private Date createdDate;
	
	private Date updatedDate;

	private CmnDatabaseMst cmnDatabaseMst;

	private OrgPostMst orgPostMstByUpdatedByPost;

	private OrgPostMst orgPostMstByCreatedByPost;

	private CmnLocationMst cmnLocationMst;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;
	private HrLoanEmpDtls hrLoanEmpDtls;

	// Constructors

	/** default constructor */
	public HrPayPaybillLoanDtls() {
	}

	/** minimal constructor */
	public HrPayPaybillLoanDtls(long id) {
		this.id = id;
	}

	/** full constructor */
	public HrPayPaybillLoanDtls(long id, HrPayPaybill paybillId,
			HrLoanAdvMst hrLoanAdvMst, CmnLookupMst recoveryType, long totalAmt,
			long totalInst, long recoveredAmt,
			long recoveredInst, CmnDatabaseMst cmnDatabaseMst, CmnLocationMst cmnLocationMst,
			OrgUserMst orgUserMstByCreatedBy, Date createdDate, OrgPostMst orgPostMstByCreatedByPost,
			OrgUserMst orgUserMstByUpdatedBy, OrgPostMst orgPostMstByUpdatedByPost, Date updatedDate,
			HrLoanEmpDtls hrLoanEmpDtls) {
		this.id = id;
		this.paybillId = paybillId;
		this.hrLoanAdvMst = hrLoanAdvMst;
		this.recoveryType = recoveryType;
		this.totalAmt = totalAmt;
		this.totalInst = totalInst;
		this.recoveredAmt = recoveredAmt;
		this.recoveredInst = recoveredInst;
		this.cmnDatabaseMst=cmnDatabaseMst;
		this.cmnLocationMst = cmnLocationMst;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.createdDate = createdDate;
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
		this.updatedDate = updatedDate;
		this.hrLoanEmpDtls = hrLoanEmpDtls;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public HrLoanEmpDtls getHrLoanEmpDtls() {
		return hrLoanEmpDtls;
	}

	public void setHrLoanEmpDtls(HrLoanEmpDtls hrLoanEmpDtls) {
		this.hrLoanEmpDtls = hrLoanEmpDtls;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public HrLoanAdvMst getHrLoanAdvMst() {
		return hrLoanAdvMst;
	}

	public void setHrLoanAdvMst(HrLoanAdvMst hrLoanAdvMst) {
		this.hrLoanAdvMst = hrLoanAdvMst;
	}

	public OrgPostMst getOrgPostMstByCreatedByPost() {
		return orgPostMstByCreatedByPost;
	}

	public void setOrgPostMstByCreatedByPost(OrgPostMst orgPostMstByCreatedByPost) {
		this.orgPostMstByCreatedByPost = orgPostMstByCreatedByPost;
	}

	public OrgPostMst getOrgPostMstByUpdatedByPost() {
		return orgPostMstByUpdatedByPost;
	}

	public void setOrgPostMstByUpdatedByPost(OrgPostMst orgPostMstByUpdatedByPost) {
		this.orgPostMstByUpdatedByPost = orgPostMstByUpdatedByPost;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public HrPayPaybill getPaybillId() {
		return paybillId;
	}

	public void setPaybillId(HrPayPaybill paybillId) {
		this.paybillId = paybillId;
	}

	public long getRecoveredAmt() {
		return recoveredAmt;
	}

	public void setRecoveredAmt(long recoveredAmt) {
		this.recoveredAmt = recoveredAmt;
	}

	public long getRecoveredInst() {
		return recoveredInst;
	}

	public void setRecoveredInst(long recoveredInst) {
		this.recoveredInst = recoveredInst;
	}

	public CmnLookupMst getRecoveryType() {
		return recoveryType;
	}

	public void setRecoveryType(CmnLookupMst recoveryType) {
		this.recoveryType = recoveryType;
	}

	public long getTotalAmt() {
		return totalAmt;
	}

	public void setTotalAmt(long totalAmt) {
		this.totalAmt = totalAmt;
	}

	public long getTotalInst() {
		return totalInst;
	}

	public void setTotalInst(long totalInst) {
		this.totalInst = totalInst;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	// Property accessors
	

}
