package com.tcs.sgv.eis.valueobject;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.tcs.sgv.common.valueobject.CmnCountryMst;
import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.ess.valueobject.OrgEmpMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;
import com.tcs.sgv.hod.common.valueobject.CmnAddressMst;

/**
 * HrEisEmpMstHst generated by hbm2java
 */
public class HrEisEmpMstHst implements java.io.Serializable {

	// Fields    

	private HrEisEmpMstHstId id;

	private OrgPostMst orgPostMst;

	private CmnAddressMst cmnAddressMstByEmpBirthPlaceAddressId;

	private CmnAddressMst cmnAddressMstByEmpPermanentAddressId;

	private CmnLookupMst cmnLanguageMst;

	private OrgEmpMst orgEmpMst;

	private CmnAddressMst cmnAddressMstByEmpNativePlaceAddressId;

	private CmnLookupMst cmnLookupMstByEmpCasteId;

	private CmnDatabaseMst cmnDatabaseMst;

	private CmnLookupMst cmnLookupMstByEmpSubCasteId;

	private CmnAddressMst cmnAddressMstByEmpCurrentAddressId;

	private CmnLookupMst cmnLookupMstByEmpReligionId;

	private CmnLookupMst cmnLookupMstByEmpCategoryId;

	private CmnLookupMst cmnLookupMstByEmpMaritalStatusId;

	private OrgUserMst orgUserMstByUpdatedBy;

	private OrgUserMst orgUserMstByCreatedBy;

	private HrEisBiometricDtl hrPersonBiometricDtls;

	private Character empGender;

	private String empStatusId;

	private Date empApptLtrDt;

	private String empApptLtrNo;

	private Date empConfDueDt;

	private String empSalDisbMd;

	//private String empNationality;	updated by sandip     
	private CmnCountryMst cmnCountryMstByEmpNationality;

	private CmnLocationMst cmnLocationMst;

	private Date createdDate;

	private Date updatedDate;

	private String empHobby;

	private Long empType;

	private Long empRecruitSrc;

	private String email;

	private Long contactNo;

	private Set hrLoanEmpDtlses = new HashSet(0);
	private Set hrEisBankDtlses = new HashSet(0);
	private Set hrLeaveEmpDtlses = new HashSet(0);
	
	
	// Constructors

	/** default constructor */
	public HrEisEmpMstHst() {
	}

	/** minimal constructor */
	public HrEisEmpMstHst(HrEisEmpMstHstId id) {
		this.id = id;
	}

	/** full constructor */
	public HrEisEmpMstHst(HrEisEmpMstHstId id, OrgPostMst orgPostMst,
			CmnAddressMst cmnAddressMstByEmpBirthPlaceAddressId,
			CmnAddressMst cmnAddressMstByEmpPermanentAddressId,
			CmnLookupMst cmnLanguageMst, OrgEmpMst orgEmpMst,
			CmnAddressMst cmnAddressMstByEmpNativePlaceAddressId,
			CmnLookupMst cmnLookupMstByEmpCasteId,
			CmnDatabaseMst cmnDatabaseMst,
			CmnLookupMst cmnLookupMstByEmpSubCasteId,
			CmnAddressMst cmnAddressMstByEmpCurrentAddressId,
			CmnLookupMst cmnLookupMstByEmpReligionId,
			CmnLookupMst cmnLookupMstByEmpCategoryId,
			CmnLookupMst cmnLookupMstByEmpMaritalStatusId,
			OrgUserMst orgUserMstByUpdatedBy, OrgUserMst orgUserMstByCreatedBy,
			HrEisBiometricDtl hrPersonBiometricDtls, Character empGender,
			String empStatusId, Date empApptLtrDt, String empApptLtrNo,
			Date empConfDueDt, String empSalDisbMd, CmnCountryMst cmnCountryMstByEmpNationality,
			CmnLocationMst cmnLocationMst, Date createdDate, Date updatedDate, String empHobby,
			Long empType, Long empRecruitSrc, String email, Long contactNo,Set hrLoanEmpDtlses,Set hrLeaveEmpDtlses) {
		this.id = id;
		this.orgPostMst = orgPostMst;
		this.cmnAddressMstByEmpBirthPlaceAddressId = cmnAddressMstByEmpBirthPlaceAddressId;
		this.cmnAddressMstByEmpPermanentAddressId = cmnAddressMstByEmpPermanentAddressId;
		this.cmnLanguageMst = cmnLanguageMst;
		this.orgEmpMst = orgEmpMst;
		this.cmnAddressMstByEmpNativePlaceAddressId = cmnAddressMstByEmpNativePlaceAddressId;
		this.cmnLookupMstByEmpCasteId = cmnLookupMstByEmpCasteId;
		this.cmnDatabaseMst = cmnDatabaseMst;
		this.cmnLookupMstByEmpSubCasteId = cmnLookupMstByEmpSubCasteId;
		this.cmnAddressMstByEmpCurrentAddressId = cmnAddressMstByEmpCurrentAddressId;
		this.cmnLookupMstByEmpReligionId = cmnLookupMstByEmpReligionId;
		this.cmnLookupMstByEmpCategoryId = cmnLookupMstByEmpCategoryId;
		this.cmnLookupMstByEmpMaritalStatusId = cmnLookupMstByEmpMaritalStatusId;
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
		this.hrPersonBiometricDtls = hrPersonBiometricDtls;
		this.empGender = empGender;
		this.empStatusId = empStatusId;
		this.empApptLtrDt = empApptLtrDt;
		this.empApptLtrNo = empApptLtrNo;
		this.empConfDueDt = empConfDueDt;
		this.empSalDisbMd = empSalDisbMd;
		this.cmnCountryMstByEmpNationality = cmnCountryMstByEmpNationality;
		this.cmnLocationMst = cmnLocationMst;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.empHobby = empHobby;
		this.empType = empType;
		this.empRecruitSrc = empRecruitSrc;
		this.email = email;
		this.hrLoanEmpDtlses = hrLoanEmpDtlses;
		this.hrLeaveEmpDtlses = hrLeaveEmpDtlses;
		this.contactNo = contactNo;
	}

	// Property accessors
	public HrEisEmpMstHstId getId() {
		return this.id;
	}

	public CmnAddressMst getCmnAddressMstByEmpBirthPlaceAddressId() {
		return cmnAddressMstByEmpBirthPlaceAddressId;
	}

	public void setCmnAddressMstByEmpBirthPlaceAddressId(
			CmnAddressMst cmnAddressMstByEmpBirthPlaceAddressId) {
		this.cmnAddressMstByEmpBirthPlaceAddressId = cmnAddressMstByEmpBirthPlaceAddressId;
	}

	public CmnAddressMst getCmnAddressMstByEmpCurrentAddressId() {
		return cmnAddressMstByEmpCurrentAddressId;
	}

	public void setCmnAddressMstByEmpCurrentAddressId(
			CmnAddressMst cmnAddressMstByEmpCurrentAddressId) {
		this.cmnAddressMstByEmpCurrentAddressId = cmnAddressMstByEmpCurrentAddressId;
	}

	public CmnAddressMst getCmnAddressMstByEmpNativePlaceAddressId() {
		return cmnAddressMstByEmpNativePlaceAddressId;
	}

	public void setCmnAddressMstByEmpNativePlaceAddressId(
			CmnAddressMst cmnAddressMstByEmpNativePlaceAddressId) {
		this.cmnAddressMstByEmpNativePlaceAddressId = cmnAddressMstByEmpNativePlaceAddressId;
	}

	public CmnAddressMst getCmnAddressMstByEmpPermanentAddressId() {
		return cmnAddressMstByEmpPermanentAddressId;
	}

	public void setCmnAddressMstByEmpPermanentAddressId(
			CmnAddressMst cmnAddressMstByEmpPermanentAddressId) {
		this.cmnAddressMstByEmpPermanentAddressId = cmnAddressMstByEmpPermanentAddressId;
	}

	public CmnDatabaseMst getCmnDatabaseMst() {
		return cmnDatabaseMst;
	}

	public void setCmnDatabaseMst(CmnDatabaseMst cmnDatabaseMst) {
		this.cmnDatabaseMst = cmnDatabaseMst;
	}

	public CmnLookupMst getCmnLanguageMst() {
		return cmnLanguageMst;
	}

	public void setCmnLanguageMst(CmnLookupMst cmnLanguageMst) {
		this.cmnLanguageMst = cmnLanguageMst;
	}

	public CmnLocationMst getCmnLocationMst() {
		return cmnLocationMst;
	}

	public void setCmnLocationMst(CmnLocationMst cmnLocationMst) {
		this.cmnLocationMst = cmnLocationMst;
	}

	public CmnLookupMst getCmnLookupMstByEmpCasteId() {
		return cmnLookupMstByEmpCasteId;
	}

	public void setCmnLookupMstByEmpCasteId(CmnLookupMst cmnLookupMstByEmpCasteId) {
		this.cmnLookupMstByEmpCasteId = cmnLookupMstByEmpCasteId;
	}

	public CmnLookupMst getCmnLookupMstByEmpCategoryId() {
		return cmnLookupMstByEmpCategoryId;
	}

	public void setCmnLookupMstByEmpCategoryId(
			CmnLookupMst cmnLookupMstByEmpCategoryId) {
		this.cmnLookupMstByEmpCategoryId = cmnLookupMstByEmpCategoryId;
	}

	public CmnLookupMst getCmnLookupMstByEmpMaritalStatusId() {
		return cmnLookupMstByEmpMaritalStatusId;
	}

	public void setCmnLookupMstByEmpMaritalStatusId(
			CmnLookupMst cmnLookupMstByEmpMaritalStatusId) {
		this.cmnLookupMstByEmpMaritalStatusId = cmnLookupMstByEmpMaritalStatusId;
	}

	public CmnLookupMst getCmnLookupMstByEmpReligionId() {
		return cmnLookupMstByEmpReligionId;
	}

	public void setCmnLookupMstByEmpReligionId(
			CmnLookupMst cmnLookupMstByEmpReligionId) {
		this.cmnLookupMstByEmpReligionId = cmnLookupMstByEmpReligionId;
	}

	public CmnLookupMst getCmnLookupMstByEmpSubCasteId() {
		return cmnLookupMstByEmpSubCasteId;
	}

	public void setCmnLookupMstByEmpSubCasteId(
			CmnLookupMst cmnLookupMstByEmpSubCasteId) {
		this.cmnLookupMstByEmpSubCasteId = cmnLookupMstByEmpSubCasteId;
	}

	public Long getContactNo() {
		return contactNo;
	}

	public void setContactNo(Long contactNo) {
		this.contactNo = contactNo;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getEmpApptLtrDt() {
		return empApptLtrDt;
	}

	public void setEmpApptLtrDt(Date empApptLtrDt) {
		this.empApptLtrDt = empApptLtrDt;
	}

	public String getEmpApptLtrNo() {
		return empApptLtrNo;
	}

	public void setEmpApptLtrNo(String empApptLtrNo) {
		this.empApptLtrNo = empApptLtrNo;
	}

	public Date getEmpConfDueDt() {
		return empConfDueDt;
	}

	public void setEmpConfDueDt(Date empConfDueDt) {
		this.empConfDueDt = empConfDueDt;
	}

	public Character getEmpGender() {
		return empGender;
	}

	public void setEmpGender(Character empGender) {
		this.empGender = empGender;
	}

	public String getEmpHobby() {
		return empHobby;
	}

	public void setEmpHobby(String empHobby) {
		this.empHobby = empHobby;
	}

	/* commented by sandip
	public String getEmpNationality() {
		return empNationality;
	}

	public void setEmpNationality(String empNationality) {
		this.empNationality = empNationality;
	}*/

	public Long getEmpRecruitSrc() {
		return empRecruitSrc;
	}

	public void setEmpRecruitSrc(Long empRecruitSrc) {
		this.empRecruitSrc = empRecruitSrc;
	}

	public String getEmpSalDisbMd() {
		return empSalDisbMd;
	}

	public void setEmpSalDisbMd(String empSalDisbMd) {
		this.empSalDisbMd = empSalDisbMd;
	}

	public String getEmpStatusId() {
		return empStatusId;
	}

	public void setEmpStatusId(String empStatusId) {
		this.empStatusId = empStatusId;
	}

	public Long getEmpType() {
		return empType;
	}

	public void setEmpType(Long empType) {
		this.empType = empType;
	}

	public Set getHrEisBankDtlses() {
		return hrEisBankDtlses;
	}

	public void setHrEisBankDtlses(Set hrEisBankDtlses) {
		this.hrEisBankDtlses = hrEisBankDtlses;
	}

	public Set getHrLeaveEmpDtlses() {
		return hrLeaveEmpDtlses;
	}

	public void setHrLeaveEmpDtlses(Set hrLeaveEmpDtlses) {
		this.hrLeaveEmpDtlses = hrLeaveEmpDtlses;
	}

	public Set getHrLoanEmpDtlses() {
		return hrLoanEmpDtlses;
	}

	public void setHrLoanEmpDtlses(Set hrLoanEmpDtlses) {
		this.hrLoanEmpDtlses = hrLoanEmpDtlses;
	}

	public HrEisBiometricDtl getHrPersonBiometricDtls() {
		return hrPersonBiometricDtls;
	}

	public void setHrPersonBiometricDtls(HrEisBiometricDtl hrPersonBiometricDtls) {
		this.hrPersonBiometricDtls = hrPersonBiometricDtls;
	}

	public OrgEmpMst getOrgEmpMst() {
		return orgEmpMst;
	}

	public void setOrgEmpMst(OrgEmpMst orgEmpMst) {
		this.orgEmpMst = orgEmpMst;
	}

	public OrgPostMst getOrgPostMst() {
		return orgPostMst;
	}

	public void setOrgPostMst(OrgPostMst orgPostMst) {
		this.orgPostMst = orgPostMst;
	}

	public OrgUserMst getOrgUserMstByCreatedBy() {
		return orgUserMstByCreatedBy;
	}

	public void setOrgUserMstByCreatedBy(OrgUserMst orgUserMstByCreatedBy) {
		this.orgUserMstByCreatedBy = orgUserMstByCreatedBy;
	}

	public OrgUserMst getOrgUserMstByUpdatedBy() {
		return orgUserMstByUpdatedBy;
	}

	public void setOrgUserMstByUpdatedBy(OrgUserMst orgUserMstByUpdatedBy) {
		this.orgUserMstByUpdatedBy = orgUserMstByUpdatedBy;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public void setId(HrEisEmpMstHstId id) {
		this.id = id;
	}
	
	/* added by sandip - start*/
	public CmnCountryMst getCmnCountryMstByEmpNationality() {
		return cmnCountryMstByEmpNationality;
	}

	public void setCmnCountryMstByEmpNationality(
			CmnCountryMst cmnCountryMstByEmpNationality) {
		this.cmnCountryMstByEmpNationality = cmnCountryMstByEmpNationality;
	}
	/* added by sandip - end*/
	

}
