// default package
// Generated Sep 14, 2009 5:50:14 PM by Hibernate Tools 3.2.0.beta8
package com.tcs.sgv.common.valueobject;
import java.util.Date;

/**
 * RltDdoOrgCoddo generated by hbm2java
 */
public class RltDdoOrgCoddo implements java.io.Serializable {

	// Fields    

	private Long ddoOrgId;

	private Byte activateFlag;

	private Date startDate;

	private Date endDate;

	private Integer createdUserId;

	private Integer createdPostId;

	private Date createdDate;

	private Integer updatedUserId;

	private Integer updatedPostId;

	private Date updatedDate;

	private Short dbId;

	private String ddoCode;

	private String locationCode;

	private Integer trnCounter;

	// Constructors

	/** default constructor */
	public RltDdoOrgCoddo() {
	}

	/** minimal constructor */
	public RltDdoOrgCoddo(Long ddoOrgId, Byte activateFlag, Integer createdUserId,
			Integer createdPostId, Date createdDate, String ddoCode) {
		this.ddoOrgId = ddoOrgId;
		this.activateFlag = activateFlag;
		this.createdUserId = createdUserId;
		this.createdPostId = createdPostId;
		this.createdDate = createdDate;
		this.ddoCode = ddoCode;
	}

	/** full constructor */
	public RltDdoOrgCoddo(Long ddoOrgId, Byte activateFlag, Date startDate,
			Date endDate, Integer createdUserId, Integer createdPostId,
			Date createdDate, Integer updatedUserId, Integer updatedPostId,
			Date updatedDate, Short dbId, String ddoCode, String locationCode,
			Integer trnCounter) {
		this.ddoOrgId = ddoOrgId;
		this.activateFlag = activateFlag;
		this.startDate = startDate;
		this.endDate = endDate;
		this.createdUserId = createdUserId;
		this.createdPostId = createdPostId;
		this.createdDate = createdDate;
		this.updatedUserId = updatedUserId;
		this.updatedPostId = updatedPostId;
		this.updatedDate = updatedDate;
		this.dbId = dbId;
		this.ddoCode = ddoCode;
		this.locationCode = locationCode;
		this.trnCounter = trnCounter;
	}

	// Property accessors
	public Long getDdoOrgId() {
		return this.ddoOrgId;
	}

	public void setDdoOrgId(Long ddoOrgId) {
		this.ddoOrgId = ddoOrgId;
	}

	public Byte getActivateFlag() {
		return this.activateFlag;
	}

	public void setActivateFlag(Byte activateFlag) {
		this.activateFlag = activateFlag;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

	public Integer getCreatedPostId() {
		return this.createdPostId;
	}

	public void setCreatedPostId(Integer createdPostId) {
		this.createdPostId = createdPostId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Integer getUpdatedUserId() {
		return this.updatedUserId;
	}

	public void setUpdatedUserId(Integer updatedUserId) {
		this.updatedUserId = updatedUserId;
	}

	public Integer getUpdatedPostId() {
		return this.updatedPostId;
	}

	public void setUpdatedPostId(Integer updatedPostId) {
		this.updatedPostId = updatedPostId;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Short getDbId() {
		return this.dbId;
	}

	public void setDbId(Short dbId) {
		this.dbId = dbId;
	}

	public String getDdoCode() {
		return this.ddoCode;
	}

	public void setDdoCode(String ddoCode) {
		this.ddoCode = ddoCode;
	}

	public String getLocationCode() {
		return this.locationCode;
	}

	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}

	public Integer getTrnCounter() {
		return this.trnCounter;
	}

	public void setTrnCounter(Integer trnCounter) {
		this.trnCounter = trnCounter;
	}

}
