package com.tcs.sgv.hr.payfixation.valueobject;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.tcs.sgv.common.valueobject.CmnDatabaseMst;
import com.tcs.sgv.common.valueobject.CmnLocationMst;
import com.tcs.sgv.common.valueobject.CmnLookupMst;
import com.tcs.sgv.eis.hrModInfo.valueobject.HrModEmpRlt;
import com.tcs.sgv.eis.valueobject.HrEisScaleMst;
import com.tcs.sgv.ess.valueobject.OrgPostMst;
import com.tcs.sgv.ess.valueobject.OrgUserMst;

/**
 * HrEssTranPayFix generated by hbm2java
 */
public class HrPayFixTxn implements java.io.Serializable {

	// Fields    

	private long payFixId;

	private OrgUserMst userId;

	private CmnLookupMst cmnLookupMst;

	private Date applDate;

	private HrEisScaleMst revScaleId;

	private Date payFixDate;

	private CmnDatabaseMst dbId;

	private CmnLocationMst locId;

	private OrgUserMst createdBy;

	private OrgPostMst createdByPost;

	private Date createdDate;

	private OrgUserMst updatedBy;

	private OrgPostMst updatedByPost;

	private Date updatedDate;

	private String payFixation;

	private String payFixationAtIncr;

	private Date incrDate;

	private String emplResp;

	private Set hrPayfixReqDtles = new HashSet(0);
	

	// Constructors

	/** default constructor */
	public HrPayFixTxn() {
	}

	/** minimal constructor */
	public HrPayFixTxn(long payFixId, HrModEmpRlt hrModEmpRlt) {
		this.payFixId = payFixId;
		
	}

	/** full constructor */
	public HrPayFixTxn(long payFixId, OrgUserMst userId,
		    CmnLookupMst cmnLookupMst, Date applDate,
			HrEisScaleMst revScaleId, Date payFixDate, CmnDatabaseMst dbId,
			CmnLocationMst locId, OrgUserMst createdBy, OrgPostMst createdByPost,
			Date createdDate, OrgUserMst updatedBy, OrgPostMst updatedByPost,
			Date updatedDate, String payFixation, String payFixationAtIncr,
			Date incrDate, String emplResp, Set hrPayfixReqDtles) {
		this.payFixId = payFixId;
		this.userId = userId;
		this.cmnLookupMst = cmnLookupMst;
		this.applDate = applDate;
		this.revScaleId = revScaleId;
		this.payFixDate = payFixDate;
		this.dbId = dbId;
		this.locId = locId;
		this.createdBy = createdBy;
		this.createdByPost = createdByPost;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedByPost = updatedByPost;
		this.updatedDate = updatedDate;
		this.payFixation = payFixation;
		this.payFixationAtIncr = payFixationAtIncr;
		this.incrDate = incrDate;
		this.emplResp = emplResp;
		this.hrPayfixReqDtles = hrPayfixReqDtles;
	}

	// Property accessors
	public long getPayFixId() {
		return this.payFixId;
	}

	public void setPayFixId(long payFixId) {
		this.payFixId = payFixId;
	}

	public OrgUserMst getUserId() {
		return this.userId;
	}

	public void setUserId(OrgUserMst userId) {
		this.userId = userId;
	}

	public CmnLookupMst getCmnLookupMst() {
		return this.cmnLookupMst;
	}

	public void setCmnLookupMst(CmnLookupMst cmnLookupMst) {
		this.cmnLookupMst = cmnLookupMst;
	}

	public Date getApplDate() {
		return this.applDate;
	}

	public void setApplDate(Date applDate) {
		this.applDate = applDate;
	}

	public HrEisScaleMst getRevScaleId() {
		return this.revScaleId;
	}

	public void setRevScaleId(HrEisScaleMst revScaleId) {
		this.revScaleId = revScaleId;
	}

	public Date getPayFixDate() {
		return this.payFixDate;
	}

	public void setPayFixDate(Date payFixDate) {
		this.payFixDate = payFixDate;
	}

	public CmnDatabaseMst getDbId() {
		return this.dbId;
	}

	public void setDbId(CmnDatabaseMst dbId) {
		this.dbId = dbId;
	}

	public CmnLocationMst getLocId() {
		return this.locId;
	}

	public void setLocId(CmnLocationMst locId) {
		this.locId = locId;
	}

	public OrgUserMst getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(OrgUserMst createdBy) {
		this.createdBy = createdBy;
	}

	public OrgPostMst getCreatedByPost() {
		return this.createdByPost;
	}

	public void setCreatedByPost(OrgPostMst createdByPost) {
		this.createdByPost = createdByPost;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public OrgUserMst getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(OrgUserMst updatedBy) {
		this.updatedBy = updatedBy;
	}

	public OrgPostMst getUpdatedByPost() {
		return this.updatedByPost;
	}

	public void setUpdatedByPost(OrgPostMst updatedByPost) {
		this.updatedByPost = updatedByPost;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getPayFixation() {
		return this.payFixation;
	}

	public void setPayFixation(String payFixation) {
		this.payFixation = payFixation;
	}

	public String getPayFixationAtIncr() {
		return this.payFixationAtIncr;
	}

	public void setPayFixationAtIncr(String payFixationAtIncr) {
		this.payFixationAtIncr = payFixationAtIncr;
	}

	public Date getIncrDate() {
		return this.incrDate;
	}

	public void setIncrDate(Date incrDate) {
		this.incrDate = incrDate;
	}

	public String getEmplResp() {
		return this.emplResp;
	}

	public void setEmplResp(String emplResp) {
		this.emplResp = emplResp;
	}

	public Set getHrPayfixReqDtles() {
		return this.hrPayfixReqDtles;
	}

	public void setHrPayfixReqDtles(Set hrPayfixReqDtles) {
		this.hrPayfixReqDtles = hrPayfixReqDtles;
	}
}
