package com.tcs.sgv.exprcpt.valueobject;

// Generated May 28, 2007 3:48:54 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * TrnVoucherDetails generated by hbm2java
 */
public class TrnVoucherDetails implements java.io.Serializable {

	// Fields    

	private long voucherDetailId;

	private long voucherNo;

	private long billNo;

	private Date voucherDate;

	private String majorHead;

	private Short distributed;

	private long createdUserId;

	private long createdPostId;

	private Date createdDate;

	private Long updatedUserId;

	private Long updatedPostId;

	private Date updatedDate;

	private String locationCode;

	private Long dbId;

	// Constructors

	/** default constructor */
	public TrnVoucherDetails() {
	}

	/** minimal constructor */
	public TrnVoucherDetails(long voucherDetailId, long voucherNo,
			long billNo, String majorHead, long createdUserId,
			long createdPostId, Date createdDate) {
		this.voucherDetailId = voucherDetailId;
		this.voucherNo = voucherNo;
		this.billNo = billNo;
		this.majorHead = majorHead;
		this.createdUserId = createdUserId;
		this.createdPostId = createdPostId;
		this.createdDate = createdDate;
	}

	/** full constructor */
	public TrnVoucherDetails(long voucherDetailId, long voucherNo,
			long billNo, Date voucherDate, String majorHead, Short distributed,
			long createdUserId, long createdPostId, Date createdDate,
			Long updatedUserId, Long updatedPostId, Date updatedDate,
			String locationCode, Long dbId) {
		this.voucherDetailId = voucherDetailId;
		this.voucherNo = voucherNo;
		this.billNo = billNo;
		this.voucherDate = voucherDate;
		this.majorHead = majorHead;
		this.distributed = distributed;
		this.createdUserId = createdUserId;
		this.createdPostId = createdPostId;
		this.createdDate = createdDate;
		this.updatedUserId = updatedUserId;
		this.updatedPostId = updatedPostId;
		this.updatedDate = updatedDate;
		this.locationCode=locationCode;
		this.dbId = dbId;
	}

	// Property accessors
	public long getVoucherDetailId() {
		return this.voucherDetailId;
	}

	public void setVoucherDetailId(long voucherDetailId) {
		this.voucherDetailId = voucherDetailId;
	}

	public long getVoucherNo() {
		return this.voucherNo;
	}

	public void setVoucherNo(long voucherNo) {
		this.voucherNo = voucherNo;
	}

	public long getBillNo() {
		return this.billNo;
	}

	public void setBillNo(long billNo) {
		this.billNo = billNo;
	}

	public Date getVoucherDate() {
		return this.voucherDate;
	}

	public void setVoucherDate(Date voucherDate) {
		this.voucherDate = voucherDate;
	}

	public String getMajorHead() {
		return this.majorHead;
	}

	public void setMajorHead(String majorHead) {
		this.majorHead = majorHead;
	}

	public Short getDistributed() {
		return this.distributed;
	}

	public void setDistributed(Short distributed) {
		this.distributed = distributed;
	}

	public long getCreatedUserId() {
		return this.createdUserId;
	}

	public void setCreatedUserId(long createdUserId) {
		this.createdUserId = createdUserId;
	}

	public long getCreatedPostId() {
		return this.createdPostId;
	}

	public void setCreatedPostId(long createdPostId) {
		this.createdPostId = createdPostId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Long getUpdatedUserId() {
		return this.updatedUserId;
	}

	public void setUpdatedUserId(Long updatedUserId) {
		this.updatedUserId = updatedUserId;
	}

	public Long getUpdatedPostId() {
		return this.updatedPostId;
	}

	public void setUpdatedPostId(Long updatedPostId) {
		this.updatedPostId = updatedPostId;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Long getDbId() {
		return this.dbId;
	}

	public void setDbId(Long dbId) {
		this.dbId = dbId;
	}

	public String getLocationCode() {
		return locationCode;
	}

	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}

}
