package com.tcs.sgv.pensionpay.dao;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.Map;

import com.tcs.sgv.common.valueobject.RltBillParty;
import com.tcs.sgv.pensionpay.valueobject.SavedPensionBillVO;
import com.tcs.sgv.pensionpay.valueobject.SupplementaryPartyDtlsVO;
import com.tcs.sgv.pensionpay.valueobject.TrnPensionRecoveryDtls;
import com.tcs.sgv.pensionpay.valueobject.TrnPensionSupplyBillDtls;


public interface PensionBillDAO {

	List getAllFirstPensionBillCases(String locationCode) throws Exception;

	List getCommDtls(String pensionerCode, String locationCode);

	List getClaimantDDOInfo(Long lClaimantpostID, Long lLngLangId) throws Exception;

	List<RltBillParty> getPensionerPartyDtls(Map inputMap) throws Exception;

	List getPartyAcNoDtls(String lStrPnsnerCode, String lStrStatus) throws Exception;

	List getOtherUsersList(String lStrLevel, String lStrHirarchyRefId, String lStrOtherType, String lStrPostId, String lStrCategry, String lStrSubName, String lStrMRFlowFlag, Long lLngLangId)
			throws Exception;

	void updateBookBillNoAndTokenNo(Long lBillNo, Long lTokenNo, Long gLngPostId, Long gLngUserId, Date gDate) throws Exception;

	List getPnsnerLastPaidDateAmt(Long lLngBillNo) throws Exception;

	void updateLastPaidDateAtApproveBill(Long lLngBillNo, String lStrLocCode, Long gLngPostId, Long gLngUserId, Date gDate) throws Exception;

	void updateBillNetAmountForMRCounterPayment(Long lLngBillNo, BigDecimal lBDGrantAmtMR, Long gLngPostId, Long gLngUserId, Date gDate) throws Exception;

	// Soumya New Methods...........
	void deleteTrnPensionArrearDtls(String lStrBillNo) throws Exception;

	void deleteRltBillParty(String lStrBillNo, String lStrLocCode) throws Exception;

	void deleteTrnOnlinebillEmp(String lStrBillNo, String lStrLocCode) throws Exception;

	void deleteTrnBillMvmnt(String lStrBillNo, String lStrLocCode) throws Exception;

	void deleteRptExpEdpDtls(String lStrBillNo, String lStrLocCode, String lStrSubId) throws Exception;

	// void deleteRptExpenditureDtls(String lStrBillNo,String lStrLocCode)
	// throws Exception ;
	void deleteTrnBillEdpDtls(String lStrBillNo, String lStrLocCode) throws Exception;

	void deleteTrnPensionBillDtls(String lStrBillNo, String lStrSubId, String lStrLocCode, Long gLngPostId, Long gLngUserId, Date gDate) throws Exception;

	void deleteTrnPensionBillHdr(String lStrBillNo, String lStrLocCode) throws Exception;

	void deleteTrnBillRegister(String lStrBillNo, String lStrLocCode) throws Exception;

	// void deleteRptReceiptDtls(String lStrBillNo,String lStrLocCode) throws
	// Exception;
	void updateSuppBillDtls(String lStrBillNo, String lStrLocCode, Long gLngPostId, Long gLngUserId, Date gDate) throws Exception;

	void deleteRltPensioncaseBill(String lStrBillNo, String lStrLocCode, Long gLngPostId, Long gLngUserId, Date gDate) throws Exception;

	boolean getBooleanFlagForApprove(String lStrPPO, String locationCode, List lLstBillType) throws Exception;

	String getPPONoForBill(String lStrBillNo, String lStrLocCode) throws Exception;

	String getCaseEditStatusLogic(String lStrPpoNo, String lStrSubId, String lStrLocCode) throws Exception;

	void updateCaseApprStatus(String lStrPpoNo, String lStrLocCode, Long gLngPostId, Long gLngUserId, Date gDate) throws Exception;

	void deleteOtherPartyPayment(String lStrBillNo, String lStrLocCode) throws Exception;

	void updateRecoveryDtls(String lStrBillNo, String lStrLocCode, Long gLngPostId, Long gLngUserId, Date gDate) throws Exception;

	public String getPnsnCodeFromPPONo(String lStrPPONO, String lStrStatus) throws Exception;

	Long getMrBillHdrIdForRejection(String lStrBillNo, String lStrLocCode) throws Exception;

	void updateMedicalOnRejection(Long lLngBillHdrId, Long gLngPostId, Long gLngUserId, Date gDate) throws Exception;

	List getDraftBills(Map displayTag, String locationCode, String lStrSearchStr, String lStrSearchValue, List lLstBillType, String lStrCurrRoleId, String lStrBillFlag, Long lLngPostId)
			throws Exception;

	int getDraftBillCounts(String locationCode, String lStrSearchStr, String lStrSearchValue, List lLstBillType, String lStrCurrRoleId, String lStrBillFlag, Long lLngPostId) throws Exception;

	List getAuditorsListFromRoleID(Long lLngRoleId, String locationCode) throws Exception;

	public BigDecimal autoGeneratedECSCode(String locCode) throws Exception;

	public List getPensionerDtls(List billNoList, String lStrLocCode) throws Exception;

	void updateECSRqstHdrDtls(List billno, Short stChqCstdn, Long lngPostId, Long lngUserId, Date dtCurDate);

	String getAttDocId(String code);

	public int getECSForAuthorizationCount(String lStrLocId, String lStrRoleId, String lStrAuthFlag) throws Exception;

	public List getECSForAuthorization(Map displayTag, String lStrLocId, String lStrRoleId, String lStrAuthFlag) throws Exception;

	public void updateStatusInChqDtls(List lLstChequeNos, Short status, Long gLngPostId, Long gLngUserId, Date gDate) throws Exception;

	public void updateDateInChequeDtls(String lStrECSNo, Date lDtAuthDate, String lStrChequeNo, Long gLngPostId, Long gLngUserId, Date gDate, Date lDtSettDate) throws Exception;

	public void deleteRltBillCheque(String lStrChequeId) throws Exception;

	public void deleteTrnChequeDtls(String lStrChequeId) throws Exception;

	public void deleteTrnEcsDtl(String lStrECSCode) throws Exception;

	List getRemarksOfBill(Long lLngBillNo, String gStrLocationCode, Long gLngLangId);

	public List getBillNosFromECSCode(String lStrECSCode, String lStrLocCode) throws Exception;

	public List isChequeNoExsist(String lStrChequeNo, String lStrLocationCode) throws Exception;

	public List getRltBillPartyDtls(String lStrBillNo) throws Exception;

	public List getAllCheques(Map displayTag, String lStrLocationCode) throws Exception;

	public int getAllChequesCount(String lStrLocationCode) throws Exception;

	public List<SupplementaryPartyDtlsVO> getSuppBillData(String lStrPnsnCode, String lStrLocCode, String lStrBillType) throws Exception;

	public List<SupplementaryPartyDtlsVO> getFamilyDtlsSuppBill(String lStrPnsnCode, String lStrLocCode, String lStrBillType) throws Exception;

	public List<SupplementaryPartyDtlsVO> getNomineeDtlsSuppBill(String lStrPnsnCode, String lStrLocCode) throws Exception;

	public List isValidPPONo(String lStrPPONo, String lStrLocCode, String lStrStatus, Long lLngPostId) throws Exception;

	public String getBranchName(String lStrBank, String lStrBranch, String lStrLocCode) throws Exception;

	public List<TrnPensionRecoveryDtls> getTrnPensionRecoveryDtlsForSupp(String lStrPensionerCode, String lStrStatus, Long lLngBillNo) throws Exception;

	public String getBillTypeForSupp(String lStrPensionerCode, Long lLngBillNo, String lStrLocCode) throws Exception;

	public TrnPensionSupplyBillDtls getSupplyDtlsVO(String lStrPensionerCode, Long lLngBillNo, String lStrLocCode) throws Exception;

	public void updateLastPaidDateForPensionBills(List<String> lLstPpoNos, Date gCurrDate) throws Exception;

	public List<String> getPPONoListFromPnsncaseRlt(List<Long> lLstBillNos) throws Exception;

	public List<String> getPpoNoByBillNo(List<Long> lLstBillNo) throws Exception;

	List getPrintBillDtls(String lStrPnsnrCode, String lStrLocationCode, String lStrCurrDate, String lStrBillType) throws Exception;

	/**
	 * <H3>Description -</H3>
	 * 
	 * 
	 * 
	 * @author Shivani Rana
	 * @param strPPONo
	 * @param strLocCode
	 * @param strStatus
	 * @return
	 */
	public void updateRltPensioncaseBill(List<Long> lStrBillNo, String lStrLocCode, Long gLngPostId, Long gLngUserId, Date gDate) throws Exception;

	public void saveVoucherDetails(Long lLngVoucherNo, Date lDtVoucherDate, Long lLngUserId, Long lLngPostId, Date lDate, Long lLngBillNo) throws Exception;

	public List getAllData(Long lLngMandateNo, Double lLngNetAmt, String lStrPpoNo, String lStrLocationCode) throws Exception;

	public void updateTrnPensionBillDtls(List<Long> lLngBillHdrId) throws Exception;

	public List<Long> getBillNosFromAdviceNo(String ecsCode) throws Exception;

	public List<Object[]> getPnsrCodeFromBillNo(List<Long> lLstBillNo) throws Exception;

	public void updateSixpayArrearPaidFlag(List<String> lLstPnsrCode, Long lLngUserId, Long lLngPostId, Date lCurrDate, Character lCharPaidFlag, Integer lIntPayForMonth) throws Exception;

	public void updateBillNoForRecovery(List<String> lLstPensionerCode, Integer lIntForMonth, String lStrLocCode, Long lLngBillNo, Long gLngUserId, Long gLngPostId, Date gDate) throws Exception;

	public List getAllCashPayment(Map displayTag, String lStrLocationCode) throws Exception;

	public int getAllCashPaymentCount(String lStrLocationCode) throws Exception;

	int getBillVoucherMappingCount(String lStrLocationCode, Long lLngPostId) throws Exception;

	List<SavedPensionBillVO> getBillVoucherMappingList(String lStrLocationCode, Long lLngPostId) throws Exception;

	public void archieveBill(List<Long> lLstBillNo, String lStrLocCode) throws Exception;

	void updateBillNoInArrearDtls(List<String> lLstStrPnsrCode, Long lLngBillNo, Integer lIntForMonth, Long lLngUpdtUserId, Long lLngUpdtPostId, Date lDtUpdtDate) throws Exception;

	void updatePaidFlagInArrearDtlsOnApproveReject(List<Long> lLstBillNo, String lStrPaidFlagTo, Long lLngUpdtUserId, Long lLngUpdtPostId, Date lDtUpdtDate) throws Exception;

	List<Object[]> getPensionOuterBillData(String lStrBillNo, String lStrLocationCode) throws Exception;

	List<Object[]> getPensionInnerBillData(String lStrBillNo, String lStrLocationCode) throws Exception;

	void updateSixpayArrearDtlBySupplementaryBill(Long lLngBillNo, Character lCharPaidFlag, Long lLngUserId, Long lLngPostId, Date lCurrDate) throws Exception;

	void deleteSixpayArrearConfigBySuppleBill(Long lLngBillNo) throws Exception;
}
